cc_library(
    name = "buffer_pool",
    srcs = [
        "buffer_pool_sharded.cpp",
        "replace_strategy.cpp",
    ],
    hdrs = [
        "buffer_pool_sharded.h",
    ],
    deps = [
        "//src/utils:utils",
        "//src/storage_engine/disk_manager",
        "//src/storage_engine/replace_strategy:replace_strategy_headers",
        "//src/storage_engine:storage_engine_headers",
        "//src/config_manager",
        "//src/logger",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "buffer_pool_coverage",
    srcs = [
        "buffer_pool_sharded.cpp",
        "replace_strategy.cpp",
    ],
    hdrs = [
        "buffer_pool_sharded.h",
        "replace_strategy.h",
    ],
    copts = [
        "-std=c++20",
        "-fprofile-instr-generate",
        "-fcoverage-mapping",
    ],
    linkopts = ["-fprofile-instr-generate"],
    deps = [
        "//src/utils:utils_coverage",
        "//src/storage_engine/disk_manager:disk_manager_coverage",
        "//src/exception:exception_coverage",
        "//src/logger:logger_coverage",
        "//src/storage_engine/replace_strategy:replace_strategy_headers",
        "//src/storage_engine:storage_engine_headers",
    ],
    visibility = ["//visibility:public"],
    tags = ["coverage"],
)
