cc_library(
    name = "buffer_pool",
    srcs = [
        "buffer_pool_sharded.cpp",
        "replace_strategy.cpp",
    ],
    hdrs = [
        "buffer_pool_sharded.h",
    ],
    deps = [
        "//src/utils:utils",
        "//src/storage_engine/disk_manager",
        "//src/storage_engine/replace_strategy:replace_strategy_headers",
        "//src/storage_engine:storage_engine_headers",
        "//src/config_manager",
        "//src/logger",
    ],
    visibility = ["//visibility:public"],
)
