cc_library(
    name = "lru_manager",
    srcs = ["lru_manager.cpp"],
    hdrs = ["//include/storage_engine/buffer_pool:lru_manager.h"],
    deps = [
        "//src/utils:utils",
        "//include/exception:exception",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "statistics_collector",
    srcs = ["statistics_collector.cpp"],
    hdrs = ["//include/storage_engine/buffer_pool:statistics_collector.h"],
    deps = [
        "//src/utils:utils",
        "//include/exception:exception",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
)
