#include "ast/ast_node.h"
#include "token.h"
#include <iostream>
#include <unordered_map>

namespace sqlcc {
namespace sql_parser {

Token::Token() : type_(UNKNOWN), line_(0), column_(0) {}

Token::Token(Type type, const std::string &lexeme, size_t line, size_t column)
    : type_(type), lexeme_(lexeme), line_(line), column_(column) {}

std::string Token::getTypeName(Type type) {
  static std::unordered_map<Type, std::string> typeNames = {
      // Punctuation
      {SEMICOLON, "SEMICOLON"},
      {COLON, "COLON"},
      {LPAREN, "LPAREN"},
      {RPAREN, "RPAREN"},
      {COMMA, "COMMA"},
      {DOT, "DOT"},
      {LEFT_BRACE, "LEFT_BRACE"},
      {RIGHT_BRACE, "RIGHT_BRACE"},
      {LEFT_BRACKET, "LEFT_BRACKET"},
      {RIGHT_BRACKET, "RIGHT_BRACKET"},

      // Literals
      {INTEGER_LITERAL, "INTEGER_LITERAL"},
      {FLOAT_LITERAL, "FLOAT_LITERAL"},
      {STRING_LITERAL, "STRING_LITERAL"},
      {BOOLEAN_LITERAL, "BOOLEAN_LITERAL"},
      {NULL_LITERAL, "NULL_LITERAL"},

      // Identifiers
      {IDENTIFIER, "IDENTIFIER"},

      // Operators
      {OPERATOR, "OPERATOR"},
      {OPERATOR_PLUS, "OPERATOR_PLUS"},
      {OPERATOR_MINUS, "OPERATOR_MINUS"},
      {OPERATOR_MULTIPLY, "OPERATOR_MULTIPLY"},
      {OPERATOR_DIVIDE, "OPERATOR_DIVIDE"},
      {OPERATOR_EQUAL, "OPERATOR_EQUAL"},
      {OPERATOR_NOT_EQUAL, "OPERATOR_NOT_EQUAL"},
      {OPERATOR_LESS_THAN, "OPERATOR_LESS_THAN"},
      {OPERATOR_LESS_EQUAL, "OPERATOR_LESS_EQUAL"},
      {OPERATOR_GREATER_THAN, "OPERATOR_GREATER_THAN"},
      {OPERATOR_GREATER_EQUAL, "OPERATOR_GREATER_EQUAL"},
      {OPERATOR_MODULO, "OPERATOR_MODULO"},
      {OPERATOR_AND, "OPERATOR_AND"},
      {OPERATOR_OR, "OPERATOR_OR"},
      {OPERATOR_NOT, "OPERATOR_NOT"},
      {OPERATOR_BITWISE_AND, "OPERATOR_BITWISE_AND"},
      {OPERATOR_BITWISE_OR, "OPERATOR_BITWISE_OR"},
      {OPERATOR_BITWISE_NOT, "OPERATOR_BITWISE_NOT"},
      {OPERATOR_BITWISE_XOR, "OPERATOR_BITWISE_XOR"},
      {OPERATOR_TERNARY, "OPERATOR_TERNARY"},
      {OPERATOR_AT, "OPERATOR_AT"},

      // Keywords - DDL
      {KEYWORD_CREATE, "KEYWORD_CREATE"},
      {KEYWORD_ALTER, "KEYWORD_ALTER"},
      {KEYWORD_DROP, "KEYWORD_DROP"},
      {KEYWORD_TRUNCATE, "KEYWORD_TRUNCATE"},
      {KEYWORD_RENAME, "KEYWORD_RENAME"},
      {KEYWORD_COMMENT, "KEYWORD_COMMENT"},
      {KEYWORD_ADD, "KEYWORD_ADD"},
      {KEYWORD_COLUMN, "KEYWORD_COLUMN"},
      {KEYWORD_MODIFY, "KEYWORD_MODIFY"},
      {KEYWORD_CONSTRAINT, "KEYWORD_CONSTRAINT"},

      // Keywords - DML
      {KEYWORD_SELECT, "KEYWORD_SELECT"},
      {KEYWORD_INSERT, "KEYWORD_INSERT"},
      {KEYWORD_UPDATE, "KEYWORD_UPDATE"},
      {KEYWORD_DELETE, "KEYWORD_DELETE"},
      {KEYWORD_MERGE, "KEYWORD_MERGE"},
      {KEYWORD_FROM, "KEYWORD_FROM"},
      {KEYWORD_INTO, "KEYWORD_INTO"},
      {KEYWORD_VALUES, "KEYWORD_VALUES"},
      {KEYWORD_SET, "KEYWORD_SET"},
      {KEYWORD_WHERE, "KEYWORD_WHERE"},
      {KEYWORD_GROUP, "KEYWORD_GROUP"},
      {KEYWORD_BY, "KEYWORD_BY"},
      {KEYWORD_HAVING, "KEYWORD_HAVING"},
      {KEYWORD_ORDER, "KEYWORD_ORDER"},
      {KEYWORD_LIMIT, "KEYWORD_LIMIT"},
      {KEYWORD_OFFSET, "KEYWORD_OFFSET"},
      {KEYWORD_DISTINCT, "KEYWORD_DISTINCT"},
      {KEYWORD_ALL, "KEYWORD_ALL"},
      {KEYWORD_AS, "KEYWORD_AS"},
      {KEYWORD_JOIN, "KEYWORD_JOIN"},
      {KEYWORD_INNER, "KEYWORD_INNER"},
      {KEYWORD_LEFT, "KEYWORD_LEFT"},
      {KEYWORD_RIGHT, "KEYWORD_RIGHT"},
      {KEYWORD_FULL, "KEYWORD_FULL"},
      {KEYWORD_OUTER, "KEYWORD_OUTER"},
      {KEYWORD_ON, "KEYWORD_ON"},
      {KEYWORD_USING, "KEYWORD_USING"},

      // Keywords - DCL
      {KEYWORD_GRANT, "KEYWORD_GRANT"},
      {KEYWORD_REVOKE, "KEYWORD_REVOKE"},
      {KEYWORD_DENY, "KEYWORD_DENY"},

      // Keywords - TCL
      {KEYWORD_BEGIN, "KEYWORD_BEGIN"},
      {KEYWORD_COMMIT, "KEYWORD_COMMIT"},
      {KEYWORD_ROLLBACK, "KEYWORD_ROLLBACK"},
      {KEYWORD_SAVEPOINT, "KEYWORD_SAVEPOINT"},
      {KEYWORD_TRANSACTION, "KEYWORD_TRANSACTION"},

      // Keywords - Logical Operators
      {KEYWORD_AND, "KEYWORD_AND"},
      {KEYWORD_OR, "KEYWORD_OR"},
      {KEYWORD_IN, "KEYWORD_IN"},
      {KEYWORD_EXISTS, "KEYWORD_EXISTS"},
      {KEYWORD_BETWEEN, "KEYWORD_BETWEEN"},
      {KEYWORD_LIKE, "KEYWORD_LIKE"},
      {KEYWORD_IS, "KEYWORD_IS"},

      // Keywords - Set Operations
      {KEYWORD_UNION, "KEYWORD_UNION"},
      {KEYWORD_INTERSECT, "KEYWORD_INTERSECT"},
      {KEYWORD_EXCEPT, "KEYWORD_EXCEPT"},

      // Keywords - Control Flow
      {KEYWORD_CASE, "KEYWORD_CASE"},
      {KEYWORD_WHEN, "KEYWORD_WHEN"},
      {KEYWORD_THEN, "KEYWORD_THEN"},
      {KEYWORD_ELSE, "KEYWORD_ELSE"},
      {KEYWORD_END, "KEYWORD_END"},
      {KEYWORD_IF, "KEYWORD_IF"},
      {KEYWORD_WHILE, "KEYWORD_WHILE"},
      {KEYWORD_FOR, "KEYWORD_FOR"},
      {KEYWORD_DO, "KEYWORD_DO"},

      // Keywords - Database Objects
      {KEYWORD_DATABASE, "KEYWORD_DATABASE"},
      {KEYWORD_TABLE, "KEYWORD_TABLE"},
      {KEYWORD_INDEX, "KEYWORD_INDEX"},
      {KEYWORD_VIEW, "KEYWORD_VIEW"},
      {KEYWORD_SEQUENCE, "KEYWORD_SEQUENCE"},
      {KEYWORD_TRIGGER, "KEYWORD_TRIGGER"},
      {KEYWORD_PROCEDURE, "KEYWORD_PROCEDURE"},
      {KEYWORD_FUNCTION, "KEYWORD_FUNCTION"},

      // Keywords - Constraints
      {KEYWORD_PRIMARY, "KEYWORD_PRIMARY"},
      {KEYWORD_KEY, "KEYWORD_KEY"},
      {KEYWORD_FOREIGN, "KEYWORD_FOREIGN"},
      {KEYWORD_REFERENCES, "KEYWORD_REFERENCES"},
      {KEYWORD_UNIQUE, "KEYWORD_UNIQUE"},
      {KEYWORD_CHECK, "KEYWORD_CHECK"},
      {KEYWORD_NOT, "KEYWORD_NOT"},
      {KEYWORD_NULL, "KEYWORD_NULL"},
      {KEYWORD_DEFAULT, "KEYWORD_DEFAULT"},
      {KEYWORD_AUTO_INCREMENT, "KEYWORD_AUTO_INCREMENT"},

      // Keywords - Data Types
      {KEYWORD_INT, "KEYWORD_INT"},
      {KEYWORD_INTEGER, "KEYWORD_INTEGER"},
      {KEYWORD_SMALLINT, "KEYWORD_SMALLINT"},
      {KEYWORD_BIGINT, "KEYWORD_BIGINT"},
      {KEYWORD_TINYINT, "KEYWORD_TINYINT"},
      {KEYWORD_VARCHAR, "KEYWORD_VARCHAR"},
      {KEYWORD_CHAR, "KEYWORD_CHAR"},
      {KEYWORD_TEXT, "KEYWORD_TEXT"},
      {KEYWORD_BLOB, "KEYWORD_BLOB"},
      {KEYWORD_CLOB, "KEYWORD_CLOB"},
      {KEYWORD_DECIMAL, "KEYWORD_DECIMAL"},
      {KEYWORD_NUMERIC, "KEYWORD_NUMERIC"},
      {KEYWORD_FLOAT, "KEYWORD_FLOAT"},
      {KEYWORD_DOUBLE, "KEYWORD_DOUBLE"},
      {KEYWORD_REAL, "KEYWORD_REAL"},
      {KEYWORD_DATE, "KEYWORD_DATE"},
      {KEYWORD_TIME, "KEYWORD_TIME"},
      {KEYWORD_TIMESTAMP, "KEYWORD_TIMESTAMP"},
      {KEYWORD_DATETIME, "KEYWORD_DATETIME"},
      {KEYWORD_YEAR, "KEYWORD_YEAR"},
      {KEYWORD_BOOLEAN, "KEYWORD_BOOLEAN"},
      {KEYWORD_BOOL, "KEYWORD_BOOL"},

      // Keywords - Others
      {KEYWORD_USE, "KEYWORD_USE"},
      {KEYWORD_SHOW, "KEYWORD_SHOW"},
      {KEYWORD_DESCRIBE, "KEYWORD_DESCRIBE"},
      {KEYWORD_EXPLAIN, "KEYWORD_EXPLAIN"},
      {KEYWORD_HELP, "KEYWORD_HELP"},
      {KEYWORD_STATUS, "KEYWORD_STATUS"},
      {KEYWORD_ASC, "KEYWORD_ASC"},
      {KEYWORD_DESC, "KEYWORD_DESC"},
      {KEYWORD_USER, "KEYWORD_USER"},
      {KEYWORD_TO, "KEYWORD_TO"},
      {KEYWORD_PRIVILEGES, "KEYWORD_PRIVILEGES"},
      {KEYWORD_WITH, "KEYWORD_WITH"},
      {KEYWORD_PASSWORD, "KEYWORD_PASSWORD"},
      {KEYWORD_IDENTIFIED, "KEYWORD_IDENTIFIED"},
      {KEYWORD_COLUMNS, "KEYWORD_COLUMNS"},
      {KEYWORD_INDEXES, "KEYWORD_INDEXES"},
      {KEYWORD_GRANTS, "KEYWORD_GRANTS"},
      {KEYWORD_DATABASES, "KEYWORD_DATABASES"},
      {KEYWORD_TABLES, "KEYWORD_TABLES"},
      
      // Keywords - LOAD DATA Statement
      {KEYWORD_LOAD, "KEYWORD_LOAD"},
      {KEYWORD_DATA, "KEYWORD_DATA"},
      {KEYWORD_INFILE, "KEYWORD_INFILE"},
      {KEYWORD_REPLACE, "KEYWORD_REPLACE"},
      {KEYWORD_IGNORE, "KEYWORD_IGNORE"},
      {KEYWORD_LOW_PRIORITY, "KEYWORD_LOW_PRIORITY"},
      {KEYWORD_CONCURRENT, "KEYWORD_CONCURRENT"},
      {KEYWORD_LOCAL, "KEYWORD_LOCAL"},
      {KEYWORD_PARTITION, "KEYWORD_PARTITION"},
      {KEYWORD_CHARACTER, "KEYWORD_CHARACTER"},
      {KEYWORD_FIELDS, "KEYWORD_FIELDS"},
      {KEYWORD_TERMINATED, "KEYWORD_TERMINATED"},
      {KEYWORD_OPTIONALLY, "KEYWORD_OPTIONALLY"},
      {KEYWORD_ENCLOSED, "KEYWORD_ENCLOSED"},
      {KEYWORD_ESCAPED, "KEYWORD_ESCAPED"},
      {KEYWORD_LINES, "KEYWORD_LINES"},
      {KEYWORD_STARTING, "KEYWORD_STARTING"},

      // Keywords - Trigger specific
      {KEYWORD_BEFORE, "KEYWORD_BEFORE"},
      {KEYWORD_AFTER, "KEYWORD_AFTER"},
      {KEYWORD_INSTEAD, "KEYWORD_INSTEAD"},
      {KEYWORD_OF, "KEYWORD_OF"},
      {KEYWORD_EACH, "KEYWORD_EACH"},
      {KEYWORD_ROW, "KEYWORD_ROW"},
      {KEYWORD_STATEMENT, "KEYWORD_STATEMENT"},
      
      // Keywords - Procedure specific
      {KEYWORD_OUT, "KEYWORD_OUT"},
      {KEYWORD_INOUT, "KEYWORD_INOUT"},
      {KEYWORD_RETURNS, "KEYWORD_RETURNS"},
      {KEYWORD_RETURN, "KEYWORD_RETURN"},
      
      // Keywords - Date/Time Functions
      {KEYWORD_NOW, "KEYWORD_NOW"},
      {KEYWORD_CURRENT_TIMESTAMP, "KEYWORD_CURRENT_TIMESTAMP"},
      
      // Keywords - LOAD DATA Statement
      {KEYWORD_LOAD, "KEYWORD_LOAD"},
      {KEYWORD_DATA, "KEYWORD_DATA"},
      {KEYWORD_INFILE, "KEYWORD_INFILE"},
      {KEYWORD_REPLACE, "KEYWORD_REPLACE"},
      {KEYWORD_IGNORE, "KEYWORD_IGNORE"},
      {KEYWORD_LOW_PRIORITY, "KEYWORD_LOW_PRIORITY"},
      {KEYWORD_CONCURRENT, "KEYWORD_CONCURRENT"},
      {KEYWORD_LOCAL, "KEYWORD_LOCAL"},
      {KEYWORD_PARTITION, "KEYWORD_PARTITION"},
      {KEYWORD_CHARACTER, "KEYWORD_CHARACTER"},
      {KEYWORD_FIELDS, "KEYWORD_FIELDS"},
      {KEYWORD_TERMINATED, "KEYWORD_TERMINATED"},
      {KEYWORD_OPTIONALLY, "KEYWORD_OPTIONALLY"},
      {KEYWORD_ENCLOSED, "KEYWORD_ENCLOSED"},
      {KEYWORD_ESCAPED, "KEYWORD_ESCAPED"},
      {KEYWORD_LINES, "KEYWORD_LINES"},
      {KEYWORD_STARTING, "KEYWORD_STARTING"},
      
      // Special tokens
      {END_OF_INPUT, "END_OF_INPUT"},
      {ERROR, "ERROR"},
      {UNKNOWN, "UNKNOWN"}};

  auto it = typeNames.find(type);
  if (it != typeNames.end()) {
    return it->second;
  }
  return "UNKNOWN_TYPE";
}

} // namespace sql_parser
} // namespace sqlcc
