SQLCC: sqlcc::sql_parser::Expression Class Reference
sqlcc::sql_parser::Expression Class Reference abstract
#include <ast_node.h>
Public Types
enum Type {
IDENTIFIER , STRING_LITERAL , NUMERIC_LITERAL , BINARY ,
UNARY , FUNCTION , EXISTS , IN
}
Public Member Functions
virtual Type getType () const =0
std::string getTypeName () const
Public Member Functions inherited from sqlcc::sql_parser::Node
virtual ~Node ()=default
virtual void accept (NodeVisitor &visitor)=0
Detailed Description
表达式节点基类
Definition at line 132 of file ast_node.h.
Member Enumeration Documentation
Type
enum sqlcc::sql_parser::Expression::Type
表达式类型枚举
Enumerator
IDENTIFIER
STRING_LITERAL
NUMERIC_LITERAL
BINARY
UNARY
FUNCTION
EXISTS
IN
Definition at line 137 of file ast_node.h.
            {
    IDENTIFIER,
    STRING_LITERAL,
    NUMERIC_LITERAL,
    BINARY,
    UNARY,
    FUNCTION,
    EXISTS,
    IN
  };
Member Function Documentation
getType()
virtual Type sqlcc::sql_parser::Expression::getType () const pure virtual
获取表达式类型
Implemented in sqlcc::sql_parser::IdentifierExpression, sqlcc::sql_parser::StringLiteralExpression, sqlcc::sql_parser::NumericLiteralExpression, sqlcc::sql_parser::BinaryExpression, sqlcc::sql_parser::UnaryExpression, sqlcc::sql_parser::FunctionExpression, sqlcc::sql_parser::ExistsExpression, and sqlcc::sql_parser::InExpression.
Referenced by sqlcc::ExpressionEvaluator::evaluate(), and getTypeName().
getTypeName()
std::string sqlcc::sql_parser::Expression::getTypeName () const
获取表达式类型的名称
Definition at line 8 of file ast_node.cpp.
{
    Type type = getType();
    switch (type) {
        case IDENTIFIER: return "IDENTIFIER";
        case STRING_LITERAL: return "STRING_LITERAL";
        case NUMERIC_LITERAL: return "NUMERIC_LITERAL";
        case BINARY: return "BINARY";
        case UNARY: return "UNARY";
        case FUNCTION: return "FUNCTION";
        case EXISTS: return "EXISTS";
        case IN: return "IN";
        default: return "UNKNOWN_EXPRESSION_TYPE";
    }
}
References BINARY, EXISTS, FUNCTION, getType(), IDENTIFIER, IN, NUMERIC_LITERAL, STRING_LITERAL, and UNARY.
The documentation for this class was generated from the following files:
include/sql_parser/ast_node.h
src/sql_parser/ast_node.cpp