SQLCC: sqlcc::TestDiskManager Class Reference
sqlcc::TestDiskManager Class Reference
测试专用的磁盘管理器类，可以模拟文件操作失败
#include <test_disk_manager.h>
Public Member Functions
TestDiskManager (const std::string &db_file, ConfigManager &config_manager)
构造函数
void SetSimulateWriteFailure (bool simulate_failure)
设置是否模拟写入失败
void SetSimulateFlushFailure (bool simulate_failure)
设置是否模拟刷新失败
void SetSimulateSeekFailure (bool simulate_failure)
设置是否模拟定位失败
bool TestWritePage (const Page &page)
模拟WritePage方法，可以模拟写入失败
bool TestReadPage (int32_t page_id, char *page_data)
模拟ReadPage方法，可以模拟定位失败
Public Member Functions inherited from sqlcc::DiskManager
DiskManager (const std::string &db_file, ConfigManager &config_manager)
~DiskManager ()
DiskManager (const DiskManager &)=delete
DiskManager & operator= (const DiskManager &)=delete
bool WritePage (int32_t page_id, const char *page_data)
写入指定页的数据
bool ReadPage (int32_t page_id, char *page_data)
bool BatchReadPages (const std::vector< int32_t > &page_ids, std::vector< char * > &page_data)
bool PrefetchPage (int32_t page_id)
bool BatchPrefetchPages (const std::vector< int32_t > &page_ids)
int32_t AllocatePage ()
bool DeallocatePage (int32_t page_id)
int32_t GetFileSize () const
bool Sync ()
std::unordered_map< std::string, uint64_t > GetIOStats () const
void ResetIOStats ()
void SetSimulateReadFailure (bool simulate)
设置是否模拟读取失败（仅用于测试）
void SetSimulateWriteFailure (bool simulate)
设置是否模拟写入失败（仅用于测试）
void SetSimulateSeekFailure (bool simulate)
设置是否模拟寻道失败（仅用于测试）
void SetSimulateFlushFailure (bool simulate)
设置是否模拟刷新失败（仅用于测试）
Private Attributes
bool simulate_write_failure_ = false
bool simulate_flush_failure_ = false
bool simulate_seek_failure_ = false
Detailed Description
测试专用的磁盘管理器类，可以模拟文件操作失败
Definition at line 13 of file test_disk_manager.h.
Constructor & Destructor Documentation
TestDiskManager()
sqlcc::TestDiskManager::TestDiskManager (const std::string & db_file, ConfigManager & config_manager) inline explicit
构造函数
Parameters
db_file 数据库文件路径
config_manager 配置管理器
Definition at line 20 of file test_disk_manager.h.
: DiskManager(db_file, config_manager) {}
Member Function Documentation
SetSimulateFlushFailure()
void sqlcc::TestDiskManager::SetSimulateFlushFailure (bool simulate_failure) inline
设置是否模拟刷新失败
Parameters
simulate_failure 是否模拟刷新失败
Definition at line 34 of file test_disk_manager.h.
{
        simulate_flush_failure_ = simulate_failure;
    }
References simulate_flush_failure_.
SetSimulateSeekFailure()
void sqlcc::TestDiskManager::SetSimulateSeekFailure (bool simulate_failure) inline
设置是否模拟定位失败
Parameters
simulate_failure 是否模拟定位失败
Definition at line 42 of file test_disk_manager.h.
{
        simulate_seek_failure_ = simulate_failure;
    }
References simulate_seek_failure_.
SetSimulateWriteFailure()
void sqlcc::TestDiskManager::SetSimulateWriteFailure (bool simulate_failure) inline
设置是否模拟写入失败
Parameters
simulate_failure 是否模拟写入失败
Definition at line 26 of file test_disk_manager.h.
{
        simulate_write_failure_ = simulate_failure;
    }
References simulate_write_failure_.
TestReadPage()
bool sqlcc::TestDiskManager::TestReadPage (int32_t page_id, char * page_data) inline
模拟ReadPage方法，可以模拟定位失败
Definition at line 84 of file test_disk_manager.h.
{
        if (simulate_seek_failure_) {
            // 模拟定位失败
            std::string error_msg = "Failed to seek to page " + std::to_string(page_id);
            SQLCC_LOG_ERROR(error_msg);
            return false;
        }
        // 正常读取
        return DiskManager::ReadPage(page_id, page_data);
    }
References sqlcc::DiskManager::ReadPage(), simulate_seek_failure_, and SQLCC_LOG_ERROR.
TestWritePage()
bool sqlcc::TestDiskManager::TestWritePage (const Page & page) inline
模拟WritePage方法，可以模拟写入失败
Definition at line 49 of file test_disk_manager.h.
{
        if (simulate_write_failure_) {
            // 模拟写入失败
            return false;
        }
        if (simulate_seek_failure_) {
            // 模拟定位失败
            int32_t page_id = page.GetPageId();
            std::string error_msg = "Failed to seek to page " + std::to_string(page_id);
            SQLCC_LOG_ERROR(error_msg);
            return false;
        }
        if (simulate_flush_failure_) {
            // 模拟刷新失败
            // 先执行正常的写入操作
            bool write_success = DiskManager::WritePage(page.GetPageId(), page.GetData());
            if (write_success) {
                // 模拟刷新失败
                int32_t page_id = page.GetPageId();
                std::string error_msg = "Failed to flush page " + std::to_string(page_id) + " to disk";
                SQLCC_LOG_ERROR(error_msg);
                return false;
            }
            return false;
        }
        // 正常写入
        return DiskManager::WritePage(page.GetPageId(), page.GetData());
    }
References sqlcc::Page::GetData(), sqlcc::Page::GetPageId(), simulate_flush_failure_, simulate_seek_failure_, simulate_write_failure_, SQLCC_LOG_ERROR, and sqlcc::DiskManager::WritePage().
Member Data Documentation
simulate_flush_failure_
bool sqlcc::TestDiskManager::simulate_flush_failure_ = false private
Definition at line 101 of file test_disk_manager.h.
Referenced by SetSimulateFlushFailure(), and TestWritePage().
simulate_seek_failure_
bool sqlcc::TestDiskManager::simulate_seek_failure_ = false private
Definition at line 104 of file test_disk_manager.h.
Referenced by SetSimulateSeekFailure(), TestReadPage(), and TestWritePage().
simulate_write_failure_
bool sqlcc::TestDiskManager::simulate_write_failure_ = false private
Definition at line 98 of file test_disk_manager.h.
Referenced by SetSimulateWriteFailure(), and TestWritePage().
The documentation for this class was generated from the following file:
tests/test_disk_manager.h