SQLCC: sqlcc::ExpressionEvaluator Class Reference
sqlcc::ExpressionEvaluator Class Reference
表达式求值器
#include <constraint_executor.h>
Static Public Member Functions
static bool evaluate (const sql_parser::Expression *expr, const std::vector< std::string > &record, const std::vector< sql_parser::ColumnDefinition > &table_schema)
求值表达式
Static Private Member Functions
static bool evaluateBinaryExpression (const sql_parser::BinaryExpression *expr, const std::vector< std::string > &record, const std::vector< sql_parser::ColumnDefinition > &table_schema)
求值二元表达式
static std::string evaluateIdentifier (const sql_parser::IdentifierExpression *expr, const std::vector< std::string > &record, const std::vector< sql_parser::ColumnDefinition > &table_schema)
求值标识符（列引用）
static int getColumnIndex (const std::string &column_name, const std::vector< sql_parser::ColumnDefinition > &table_schema)
获取列索引
Detailed Description
表达式求值器
为CHECK约束提供表达式求值功能
Definition at line 281 of file constraint_executor.h.
Member Function Documentation
evaluate()
bool sqlcc::ExpressionEvaluator::evaluate (const sql_parser::Expression * expr, const std::vector< std::string > & record, const std::vector< sql_parser::ColumnDefinition > & table_schema) static
求值表达式
Parameters
expr 表达式节点
record 记录数据
table_schema 表结构
Returns
求值结果
Definition at line 392 of file constraint_executor.cpp.
{
  if (!expr)
    return true;
  switch (expr->getType()) {
  case sql_parser::Expression::BINARY: {
    const auto *binary_expr =
        dynamic_cast<const sql_parser::BinaryExpression *>(expr);
    return evaluateBinaryExpression(binary_expr, record, table_schema);
  }
  case sql_parser::Expression::IDENTIFIER: {
    // 标识符通常为真（简化处理）
    return true;
  }
  case sql_parser::Expression::STRING_LITERAL:
  case sql_parser::Expression::NUMERIC_LITERAL: {
    // 字面量通常为真（除非是布尔字面量）
    return true;
  }
  default: {
    // 其他表达式类型默认通过
    return true;
  }
  }
}
References sqlcc::sql_parser::Expression::BINARY, evaluateBinaryExpression(), sqlcc::sql_parser::Expression::getType(), sqlcc::sql_parser::Expression::IDENTIFIER, sqlcc::sql_parser::Expression::NUMERIC_LITERAL, and sqlcc::sql_parser::Expression::STRING_LITERAL.
Referenced by sqlcc::CheckConstraintExecutor::evaluateCheckCondition().
evaluateBinaryExpression()
bool sqlcc::ExpressionEvaluator::evaluateBinaryExpression (const sql_parser::BinaryExpression * expr, const std::vector< std::string > & record, const std::vector< sql_parser::ColumnDefinition > & table_schema) static private
求值二元表达式
Definition at line 424 of file constraint_executor.cpp.
{
  if (!expr)
    return true;
  // 简化的二元表达式求值
  // 这里只处理最基本的比较操作
  auto op = expr->getOperator();
  switch (op) {
  case sql_parser::Token::Type::LPAREN:
  case sql_parser::Token::Type::RPAREN:
  case sql_parser::Token::Type::SEMICOLON: {
    // 比较操作的简化验证
    return true; // 占位符实现
  }
  default: {
    return true;
  }
  }
}
References sqlcc::sql_parser::BinaryExpression::getOperator(), sqlcc::sql_parser::Token::LPAREN, sqlcc::sql_parser::Token::RPAREN, and sqlcc::sql_parser::Token::SEMICOLON.
Referenced by evaluate().
evaluateIdentifier()
static std::string sqlcc::ExpressionEvaluator::evaluateIdentifier (const sql_parser::IdentifierExpression * expr, const std::vector< std::string > & record, const std::vector< sql_parser::ColumnDefinition > & table_schema) static private
求值标识符（列引用）
getColumnIndex()
static int sqlcc::ExpressionEvaluator::getColumnIndex (const std::string & column_name, const std::vector< sql_parser::ColumnDefinition > & table_schema) static private
获取列索引
The documentation for this class was generated from the following files:
include/constraint_executor.h
src/sql_executor/constraint_executor.cpp