SQLCC: sqlcc::SqlExecutor Class Reference
sqlcc::SqlExecutor Class Reference
#include <sql_executor.h>
Public Member Functions
SqlExecutor ()
~SqlExecutor ()
std::string Execute (const std::string &sql)
std::string ExecuteFile (const std::string &file_path)
std::string GetLastError ()
void SetError (const std::string &error)
Private Member Functions
std::string ExecuteSelect (const std::string &sql)
std::string ExecuteInsert (const std::string &sql)
std::string ExecuteUpdate (const std::string &sql)
std::string ExecuteDelete (const std::string &sql)
Private Attributes
std::string last_error_
std::shared_ptr< UserManager > user_manager_
Detailed Description
Definition at line 11 of file sql_executor.h.
Constructor & Destructor Documentation
SqlExecutor()
sqlcc::SqlExecutor::SqlExecutor ()
Definition at line 9 of file sql_executor.cpp.
    : last_error_(""), user_manager_(std::make_shared<UserManager>()) {}
~SqlExecutor()
sqlcc::SqlExecutor::~SqlExecutor ()
Definition at line 13 of file sql_executor.cpp.
{
  // 析构函数实现
}
Member Function Documentation
Execute()
std::string sqlcc::SqlExecutor::Execute (const std::string & sql)
Definition at line 18 of file sql_executor.cpp.
{
  std::string trimmed_sql = sql;
  TrimString(trimmed_sql);
  // 简单的SQL语句类型识别和分发
  std::string upper_sql = trimmed_sql;
  std::transform(upper_sql.begin(), upper_sql.end(), upper_sql.begin(),
                 ::toupper);
  if (upper_sql.find("SELECT") == 0) {
    return ExecuteSelect(trimmed_sql);
  } else if (upper_sql.find("INSERT") == 0) {
    return ExecuteInsert(trimmed_sql);
  } else if (upper_sql.find("UPDATE") == 0) {
    return ExecuteUpdate(trimmed_sql);
  } else if (upper_sql.find("DELETE") == 0) {
    return ExecuteDelete(trimmed_sql);
  }
  return "SQL语句类型不支持";
}
References ExecuteDelete(), ExecuteInsert(), ExecuteSelect(), ExecuteUpdate(), and sqlcc::TrimString().
Referenced by handleInteractiveCommand(), main(), main(), sqlcc::test::IndexConstraintBenchmark::RunAllTests(), sqlcc::test::LargeScaleIndexConstraintTest::RunAllTests(), sqlcc::test::NetworkPerformanceTest::RunAllTests(), sqlcc::test::CpuIntensivePerformanceTest::SetUp(), sqlcc::test::MemoryStressTest::SetUp(), sqlcc::test::LongTermStabilityTest::SetUp(), SqlExecutorTest::SetUp(), sqlcc::test::CpuIntensivePerformanceTest::TearDown(), sqlcc::test::MemoryStressTest::TearDown(), sqlcc::test::LongTermStabilityTest::TearDown(), SqlExecutorTest::TearDown(), TestErrorHandling(), TestSqlExecutorComprehensive(), TestSqlExecutorMinimal(), TestSqlExecutorUncoveredParts(), TestSqlExecutorUnit(), and TestUserManagement().
ExecuteDelete()
std::string sqlcc::SqlExecutor::ExecuteDelete (const std::string & sql) private
Definition at line 66 of file sql_executor.cpp.
{
  return "删除成功";
}
Referenced by Execute().
ExecuteFile()
std::string sqlcc::SqlExecutor::ExecuteFile (const std::string & file_path)
Definition at line 41 of file sql_executor.cpp.
{
  // 简化实现：直接返回成功信息
  return "文件执行功能暂未实现";
}
Referenced by executeScript(), TestErrorHandling(), TestExecuteFile(), TestSqlExecutorComprehensive(), TestSqlExecutorUncoveredParts(), and TestSqlExecutorUnit().
ExecuteInsert()
std::string sqlcc::SqlExecutor::ExecuteInsert (const std::string & sql) private
Definition at line 58 of file sql_executor.cpp.
{
  return "插入成功";
}
Referenced by Execute().
ExecuteSelect()
std::string sqlcc::SqlExecutor::ExecuteSelect (const std::string & sql) private
Definition at line 53 of file sql_executor.cpp.
{
  return "SELECT查询结果";
}
Referenced by Execute().
ExecuteUpdate()
std::string sqlcc::SqlExecutor::ExecuteUpdate (const std::string & sql) private
Definition at line 62 of file sql_executor.cpp.
{
  return "更新成功";
}
Referenced by Execute().
GetLastError()
std::string sqlcc::SqlExecutor::GetLastError ()
Definition at line 47 of file sql_executor.cpp.
{ return last_error_; }
References last_error_.
Referenced by TestSqlExecutorComprehensive(), TestSqlExecutorMinimal(), TestSqlExecutorUncoveredParts(), and TestSqlExecutorUnit().
SetError()
void sqlcc::SqlExecutor::SetError (const std::string & error)
Definition at line 50 of file sql_executor.cpp.
{ last_error_ = error; }
References last_error_.
Referenced by TestSqlExecutorMinimal().
Member Data Documentation
last_error_
std::string sqlcc::SqlExecutor::last_error_ private
Definition at line 38 of file sql_executor.h.
Referenced by GetLastError(), and SetError().
user_manager_
std::shared_ptr<UserManager> sqlcc::SqlExecutor::user_manager_ private
Definition at line 39 of file sql_executor.h.
The documentation for this class was generated from the following files:
include/sql_executor.h
src/sql_executor.cpp
src/sql_executor/sql_executor.cpp