SQLCC: sqlcc::UniqueConstraintExecutor Class Reference
sqlcc::UniqueConstraintExecutor Class Reference
唯一约束执行器
#include <constraint_executor.h>
Public Member Functions
UniqueConstraintExecutor (const sql_parser::TableConstraint &constraint, StorageEngine &storage_engine, const std::string &table_name, bool is_primary_key=false)
构造函数
bool validateInsert (const std::vector< std::string > &record, const std::vector< sql_parser::ColumnDefinition > &table_schema) override
验证插入操作
bool validateUpdate (const std::vector< std::string > &old_record, const std::vector< std::string > &new_record, const std::vector< sql_parser::ColumnDefinition > &table_schema) override
验证更新操作
bool validateDelete (const std::vector< std::string > &record, const std::vector< sql_parser::ColumnDefinition > &table_schema) override
验证删除操作
const std::string & getConstraintName () const override
获取约束名称
sql_parser::TableConstraint::Type getConstraintType () const override
获取约束类型
Public Member Functions inherited from sqlcc::ConstraintExecutor
virtual ~ConstraintExecutor ()=default
Private Member Functions
bool checkUniqueness (const std::vector< std::string > &values)
检查值是否唯一
std::vector< std::string > getConstraintValues (const std::vector< std::string > &record, const std::vector< sql_parser::ColumnDefinition > &table_schema)
获取记录中约束列的值
std::string toLower (const std::string &str) const
字符串转换为小写
Private Attributes
std::reference_wrapper< const sql_parser::TableConstraint > constraint_
StorageEngine & storage_engine_
std::string table_name_
bool is_primary_key_
std::vector< std::string > lower_constraint_columns_
Detailed Description
唯一约束执行器
负责验证唯一性约束，包括主键和UNIQUE约束
Definition at line 163 of file constraint_executor.h.
Constructor & Destructor Documentation
UniqueConstraintExecutor()
sqlcc::UniqueConstraintExecutor::UniqueConstraintExecutor (const sql_parser::TableConstraint & constraint, StorageEngine & storage_engine, const std::string & table_name, bool is_primary_key = false)
构造函数
Parameters
constraint 唯一约束定义（主键或UNIQUE）
storage_engine 存储引擎引用
table_name 表名
is_primary_key 是否为主键约束
Definition at line 130 of file constraint_executor.cpp.
    : constraint_(constraint),
      storage_engine_(storage_engine),
      table_name_(table_name),
      is_primary_key_(is_primary_key) {
  // 将唯一约束列名转换为小写
  // 注意：这里需要根据TableConstraint类型获取列信息
  // 为了简化，这里暂时假设可以获取列信息
  (void)constraint; // 避免未使用参数警告
  (void)storage_engine; // 避免未使用参数警告
  (void)table_name; // 避免未使用参数警告
  (void)is_primary_key; // 避免未使用参数警告
}
Member Function Documentation
checkUniqueness()
bool sqlcc::UniqueConstraintExecutor::checkUniqueness (const std::vector< std::string > & values) private
检查值是否唯一
Parameters
values 要检查的值列表
Returns
true if values are unique
Definition at line 235 of file constraint_executor.cpp.
{
  try {
    // 构建SELECT查询来检查是否存在重复值
    std::string query = "SELECT COUNT(*) FROM " + table_name_ + " WHERE ";
    std::vector<std::string> conditions;
    if (is_primary_key_) {
      const auto &pk_constraint =
          dynamic_cast<const sql_parser::PrimaryKeyConstraint &>(
              constraint_.get());
      const auto &columns = pk_constraint.getColumns();
      for (size_t i = 0; i < columns.size(); ++i) {
        std::string condition = columns[i] + " = '" + values[i] + "'";
        conditions.push_back(condition);
      }
    } else {
      const auto &unique_constraint =
          dynamic_cast<const sql_parser::UniqueConstraint &>(constraint_.get());
      const auto &columns = unique_constraint.getColumns();
      for (size_t i = 0; i < columns.size(); ++i) {
        std::string condition = columns[i] + " = '" + values[i] + "'";
        conditions.push_back(condition);
      }
    }
    // 连接所有条件
    for (size_t i = 0; i < conditions.size(); ++i) {
      if (i > 0)
        query += " AND ";
      query += conditions[i];
    }
    // 实际的查询执行应当返回是否存在记录
    // 这里返回true表示没有重复记录，允许插入
    return true; // 占位符实现
  } catch (const std::exception &e) {
    // 记录错误但不抛出异常，返回false表示验证失败
    return false;
  }
}
References constraint_, sqlcc::sql_parser::PrimaryKeyConstraint::getColumns(), sqlcc::sql_parser::UniqueConstraint::getColumns(), is_primary_key_, and table_name_.
Referenced by validateInsert(), and validateUpdate().
getConstraintName()
const std::string & sqlcc::UniqueConstraintExecutor::getConstraintName () const override virtual
获取约束名称
Returns
约束名称
Implements sqlcc::ConstraintExecutor.
Definition at line 225 of file constraint_executor.cpp.
{
  return constraint_.get().getName();
}
References constraint_.
getConstraintType()
sql_parser::TableConstraint::Type sqlcc::UniqueConstraintExecutor::getConstraintType () const override virtual
获取约束类型
Returns
约束类型
Implements sqlcc::ConstraintExecutor.
Definition at line 230 of file constraint_executor.cpp.
{
  return is_primary_key_ ? sql_parser::TableConstraint::PRIMARY_KEY
                         : sql_parser::TableConstraint::UNIQUE;
}
References is_primary_key_, sqlcc::sql_parser::TableConstraint::PRIMARY_KEY, and sqlcc::sql_parser::TableConstraint::UNIQUE.
getConstraintValues()
std::vector< std::string > sqlcc::UniqueConstraintExecutor::getConstraintValues (const std::vector< std::string > & record, const std::vector< sql_parser::ColumnDefinition > & table_schema) private
获取记录中约束列的值
Parameters
record 记录数据
table_schema 表结构
Returns
约束列值列表
Definition at line 279 of file constraint_executor.cpp.
{
  std::vector<std::string> constraint_values;
  // 获取约束涉及的所有列名
  std::vector<std::string> constraint_columns;
  if (is_primary_key_) {
    const auto &pk_constraint =
        dynamic_cast<const sql_parser::PrimaryKeyConstraint &>(
            constraint_.get());
    constraint_columns = pk_constraint.getColumns();
  } else {
    const auto &unique_constraint =
        dynamic_cast<const sql_parser::UniqueConstraint &>(constraint_.get());
    constraint_columns = unique_constraint.getColumns();
  }
  // 将列名转换为小写
  std::vector<std::string> lower_columns;
  for (const auto &col : constraint_columns) {
    lower_columns.push_back(toLower(col));
  }
  // 按照列的顺序提取值
  for (const auto &constraint_col : lower_columns) {
    // 在表结构中找到对应列的索引
    for (size_t i = 0; i < table_schema.size(); ++i) {
      if (toLower(table_schema[i].getName()) == constraint_col) {
        if (i < record.size()) {
          constraint_values.push_back(record[i]);
        } else {
          constraint_values.push_back(""); // 缺少值的情况
        }
        break;
      }
    }
  }
  return constraint_values;
}
References constraint_, sqlcc::sql_parser::PrimaryKeyConstraint::getColumns(), sqlcc::sql_parser::UniqueConstraint::getColumns(), is_primary_key_, and toLower().
Referenced by validateInsert(), and validateUpdate().
toLower()
std::string sqlcc::UniqueConstraintExecutor::toLower (const std::string & str) const private
字符串转换为小写
Parameters
str 输入字符串
Returns
小写字符串
Referenced by getConstraintValues().
validateDelete()
bool sqlcc::UniqueConstraintExecutor::validateDelete (const std::vector< std::string > & record, const std::vector< sql_parser::ColumnDefinition > & table_schema) override virtual
验证删除操作
Parameters
record 要删除的记录
table_schema 表结构信息
Returns
true if validation passes, false otherwise
Implements sqlcc::ConstraintExecutor.
Definition at line 218 of file constraint_executor.cpp.
{
  // 删除操作不影响唯一性约束
  return true;
}
validateInsert()
bool sqlcc::UniqueConstraintExecutor::validateInsert (const std::vector< std::string > & record, const std::vector< sql_parser::ColumnDefinition > & table_schema) override virtual
验证插入操作
Parameters
record 要插入的记录
table_schema 表结构信息
Returns
true if validation passes, false otherwise
Implements sqlcc::ConstraintExecutor.
Definition at line 148 of file constraint_executor.cpp.
{
  // 获取约束列的值
  std::vector<std::string> constraint_values =
      getConstraintValues(record, table_schema);
  // 检查值列表中是否有空值（对于主键，不允许NULL；对于唯一索引，允许NULL但需要特殊处理）
  bool has_null = false;
  for (const auto &value : constraint_values) {
    if (value.empty()) {
      has_null = true;
      break;
    }
  }
  // 如果是主键约束，NULL值不允许
  if (is_primary_key_ && has_null) {
    return false;
  }
  // 如果有NULL值且不是主键约束，允许插入（SQL标准：NULL值不参与唯一性检查）
  if (!is_primary_key_ && has_null) {
    return true;
  }
  // 检查唯一性
  return checkUniqueness(constraint_values);
}
References checkUniqueness(), getConstraintValues(), and is_primary_key_.
validateUpdate()
bool sqlcc::UniqueConstraintExecutor::validateUpdate (const std::vector< std::string > & old_record, const std::vector< std::string > & new_record, const std::vector< sql_parser::ColumnDefinition > & table_schema) override virtual
验证更新操作
Parameters
old_record 旧记录
new_record 新记录
table_schema 表结构信息
Returns
true if validation passes, false otherwise
Implements sqlcc::ConstraintExecutor.
Definition at line 179 of file constraint_executor.cpp.
{
  // 获取新旧记录的约束列值
  std::vector<std::string> old_values =
      getConstraintValues(old_record, table_schema);
  std::vector<std::string> new_values =
      getConstraintValues(new_record, table_schema);
  // 如果新旧值相同，不需要验证
  if (old_values == new_values) {
    return true;
  }
  // 检查新值是否包含NULL
  bool has_null = false;
  for (const auto &value : new_values) {
    if (value.empty()) {
      has_null = true;
      break;
    }
  }
  // 主键不允许NULL
  if (is_primary_key_ && has_null) {
    return false;
  }
  // 非主键约束的NULL值允许
  if (!is_primary_key_ && has_null) {
    return true;
  }
  // 检查新值的唯一性
  return checkUniqueness(new_values);
}
References checkUniqueness(), getConstraintValues(), and is_primary_key_.
Member Data Documentation
constraint_
std::reference_wrapper<const sql_parser::TableConstraint> sqlcc::UniqueConstraintExecutor::constraint_ private
Definition at line 219 of file constraint_executor.h.
Referenced by checkUniqueness(), getConstraintName(), and getConstraintValues().
is_primary_key_
bool sqlcc::UniqueConstraintExecutor::is_primary_key_ private
Definition at line 222 of file constraint_executor.h.
Referenced by checkUniqueness(), getConstraintType(), getConstraintValues(), validateInsert(), and validateUpdate().
lower_constraint_columns_
std::vector<std::string> sqlcc::UniqueConstraintExecutor::lower_constraint_columns_ private
Definition at line 223 of file constraint_executor.h.
storage_engine_
StorageEngine& sqlcc::UniqueConstraintExecutor::storage_engine_ private
Definition at line 220 of file constraint_executor.h.
table_name_
std::string sqlcc::UniqueConstraintExecutor::table_name_ private
Definition at line 221 of file constraint_executor.h.
Referenced by checkUniqueness().
The documentation for this class was generated from the following files:
include/constraint_executor.h
src/sql_executor/constraint_executor.cpp