SQLCC: sqlcc::Logger Class Reference
sqlcc::Logger Class Reference
简单日志记录器类
#include <logger.h>
Public Member Functions
void SetLogLevel (LogLevel level)
设置日志级别
void SetLogFile (const std::string &filename)
设置日志文件
void Debug (const std::string &message)
记录调试日志
void Info (const std::string &message)
记录信息日志
void Warn (const std::string &message)
记录警告日志
void Error (const std::string &message)
记录错误日志
Static Public Member Functions
static Logger & GetInstance ()
获取单例实例
Private Member Functions
Logger ()
私有构造函数
Logger (const Logger &)=delete
禁止拷贝构造函数
Logger & operator= (const Logger &)=delete
禁止赋值操作
void Log (LogLevel level, const std::string &message)
记录日志的实际实现
Private Attributes
LogLevel log_level_
当前日志级别
std::ofstream log_file_
日志文件流
bool use_file_
是否使用文件输出
Detailed Description
简单日志记录器类
Why: 需要一个统一的日志记录接口来记录系统运行状态、调试信息和错误信息 What: Logger类提供单例模式的日志记录功能，支持多种日志级别和输出方式 How: 使用单例模式确保全局只有一个日志记录器实例，提供多种日志记录方法
Definition at line 71 of file logger.h.
Constructor & Destructor Documentation
Logger() [1/2]
sqlcc::Logger::Logger () inline private
私有构造函数
Why: 防止外部直接创建Logger实例，确保单例模式的正确实现 What: Logger类的私有构造函数 How: 将构造函数声明为private，只允许GetInstance方法访问
Definition at line 177 of file logger.h.
: log_level_(LogLevel::INFO), use_file_(false) {}
Logger() [2/2]
sqlcc::Logger::Logger (const Logger &) private delete
禁止拷贝构造函数
Why: 防止通过拷贝构造函数创建新的Logger实例，确保单例模式的正确实现 What: 将拷贝构造函数声明为delete，禁止编译器自动生成 How: 使用= delete语法显式删除拷贝构造函数
Member Function Documentation
Debug()
void sqlcc::Logger::Debug (const std::string & message) inline
记录调试日志
Why: 需要记录详细的调试信息，帮助开发者了解系统内部状态 What: Debug方法记录DEBUG级别的日志消息 How: 调用Log方法，传入DEBUG级别和消息内容
Parameters
message 日志消息
Definition at line 126 of file logger.h.
{
        Log(LogLevel::DEBUG, message);
    }
References sqlcc::DEBUG, and Log().
Error()
void sqlcc::Logger::Error (const std::string & message) inline
记录错误日志
Why: 需要记录严重错误，帮助诊断和解决系统问题 What: Error方法记录ERROR级别的日志消息 How: 调用Log方法，传入ERROR级别和消息内容
Parameters
message 日志消息
Definition at line 165 of file logger.h.
{
        Log(LogLevel::ERROR, message);
    }
References sqlcc::ERROR, and Log().
GetInstance()
static Logger & sqlcc::Logger::GetInstance () inline static
获取单例实例
Why: 需要确保全局只有一个日志记录器实例，避免多个实例造成的资源浪费和日志混乱 What: GetInstance方法返回Logger类的唯一实例引用 How: 使用静态局部变量实现线程安全的单例模式
Returns
Logger实例引用
Definition at line 82 of file logger.h.
{
        // Why: 使用静态局部变量实现线程安全的懒加载单例
        // What: 定义静态局部变量instance，在第一次调用时初始化
        // How: 使用static关键字定义局部变量，C++11保证线程安全
        static Logger instance;
        return instance;
    }
Info()
void sqlcc::Logger::Info (const std::string & message) inline
记录信息日志
Why: 需要记录系统正常运行状态的信息，帮助了解系统运行情况 What: Info方法记录INFO级别的日志消息 How: 调用Log方法，传入INFO级别和消息内容
Parameters
message 日志消息
Definition at line 139 of file logger.h.
{
        Log(LogLevel::INFO, message);
    }
References sqlcc::INFO, and Log().
Log()
void sqlcc::Logger::Log (LogLevel level, const std::string & message) inline private
记录日志的实际实现
Why: 需要一个统一的日志记录实现，处理时间戳、级别过滤和输出 What: Log方法根据日志级别过滤消息，添加时间戳和级别信息，输出到控制台或文件 How: 检查日志级别，获取当前时间，格式化日志消息，选择输出流并输出
Parameters
level 日志级别
message 日志消息内容
Definition at line 207 of file logger.h.
{
        if (level < log_level_) {
            return;
        }
        auto now = std::chrono::system_clock::now();
        auto time_t = std::chrono::system_clock::to_time_t(now);
        auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
            now.time_since_epoch()) % 1000;
        std::ostringstream timestamp;
        timestamp << std::put_time(std::localtime(&time_t), "%Y-%m-%d %H:%M:%S");
        timestamp << '.' << std::setfill('0') << std::setw(3) << ms.count();
        std::string level_str;
        switch (level) {
            case LogLevel::DEBUG: level_str = "DEBUG"; break;
            case LogLevel::INFO:  level_str = "INFO";  break;
            case LogLevel::WARN:  level_str = "WARN";  break;
            case LogLevel::ERROR: level_str = "ERROR"; break;
        }
        std::ostringstream log_msg;
        log_msg << "[" << timestamp.str() << "] [" << level_str << "] " << message;
        if (use_file_ && log_file_.is_open()) {
            log_file_ << log_msg.str() << std::endl;
            log_file_.flush();
        } else {
            if (level == LogLevel::ERROR) {
                std::cerr << log_msg.str() << std::endl;
            } else {
                std::cout << log_msg.str() << std::endl;
            }
        }
    }
References sqlcc::DEBUG, sqlcc::ERROR, sqlcc::INFO, log_file_, log_level_, use_file_, and sqlcc::WARN.
Referenced by Debug(), Error(), Info(), and Warn().
operator=()
Logger & sqlcc::Logger::operator= (const Logger &) private delete
禁止赋值操作
Why: 防止通过赋值操作创建新的Logger实例，确保单例模式的正确实现 What: 将赋值运算符声明为delete，禁止编译器自动生成 How: 使用= delete语法显式删除赋值运算符
SetLogFile()
void sqlcc::Logger::SetLogFile (const std::string & filename) inline
设置日志文件
Why: 需要将日志输出到文件，便于长期保存和后续分析 What: SetLogFile方法打开指定的日志文件，将日志输出到文件而不是控制台 How: 使用std::ofstream打开文件，设置输出和追加模式
Parameters
filename 日志文件名
Definition at line 112 of file logger.h.
{
        log_file_.open(filename, std::ios::out | std::ios::app);
        use_file_ = log_file_.is_open();
    }
References log_file_, and use_file_.
SetLogLevel()
void sqlcc::Logger::SetLogLevel (LogLevel level) inline
设置日志级别
Why: 需要控制日志输出的详细程度，过滤掉不重要的日志信息 What: SetLogLevel方法设置当前日志级别，只有等于或高于此级别的日志才会被输出 How: 将传入的日志级别赋值给成员变量log_level_
Parameters
level 日志级别
Definition at line 99 of file logger.h.
{
        log_level_ = level;
    }
References log_level_.
Warn()
void sqlcc::Logger::Warn (const std::string & message) inline
记录警告日志
Why: 需要记录潜在问题，提醒开发者注意可能的问题 What: Warn方法记录WARN级别的日志消息 How: 调用Log方法，传入WARN级别和消息内容
Parameters
message 日志消息
Definition at line 152 of file logger.h.
{
        Log(LogLevel::WARN, message);
    }
References Log(), and sqlcc::WARN.
Member Data Documentation
log_file_
std::ofstream sqlcc::Logger::log_file_ private
日志文件流
Definition at line 245 of file logger.h.
Referenced by Log(), and SetLogFile().
log_level_
LogLevel sqlcc::Logger::log_level_ private
当前日志级别
Definition at line 244 of file logger.h.
Referenced by Log(), and SetLogLevel().
use_file_
bool sqlcc::Logger::use_file_ private
是否使用文件输出
Definition at line 246 of file logger.h.
Referenced by Log(), and SetLogFile().
The documentation for this class was generated from the following file:
include/logger.h