SQLCC: SqlNetworkTest Class Reference
SqlNetworkTest Class Reference
Protected Member Functions
SqlNetworkTest ()
void ConfigureClient (bool disable_encryption, bool disable_auth)
void TestConnection ()
void SetUp () override
void TearDown () override
Static Protected Member Functions
static void SetUpTestSuite ()
Protected Attributes
SqlNetworkTestClient client
Static Protected Attributes
static constexpr int kTestPort = 5000
static constexpr const char * kTestHost = "127.0.0.1"
static constexpr const char * kTestUsername = "admin"
static constexpr const char * kTestPassword = "admin"
static constexpr bool kDisableEncryption = true
static constexpr bool kDisableAuth = true
Detailed Description
Definition at line 230 of file sql_network_test.cpp.
Constructor & Destructor Documentation
SqlNetworkTest()
SqlNetworkTest::SqlNetworkTest () inline protected
Definition at line 246 of file sql_network_test.cpp.
: client(kTestHost, kTestPort, kDisableEncryption, kDisableAuth) {}
Member Function Documentation
ConfigureClient()
void SqlNetworkTest::ConfigureClient (bool disable_encryption, bool disable_auth) inline protected
Definition at line 249 of file sql_network_test.cpp.
{
        client.SetDisableEncryption(disable_encryption);
        client.SetDisableAuth(disable_auth);
        std::cout << "Client configured: encryption=" << (disable_encryption ? "disabled" : "enabled")
                  << ", auth=" << (disable_auth ? "disabled" : "enabled") << std::endl;
    }
References client, SqlNetworkTestClient::SetDisableAuth(), and SqlNetworkTestClient::SetDisableEncryption().
SetUp()
void SqlNetworkTest::SetUp () inline override protected
Definition at line 268 of file sql_network_test.cpp.
{
        // 尝试连接服务器，重试几次
        int retry_count = 5;
        while (retry_count > 0) {
            if (client.Connect()) {
                // 尝试认证
                if (client.Authenticate(kTestUsername, kTestPassword)) {
                    break;
                }
            }
            retry_count--;
            this_thread::sleep_for(chrono::seconds(1));
        }
        // 清理之前可能存在的表
        if (client.IsConnected()) {
            client.ExecuteQuery("DROP TABLE IF EXISTS network_test_users");
            client.ExecuteQuery("DROP TABLE IF EXISTS network_test_products");
        }
    }
References SqlNetworkTestClient::Authenticate(), client, SqlNetworkTestClient::Connect(), SqlNetworkTestClient::ExecuteQuery(), SqlNetworkTestClient::IsConnected(), kTestPassword, and kTestUsername.
SetUpTestSuite()
static void SqlNetworkTest::SetUpTestSuite () inline static protected
Definition at line 239 of file sql_network_test.cpp.
{
        // 启动服务器（在实际测试中可能需要单独启动）
        std::cout << "Test suite setup: Server should be running on port 5000" << std::endl;
    }
TearDown()
void SqlNetworkTest::TearDown () inline override protected
Definition at line 290 of file sql_network_test.cpp.
{
        // 清理测试环境
        if (client.IsConnected()) {
            client.ExecuteQuery("DROP TABLE IF EXISTS network_test_users");
            client.ExecuteQuery("DROP TABLE IF EXISTS network_test_products");
            client.Disconnect();
        }
    }
References client, SqlNetworkTestClient::Disconnect(), SqlNetworkTestClient::ExecuteQuery(), and SqlNetworkTestClient::IsConnected().
TestConnection()
void SqlNetworkTest::TestConnection () inline protected
Definition at line 257 of file sql_network_test.cpp.
{
        std::cout << "Starting connection test to " << kTestHost << ":" << kTestPort << std::endl;
        bool connected = client.Connect();
        std::cout << "Connection result: " << (connected ? "SUCCESS" : "FAILED") << std::endl;
        if (connected) {
            bool authenticated = client.Authenticate(kTestUsername, kTestPassword);
            std::cout << "Authentication result: " << (authenticated ? "SUCCESS" : "FAILED") << std::endl;
        }
    }
References SqlNetworkTestClient::Authenticate(), client, SqlNetworkTestClient::Connect(), kTestHost, kTestPassword, kTestPort, and kTestUsername.
Member Data Documentation
client
SqlNetworkTestClient SqlNetworkTest::client protected
Definition at line 244 of file sql_network_test.cpp.
Referenced by ConfigureClient(), SetUp(), TearDown(), and TestConnection().
kDisableAuth
constexpr bool SqlNetworkTest::kDisableAuth = true static constexpr protected
Definition at line 237 of file sql_network_test.cpp.
kDisableEncryption
constexpr bool SqlNetworkTest::kDisableEncryption = true static constexpr protected
Definition at line 236 of file sql_network_test.cpp.
kTestHost
constexpr const char* SqlNetworkTest::kTestHost = "127.0.0.1" static constexpr protected
Definition at line 233 of file sql_network_test.cpp.
Referenced by TestConnection().
kTestPassword
constexpr const char* SqlNetworkTest::kTestPassword = "admin" static constexpr protected
Definition at line 235 of file sql_network_test.cpp.
Referenced by SetUp(), and TestConnection().
kTestPort
constexpr int SqlNetworkTest::kTestPort = 5000 static constexpr protected
Definition at line 232 of file sql_network_test.cpp.
Referenced by TestConnection().
kTestUsername
constexpr const char* SqlNetworkTest::kTestUsername = "admin" static constexpr protected
Definition at line 234 of file sql_network_test.cpp.
Referenced by SetUp(), and TestConnection().
The documentation for this class was generated from the following file:
tests/network/sql_network_test.cpp