SQLCC: sqlcc::StorageEngine Class Reference
sqlcc::StorageEngine Class Reference
存储引擎类，封装磁盘管理和缓冲池功能
#include <storage_engine.h>
Public Member Functions
StorageEngine (const std::string &db_filename, size_t pool_size=64)
构造函数
~StorageEngine ()
析构函数
StorageEngine (const StorageEngine &)=delete
禁止拷贝构造
StorageEngine & operator= (const StorageEngine &)=delete
禁止赋值操作
Page * NewPage (int32_t *page_id)
创建新页面
Page * FetchPage (int32_t page_id)
获取页面
bool UnpinPage (int32_t page_id, bool is_dirty)
取消固定页面
bool FlushPage (int32_t page_id)
刷新页面到磁盘
bool DeletePage (int32_t page_id)
删除页面
void FlushAllPages ()
刷新所有页面到磁盘
Private Attributes
std::unique_ptr< DiskManager > disk_manager_
磁盘管理器
std::unique_ptr< BufferPool > buffer_pool_
缓冲池管理器
Detailed Description
存储引擎类，封装磁盘管理和缓冲池功能
Definition at line 12 of file storage_engine.h.
Constructor & Destructor Documentation
StorageEngine() [1/2]
sqlcc::StorageEngine::StorageEngine (const std::string & db_filename, size_t pool_size = 64) explicit
构造函数
Parameters
db_filename 数据库文件名
pool_size 缓冲池大小（页面数量）
Definition at line 6 of file storage_engine.cc.
{
    SQLCC_LOG_INFO("Initializing StorageEngine with database file: " + db_filename +
                  " and pool size: " + std::to_string(pool_size));
    // 创建磁盘管理器
    disk_manager_ = std::make_unique<DiskManager>(db_filename);
    // 创建缓冲池管理器
    buffer_pool_ = std::make_unique<BufferPool>(disk_manager_.get(), pool_size);
    SQLCC_LOG_INFO("StorageEngine initialized successfully");
}
References buffer_pool_, disk_manager_, and SQLCC_LOG_INFO.
~StorageEngine()
sqlcc::StorageEngine::~StorageEngine ()
析构函数
Definition at line 19 of file storage_engine.cc.
{
    SQLCC_LOG_INFO("Destroying StorageEngine");
    // 析构函数会自动清理资源
}
References SQLCC_LOG_INFO.
StorageEngine() [2/2]
sqlcc::StorageEngine::StorageEngine (const StorageEngine &) delete
禁止拷贝构造
Member Function Documentation
DeletePage()
bool sqlcc::StorageEngine::DeletePage (int32_t page_id)
删除页面
Parameters
page_id 页面ID
Returns
操作是否成功
Definition at line 68 of file storage_engine.cc.
{
    SQLCC_LOG_DEBUG("Deleting page ID: " + std::to_string(page_id));
    bool result = buffer_pool_->DeletePage(page_id);
    if (result) {
        SQLCC_LOG_DEBUG("Page ID " + std::to_string(page_id) + " deleted successfully");
    } else {
        SQLCC_LOG_WARN("Failed to delete page ID " + std::to_string(page_id));
    }
    return result;
}
References buffer_pool_, SQLCC_LOG_DEBUG, and SQLCC_LOG_WARN.
Referenced by TEST_F().
FetchPage()
Page * sqlcc::StorageEngine::FetchPage (int32_t page_id)
获取页面
Parameters
page_id 页面ID
Returns
页面指针，如果失败返回nullptr
Definition at line 35 of file storage_engine.cc.
{
    SQLCC_LOG_DEBUG("Fetching page ID: " + std::to_string(page_id));
    Page* page = buffer_pool_->FetchPage(page_id);
    if (page != nullptr) {
        SQLCC_LOG_DEBUG("Page ID " + std::to_string(page_id) + " fetched successfully");
    } else {
        SQLCC_LOG_WARN("Failed to fetch page ID " + std::to_string(page_id));
    }
    return page;
}
References buffer_pool_, SQLCC_LOG_DEBUG, and SQLCC_LOG_WARN.
Referenced by TEST_F(), TEST_F(), and TEST_F().
FlushAllPages()
void sqlcc::StorageEngine::FlushAllPages ()
刷新所有页面到磁盘
Definition at line 79 of file storage_engine.cc.
{
    SQLCC_LOG_INFO("Flushing all pages");
    buffer_pool_->FlushAllPages();
    SQLCC_LOG_INFO("All pages flushed successfully");
}
References buffer_pool_, and SQLCC_LOG_INFO.
Referenced by TEST_F().
FlushPage()
bool sqlcc::StorageEngine::FlushPage (int32_t page_id)
刷新页面到磁盘
Parameters
page_id 页面ID
Returns
操作是否成功
Definition at line 57 of file storage_engine.cc.
{
    SQLCC_LOG_DEBUG("Flushing page ID: " + std::to_string(page_id));
    bool result = buffer_pool_->FlushPage(page_id);
    if (result) {
        SQLCC_LOG_DEBUG("Page ID " + std::to_string(page_id) + " flushed successfully");
    } else {
        SQLCC_LOG_WARN("Failed to flush page ID " + std::to_string(page_id));
    }
    return result;
}
References buffer_pool_, SQLCC_LOG_DEBUG, and SQLCC_LOG_WARN.
Referenced by TEST_F().
NewPage()
Page * sqlcc::StorageEngine::NewPage (int32_t * page_id)
创建新页面
Parameters
[out] page_id 新页面的ID
Returns
页面指针，如果失败返回nullptr
Definition at line 24 of file storage_engine.cc.
{
    SQLCC_LOG_DEBUG("Creating new page");
    Page* page = buffer_pool_->NewPage(page_id);
    if (page != nullptr) {
        SQLCC_LOG_DEBUG("New page created with ID: " + std::to_string(*page_id));
    } else {
        SQLCC_LOG_ERROR("Failed to create new page");
    }
    return page;
}
References buffer_pool_, SQLCC_LOG_DEBUG, and SQLCC_LOG_ERROR.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
operator=()
StorageEngine & sqlcc::StorageEngine::operator= (const StorageEngine &) delete
禁止赋值操作
UnpinPage()
bool sqlcc::StorageEngine::UnpinPage (int32_t page_id, bool is_dirty)
取消固定页面
Parameters
page_id 页面ID
is_dirty 是否标记为脏页
Returns
操作是否成功
Definition at line 46 of file storage_engine.cc.
{
    SQLCC_LOG_DEBUG("Unpinning page ID: " + std::to_string(page_id) + ", is_dirty: " + std::to_string(is_dirty));
    bool result = buffer_pool_->UnpinPage(page_id, is_dirty);
    if (result) {
        SQLCC_LOG_DEBUG("Page ID " + std::to_string(page_id) + " unpinned successfully");
    } else {
        SQLCC_LOG_WARN("Failed to unpin page ID " + std::to_string(page_id));
    }
    return result;
}
References buffer_pool_, SQLCC_LOG_DEBUG, and SQLCC_LOG_WARN.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
Member Data Documentation
buffer_pool_
std::unique_ptr<BufferPool> sqlcc::StorageEngine::buffer_pool_ private
缓冲池管理器
Definition at line 82 of file storage_engine.h.
Referenced by DeletePage(), FetchPage(), FlushAllPages(), FlushPage(), NewPage(), StorageEngine(), and UnpinPage().
disk_manager_
std::unique_ptr<DiskManager> sqlcc::StorageEngine::disk_manager_ private
磁盘管理器
Definition at line 79 of file storage_engine.h.
Referenced by StorageEngine().
The documentation for this class was generated from the following files:
include/storage_engine.h
src/storage_engine.cc