SQLCC: sqlcc::IndexManager Class Reference
sqlcc::IndexManager Class Reference
索引管理器类 管理所有表的索引，提供索引的创建、删除、查询等功能
#include <b_plus_tree.h>
Public Member Functions
IndexManager (sqlcc::StorageEngine *storage_engine, sqlcc::ConfigManager &config_manager)
~IndexManager ()
bool CreateIndex (const std::string &index_name, const std::string &table_name, const std::string &column_name, bool is_unique=false)
bool DropIndex (const std::string &index_name, const std::string &table_name)
bool IndexExists (const std::string &index_name, const std::string &table_name) const
class BPlusTreeIndex * GetIndex (const std::string &index_name, const std::string &table_name)
std::vector< class BPlusTreeIndex * > GetTableIndexes (const std::string &table_name) const
void LoadAllIndexes ()
Private Member Functions
std::string GetIndexName (const std::string &table_name, const std::string &column_name) const
Private Attributes
StorageEngine * storage_engine_
std::unordered_map< std::string, std::unique_ptr< class BPlusTreeIndex > > indexes_
Detailed Description
索引管理器类 管理所有表的索引，提供索引的创建、删除、查询等功能
Definition at line 178 of file b_plus_tree.h.
Constructor & Destructor Documentation
IndexManager()
sqlcc::IndexManager::IndexManager (sqlcc::StorageEngine * storage_engine, sqlcc::ConfigManager & config_manager)
Definition at line 7 of file index_manager.cpp.
    : storage_engine_(storage_engine) {
    SQLCC_LOG_INFO("Initializing IndexManager");
    LoadAllIndexes();
}
References LoadAllIndexes(), and SQLCC_LOG_INFO.
~IndexManager()
sqlcc::IndexManager::~IndexManager ()
Definition at line 13 of file index_manager.cpp.
{
    SQLCC_LOG_INFO("Destroying IndexManager");
    // 索引对象会通过unique_ptr自动清理
    indexes_.clear();
}
References indexes_, and SQLCC_LOG_INFO.
Member Function Documentation
CreateIndex()
bool sqlcc::IndexManager::CreateIndex (const std::string & index_name, const std::string & table_name, const std::string & column_name, bool is_unique = false)
Definition at line 19 of file index_manager.cpp.
{
    SQLCC_LOG_INFO("Creating index: " + index_name + " on table: " + table_name + ", column: " + column_name);
    // 检查索引是否已存在
    if (IndexExists(index_name, table_name)) {
        SQLCC_LOG_WARN("Index already exists: " + index_name);
        return false;
    }
    // 创建新的B+树索引
    auto index = std::make_unique<BPlusTreeIndex>(storage_engine_, table_name, column_name);
    if (!index->Create()) {
        SQLCC_LOG_ERROR("Failed to create index: " + index_name);
        return false;
    }
    // 将索引添加到索引映射表
    indexes_[index_name] = std::move(index);
    SQLCC_LOG_INFO("Index created successfully: " + index_name);
    return true;
}
References indexes_, IndexExists(), SQLCC_LOG_ERROR, SQLCC_LOG_INFO, SQLCC_LOG_WARN, and storage_engine_.
DropIndex()
bool sqlcc::IndexManager::DropIndex (const std::string & index_name, const std::string & table_name)
Definition at line 41 of file index_manager.cpp.
{
    SQLCC_LOG_INFO("Dropping index: " + index_name + " on table: " + table_name);
    // 查找索引
    auto it = indexes_.find(index_name);
    if (it == indexes_.end() || it->second->GetTableName() != table_name) {
        SQLCC_LOG_WARN("Index not found: " + index_name);
        return false;
    }
    // 删除索引
    if (!it->second->Drop()) {
        SQLCC_LOG_ERROR("Failed to drop index: " + index_name);
        return false;
    }
    // 从映射表中移除索引
    indexes_.erase(it);
    SQLCC_LOG_INFO("Index dropped successfully: " + index_name);
    return true;
}
References indexes_, SQLCC_LOG_ERROR, SQLCC_LOG_INFO, and SQLCC_LOG_WARN.
GetIndex()
BPlusTreeIndex * sqlcc::IndexManager::GetIndex (const std::string & index_name, const std::string & table_name)
Definition at line 71 of file index_manager.cpp.
{
    auto it = indexes_.find(index_name);
    if (it != indexes_.end() && it->second->GetTableName() == table_name) {
        return it->second.get();
    }
    return nullptr;
}
References indexes_.
GetIndexName()
std::string sqlcc::IndexManager::GetIndexName (const std::string & table_name, const std::string & column_name) const private
Definition at line 91 of file index_manager.cpp.
{
    return table_name + "_" + column_name + "_idx";
}
GetTableIndexes()
std::vector< BPlusTreeIndex * > sqlcc::IndexManager::GetTableIndexes (const std::string & table_name) const
Definition at line 79 of file index_manager.cpp.
{
    std::vector<BPlusTreeIndex*> result;
    for (const auto& [index_name, index] : indexes_) {
        if (index->GetTableName() == table_name) {
            result.push_back(index.get());
        }
    }
    return result;
}
References indexes_.
IndexExists()
bool sqlcc::IndexManager::IndexExists (const std::string & index_name, const std::string & table_name) const
Definition at line 63 of file index_manager.cpp.
{
    auto it = indexes_.find(index_name);
    if (it != indexes_.end()) {
        return it->second->GetTableName() == table_name;
    }
    return false;
}
References indexes_.
Referenced by CreateIndex().
LoadAllIndexes()
void sqlcc::IndexManager::LoadAllIndexes ()
Definition at line 95 of file index_manager.cpp.
{
    SQLCC_LOG_INFO("Loading all indexes from storage");
    // 实现从存储加载所有索引的功能
    // 目前只是一个基本实现
}
References SQLCC_LOG_INFO.
Referenced by IndexManager().
Member Data Documentation
indexes_
std::unordered_map<std::string, std::unique_ptr<class BPlusTreeIndex> > sqlcc::IndexManager::indexes_ private
Definition at line 197 of file b_plus_tree.h.
Referenced by CreateIndex(), DropIndex(), GetIndex(), GetTableIndexes(), IndexExists(), and ~IndexManager().
storage_engine_
StorageEngine* sqlcc::IndexManager::storage_engine_ private
Definition at line 196 of file b_plus_tree.h.
Referenced by CreateIndex().
The documentation for this class was generated from the following files:
include/b_plus_tree.h
src/sql_executor/index_manager.cpp