SQLCC: sqlcc::network::ServerNetworkManager Class Reference
sqlcc::network::ServerNetworkManager Class Reference
#include <network.h>
Public Member Functions
ServerNetworkManager (int port, int max_connections=100)
~ServerNetworkManager ()
bool Start ()
void Stop ()
void ProcessEvents ()
void SetSqlExecutor (std::shared_ptr< sqlcc::SqlExecutor > sql_executor)
Private Member Functions
void AcceptConnection ()
Private Attributes
int port_
int max_connections_
int listen_fd_
int epoll_fd_
bool running_
std::shared_ptr< SessionManager > session_manager_
std::shared_ptr< sqlcc::SqlExecutor > sql_executor_
std::unordered_map< int, ConnectionHandler * > connections_
Detailed Description
Definition at line 173 of file network.h.
Constructor & Destructor Documentation
ServerNetworkManager()
sqlcc::network::ServerNetworkManager::ServerNetworkManager (int port, int max_connections = 100)
Definition at line 570 of file network.cpp.
    : port_(port), max_connections_(max_connections), listen_fd_(-1), epoll_fd_(-1), running_(false),
      session_manager_(std::make_shared<SessionManager>()) {}
~ServerNetworkManager()
sqlcc::network::ServerNetworkManager::~ServerNetworkManager ()
Definition at line 574 of file network.cpp.
{
    Stop();
}
References Stop().
Member Function Documentation
AcceptConnection()
void sqlcc::network::ServerNetworkManager::AcceptConnection () private
Definition at line 686 of file network.cpp.
{
#ifdef __linux__
    struct sockaddr_in client_addr;
    socklen_t client_len = sizeof(client_addr);
    int client_fd = accept4(listen_fd_, (struct sockaddr*)&client_addr, &client_len, SOCK_NONBLOCK);
    if (client_fd < 0) {
        return;
    }
    // 创建连接处理器，传入SQL执行器
    ConnectionHandler* handler = new ConnectionHandler(client_fd, session_manager_, sql_executor_);
    // 添加到epoll
    struct epoll_event ev;
    ev.events = EPOLLIN | EPOLLET; // 边缘触发
    ev.data.ptr = handler;
    if (epoll_ctl(epoll_fd_, EPOLL_CTL_ADD, client_fd, &ev) < 0) {
        delete handler;
        close(client_fd);
        return;
    }
    // 添加到连接映射
    connections_[client_fd] = handler;
#endif
}
References connections_, epoll_fd_, listen_fd_, session_manager_, and sql_executor_.
Referenced by ProcessEvents().
ProcessEvents()
void sqlcc::network::ServerNetworkManager::ProcessEvents ()
Definition at line 653 of file network.cpp.
{
#ifdef __linux__
    if (!running_ || epoll_fd_ < 0) {
        return;
    }
    struct epoll_event events[64];
    int nfds = epoll_wait(epoll_fd_, events, 64, 0);
    for (int i = 0; i < nfds; i++) {
        if (events[i].data.ptr == nullptr) {
            // 监听socket有事件，接受新连接
            AcceptConnection();
        } else {
            // 客户端连接有事件
            ConnectionHandler* handler = static_cast<ConnectionHandler*>(events[i].data.ptr);
            handler->HandleEvent(events[i].events);
            if (handler->IsClosed()) {
                // 从epoll中移除并删除连接处理器
                epoll_ctl(epoll_fd_, EPOLL_CTL_DEL, handler->GetFd(), nullptr);
                connections_.erase(handler->GetFd());
                delete handler;
            }
        }
    }
#endif
}
References AcceptConnection(), connections_, epoll_fd_, sqlcc::network::ConnectionHandler::GetFd(), sqlcc::network::ConnectionHandler::HandleEvent(), sqlcc::network::ConnectionHandler::IsClosed(), and running_.
Referenced by main().
SetSqlExecutor()
void sqlcc::network::ServerNetworkManager::SetSqlExecutor (std::shared_ptr< sqlcc::SqlExecutor > sql_executor)
Definition at line 682 of file network.cpp.
{
    sql_executor_ = std::move(sql_executor);
}
References sql_executor_.
Referenced by main().
Start()
bool sqlcc::network::ServerNetworkManager::Start ()
Definition at line 578 of file network.cpp.
{
#ifdef __linux__
    // 创建监听socket
    listen_fd_ = socket(AF_INET, SOCK_STREAM | SOCK_NONBLOCK, 0);
    if (listen_fd_ < 0) {
        return false;
    }
    // 设置socket选项
    int opt = 1;
    setsockopt(listen_fd_, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));
    // 绑定地址
    struct sockaddr_in addr;
    std::memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = INADDR_ANY;
    addr.sin_port = htons(port_);
    if (bind(listen_fd_, (struct sockaddr*)&addr, sizeof(addr)) < 0) {
        close(listen_fd_);
        listen_fd_ = -1;
        return false;
    }
    // 开始监听
    if (listen(listen_fd_, SOMAXCONN) < 0) {
        close(listen_fd_);
        listen_fd_ = -1;
        return false;
    }
    // 创建epoll实例
    epoll_fd_ = epoll_create1(0);
    if (epoll_fd_ < 0) {
        close(listen_fd_);
        listen_fd_ = -1;
        return false;
    }
    // 添加监听socket到epoll
    struct epoll_event ev;
    ev.events = EPOLLIN;
    ev.data.ptr = nullptr;
    if (epoll_ctl(epoll_fd_, EPOLL_CTL_ADD, listen_fd_, &ev) < 0) {
        close(epoll_fd_);
        close(listen_fd_);
        epoll_fd_ = -1;
        listen_fd_ = -1;
        return false;
    }
    running_ = true;
    return true;
#else
    return false; // 非Linux平台不支持
#endif
}
References epoll_fd_, listen_fd_, port_, and running_.
Referenced by main().
Stop()
void sqlcc::network::ServerNetworkManager::Stop ()
Definition at line 637 of file network.cpp.
{
    running_ = false;
#ifdef __linux__
    if (epoll_fd_ >= 0) {
        close(epoll_fd_);
        epoll_fd_ = -1;
    }
    if (listen_fd_ >= 0) {
        close(listen_fd_);
        listen_fd_ = -1;
    }
#endif
}
References epoll_fd_, listen_fd_, and running_.
Referenced by main(), signalHandler(), and ~ServerNetworkManager().
Member Data Documentation
connections_
std::unordered_map<int, ConnectionHandler*> sqlcc::network::ServerNetworkManager::connections_ private
Definition at line 193 of file network.h.
Referenced by AcceptConnection(), and ProcessEvents().
epoll_fd_
int sqlcc::network::ServerNetworkManager::epoll_fd_ private
Definition at line 189 of file network.h.
Referenced by AcceptConnection(), ProcessEvents(), Start(), and Stop().
listen_fd_
int sqlcc::network::ServerNetworkManager::listen_fd_ private
Definition at line 188 of file network.h.
Referenced by AcceptConnection(), Start(), and Stop().
max_connections_
int sqlcc::network::ServerNetworkManager::max_connections_ private
Definition at line 187 of file network.h.
port_
int sqlcc::network::ServerNetworkManager::port_ private
Definition at line 186 of file network.h.
Referenced by Start().
running_
bool sqlcc::network::ServerNetworkManager::running_ private
Definition at line 190 of file network.h.
Referenced by ProcessEvents(), Start(), and Stop().
session_manager_
std::shared_ptr<SessionManager> sqlcc::network::ServerNetworkManager::session_manager_ private
Definition at line 191 of file network.h.
Referenced by AcceptConnection().
sql_executor_
std::shared_ptr<sqlcc::SqlExecutor> sqlcc::network::ServerNetworkManager::sql_executor_ private
Definition at line 192 of file network.h.
Referenced by AcceptConnection(), and SetSqlExecutor().
The documentation for this class was generated from the following files:
include/network/network.h
src/network/network.cpp