SQLCC: SqlNetworkTestClient Class Reference
SqlNetworkTestClient Class Reference
Public Member Functions
SqlNetworkTestClient (const string &host, int port, bool disable_encryption=true, bool disable_auth=true)
void SetDisableEncryption (bool disable)
void SetDisableAuth (bool disable)
~SqlNetworkTestClient ()
bool Connect ()
bool Authenticate (const string &username, const string &password)
string ExecuteQuery (const string &query)
void Disconnect ()
bool IsConnected () const
Private Attributes
string host_
int port_
int sock_fd_
bool disable_encryption_
bool disable_auth_
Detailed Description
Definition at line 19 of file sql_network_test.cpp.
Constructor & Destructor Documentation
SqlNetworkTestClient()
SqlNetworkTestClient::SqlNetworkTestClient (const string & host, int port, bool disable_encryption = true, bool disable_auth = true) inline
Definition at line 21 of file sql_network_test.cpp.
        : host_(host), port_(port), sock_fd_(-1), disable_encryption_(disable_encryption), disable_auth_(disable_auth) {}
~SqlNetworkTestClient()
SqlNetworkTestClient::~SqlNetworkTestClient () inline
Definition at line 32 of file sql_network_test.cpp.
{
        Disconnect();
    }
References Disconnect().
Member Function Documentation
Authenticate()
bool SqlNetworkTestClient::Authenticate (const string & username, const string & password) inline
Definition at line 124 of file sql_network_test.cpp.
{
        if (sock_fd_ < 0) return false;
        // 如果禁用认证，直接返回成功
        if (disable_auth_) {
            std::cout << "Authentication disabled, skipping auth step" << std::endl;
            return true;
        }
        // 构造认证消息
        uint32_t username_len = username.length();
        uint32_t password_len = password.length();
        size_t body_len = 2 * sizeof(uint32_t) + username_len + password_len;
        vector<char> message(sizeof(MessageHeader) + body_len);
        MessageHeader* header = reinterpret_cast<MessageHeader*>(message.data());
        header->magic = 0x53514C43; // 'SQLC'
        header->length = body_len;
        header->type = AUTH;
        header->flags = 0;
        // 设置禁用加密标志
        if (disable_encryption_) {
            header->flags |= 0x01;
            std::cout << "Encryption disabled in auth message" << std::endl;
        }
        header->sequence_id = 2;
        // 填充认证数据
        char* body = message.data() + sizeof(MessageHeader);
        memcpy(body, &username_len, sizeof(username_len));
        memcpy(body + sizeof(username_len), &password_len, sizeof(password_len));
        memcpy(body + 2 * sizeof(uint32_t), username.c_str(), username_len);
        memcpy(body + 2 * sizeof(uint32_t) + username_len, password.c_str(), password_len);
        // 发送认证消息
        if (send(sock_fd_, message.data(), message.size(), 0) <= 0) {
            return false;
        }
        // 接收认证结果
        char buffer[1024];
        int ret = recv(sock_fd_, buffer, sizeof(buffer), 0);
        if (ret <= 0) {
            return false;
        }
        MessageHeader* resp_header = reinterpret_cast<MessageHeader*>(buffer);
        return resp_header->flags == 0; // 0表示认证成功
    }
References sqlcc::network::AUTH, disable_auth_, disable_encryption_, sqlcc::network::MessageHeader::flags, sqlcc::network::MessageHeader::length, sqlcc::network::MessageHeader::magic, sqlcc::network::MessageHeader::sequence_id, sock_fd_, and sqlcc::network::MessageHeader::type.
Referenced by SqlNetworkTest::SetUp(), and SqlNetworkTest::TestConnection().
Connect()
bool SqlNetworkTestClient::Connect () inline
Definition at line 36 of file sql_network_test.cpp.
                   {
#ifdef __linux__
        sock_fd_ = socket(AF_INET, SOCK_STREAM, 0);
        if (sock_fd_ < 0) {
            std::cerr << "Failed to create socket: " << strerror(errno) << std::endl;
            return false;
        }
        struct sockaddr_in addr;
        memset(&addr, 0, sizeof(addr));
        addr.sin_family = AF_INET;
        addr.sin_port = htons(port_);
        addr.sin_addr.s_addr = inet_addr(host_.c_str());
        std::cout << "Connecting to " << host_ << ":" << port_ << std::endl;
        if (connect(sock_fd_, (struct sockaddr*)&addr, sizeof(addr)) < 0) {
            std::cerr << "Failed to connect: " << strerror(errno) << std::endl;
            close(sock_fd_);
            sock_fd_ = -1;
            return false;
        }
        std::cout << "Connected to server" << std::endl;
        // 发送连接消息
        MessageHeader connect_header;
        connect_header.magic = 0x53514C43; // 'SQLC'
        connect_header.length = 0;
        connect_header.type = CONNECT;
        connect_header.flags = 0;
        // 设置禁用加密标志
        if (disable_encryption_) {
            connect_header.flags |= 0x01; // 假设0x01是禁用加密的标志位
            std::cout << "Encryption disabled in connect message" << std::endl;
        }
        connect_header.sequence_id = 1;
        if (send(sock_fd_, &connect_header, sizeof(connect_header), 0) <= 0) {
            std::cerr << "Failed to send connect message: " << strerror(errno) << std::endl;
            Disconnect();
            return false;
        }
        std::cout << "Connect message sent" << std::endl;
        // 接收连接确认 - 添加超时和更详细的调试
        char buffer[1024];
        // 设置接收超时为5秒
        struct timeval timeout;
        timeout.tv_sec = 5;
        timeout.tv_usec = 0;
        setsockopt(sock_fd_, SOL_SOCKET, SO_RCVTIMEO, (char*)&timeout, sizeof(timeout));
        std::cout << "Waiting for server response..." << std::endl;
        int ret = recv(sock_fd_, buffer, sizeof(buffer), 0);
        if (ret < 0) {
            if (errno == EWOULDBLOCK || errno == EAGAIN) {
                std::cerr << "Timeout waiting for server response" << std::endl;
            } else {
                std::cerr << "Failed to receive response: " << strerror(errno) << std::endl;
            }
            Disconnect();
            return false;
        } else if (ret == 0) {
            std::cerr << "Connection closed by server" << std::endl;
            Disconnect();
            return false;
        }
        std::cout << "Received response of length: " << ret << std::endl;
        // 检查接收到的消息格式
        if (ret >= static_cast<int>(sizeof(MessageHeader))) {
            MessageHeader* resp_header = reinterpret_cast<MessageHeader*>(buffer);
            std::cout << "Response message type: " << resp_header->type
                      << ", flags: " << resp_header->flags << std::endl;
        }
        return true;
#else
        return false;
#endif
    }
References sqlcc::network::CONNECT, disable_encryption_, Disconnect(), sqlcc::network::MessageHeader::flags, host_, sqlcc::network::MessageHeader::length, sqlcc::network::MessageHeader::magic, port_, sqlcc::network::MessageHeader::sequence_id, sock_fd_, and sqlcc::network::MessageHeader::type.
Referenced by SqlNetworkTest::SetUp(), and SqlNetworkTest::TestConnection().
Disconnect()
void SqlNetworkTestClient::Disconnect () inline
Definition at line 210 of file sql_network_test.cpp.
                      {
        if (sock_fd_ >= 0) {
            close(sock_fd_);
            sock_fd_ = -1;
        }
    }
References sock_fd_.
Referenced by Connect(), SqlNetworkTest::TearDown(), and ~SqlNetworkTestClient().
ExecuteQuery()
string SqlNetworkTestClient::ExecuteQuery (const string & query) inline
Definition at line 176 of file sql_network_test.cpp.
{
        if (sock_fd_ < 0) return "Error: Not connected";
        // 构造查询消息
        vector<char> message(sizeof(MessageHeader) + query.length());
        MessageHeader* header = reinterpret_cast<MessageHeader*>(message.data());
        header->magic = 0x53514C43; // 'SQLC'
        header->length = query.length();
        header->type = QUERY;
        header->flags = 0;
        header->sequence_id = 3;
        memcpy(message.data() + sizeof(MessageHeader), query.c_str(), query.length());
        // 发送查询
        if (send(sock_fd_, message.data(), message.size(), 0) <= 0) {
            return "Error: Send failed";
        }
        // 接收结果
        char buffer[4096];
        int ret = recv(sock_fd_, buffer, sizeof(buffer), 0);
        if (ret <= 0) {
            return "Error: Receive failed";
        }
        MessageHeader* resp_header = reinterpret_cast<MessageHeader*>(buffer);
        if (resp_header->type != QUERY_RESULT) {
            return "Error: Unexpected response type";
        }
        return string(buffer + sizeof(MessageHeader), resp_header->length);
    }
References sqlcc::network::MessageHeader::flags, sqlcc::network::MessageHeader::length, sqlcc::network::MessageHeader::magic, sqlcc::network::QUERY, sqlcc::network::QUERY_RESULT, sqlcc::network::MessageHeader::sequence_id, sock_fd_, and sqlcc::network::MessageHeader::type.
Referenced by SqlNetworkTest::SetUp(), and SqlNetworkTest::TearDown().
IsConnected()
bool SqlNetworkTestClient::IsConnected () const inline
Definition at line 217 of file sql_network_test.cpp.
{
        return sock_fd_ >= 0;
    }
References sock_fd_.
Referenced by SqlNetworkTest::SetUp(), and SqlNetworkTest::TearDown().
SetDisableAuth()
void SqlNetworkTestClient::SetDisableAuth (bool disable) inline
Definition at line 28 of file sql_network_test.cpp.
{
        disable_auth_ = disable;
    }
References disable_auth_.
Referenced by SqlNetworkTest::ConfigureClient().
SetDisableEncryption()
void SqlNetworkTestClient::SetDisableEncryption (bool disable) inline
Definition at line 24 of file sql_network_test.cpp.
{
        disable_encryption_ = disable;
    }
References disable_encryption_.
Referenced by SqlNetworkTest::ConfigureClient().
Member Data Documentation
disable_auth_
bool SqlNetworkTestClient::disable_auth_ private
Definition at line 226 of file sql_network_test.cpp.
Referenced by Authenticate(), and SetDisableAuth().
disable_encryption_
bool SqlNetworkTestClient::disable_encryption_ private
Definition at line 225 of file sql_network_test.cpp.
Referenced by Authenticate(), Connect(), and SetDisableEncryption().
host_
string SqlNetworkTestClient::host_ private
Definition at line 222 of file sql_network_test.cpp.
Referenced by Connect().
port_
int SqlNetworkTestClient::port_ private
Definition at line 223 of file sql_network_test.cpp.
Referenced by Connect().
sock_fd_
int SqlNetworkTestClient::sock_fd_ private
Definition at line 224 of file sql_network_test.cpp.
Referenced by Authenticate(), Connect(), Disconnect(), ExecuteQuery(), and IsConnected().
The documentation for this class was generated from the following file:
tests/network/sql_network_test.cpp