SQLCC: sqlcc::ForeignKeyConstraintExecutor Class Reference
sqlcc::ForeignKeyConstraintExecutor Class Reference
外键约束执行器
#include <constraint_executor.h>
Public Member Functions
ForeignKeyConstraintExecutor (const sql_parser::ForeignKeyConstraint &constraint, StorageEngine &storage_engine)
构造函数
bool validateInsert (const std::vector< std::string > &record, const std::vector< sql_parser::ColumnDefinition > &table_schema) override
验证插入操作
bool validateUpdate (const std::vector< std::string > &old_record, const std::vector< std::string > &new_record, const std::vector< sql_parser::ColumnDefinition > &table_schema) override
验证更新操作
bool validateDelete (const std::vector< std::string > &record, const std::vector< sql_parser::ColumnDefinition > &table_schema) override
验证删除操作
const std::string & getConstraintName () const override
获取约束名称
sql_parser::TableConstraint::Type getConstraintType () const override
获取约束类型
void setCurrentTableName (const std::string &table_name)
设置当前表名
std::string toLower (const std::string &str) const
字符串转换为小写
Public Member Functions inherited from sqlcc::ConstraintExecutor
virtual ~ConstraintExecutor ()=default
Public Attributes
sql_parser::ForeignKeyConstraint constraint_
StorageEngine & storage_engine_
std::string current_table_name_
std::vector< std::string > lower_foreign_key_columns_
std::string lower_referenced_table_
std::string lower_referenced_column_
Private Member Functions
bool parentRecordExists (const std::string &foreign_key_value)
检查父表中是否存在对应的记录
bool hasChildReferences (const std::string &primary_key_value)
检查是否有子表记录引用此父表记录
std::string getForeignKeyValue (const std::vector< std::string > &record, const std::vector< sql_parser::ColumnDefinition > &table_schema)
获取记录中外键列的值
std::string getPrimaryKeyValue (const std::vector< std::string > &record, const std::vector< sql_parser::ColumnDefinition > &table_schema)
获取记录中主键的值
Detailed Description
外键约束执行器
负责验证外键参照完整性约束
Definition at line 71 of file constraint_executor.h.
Constructor & Destructor Documentation
ForeignKeyConstraintExecutor()
sqlcc::ForeignKeyConstraintExecutor::ForeignKeyConstraintExecutor (const sql_parser::ForeignKeyConstraint & constraint, StorageEngine & storage_engine)
构造函数
Parameters
constraint 外键约束定义
storage_engine 存储引擎引用
Definition at line 18 of file constraint_executor.cpp.
    : constraint_(constraint), storage_engine_(storage_engine),
      current_table_name_("unknown") {
  // 将外键列名转换为小写，以便匹配
  for (const auto &col : constraint_.getColumns()) {
    lower_foreign_key_columns_.push_back(toLower(col));
  }
  lower_referenced_table_ = toLower(constraint_.getReferencedTable());
  lower_referenced_column_ = toLower(constraint_.getReferencedColumn());
}
References constraint_, sqlcc::sql_parser::ForeignKeyConstraint::getColumns(), sqlcc::sql_parser::ForeignKeyConstraint::getReferencedColumn(), sqlcc::sql_parser::ForeignKeyConstraint::getReferencedTable(), lower_foreign_key_columns_, lower_referenced_column_, lower_referenced_table_, and toLower().
Member Function Documentation
getConstraintName()
const std::string & sqlcc::ForeignKeyConstraintExecutor::getConstraintName () const override virtual
获取约束名称
Returns
约束名称
Implements sqlcc::ConstraintExecutor.
Definition at line 76 of file constraint_executor.cpp.
{
  return constraint_.getName();
}
References constraint_, and sqlcc::sql_parser::TableConstraint::getName().
getConstraintType()
sql_parser::TableConstraint::Type sqlcc::ForeignKeyConstraintExecutor::getConstraintType () const inline override virtual
获取约束类型
Returns
约束类型
Implements sqlcc::ConstraintExecutor.
Definition at line 96 of file constraint_executor.h.
{
    return sql_parser::TableConstraint::FOREIGN_KEY;
  }
References sqlcc::sql_parser::TableConstraint::FOREIGN_KEY.
getForeignKeyValue()
std::string sqlcc::ForeignKeyConstraintExecutor::getForeignKeyValue (const std::vector< std::string > & record, const std::vector< sql_parser::ColumnDefinition > & table_schema) private
获取记录中外键列的值
Parameters
record 记录数据
table_schema 表结构
Returns
外键值
Definition at line 89 of file constraint_executor.cpp.
{
  // 在记录中找到外键列的值
  for (size_t i = 0; i < table_schema.size() && i < record.size(); ++i) {
    std::string column_name = toLower(table_schema[i].getName());
    if (std::find(lower_foreign_key_columns_.begin(),
                  lower_foreign_key_columns_.end(),
                  column_name) != lower_foreign_key_columns_.end()) {
      return record[i];
    }
  }
  return ""; // 未找到外键列
}
References lower_foreign_key_columns_, and toLower().
Referenced by getPrimaryKeyValue(), validateInsert(), and validateUpdate().
getPrimaryKeyValue()
std::string sqlcc::ForeignKeyConstraintExecutor::getPrimaryKeyValue (const std::vector< std::string > & record, const std::vector< sql_parser::ColumnDefinition > & table_schema) private
获取记录中主键的值
Parameters
record 记录数据
table_schema 表结构
Returns
主键值
Definition at line 104 of file constraint_executor.cpp.
{
  // 找到被引用列（实际上应该是主键）对应的值
  // 这里简化处理，当只有一个外键列时返回该列的值
  if (constraint_.getColumns().size() == 1) {
    return getForeignKeyValue(record, table_schema);
  }
  // 多列外键情况，返回空字符串（需要更复杂的主键查找逻辑）
  return "";
}
References constraint_, sqlcc::sql_parser::ForeignKeyConstraint::getColumns(), and getForeignKeyValue().
hasChildReferences()
bool sqlcc::ForeignKeyConstraintExecutor::hasChildReferences (const std::string & primary_key_value) private
检查是否有子表记录引用此父表记录
Parameters
primary_key_value 主键值
Returns
true if has child references
parentRecordExists()
bool sqlcc::ForeignKeyConstraintExecutor::parentRecordExists (const std::string & foreign_key_value) private
检查父表中是否存在对应的记录
Parameters
foreign_key_value 外键值
Returns
true if parent record exists
Definition at line 80 of file constraint_executor.cpp.
{
  // TODO: 实现检查父表中是否存在对应记录的逻辑
  // 这需要访问存储引擎并查询引用表
  (void)foreign_key_value; // 避免未使用参数警告
  // 为简化起见，暂时返回true
  return true;
}
Referenced by validateInsert(), and validateUpdate().
setCurrentTableName()
void sqlcc::ForeignKeyConstraintExecutor::setCurrentTableName (const std::string & table_name)
设置当前表名
Parameters
table_name 表名
Definition at line 118 of file constraint_executor.cpp.
{
  current_table_name_ = table_name;
  // 重置列名的小写版本
  lower_foreign_key_columns_.clear();
  for (const auto &col : constraint_.getColumns()) {
    lower_foreign_key_columns_.push_back(toLower(col));
  }
}
References constraint_, current_table_name_, sqlcc::sql_parser::ForeignKeyConstraint::getColumns(), lower_foreign_key_columns_, and toLower().
toLower()
std::string sqlcc::ForeignKeyConstraintExecutor::toLower (const std::string & str) const
字符串转换为小写
Parameters
str 输入字符串
Returns
小写字符串
Referenced by ForeignKeyConstraintExecutor(), getForeignKeyValue(), and setCurrentTableName().
validateDelete()
bool sqlcc::ForeignKeyConstraintExecutor::validateDelete (const std::vector< std::string > & record, const std::vector< sql_parser::ColumnDefinition > & table_schema) override virtual
验证删除操作
Parameters
record 要删除的记录
table_schema 表结构信息
Returns
true if validation passes, false otherwise
Implements sqlcc::ConstraintExecutor.
Definition at line 66 of file constraint_executor.cpp.
{
  // 删除操作不涉及外键约束验证。
  // 外键约束的级联行为应由数据库引擎的更高层逻辑处理。
  (void)record; // 避免未使用参数警告
  (void)table_schema; // 避免未使用参数警告
  return true;
}
validateInsert()
bool sqlcc::ForeignKeyConstraintExecutor::validateInsert (const std::vector< std::string > & record, const std::vector< sql_parser::ColumnDefinition > & table_schema) override virtual
验证插入操作
Parameters
record 要插入的记录
table_schema 表结构信息
Returns
true if validation passes, false otherwise
Implements sqlcc::ConstraintExecutor.
Definition at line 31 of file constraint_executor.cpp.
{
  // 检查外键列是否在record中，如果不在或为NULL，允许插入
  std::string foreign_key_value = getForeignKeyValue(record, table_schema);
  if (foreign_key_value.empty()) {
    return true; // NULL值允许插入
  }
  // 检查被引用表中是否存在对应的记录
  return parentRecordExists(foreign_key_value);
}
References getForeignKeyValue(), and parentRecordExists().
validateUpdate()
bool sqlcc::ForeignKeyConstraintExecutor::validateUpdate (const std::vector< std::string > & old_record, const std::vector< std::string > & new_record, const std::vector< sql_parser::ColumnDefinition > & table_schema) override virtual
验证更新操作
Parameters
old_record 旧记录
new_record 新记录
table_schema 表结构信息
Returns
true if validation passes, false otherwise
Implements sqlcc::ConstraintExecutor.
Definition at line 45 of file constraint_executor.cpp.
{
  // 只有当外键列被修改时才需要验证
  std::string old_fk_value = getForeignKeyValue(old_record, table_schema);
  std::string new_fk_value = getForeignKeyValue(new_record, table_schema);
  if (old_fk_value == new_fk_value) {
    return true; // 外键值没有变化，不需要验证
  }
  // 新值为空(NULL)或在父表中存在
  if (new_fk_value.empty() || parentRecordExists(new_fk_value)) {
    return true;
  }
  return false;
}
References getForeignKeyValue(), and parentRecordExists().
Member Data Documentation
constraint_
sql_parser::ForeignKeyConstraint sqlcc::ForeignKeyConstraintExecutor::constraint_
Definition at line 150 of file constraint_executor.h.
Referenced by ForeignKeyConstraintExecutor(), getConstraintName(), getPrimaryKeyValue(), and setCurrentTableName().
current_table_name_
std::string sqlcc::ForeignKeyConstraintExecutor::current_table_name_
Definition at line 152 of file constraint_executor.h.
Referenced by setCurrentTableName().
lower_foreign_key_columns_
std::vector<std::string> sqlcc::ForeignKeyConstraintExecutor::lower_foreign_key_columns_
Definition at line 153 of file constraint_executor.h.
Referenced by ForeignKeyConstraintExecutor(), getForeignKeyValue(), and setCurrentTableName().
lower_referenced_column_
std::string sqlcc::ForeignKeyConstraintExecutor::lower_referenced_column_
Definition at line 155 of file constraint_executor.h.
Referenced by ForeignKeyConstraintExecutor().
lower_referenced_table_
std::string sqlcc::ForeignKeyConstraintExecutor::lower_referenced_table_
Definition at line 154 of file constraint_executor.h.
Referenced by ForeignKeyConstraintExecutor().
storage_engine_
StorageEngine& sqlcc::ForeignKeyConstraintExecutor::storage_engine_
Definition at line 151 of file constraint_executor.h.
The documentation for this class was generated from the following files:
include/constraint_executor.h
src/sql_executor/constraint_executor.cpp