SQLCC: sqlcc::network::ConnectionHandler Class Reference
sqlcc::network::ConnectionHandler Class Reference
#include <network.h>
Public Member Functions
ConnectionHandler (int fd, std::shared_ptr< SessionManager > session_manager, std::shared_ptr< sqlcc::SqlExecutor > sql_executor)
~ConnectionHandler ()
int GetFd () const
bool IsClosed () const
void HandleEvent (uint32_t events)
void ProcessMessage (const std::vector< char > &data)
Private Member Functions
void HandleRead ()
void HandleWrite ()
void SendMessage (const std::vector< char > &message)
void Close ()
void HandleConnectMessage (const std::vector< char > &data)
void HandleAuthMessage (const std::vector< char > &data)
void HandleQueryMessage (const std::vector< char > &data)
void HandleKeyExchangeMessage (const std::vector< char > &data)
void SendErrorMessage (const std::string &error)
Private Attributes
int fd_
std::shared_ptr< SessionManager > session_manager_
std::shared_ptr< sqlcc::SqlExecutor > sql_executor_
std::shared_ptr< Session > session_
bool closed_
std::queue< std::vector< char > > write_queue_
std::mutex write_mutex_
Detailed Description
Definition at line 132 of file network.h.
Constructor & Destructor Documentation
ConnectionHandler()
sqlcc::network::ConnectionHandler::ConnectionHandler (int fd, std::shared_ptr< SessionManager > session_manager, std::shared_ptr< sqlcc::SqlExecutor > sql_executor)
Definition at line 258 of file network.cpp.
    : fd_(fd), session_manager_(std::move(session_manager)), sql_executor_(std::move(sql_executor)),
      session_(nullptr), closed_(false) {
#ifdef __linux__
    // 设置为非阻塞模式
    int flags = fcntl(fd_, F_GETFL, 0);
    fcntl(fd_, F_SETFL, flags | O_NONBLOCK);
#endif
}
References fd_.
~ConnectionHandler()
sqlcc::network::ConnectionHandler::~ConnectionHandler ()
Definition at line 268 of file network.cpp.
{
    Close();
}
References Close().
Member Function Documentation
Close()
void sqlcc::network::ConnectionHandler::Close () private
Definition at line 352 of file network.cpp.
{
    if (!closed_) {
        closed_ = true;
#ifdef __linux__
        close(fd_);
#endif
    }
}
References closed_, and fd_.
Referenced by HandleEvent(), HandleRead(), HandleWrite(), and ~ConnectionHandler().
GetFd()
int sqlcc::network::ConnectionHandler::GetFd () const
Definition at line 272 of file network.cpp.
{
    return fd_;
}
References fd_.
Referenced by sqlcc::network::ServerNetworkManager::ProcessEvents().
HandleAuthMessage()
void sqlcc::network::ConnectionHandler::HandleAuthMessage (const std::vector< char > & data) private
Definition at line 430 of file network.cpp.
{
    if (data.size() < sizeof(MessageHeader)) {
        return;
    }
    MessageHeader* header = reinterpret_cast<MessageHeader*>(const_cast<char*>(data.data()));
    if (data.size() < sizeof(MessageHeader) + header->length) {
        return;
    }
    // 解析新的认证数据格式
    // 格式: [uint32_t username_len][uint32_t password_len][username][password]
    const char* body = data.data() + sizeof(MessageHeader);
    if (header->length < 2 * sizeof(uint32_t)) {
        return;
    }
    uint32_t username_len = *reinterpret_cast<const uint32_t*>(body);
    uint32_t password_len = *reinterpret_cast<const uint32_t*>(body + sizeof(uint32_t));
    if (header->length != 2 * sizeof(uint32_t) + username_len + password_len) {
        return;
    }
    std::string username(body + 2 * sizeof(uint32_t), username_len);
    std::string password(body + 2 * sizeof(uint32_t) + username_len, password_len);
    bool authenticated = session_manager_->Authenticate(session_->GetSessionId(), username, password);
    // 发送认证确认消息
    MessageHeader ack_header;
    ack_header.magic = 0x53514C43; // 'SQLC'
    ack_header.length = 0;
    ack_header.type = AUTH_ACK;
    ack_header.flags = authenticated ? 0 : 1; // 使用flags表示认证结果
    ack_header.sequence_id = header->sequence_id;
    std::vector<char> ack_msg(sizeof(MessageHeader));
    std::memcpy(ack_msg.data(), &ack_header, sizeof(MessageHeader));
    SendMessage(ack_msg);
}
References sqlcc::network::AUTH_ACK, sqlcc::network::MessageHeader::flags, sqlcc::network::MessageHeader::length, sqlcc::network::MessageHeader::magic, SendMessage(), sqlcc::network::MessageHeader::sequence_id, session_, session_manager_, and sqlcc::network::MessageHeader::type.
Referenced by ProcessMessage().
HandleConnectMessage()
void sqlcc::network::ConnectionHandler::HandleConnectMessage (const std::vector< char > & data) private
Definition at line 394 of file network.cpp.
{
    // 创建会话
    session_ = session_manager_->CreateSession();
    // 检查客户端连接消息中的标志
    uint32_t client_flags = 0;
    if (data.size() >= sizeof(MessageHeader)) {
        MessageHeader* header = reinterpret_cast<MessageHeader*>(const_cast<char*>(data.data()));
        client_flags = header->flags;
        // 如果客户端请求禁用加密，记录到会话中
        if (client_flags & 0x01) {
            session_->SetEncryptionDisabled(true);
        }
        // 如果客户端请求禁用认证，记录到会话中
        if (client_flags & 0x02) {
            session_->SetAuthenticationDisabled(true);
            // 自动通过认证
            session_->SetAuthenticated("anonymous");
        }
    }
    // 发送连接确认消息，包含相同的标志
    MessageHeader ack_header;
    ack_header.magic = 0x53514C43; // 'SQLC'
    ack_header.length = 0;
    ack_header.type = CONN_ACK;
    ack_header.flags = client_flags; // 回显客户端的标志
    ack_header.sequence_id = 1;
    std::vector<char> ack_msg(sizeof(MessageHeader));
    std::memcpy(ack_msg.data(), &ack_header, sizeof(MessageHeader));
    SendMessage(ack_msg);
}
References sqlcc::network::CONN_ACK, sqlcc::network::MessageHeader::flags, sqlcc::network::MessageHeader::length, sqlcc::network::MessageHeader::magic, SendMessage(), sqlcc::network::MessageHeader::sequence_id, session_, session_manager_, and sqlcc::network::MessageHeader::type.
Referenced by ProcessMessage().
HandleEvent()
void sqlcc::network::ConnectionHandler::HandleEvent (uint32_t events)
Definition at line 280 of file network.cpp.
{
#ifdef __linux__
    if (events & EPOLLIN) {
        HandleRead();
    }
    if (events & EPOLLOUT) {
        HandleWrite();
    }
    if (events & (EPOLLERR | EPOLLHUP)) {
        Close();
    }
#endif
}
References Close(), HandleRead(), and HandleWrite().
Referenced by sqlcc::network::ServerNetworkManager::ProcessEvents().
HandleKeyExchangeMessage()
void sqlcc::network::ConnectionHandler::HandleKeyExchangeMessage (const std::vector< char > & data) private
Definition at line 531 of file network.cpp.
{
    // 处理密钥交换消息
    MessageHeader* header = reinterpret_cast<MessageHeader*>(const_cast<char*>(data.data()));
    // 构造密钥交换确认消息
    std::string ack_data = "Key exchange completed";
    MessageHeader ack_header;
    ack_header.magic = 0x53514C43; // 'SQLC'
    ack_header.length = ack_data.length();
    ack_header.type = KEY_EXCHANGE_ACK;
    ack_header.flags = 0;
    ack_header.sequence_id = header->sequence_id;
    std::vector<char> ack_msg(sizeof(MessageHeader) + ack_data.length());
    std::memcpy(ack_msg.data(), &ack_header, sizeof(MessageHeader));
    std::memcpy(ack_msg.data() + sizeof(MessageHeader), ack_data.c_str(), ack_data.length());
    SendMessage(ack_msg);
}
References sqlcc::network::MessageHeader::flags, sqlcc::network::KEY_EXCHANGE_ACK, sqlcc::network::MessageHeader::length, sqlcc::network::MessageHeader::magic, SendMessage(), sqlcc::network::MessageHeader::sequence_id, and sqlcc::network::MessageHeader::type.
Referenced by ProcessMessage().
HandleQueryMessage()
void sqlcc::network::ConnectionHandler::HandleQueryMessage (const std::vector< char > & data) private
Definition at line 472 of file network.cpp.
{
    if (!session_) {
        // 会话不存在
        SendErrorMessage("Session not found");
        return;
    }
    // 检查是否需要认证（只有在未禁用认证的情况下才要求认证）
    if (!session_->IsAuthenticationDisabled() && !session_->IsAuthenticated()) {
        // 未禁用认证但用户未认证，拒绝请求
        SendErrorMessage("Not authenticated");
        return;
    }
    MessageHeader* header = reinterpret_cast<MessageHeader*>(const_cast<char*>(data.data()));
    // 确保有足够的数据
    if (data.size() < sizeof(MessageHeader) + header->length) {
        SendErrorMessage("Invalid query message");
        return;
    }
    // 获取查询语句
    std::string query(data.data() + sizeof(MessageHeader), header->length);
    // 执行SQL查询
    std::string result;
    bool success = true;  // 默认成功，只有发生错误时设为false
    if (sql_executor_) {
        try {
            result = sql_executor_->Execute(query);
            // 检查执行结果是否表示错误
            if (result.find("ERROR:") == 0 || result.find("Error:") == 0) {
                success = false;
            }
        } catch (const std::exception& e) {
            result = "Exception: " + std::string(e.what());
            success = false;
        }
    } else {
        result = "SQL executor not initialized";
        success = false;
    }
    // 构造查询结果消息
    MessageHeader result_header;
    result_header.magic = 0x53514C43; // 'SQLC'
    result_header.length = result.length();
    result_header.type = QUERY_RESULT;
    result_header.flags = success ? 0 : 1; // 使用flags表示执行结果
    result_header.sequence_id = header->sequence_id;
    std::vector<char> result_msg(sizeof(MessageHeader) + result.length());
    std::memcpy(result_msg.data(), &result_header, sizeof(MessageHeader));
    std::memcpy(result_msg.data() + sizeof(MessageHeader), result.c_str(), result.length());
    SendMessage(result_msg);
}
References sqlcc::network::MessageHeader::flags, sqlcc::network::MessageHeader::length, sqlcc::network::MessageHeader::magic, sqlcc::network::QUERY_RESULT, SendErrorMessage(), SendMessage(), sqlcc::network::MessageHeader::sequence_id, session_, sql_executor_, and sqlcc::network::MessageHeader::type.
Referenced by ProcessMessage().
HandleRead()
void sqlcc::network::ConnectionHandler::HandleRead () private
Definition at line 294 of file network.cpp.
{
#ifdef __linux__
    // 读取数据并处理
    std::vector<char> buffer(4096);
    ssize_t bytes_read = recv(fd_, buffer.data(), buffer.size(), 0);
    if (bytes_read > 0) {
        buffer.resize(bytes_read);
        ProcessMessage(buffer);
    } else if (bytes_read == 0) {
        // 客户端关闭连接
        Close();
    } else {
        // 错误发生
        if (errno != EAGAIN && errno != EWOULDBLOCK) {
            Close();
        }
    }
#endif
}
References Close(), fd_, and ProcessMessage().
Referenced by HandleEvent().
HandleWrite()
void sqlcc::network::ConnectionHandler::HandleWrite () private
Definition at line 315 of file network.cpp.
{
#ifdef __linux__
    // 处理写事件（如果有待发送的数据）
    std::lock_guard<std::mutex> lock(write_mutex_);
    while (!write_queue_.empty()) {
        const std::vector<char>& data = write_queue_.front();
        ssize_t bytes_sent = send(fd_, data.data(), data.size(), 0);
        if (bytes_sent > 0) {
            // 成功发送数据
            write_queue_.pop();
        } else if (bytes_sent < 0) {
            if (errno == EAGAIN || errno == EWOULDBLOCK) {
                // 发送缓冲区满，稍后重试
                break;
            } else {
                // 错误发生，关闭连接
                Close();
                break;
            }
        }
    }
#endif
}
References Close(), fd_, write_mutex_, and write_queue_.
Referenced by HandleEvent(), and SendMessage().
IsClosed()
bool sqlcc::network::ConnectionHandler::IsClosed () const
Definition at line 276 of file network.cpp.
{
    return closed_;
}
References closed_.
Referenced by sqlcc::network::ServerNetworkManager::ProcessEvents().
ProcessMessage()
void sqlcc::network::ConnectionHandler::ProcessMessage (const std::vector< char > & data)
Definition at line 361 of file network.cpp.
{
    // 处理接收到的消息
    if (data.size() < sizeof(MessageHeader)) {
        return;
    }
    MessageHeader* header = reinterpret_cast<MessageHeader*>(const_cast<char*>(data.data()));
    // 检查消息魔数
    if (header->magic != 0x53514C43) { // 'SQLC'
        return;
    }
    // 根据消息类型处理
    switch (header->type) {
        case CONNECT:
            HandleConnectMessage(data);
            break;
        case AUTH:
            HandleAuthMessage(data);
            break;
        case QUERY:
            HandleQueryMessage(data);
            break;
        case KEY_EXCHANGE:
            HandleKeyExchangeMessage(data);
            break;
        default:
            // 未知消息类型
            break;
    }
}
References sqlcc::network::AUTH, sqlcc::network::CONNECT, HandleAuthMessage(), HandleConnectMessage(), HandleKeyExchangeMessage(), HandleQueryMessage(), sqlcc::network::KEY_EXCHANGE, sqlcc::network::MessageHeader::magic, sqlcc::network::QUERY, and sqlcc::network::MessageHeader::type.
Referenced by HandleRead().
SendErrorMessage()
void sqlcc::network::ConnectionHandler::SendErrorMessage (const std::string & error) private
Definition at line 551 of file network.cpp.
{
    MessageHeader error_header;
    error_header.magic = 0x53514C43; // 'SQLC'
    error_header.length = error.length();
    error_header.type = ERROR;
    error_header.flags = 0;
    error_header.sequence_id = 0;
    std::vector<char> error_msg(sizeof(MessageHeader) + error.length());
    std::memcpy(error_msg.data(), &error_header, sizeof(MessageHeader));
    std::memcpy(error_msg.data() + sizeof(MessageHeader), error.c_str(), error.length());
    SendMessage(error_msg);
}
References sqlcc::network::ERROR, sqlcc::network::MessageHeader::flags, sqlcc::network::MessageHeader::length, sqlcc::network::MessageHeader::magic, SendMessage(), sqlcc::network::MessageHeader::sequence_id, and sqlcc::network::MessageHeader::type.
Referenced by HandleQueryMessage().
SendMessage()
void sqlcc::network::ConnectionHandler::SendMessage (const std::vector< char > & message) private
Definition at line 340 of file network.cpp.
{
#ifdef __linux__
    std::lock_guard<std::mutex> lock(write_mutex_);
    write_queue_.push(message);
    // 尝试立即发送
    if (write_queue_.size() == 1) {
        HandleWrite();
    }
#endif
}
References HandleWrite(), write_mutex_, and write_queue_.
Referenced by HandleAuthMessage(), HandleConnectMessage(), HandleKeyExchangeMessage(), HandleQueryMessage(), and SendErrorMessage().
Member Data Documentation
closed_
bool sqlcc::network::ConnectionHandler::closed_ private
Definition at line 158 of file network.h.
Referenced by Close(), and IsClosed().
fd_
int sqlcc::network::ConnectionHandler::fd_ private
Definition at line 154 of file network.h.
Referenced by Close(), ConnectionHandler(), GetFd(), HandleRead(), and HandleWrite().
session_
std::shared_ptr<Session> sqlcc::network::ConnectionHandler::session_ private
Definition at line 157 of file network.h.
Referenced by HandleAuthMessage(), HandleConnectMessage(), and HandleQueryMessage().
session_manager_
std::shared_ptr<SessionManager> sqlcc::network::ConnectionHandler::session_manager_ private
Definition at line 155 of file network.h.
Referenced by HandleAuthMessage(), and HandleConnectMessage().
sql_executor_
std::shared_ptr<sqlcc::SqlExecutor> sqlcc::network::ConnectionHandler::sql_executor_ private
Definition at line 156 of file network.h.
Referenced by HandleQueryMessage().
write_mutex_
std::mutex sqlcc::network::ConnectionHandler::write_mutex_ private
Definition at line 160 of file network.h.
Referenced by HandleWrite(), and SendMessage().
write_queue_
std::queue<std::vector<char> > sqlcc::network::ConnectionHandler::write_queue_ private
Definition at line 159 of file network.h.
Referenced by HandleWrite(), and SendMessage().
The documentation for this class was generated from the following files:
include/network/network.h
src/network/network.cpp