SQLCC: sqlcc::sql_parser::NodeVisitor Class Reference
sqlcc::sql_parser::NodeVisitor Class Reference abstract
#include <ast_node.h>
Public Member Functions
virtual ~NodeVisitor ()=default
virtual void visit (class CreateStatement &node)=0
virtual void visit (class SelectStatement &node)=0
virtual void visit (class InsertStatement &node)=0
virtual void visit (class UpdateStatement &node)=0
virtual void visit (class DeleteStatement &node)=0
virtual void visit (class DropStatement &node)=0
virtual void visit (class AlterStatement &node)=0
virtual void visit (class UseStatement &node)=0
virtual void visit (class CreateIndexStatement &node)=0
virtual void visit (class DropIndexStatement &node)=0
virtual void visit (class BeginTransactionStatement &node)=0
virtual void visit (class CommitStatement &node)=0
virtual void visit (class RollbackStatement &node)=0
virtual void visit (class SavepointStatement &node)=0
virtual void visit (class SetTransactionStatement &node)=0
virtual void visit (class CreateUserStatement &node)=0
virtual void visit (class DropUserStatement &node)=0
virtual void visit (class AlterUserStatement &node)=0
virtual void visit (class GrantStatement &node)=0
virtual void visit (class RevokeStatement &node)=0
virtual void visit (class IdentifierExpression &node)=0
virtual void visit (class StringLiteralExpression &node)=0
virtual void visit (class NumericLiteralExpression &node)=0
virtual void visit (class BinaryExpression &node)=0
virtual void visit (class UnaryExpression &node)=0
virtual void visit (class FunctionExpression &node)=0
virtual void visit (class ExistsExpression &node)=0
virtual void visit (class InExpression &node)=0
virtual void visit (class WhereClause &node)=0
virtual void visit (class JoinClause &node)=0
virtual void visit (class GroupByClause &node)=0
virtual void visit (class OrderByClause &node)=0
Detailed Description
AST节点访问者接口
Definition at line 31 of file ast_node.h.
Constructor & Destructor Documentation
~NodeVisitor()
virtual sqlcc::sql_parser::NodeVisitor::~NodeVisitor () virtual default
Member Function Documentation
visit() [1/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class AlterStatement & node) pure virtual
visit() [2/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class AlterUserStatement & node) pure virtual
visit() [3/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class BeginTransactionStatement & node) pure virtual
visit() [4/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class BinaryExpression & node) pure virtual
visit() [5/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class CommitStatement & node) pure virtual
visit() [6/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class CreateIndexStatement & node) pure virtual
visit() [7/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class CreateStatement & node) pure virtual
Referenced by sqlcc::sql_parser::CreateStatement::accept(), sqlcc::sql_parser::SelectStatement::accept(), sqlcc::sql_parser::InsertStatement::accept(), sqlcc::sql_parser::UpdateStatement::accept(), sqlcc::sql_parser::DeleteStatement::accept(), sqlcc::sql_parser::DropStatement::accept(), sqlcc::sql_parser::AlterStatement::accept(), sqlcc::sql_parser::UseStatement::accept(), sqlcc::sql_parser::CreateIndexStatement::accept(), sqlcc::sql_parser::DropIndexStatement::accept(), sqlcc::sql_parser::BeginTransactionStatement::accept(), sqlcc::sql_parser::CommitStatement::accept(), sqlcc::sql_parser::RollbackStatement::accept(), sqlcc::sql_parser::SavepointStatement::accept(), sqlcc::sql_parser::GrantStatement::accept(), sqlcc::sql_parser::RevokeStatement::accept(), sqlcc::sql_parser::CreateUserStatement::accept(), sqlcc::sql_parser::DropUserStatement::accept(), sqlcc::sql_parser::AlterUserStatement::accept(), sqlcc::sql_parser::SetTransactionStatement::accept(), sqlcc::sql_parser::IdentifierExpression::accept(), sqlcc::sql_parser::StringLiteralExpression::accept(), sqlcc::sql_parser::NumericLiteralExpression::accept(), sqlcc::sql_parser::BinaryExpression::accept(), sqlcc::sql_parser::UnaryExpression::accept(), sqlcc::sql_parser::FunctionExpression::accept(), sqlcc::sql_parser::ExistsExpression::accept(), sqlcc::sql_parser::InExpression::accept(), sqlcc::sql_parser::WhereClause::accept(), sqlcc::sql_parser::JoinClause::accept(), sqlcc::sql_parser::GroupByClause::accept(), and sqlcc::sql_parser::OrderByClause::accept().
visit() [8/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class CreateUserStatement & node) pure virtual
visit() [9/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class DeleteStatement & node) pure virtual
visit() [10/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class DropIndexStatement & node) pure virtual
visit() [11/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class DropStatement & node) pure virtual
visit() [12/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class DropUserStatement & node) pure virtual
visit() [13/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class ExistsExpression & node) pure virtual
visit() [14/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class FunctionExpression & node) pure virtual
visit() [15/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class GrantStatement & node) pure virtual
visit() [16/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class GroupByClause & node) pure virtual
visit() [17/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class IdentifierExpression & node) pure virtual
visit() [18/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class InExpression & node) pure virtual
visit() [19/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class InsertStatement & node) pure virtual
visit() [20/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class JoinClause & node) pure virtual
visit() [21/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class NumericLiteralExpression & node) pure virtual
visit() [22/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class OrderByClause & node) pure virtual
visit() [23/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class RevokeStatement & node) pure virtual
visit() [24/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class RollbackStatement & node) pure virtual
visit() [25/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class SavepointStatement & node) pure virtual
visit() [26/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class SelectStatement & node) pure virtual
visit() [27/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class SetTransactionStatement & node) pure virtual
visit() [28/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class StringLiteralExpression & node) pure virtual
visit() [29/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class UnaryExpression & node) pure virtual
visit() [30/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class UpdateStatement & node) pure virtual
visit() [31/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class UseStatement & node) pure virtual
visit() [32/32]
virtual void sqlcc::sql_parser::NodeVisitor::visit (class WhereClause & node) pure virtual
The documentation for this class was generated from the following file:
include/sql_parser/ast_node.h