SQLCC: sqlcc::Page Class Reference
sqlcc::Page Class Reference
数据库页面类，表示一个8KB的定长页面
#include <page.h>
Public Member Functions
Page ()
构造函数
Page (int32_t page_id)
构造函数，使用指定的页面ID初始化
~Page ()
析构函数
int32_t GetPageId () const
获取页面ID
void SetPageId (int32_t page_id)
设置页面ID
char * GetData ()
获取页面数据指针
const char * GetData () const
获取页面数据指针(const版本)
void WriteData (size_t offset, const char *data, size_t size)
将数据写入页面
void ReadData (size_t offset, char *data, size_t size) const
从页面读取数据
Private Attributes
int32_t page_id_ = -1
char data_ [PAGE_SIZE] = {0}
Detailed Description
数据库页面类，表示一个8KB的定长页面
Why: 数据库系统需要将数据组织成固定大小的页面，以便在磁盘和内存之间高效传输和管理 What: Page类封装了一个固定大小的数据块，包含页面ID和实际数据，是数据库存储系统的基本单位 How: 使用字符数组存储页面数据，提供读写操作接口，通过页面ID唯一标识每个页面
Definition at line 21 of file page.h.
Constructor & Destructor Documentation
Page() [1/2]
sqlcc::Page::Page () default
构造函数
Why: 需要创建页面对象并初始化其内部状态 What: 默认构造函数创建一个新页面，初始化页面ID为-1(表示无效页面)，清零数据缓冲区 How: 使用成员初始化列表设置page_id_为-1，使用{0}初始化data_数组为全零
Page() [2/2]
sqlcc::Page::Page (int32_t page_id) explicit
构造函数，使用指定的页面ID初始化
Parameters
page_id 页面ID
Why: 有时需要在创建页面对象时直接指定其ID，例如从磁盘读取页面时 What: 带参数的构造函数创建一个新页面，使用指定的页面ID初始化，清零数据缓冲区 How: 使用成员初始化列表设置page_id_为传入的参数值，使用{0}初始化data_数组为全零
Definition at line 18 of file page.cpp.
                          : page_id_(page_id) {
    // 记录页面创建，便于调试
    // Why: 日志记录有助于系统运行状态的监控和问题排查
    // What: 记录正在创建的页面ID
    // How: 使用SQLCC_LOG_DEBUG宏记录调试级别日志
    SQLCC_LOG_DEBUG("Creating page with ID: " + std::to_string(page_id_));
    // 初始化页面数据为0
    // Why: 需要确保新页面的数据区域是干净的，不包含随机数据
    // What: 使用memset将data_数组的所有字节设置为0
    // How: 调用memset函数，传入数组指针、0值和数组大小
    memset(data_, 0, PAGE_SIZE);
}
References data_, page_id_, sqlcc::PAGE_SIZE, and SQLCC_LOG_DEBUG.
~Page()
sqlcc::Page::~Page ()
析构函数
Why: 需要在页面对象销毁时释放资源(虽然当前实现没有动态资源) What: 析构函数负责清理页面对象的资源 How: 当前实现使用默认析构函数，因为Page类没有动态分配的资源
Definition at line 36 of file page.cpp.
            {
    // 记录页面销毁，便于调试
    // Why: 日志记录有助于系统运行状态的监控和问题排查
    // What: 记录正在销毁的页面ID
    // How: 使用SQLCC_LOG_DEBUG宏记录调试级别日志
    SQLCC_LOG_DEBUG("Destroying page with ID: " + std::to_string(page_id_));
}
References page_id_, and SQLCC_LOG_DEBUG.
Member Function Documentation
GetData() [1/2]
char * sqlcc::Page::GetData () inline
获取页面数据指针
Returns
指向页面数据的指针
Why: 需要访问页面中的实际数据，以便进行读写操作 What: GetData方法返回指向页面数据缓冲区的指针 How: 直接返回data_数组的指针，使用inline关键字提高性能
Definition at line 79 of file page.h.
{ return data_; }
References data_.
Referenced by sqlcc::BufferPool::DeletePage(), sqlcc::BufferPool::FlushPage(), sqlcc::BufferPool::PrefetchPage(), sqlcc::BufferPool::ReplacePage(), and sqlcc::TestDiskManager::TestWritePage().
GetData() [2/2]
const char * sqlcc::Page::GetData () const inline
获取页面数据指针(const版本)
Returns
指向页面数据的const指针
Why: 在const上下文中需要访问页面数据，但不允许修改 What: GetData方法(const版本)返回指向页面数据缓冲区的const指针 How: 直接返回data_数组的const指针，使用inline关键字提高性能
Definition at line 89 of file page.h.
{ return data_; }
References data_.
GetPageId()
int32_t sqlcc::Page::GetPageId () const inline
获取页面ID
Returns
页面ID
Why: 需要知道页面的唯一标识符，以便进行页面管理和定位 What: GetPageId方法返回当前页面的ID值 How: 直接返回page_id_成员变量的值，使用inline关键字提高性能
Definition at line 59 of file page.h.
{ return page_id_; }
References page_id_.
Referenced by sqlcc::TestDiskManager::TestWritePage().
ReadData()
void sqlcc::Page::ReadData (size_t offset, char * data, size_t size) const
从页面读取数据
Parameters
offset 读取偏移量
data 读取数据的缓冲区
size 要读取的数据大小
Why: 需要从页面的特定位置读取数据，例如读取记录或元数据 What: ReadData方法从页面的指定偏移量处读取指定大小的数据到目标缓冲区 How: 使用memcpy函数进行内存复制，检查边界条件确保不会越界读取
Definition at line 95 of file page.cpp.
{
    // 记录读取操作，便于调试
    // Why: 日志记录有助于系统运行状态的监控和问题排查
    // What: 记录正在读取的页面ID、偏移量和数据大小
    // How: 使用SQLCC_LOG_DEBUG宏记录调试级别日志
    SQLCC_LOG_DEBUG("Reading data from page ID " + std::to_string(page_id_) +
                   " at offset " + std::to_string(offset) + " with size " + std::to_string(size));
    // 检查边界
    // Why: 防止读取超出页面边界，避免内存越界和读取无效数据
    // What: 检查偏移量加上数据大小是否超过页面大小
    // How: 使用if语句比较offset+size和PAGE_SIZE，如果越界则抛出异常
    if (offset + size > PAGE_SIZE) {
        // 创建错误消息
        // Why: 需要提供详细的错误信息，帮助调试和问题定位
        // What: 构建包含偏移量、数据大小和页面大小的错误消息
        // How: 使用字符串拼接和std::to_string函数
        std::string error_msg = "ReadData out of bounds: offset=" + std::to_string(offset) +
                               ", size=" + std::to_string(size) + ", page_size=" + std::to_string(PAGE_SIZE);
        // 记录错误，便于调试
        // Why: 错误日志有助于问题排查和系统监控
        // What: 记录错误消息
        // How: 使用SQLCC_LOG_ERROR宏记录错误级别日志
        SQLCC_LOG_ERROR(error_msg);
        // 抛出异常，终止操作
        // Why: 边界检查失败是严重错误，需要终止操作以避免数据损坏
        // What: 抛出PageException异常
        // How: 使用throw关键字抛出异常
        throw PageException(error_msg);
    }
    // 复制数据
    // Why: 需要将页面数据复制到目标缓冲区
    // What: 使用memcpy函数进行内存复制
    // How: 调用memcpy函数，传入目标地址、源地址和大小
    memcpy(dest, data_ + offset, size);
    // 记录读取成功，便于调试
    // Why: 日志记录有助于系统运行状态的监控和问题排查
    // What: 记录读取成功的页面ID
    // How: 使用SQLCC_LOG_DEBUG宏记录调试级别日志
    SQLCC_LOG_DEBUG("Successfully read data from page ID " + std::to_string(page_id_));
}
References data_, page_id_, sqlcc::PAGE_SIZE, SQLCC_LOG_DEBUG, and SQLCC_LOG_ERROR.
SetPageId()
void sqlcc::Page::SetPageId (int32_t page_id) inline
设置页面ID
Parameters
page_id 新的页面ID
Why: 有时需要修改页面的ID，例如从磁盘读取页面后设置正确的ID What: SetPageId方法将当前页面的ID设置为指定值 How: 直接将传入的page_id参数赋值给page_id_成员变量，使用inline关键字提高性能
Definition at line 69 of file page.h.
{ page_id_ = page_id; }
References page_id_.
Referenced by sqlcc::BufferPool::PrefetchPage().
WriteData()
void sqlcc::Page::WriteData (size_t offset, const char * data, size_t size)
将数据写入页面
Parameters
offset 写入偏移量
data 要写入的数据
size 数据大小
Why: 需要将外部数据写入到页面的特定位置，例如存储记录或元数据 What: WriteData方法将指定大小的数据从源缓冲区复制到页面的指定偏移量处 How: 使用memcpy函数进行内存复制，检查边界条件确保不会越界写入
Definition at line 48 of file page.cpp.
{
    // 记录写入操作，便于调试
    // Why: 日志记录有助于系统运行状态的监控和问题排查
    // What: 记录正在写入的页面ID、偏移量和数据大小
    // How: 使用SQLCC_LOG_DEBUG宏记录调试级别日志
    SQLCC_LOG_DEBUG("Writing data to page ID " + std::to_string(page_id_) +
                   " at offset " + std::to_string(offset) + " with size " + std::to_string(size));
    // 检查边界
    // Why: 防止写入超出页面边界，避免内存越界和缓冲区溢出
    // What: 检查偏移量加上数据大小是否超过页面大小
    // How: 使用if语句比较offset+size和PAGE_SIZE，如果越界则抛出异常
    if (offset + size > PAGE_SIZE) {
        // 创建错误消息
        // Why: 需要提供详细的错误信息，帮助调试和问题定位
        // What: 构建包含偏移量、数据大小和页面大小的错误消息
        // How: 使用字符串拼接和std::to_string函数
        std::string error_msg = "WriteData out of bounds: offset=" + std::to_string(offset) +
                               ", size=" + std::to_string(size) + ", page_size=" + std::to_string(PAGE_SIZE);
        // 记录错误，便于调试
        // Why: 错误日志有助于问题排查和系统监控
        // What: 记录错误消息
        // How: 使用SQLCC_LOG_ERROR宏记录错误级别日志
        SQLCC_LOG_ERROR(error_msg);
        // 抛出异常，终止操作
        // Why: 边界检查失败是严重错误，需要终止操作以避免数据损坏
        // What: 抛出PageException异常
        // How: 使用throw关键字抛出异常
        throw PageException(error_msg);
    }
    // 复制数据
    // Why: 需要将源数据复制到页面的指定位置
    // What: 使用memcpy函数进行内存复制
    // How: 调用memcpy函数，传入目标地址、源地址和大小
    memcpy(data_ + offset, src, size);
    // 记录写入成功，便于调试
    // Why: 日志记录有助于系统运行状态的监控和问题排查
    // What: 记录写入成功的页面ID
    // How: 使用SQLCC_LOG_DEBUG宏记录调试级别日志
    SQLCC_LOG_DEBUG("Successfully wrote data to page ID " + std::to_string(page_id_));
}
References data_, page_id_, sqlcc::PAGE_SIZE, SQLCC_LOG_DEBUG, and SQLCC_LOG_ERROR.
Member Data Documentation
data_
char sqlcc::Page::data_[PAGE_SIZE] = {0} private
Definition at line 126 of file page.h.
{0};
Referenced by GetData(), GetData(), Page(), ReadData(), and WriteData().
page_id_
int32_t sqlcc::Page::page_id_ = -1 private
Definition at line 120 of file page.h.
Referenced by GetPageId(), Page(), ReadData(), SetPageId(), WriteData(), and ~Page().
The documentation for this class was generated from the following files:
include/page.h
src/storage_engine/page.cpp