SQLCC: sqlcc::DataTypeUtils Class Reference
sqlcc::DataTypeUtils Class Reference
数据类型帮助函数
#include <data_type.h>
Static Public Member Functions
static std::string typeToString (DataType::Type type)
获取类型的字符串表示
static DataType::Type stringToType (const std::string &str)
从字符串解析类型
static std::string valueToString (const DataType::Value &value, DataType::Type type)
值转换为字符串
static DataType::Value stringToValue (const std::string &str, DataType::Type type)
字符串转换为值
static bool areCompatible (DataType::Type from, DataType::Type to)
检查类型兼容性
static DataType::Value convertValue (const DataType::Value &value, DataType::Type fromType, DataType::Type toType)
执行类型转换
static bool isNumericType (DataType::Type type)
检查是否为数值类型
static bool isStringType (DataType::Type type)
检查是否为字符串类型
static double extractNumericValue (const DataType::Value &value, DataType::Type type)
提取数值类型的值为double
static DataType::Value convertToNumericType (double value, DataType::Type toType)
将double转换为指定的数值类型
static std::string getStringValue (const DataType::Value &value)
获取字符串类型的数值
Detailed Description
数据类型帮助函数
Definition at line 132 of file data_type.h.
Member Function Documentation
areCompatible()
bool sqlcc::DataTypeUtils::areCompatible (DataType::Type from, DataType::Type to) static
检查类型兼容性
Definition at line 338 of file data_type.cpp.
{
  // 相同类型总是兼容的
  if (from == to)
    return true;
  // 数值类型之间的兼容性
  if (isNumericType(from) && isNumericType(to)) {
    return true;
  }
  // 字符串类型兼容性
  if (isStringType(from) && isStringType(to)) {
    return true;
  }
  // 布尔类型的特殊处理
  if ((from == DataType::BOOLEAN && isNumericType(to)) ||
      (isNumericType(from) && to == DataType::BOOLEAN)) {
    return true;
  }
  return false;
}
References sqlcc::DataType::BOOLEAN, isNumericType(), and isStringType().
convertToNumericType()
DataType::Value sqlcc::DataTypeUtils::convertToNumericType (double value, DataType::Type toType) static
将double转换为指定的数值类型
Definition at line 423 of file data_type.cpp.
{
  switch (toType) {
  case DataType::INTEGER:
    return static_cast<int32_t>(value);
  case DataType::SMALLINT:
    return static_cast<int16_t>(value);
  case DataType::BIGINT:
    return static_cast<int64_t>(value);
  case DataType::DECIMAL:
  case DataType::DOUBLE:
    return value;
  default:
    return value;
  }
}
References sqlcc::DataType::BIGINT, sqlcc::DataType::DECIMAL, sqlcc::DataType::DOUBLE, sqlcc::DataType::INTEGER, and sqlcc::DataType::SMALLINT.
Referenced by convertValue().
convertValue()
DataType::Value sqlcc::DataTypeUtils::convertValue (const DataType::Value & value, DataType::Type fromType, DataType::Type toType) static
执行类型转换
Definition at line 362 of file data_type.cpp.
{
  if (fromType == toType) {
    return value;
  }
  // 如果是NULL值，直接返回
  if (std::holds_alternative<std::monostate>(value)) {
    return value;
  }
  // 数字类型转换
  if (isNumericType(fromType) && isNumericType(toType)) {
    double numVal = extractNumericValue(value, fromType);
    return convertToNumericType(numVal, toType);
  }
  // 布尔类型转换
  if (fromType == DataType::BOOLEAN && isNumericType(toType)) {
    bool boolVal = std::get<bool>(value);
    return convertToNumericType(boolVal ? 1.0 : 0.0, toType);
  }
  if (isNumericType(fromType) && toType == DataType::BOOLEAN) {
    double numVal = extractNumericValue(value, fromType);
    return numVal != 0.0;
  }
  // 不支持的转换返回原值（错误处理应该在调用者处）
  return value;
}
References sqlcc::DataType::BOOLEAN, convertToNumericType(), extractNumericValue(), and isNumericType().
extractNumericValue()
double sqlcc::DataTypeUtils::extractNumericValue (const DataType::Value & value, DataType::Type type) static
提取数值类型的值为double
Definition at line 406 of file data_type.cpp.
{
  switch (type) {
  case DataType::INTEGER:
    return static_cast<double>(std::get<int32_t>(value));
  case DataType::SMALLINT:
    return static_cast<double>(std::get<int16_t>(value));
  case DataType::BIGINT:
    return static_cast<double>(std::get<int64_t>(value));
  case DataType::DECIMAL:
  case DataType::DOUBLE:
    return std::get<double>(value);
  default:
    return 0.0;
  }
}
References sqlcc::DataType::BIGINT, sqlcc::DataType::DECIMAL, sqlcc::DataType::DOUBLE, sqlcc::DataType::INTEGER, and sqlcc::DataType::SMALLINT.
Referenced by convertValue().
getStringValue()
std::string sqlcc::DataTypeUtils::getStringValue (const DataType::Value & value) static
获取字符串类型的数值
Definition at line 10 of file data_type.cpp.
{
  try {
    return std::get<std::string>(value);
  } catch (const std::bad_variant_access &) {
    throw DataTypeException("Value is not a string type");
  }
}
Referenced by valueToString().
isNumericType()
bool sqlcc::DataTypeUtils::isNumericType (DataType::Type type) static
检查是否为数值类型
Definition at line 395 of file data_type.cpp.
{
  return type == DataType::INTEGER || type == DataType::SMALLINT ||
         type == DataType::BIGINT || type == DataType::DECIMAL ||
         type == DataType::DOUBLE;
}
References sqlcc::DataType::BIGINT, sqlcc::DataType::DECIMAL, sqlcc::DataType::DOUBLE, sqlcc::DataType::INTEGER, and sqlcc::DataType::SMALLINT.
Referenced by areCompatible(), and convertValue().
isStringType()
bool sqlcc::DataTypeUtils::isStringType (DataType::Type type) static
检查是否为字符串类型
Definition at line 401 of file data_type.cpp.
{
  return type == DataType::CHAR || type == DataType::VARCHAR ||
         type == DataType::TEXT;
}
References sqlcc::DataType::CHAR, sqlcc::DataType::TEXT, and sqlcc::DataType::VARCHAR.
Referenced by areCompatible().
stringToType()
DataType::Type sqlcc::DataTypeUtils::stringToType (const std::string & str) static
从字符串解析类型
Definition at line 207 of file data_type.cpp.
{
  std::string upper = str;
  std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
  if (upper == "INT" || upper == "INTEGER")
    return DataType::INTEGER;
  if (upper == "SMALLINT")
    return DataType::SMALLINT;
  if (upper == "BIGINT")
    return DataType::BIGINT;
  if (upper == "DECIMAL" || upper == "NUMERIC")
    return DataType::DECIMAL;
  if (upper == "DOUBLE" || upper == "REAL" || upper == "FLOAT")
    return DataType::DOUBLE;
  if (upper == "CHAR")
    return DataType::CHAR;
  if (upper == "VARCHAR")
    return DataType::VARCHAR;
  if (upper == "TEXT")
    return DataType::TEXT;
  if (upper == "DATE")
    return DataType::DATE;
  if (upper == "TIME")
    return DataType::TIME;
  if (upper == "TIMESTAMP" || upper == "DATETIME")
    return DataType::TIMESTAMP;
  if (upper == "BOOLEAN" || upper == "BOOL")
    return DataType::BOOLEAN;
  throw DataTypeException("Unknown data type: " + str);
}
References sqlcc::DataType::BIGINT, sqlcc::DataType::BOOLEAN, sqlcc::DataType::CHAR, sqlcc::DataType::DATE, sqlcc::DataType::DECIMAL, sqlcc::DataType::DOUBLE, sqlcc::DataType::INTEGER, sqlcc::DataType::SMALLINT, sqlcc::DataType::TEXT, sqlcc::DataType::TIME, sqlcc::DataType::TIMESTAMP, and sqlcc::DataType::VARCHAR.
Referenced by sqlcc::DataType::parseTypeString().
stringToValue()
DataType::Value sqlcc::DataTypeUtils::stringToValue (const std::string & str, DataType::Type type) static
字符串转换为值
Definition at line 283 of file data_type.cpp.
{
  if (str == "NULL") {
    return std::monostate{};
  }
  try {
    switch (type) {
    case DataType::INTEGER: {
      return static_cast<int32_t>(std::stoi(str));
    }
    case DataType::SMALLINT: {
      return static_cast<int16_t>(std::stoi(str));
    }
    case DataType::BIGINT: {
      return static_cast<int64_t>(std::stoll(str));
    }
    case DataType::DECIMAL:
    case DataType::DOUBLE: {
      return std::stod(str);
    }
    case DataType::CHAR:
    case DataType::VARCHAR:
    case DataType::TEXT: {
      // 对于字符串类型，直接存储字符串值
      return std::string(str);
    }
    case DataType::BOOLEAN: {
      std::string upper = str;
      std::transform(upper.begin(), upper.end(), upper.begin(), ::toupper);
      if (upper == "TRUE" || upper == "1" || upper == "YES") {
        return true;
      } else if (upper == "FALSE" || upper == "0" || upper == "NO") {
        return false;
      } else {
        throw DataTypeException("Invalid boolean value: " + str);
      }
    }
    case DataType::DATE:
    case DataType::TIME:
    case DataType::TIMESTAMP: {
      // 日期时间验证可以在这里添加
      // 目前简化处理，信任输入
      return std::string(str);
    }
    default: {
      return std::monostate{};
    }
    }
  } catch (const std::exception &e) {
    throw DataTypeException("Failed to convert string '" + str + "' to type '" +
                            typeToString(type) + "': " + e.what());
  }
}
References sqlcc::DataType::BIGINT, sqlcc::DataType::BOOLEAN, sqlcc::DataType::CHAR, sqlcc::DataType::DATE, sqlcc::DataType::DECIMAL, sqlcc::DataType::DOUBLE, sqlcc::DataType::INTEGER, sqlcc::DataType::SMALLINT, sqlcc::DataType::TEXT, sqlcc::DataType::TIME, sqlcc::DataType::TIMESTAMP, typeToString(), and sqlcc::DataType::VARCHAR.
typeToString()
std::string sqlcc::DataTypeUtils::typeToString (DataType::Type type) static
获取类型的字符串表示
Definition at line 176 of file data_type.cpp.
{
  switch (type) {
  case DataType::INTEGER:
    return "INTEGER";
  case DataType::SMALLINT:
    return "SMALLINT";
  case DataType::BIGINT:
    return "BIGINT";
  case DataType::DECIMAL:
    return "DECIMAL";
  case DataType::DOUBLE:
    return "DOUBLE";
  case DataType::CHAR:
    return "CHAR";
  case DataType::VARCHAR:
    return "VARCHAR";
  case DataType::TEXT:
    return "TEXT";
  case DataType::DATE:
    return "DATE";
  case DataType::TIME:
    return "TIME";
  case DataType::TIMESTAMP:
    return "TIMESTAMP";
  case DataType::BOOLEAN:
    return "BOOLEAN";
  default:
    return "UNKNOWN";
  }
}
References sqlcc::DataType::BIGINT, sqlcc::DataType::BOOLEAN, sqlcc::DataType::CHAR, sqlcc::DataType::DATE, sqlcc::DataType::DECIMAL, sqlcc::DataType::DOUBLE, sqlcc::DataType::INTEGER, sqlcc::DataType::SMALLINT, sqlcc::DataType::TEXT, sqlcc::DataType::TIME, sqlcc::DataType::TIMESTAMP, and sqlcc::DataType::VARCHAR.
Referenced by stringToValue(), and sqlcc::DataType::toString().
valueToString()
std::string sqlcc::DataTypeUtils::valueToString (const DataType::Value & value, DataType::Type type) static
值转换为字符串
Definition at line 239 of file data_type.cpp.
{
  if (std::holds_alternative<std::monostate>(value)) {
    return "NULL";
  }
  try {
    switch (type) {
    case DataType::INTEGER: {
      return std::to_string(std::get<int32_t>(value));
    }
    case DataType::SMALLINT: {
      return std::to_string(std::get<int16_t>(value));
    }
    case DataType::BIGINT: {
      // BIGINT简化处理为string，因为variant不支持int64_t
      return std::to_string(std::get<int64_t>(value));
    }
    case DataType::DECIMAL:
    case DataType::DOUBLE: {
      std::ostringstream oss;
      oss << std::fixed << std::setprecision(2) << std::get<double>(value);
      return oss.str();
    }
    case DataType::CHAR:
    case DataType::VARCHAR:
    case DataType::TEXT:
    case DataType::DATE:
    case DataType::TIME:
    case DataType::TIMESTAMP: {
      return DataTypeUtils::getStringValue(value);
    }
    case DataType::BOOLEAN: {
      return std::get<bool>(value) ? "TRUE" : "FALSE";
    }
    default: {
      return "UNKNOWN";
    }
    }
  } catch (const std::bad_variant_access &) {
    return "TYPE_MISMATCH";
  }
}
References sqlcc::DataType::BIGINT, sqlcc::DataType::BOOLEAN, sqlcc::DataType::CHAR, sqlcc::DataType::DATE, sqlcc::DataType::DECIMAL, sqlcc::DataType::DOUBLE, getStringValue(), sqlcc::DataType::INTEGER, sqlcc::DataType::SMALLINT, sqlcc::DataType::TEXT, sqlcc::DataType::TIME, sqlcc::DataType::TIMESTAMP, and sqlcc::DataType::VARCHAR.
The documentation for this class was generated from the following files:
include/data_type.h
src/sql_executor/data_type.cpp