SQLCC: sqlcc::ConfigManager Class Reference
sqlcc::ConfigManager Class Reference
配置管理器类
#include <config_manager.h>
Public Member Functions
bool LoadConfig (const std::string &config_file_path, const std::string &env="")
加载配置文件
bool ReloadConfig ()
重新加载配置文件
void LoadDefaultConfig ()
加载默认配置
ConfigManager ()=default
构造函数（私有，实现单例模式）
~ConfigManager ()=default
析构函数
ConfigManager (const ConfigManager &)=delete
禁用拷贝构造函数
ConfigManager & operator= (const ConfigManager &)=delete
禁用赋值操作符
bool ParseConfigFile (const std::string &file_path)
解析配置文件
bool ParseConfigLine (const std::string &line, std::string &current_section)
解析配置行
bool GetBool (const std::string &key, bool default_value=false) const
获取布尔类型配置值
int GetInt (const std::string &key, int default_value=0) const
获取整数类型配置值
double GetDouble (const std::string &key, double default_value=0.0) const
获取双精度浮点类型配置值
std::string GetString (const std::string &key, const std::string &default_value="") const
获取字符串类型配置值
bool SetValue (const std::string &key, const ConfigValue &value)
设置配置值
bool HasKey (const std::string &key) const
检查配置键是否存在
bool SaveToFile (const std::string &file_path) const
保存当前配置到文件
std::vector< std::string > GetAllKeys () const
获取所有配置键
std::vector< std::string > GetKeysWithPrefix (const std::string &prefix) const
获取指定前缀的所有配置键
void SetOperationTimeout (int timeout_ms)
设置操作超时时间
int GetOperationTimeout () const
获取当前操作超时时间
Static Public Member Functions
static ConfigManager & GetInstance ()
获取配置管理器单例实例
Public Attributes
std::unordered_map< std::string, ConfigValue > config_map_
配置映射表
std::string config_file_path_
配置文件路径
std::string env_
环境标识
std::mutex config_mutex_
互斥锁，保护配置访问
int operation_timeout_ms_
操作超时时间（毫秒）
Static Public Attributes
static constexpr int kDefaultOperationTimeoutMs = 5000
默认操作超时时间（毫秒）
Detailed Description
配置管理器类
负责加载、解析、管理和提供配置参数访问接口
Definition at line 29 of file config_manager.h.
Constructor & Destructor Documentation
ConfigManager() [1/2]
sqlcc::ConfigManager::ConfigManager () default
构造函数（私有，实现单例模式）
~ConfigManager()
sqlcc::ConfigManager::~ConfigManager () default
析构函数
ConfigManager() [2/2]
sqlcc::ConfigManager::ConfigManager (const ConfigManager &) delete
禁用拷贝构造函数
Member Function Documentation
GetAllKeys()
std::vector< std::string > sqlcc::ConfigManager::GetAllKeys () const
获取所有配置键
Returns
std::vector<std::string> 配置键列表
std::vector<std::string> 配置键列表
Why: 需要提供获取所有配置键的接口，用于配置浏览和调试 What: GetAllKeys方法返回配置映射表中所有键的列表 How: 使用互斥锁保护配置访问，遍历配置映射表，收集所有键
Definition at line 207 of file config_manager.cpp.
{
    std::lock_guard<std::mutex> lock(config_mutex_);
    std::vector<std::string> keys;
    keys.reserve(config_map_.size());
    for (const auto& [key, _] : config_map_) {
        keys.push_back(key);
    }
    return keys;
}
References config_map_, and config_mutex_.
GetBool()
bool sqlcc::ConfigManager::GetBool (const std::string & key, bool default_value = false) const
获取布尔类型配置值
Parameters
key 配置键
default_value 默认值
Returns
bool 配置值
Parameters
key 配置键
default_value 默认值
Returns
bool 配置值
Why: 需要提供获取布尔类型配置值的接口，支持默认值 What: GetBool方法从配置中获取指定键的布尔值，如果不存在则返回默认值 How: 使用互斥锁保护配置访问，查找配置键并检查类型，返回对应的值或默认值
Definition at line 117 of file config_manager.cpp.
{
    std::lock_guard<std::mutex> lock(config_mutex_);
    auto it = config_map_.find(key);
    if (it != config_map_.end() && std::holds_alternative<bool>(it->second)) {
        return std::get<bool>(it->second);
    }
    return default_value;
}
References config_map_, and config_mutex_.
Referenced by sqlcc::BufferPool::BatchPrefetchPages(), sqlcc::BufferPool::GetStats(), and sqlcc::BufferPool::PrefetchPage().
GetDouble()
double sqlcc::ConfigManager::GetDouble (const std::string & key, double default_value = 0.0) const
获取双精度浮点类型配置值
Parameters
key 配置键
default_value 默认值
Returns
double 配置值
Parameters
key 配置键
default_value 默认值
Returns
double 配置值
Why: 需要提供获取双精度浮点类型配置值的接口，支持默认值和类型转换 What: GetDouble方法从配置中获取指定键的double值，支持从int类型转换 How: 使用互斥锁保护配置访问，查找配置键并检查类型，返回对应的值或默认值
Definition at line 143 of file config_manager.cpp.
{
    std::lock_guard<std::mutex> lock(config_mutex_);
    auto it = config_map_.find(key);
    if (it != config_map_.end()) {
        if (std::holds_alternative<double>(it->second)) {
            return std::get<double>(it->second);
        }
        if (std::holds_alternative<int>(it->second)) {
            return static_cast<double>(std::get<int>(it->second));
        }
    }
    return default_value;
}
References config_map_, and config_mutex_.
GetInstance()
ConfigManager & sqlcc::ConfigManager::GetInstance () static
获取配置管理器单例实例
Returns
ConfigManager& 配置管理器引用
Why: 需要确保整个应用程序中只有一个配置管理器实例，避免配置冲突 What: GetInstance方法返回ConfigManager的单例实例引用 How: 使用静态局部变量实现线程安全的单例模式
Definition at line 9 of file config_manager.cpp.
{
    static ConfigManager instance;
    return instance;
}
Referenced by main().
GetInt()
int sqlcc::ConfigManager::GetInt (const std::string & key, int default_value = 0) const
获取整数类型配置值
Parameters
key 配置键
default_value 默认值
Returns
int 配置值
Parameters
key 配置键
default_value 默认值
Returns
int 配置值
Why: 需要提供获取整数类型配置值的接口，支持默认值和类型转换 What: GetInt方法从配置中获取指定键的整数值，支持从double类型转换 How: 使用互斥锁保护配置访问，查找配置键并检查类型，返回对应的值或默认值
Definition at line 127 of file config_manager.cpp.
{
    std::lock_guard<std::mutex> lock(config_mutex_);
    auto it = config_map_.find(key);
    if (it != config_map_.end()) {
        if (std::holds_alternative<int>(it->second)) {
            return std::get<int>(it->second);
        }
        // 尝试从其他类型转换
        if (std::holds_alternative<bool>(it->second)) {
            return std::get<bool>(it->second) ? 1 : 0;
        }
    }
    return default_value;
}
References config_map_, and config_mutex_.
Referenced by sqlcc::BufferPool::BufferPool(), main(), and sqlcc::StorageEngine::StorageEngine().
GetKeysWithPrefix()
std::vector< std::string > sqlcc::ConfigManager::GetKeysWithPrefix (const std::string & prefix) const
获取指定前缀的所有配置键
Parameters
prefix 键前缀
Returns
std::vector<std::string> 配置键列表
Parameters
prefix 键前缀
Returns
std::vector<std::string> 配置键列表
Why: 需要提供按前缀筛选配置键的接口，用于分类获取配置 What: GetKeysWithPrefix方法返回所有以指定前缀开头的配置键列表 How: 使用互斥锁保护配置访问，遍历配置映射表，筛选匹配前缀的键
Definition at line 218 of file config_manager.cpp.
{
    std::lock_guard<std::mutex> lock(config_mutex_);
    std::vector<std::string> keys;
    for (const auto& [key, _] : config_map_) {
        if (key.find(prefix) == 0) {
            keys.push_back(key);
        }
    }
    return keys;
}
References config_map_, and config_mutex_.
GetOperationTimeout()
int sqlcc::ConfigManager::GetOperationTimeout () const
获取当前操作超时时间
Returns
超时时间（毫秒）
Definition at line 235 of file config_manager.cpp.
{
    return operation_timeout_ms_;
}
References operation_timeout_ms_.
GetString()
std::string sqlcc::ConfigManager::GetString (const std::string & key, const std::string & default_value = "") const
获取字符串类型配置值
Parameters
key 配置键
default_value 默认值
Returns
std::string 配置值
Parameters
key 配置键
default_value 默认值
Returns
std::string 配置值
Why: 需要提供获取字符串类型配置值的接口，支持默认值 What: GetString方法从配置中获取指定键的字符串值，如果不存在则返回默认值 How: 使用互斥锁保护配置访问，查找配置键并检查类型，返回对应的值或默认值
Definition at line 158 of file config_manager.cpp.
{
    std::lock_guard<std::mutex> lock(config_mutex_);
    auto it = config_map_.find(key);
    if (it != config_map_.end() && std::holds_alternative<std::string>(it->second)) {
        return std::get<std::string>(it->second);
    }
    return default_value;
}
References config_map_, and config_mutex_.
Referenced by sqlcc::BufferPool::BatchPrefetchPages(), main(), and sqlcc::StorageEngine::StorageEngine().
HasKey()
bool sqlcc::ConfigManager::HasKey (const std::string & key) const
检查配置键是否存在
Parameters
key 配置键
Returns
bool 是否存在
Parameters
key 配置键
Returns
bool 是否存在
Why: 需要提供检查配置键是否存在的接口 What: HasKey方法检查指定键是否存在于配置映射表中 How: 使用互斥锁保护配置访问，使用find方法查找键
Definition at line 175 of file config_manager.cpp.
{
    std::lock_guard<std::mutex> lock(config_mutex_);
    return config_map_.find(key) != config_map_.end();
}
References config_map_, and config_mutex_.
LoadConfig()
bool sqlcc::ConfigManager::LoadConfig (const std::string & config_file_path, const std::string & env = "")
加载配置文件
Parameters
config_file_path 配置文件路径
env 环境标识，用于加载环境特定配置
Returns
bool 是否加载成功
Parameters
config_file_path 配置文件路径
env 环境标识，用于加载环境特定配置
Returns
bool 是否加载成功
Why: 需要从文件中加载配置参数，支持不同环境的配置覆盖 What: LoadConfig方法加载主配置文件和环境特定配置文件，合并配置参数 How: 使用互斥锁保护配置加载过程，先加载默认配置，再加载主配置文件，最后加载环境特定配置
Definition at line 15 of file config_manager.cpp.
{
    config_file_path_ = config_file_path;
    env_ = env;
    return ParseConfigFile(config_file_path);
}
References config_file_path_, env_, and ParseConfigFile().
Referenced by main().
LoadDefaultConfig()
void sqlcc::ConfigManager::LoadDefaultConfig ()
加载默认配置
Why: 需要提供默认配置值，确保系统在缺少配置文件时也能正常运行 What: LoadDefaultConfig方法设置所有配置项的默认值 How: 直接在config_map_中设置各个配置项的默认值
Definition at line 30 of file config_manager.cpp.
{
    // 设置默认配置值
    SetValue("buffer_pool.read_lock_timeout_ms", 2000);
    SetValue("buffer_pool.write_lock_timeout_ms", 5000);
    SetValue("buffer_pool.default_lock_timeout_ms", 3000);
    operation_timeout_ms_ = kDefaultOperationTimeoutMs;
}
References kDefaultOperationTimeoutMs, operation_timeout_ms_, and SetValue().
Referenced by ParseConfigFile().
operator=()
ConfigManager & sqlcc::ConfigManager::operator= (const ConfigManager &) delete
禁用赋值操作符
ParseConfigFile()
bool sqlcc::ConfigManager::ParseConfigFile (const std::string & file_path)
解析配置文件
Parameters
file_path 文件路径
Returns
bool 是否解析成功
Parameters
file_path 文件路径
Returns
bool 是否解析成功
Why: 需要从文件中读取并解析配置内容 What: ParseConfigFile方法逐行读取配置文件，解析配置项 How: 使用ifstream打开文件，逐行读取并调用ParseConfigLine解析
Definition at line 39 of file config_manager.cpp.
{
    std::ifstream file(file_path);
    if (!file.is_open()) {
        // 文件不存在时加载默认配置
        LoadDefaultConfig();
        return true;
    }
    std::string line;
    std::string current_section;
    while (std::getline(file, line)) {
        ParseConfigLine(line, current_section);
    }
    file.close();
    return true;
}
References LoadDefaultConfig(), and ParseConfigLine().
Referenced by LoadConfig(), and ReloadConfig().
ParseConfigLine()
bool sqlcc::ConfigManager::ParseConfigLine (const std::string & line, std::string & current_section)
解析配置行
Parameters
line 配置行
current_section 当前配置节
Returns
bool 是否解析成功
Parameters
line 配置行
current_section 当前配置节
Returns
bool 是否解析成功
Why: 需要解析单行配置内容，支持节、键值对和注释 What: ParseConfigLine方法解析单行配置，处理节行、键值对行和注释行 How: 去除空白字符，根据行首字符判断行类型，进行相应处理
Definition at line 59 of file config_manager.cpp.
{
    // 简化的配置行解析
    std::string trimmed = line;
    // 移除首尾空格
    trimmed.erase(0, trimmed.find_first_not_of(" \t"));
    trimmed.erase(trimmed.find_last_not_of(" \t\r\n") + 1);
    // 跳过空行和注释
    if (trimmed.empty() || trimmed[0] == '#') {
        return true;
    }
    // 处理section行 [section]
    if (trimmed[0] == '[' && trimmed.back() == ']') {
        current_section = trimmed.substr(1, trimmed.size() - 2);
        return true;
    }
    // 处理key=value行
    size_t eq_pos = trimmed.find('=');
    if (eq_pos != std::string::npos) {
        std::string key = trimmed.substr(0, eq_pos);
        std::string value = trimmed.substr(eq_pos + 1);
        // 移除键和值的空格
        key.erase(key.find_last_not_of(" \t") + 1);
        value.erase(0, value.find_first_not_of(" \t"));
        value.erase(value.find_last_not_of(" \t\r\n") + 1);
        // 如果有section，添加section前缀
        if (!current_section.empty()) {
            key = current_section + "." + key;
        }
        // 尝试解析不同类型的值
        if (value == "true" || value == "false") {
            SetValue(key, value == "true");
        } else if (value.find_first_not_of("-0123456789") == std::string::npos) {
            SetValue(key, std::stoi(value));
        } else if (value.find_first_not_of("-0123456789.") == std::string::npos &&
                  value.find('.') != std::string::npos) {
            SetValue(key, std::stod(value));
        } else {
            // 去掉引号（如果有）
            if (value.size() >= 2 && ((value[0] == '"' && value.back() == '"') ||
                                     (value[0] == '\'' && value.back() == '\''))) {
                value = value.substr(1, value.size() - 2);
            }
            SetValue(key, value);
        }
        return true;
    }
    return false;
}
References SetValue().
Referenced by ParseConfigFile().
ReloadConfig()
bool sqlcc::ConfigManager::ReloadConfig ()
重新加载配置文件
Returns
bool 是否重新加载成功
bool 是否重新加载成功
Why: 需要在运行时重新加载配置，无需重启应用程序 What: ReloadConfig方法使用之前保存的配置文件路径和环境标识重新加载配置 How: 检查配置文件路径是否有效，然后调用LoadConfig方法重新加载
Definition at line 22 of file config_manager.cpp.
{
    if (config_file_path_.empty()) {
        return false;
    }
    return ParseConfigFile(config_file_path_);
}
References config_file_path_, and ParseConfigFile().
SaveToFile()
bool sqlcc::ConfigManager::SaveToFile (const std::string & file_path) const
保存当前配置到文件
Parameters
file_path 文件路径
Returns
bool 是否保存成功
Parameters
file_path 文件路径
Returns
bool 是否保存成功
Why: 需要提供将当前配置保存到文件的接口，支持配置持久化 What: SaveToFile方法将当前配置映射表中的所有配置项写入指定文件 How: 使用互斥锁保护配置访问，按节组织配置项，写入文件
Definition at line 181 of file config_manager.cpp.
{
    std::ofstream file(file_path);
    if (!file.is_open()) {
        return false;
    }
    std::lock_guard<std::mutex> lock(config_mutex_);
    for (const auto& [key, value] : config_map_) {
        file << key << " = ";
        if (std::holds_alternative<bool>(value)) {
            file << (std::get<bool>(value) ? "true" : "false");
        } else if (std::holds_alternative<int>(value)) {
            file << std::get<int>(value);
        } else if (std::holds_alternative<double>(value)) {
            file << std::get<double>(value);
        } else if (std::holds_alternative<std::string>(value)) {
            file << '"' << std::get<std::string>(value) << '"';
        }
        file << std::endl;
    }
    file.close();
    return true;
}
References config_map_, and config_mutex_.
Referenced by main().
SetOperationTimeout()
void sqlcc::ConfigManager::SetOperationTimeout (int timeout_ms)
设置操作超时时间
Parameters
timeout_ms 超时时间（毫秒）
Definition at line 230 of file config_manager.cpp.
{
    operation_timeout_ms_ = timeout_ms;
}
References operation_timeout_ms_.
SetValue()
bool sqlcc::ConfigManager::SetValue (const std::string & key, const ConfigValue & value)
设置配置值
Parameters
key 配置键
value 配置值
Returns
bool 是否设置成功
Parameters
key 配置键
value 配置值
Returns
bool 是否设置成功
Why: 需要提供动态设置配置值的接口，支持运行时修改配置 What: SetValue方法设置指定键的配置值，如果值发生变化则通知注册的回调函数 How: 使用互斥锁保护配置修改，保存旧值，设置新值，比较新旧值并通知回调
Definition at line 168 of file config_manager.cpp.
{
    std::lock_guard<std::mutex> lock(config_mutex_);
    config_map_[key] = value;
    return true;
}
References config_map_, and config_mutex_.
Referenced by LoadDefaultConfig(), and ParseConfigLine().
Member Data Documentation
config_file_path_
std::string sqlcc::ConfigManager::config_file_path_
配置文件路径
Definition at line 105 of file config_manager.h.
Referenced by LoadConfig(), and ReloadConfig().
config_map_
std::unordered_map<std::string, ConfigValue> sqlcc::ConfigManager::config_map_
配置映射表
Definition at line 100 of file config_manager.h.
Referenced by GetAllKeys(), GetBool(), GetDouble(), GetInt(), GetKeysWithPrefix(), GetString(), HasKey(), SaveToFile(), and SetValue().
config_mutex_
std::mutex sqlcc::ConfigManager::config_mutex_ mutable
互斥锁，保护配置访问
Definition at line 115 of file config_manager.h.
Referenced by GetAllKeys(), GetBool(), GetDouble(), GetInt(), GetKeysWithPrefix(), GetString(), HasKey(), SaveToFile(), and SetValue().
env_
std::string sqlcc::ConfigManager::env_
环境标识
Definition at line 110 of file config_manager.h.
Referenced by LoadConfig().
kDefaultOperationTimeoutMs
constexpr int sqlcc::ConfigManager::kDefaultOperationTimeoutMs = 5000 static constexpr
默认操作超时时间（毫秒）
Definition at line 34 of file config_manager.h.
Referenced by LoadDefaultConfig().
operation_timeout_ms_
int sqlcc::ConfigManager::operation_timeout_ms_
操作超时时间（毫秒）
Definition at line 120 of file config_manager.h.
Referenced by GetOperationTimeout(), LoadDefaultConfig(), and SetOperationTimeout().
The documentation for this class was generated from the following files:
include/config_manager.h
src/config_manager.cpp
src/config_manager/config_manager.cpp