SQLCC: sqlcc::network::ClientNetworkManager Class Reference
sqlcc::network::ClientNetworkManager Class Reference
#include <network.h>
Public Member Functions
ClientNetworkManager (const std::string &host, int port)
~ClientNetworkManager ()
bool Connect ()
void Disconnect ()
bool IsConnected () const
bool SendRequest (const std::vector< char > &request)
std::vector< char > ReceiveResponse ()
bool ConnectAndAuthenticate (const std::string &username, const std::string &password)
bool SendAuthMessage (const std::string &username, const std::string &password)
Private Attributes
std::unique_ptr< ClientConnection > connection_
std::shared_ptr< SessionManager > session_manager_
Detailed Description
Definition at line 112 of file network.h.
Constructor & Destructor Documentation
ClientNetworkManager()
sqlcc::network::ClientNetworkManager::ClientNetworkManager (const std::string & host, int port)
Definition at line 203 of file network.cpp.
    : connection_(std::make_unique<ClientConnection>(host, port)),
      session_manager_(std::make_shared<SessionManager>()) {}
~ClientNetworkManager()
sqlcc::network::ClientNetworkManager::~ClientNetworkManager () default
Member Function Documentation
Connect()
bool sqlcc::network::ClientNetworkManager::Connect ()
Definition at line 209 of file network.cpp.
{
    return connection_->Connect();
}
References connection_.
Referenced by ConnectAndAuthenticate().
ConnectAndAuthenticate()
bool sqlcc::network::ClientNetworkManager::ConnectAndAuthenticate (const std::string & username, const std::string & password)
Definition at line 119 of file client_main.cpp.
{
        // 连接到服务器
        if (!this->Connect()) {
            return false;
        }
        // 发送连接请求
        std::vector<char> connect_msg(sizeof(MessageHeader));
        MessageHeader* header = reinterpret_cast<MessageHeader*>(connect_msg.data());
        header->magic = 0x53514C43; // 'SQLC'
        header->length = 0;
        header->type = CONNECT;
        header->flags = 0;
        header->sequence_id = 1;
        if (!this->SendRequest(connect_msg)) {
            this->Disconnect();
            return false;
        }
        // 接收连接确认
        std::vector<char> connect_resp = this->ReceiveResponse();
        if (connect_resp.empty()) {
            this->Disconnect();
            return false;
        }
        MessageHeader* resp_header = reinterpret_cast<MessageHeader*>(connect_resp.data());
        if (resp_header->magic != 0x53514C43 || resp_header->type != CONN_ACK) {
            this->Disconnect();
            return false;
        }
        // 发送认证请求
        size_t user_len = username.length();
        size_t pass_len = password.length();
        size_t msg_len = 2 * sizeof(uint32_t) + user_len + pass_len;
        std::vector<char> auth_msg(sizeof(MessageHeader) + msg_len);
        header = reinterpret_cast<MessageHeader*>(auth_msg.data());
        header->magic = 0x53514C43; // 'SQLC'
        header->length = msg_len;
        header->type = AUTH;
        header->flags = 0;
        header->sequence_id = 2;
        char* body = auth_msg.data() + sizeof(MessageHeader);
        *reinterpret_cast<uint32_t*>(body) = user_len;
        *reinterpret_cast<uint32_t*>(body + sizeof(uint32_t)) = pass_len;
        std::memcpy(body + 2 * sizeof(uint32_t), username.c_str(), user_len);
        std::memcpy(body + 2 * sizeof(uint32_t) + user_len, password.c_str(), pass_len);
        if (!this->SendRequest(auth_msg)) {
            this->Disconnect();
            return false;
        }
        // 接收认证响应
        std::vector<char> auth_resp = this->ReceiveResponse();
        if (auth_resp.empty()) {
            this->Disconnect();
            return false;
        }
        resp_header = reinterpret_cast<MessageHeader*>(auth_resp.data());
        if (resp_header->magic != 0x53514C43 || resp_header->type != AUTH_ACK) {
            return false;
        }
        return true;
    }
References sqlcc::network::AUTH, sqlcc::network::AUTH_ACK, sqlcc::network::CONN_ACK, sqlcc::network::CONNECT, Connect(), Disconnect(), sqlcc::network::MessageHeader::flags, sqlcc::network::MessageHeader::length, sqlcc::network::MessageHeader::magic, ReceiveResponse(), SendRequest(), sqlcc::network::MessageHeader::sequence_id, and sqlcc::network::MessageHeader::type.
Referenced by main().
Disconnect()
void sqlcc::network::ClientNetworkManager::Disconnect ()
Definition at line 213 of file network.cpp.
{
    connection_->Disconnect();
}
References connection_.
Referenced by ConnectAndAuthenticate(), and main().
IsConnected()
bool sqlcc::network::ClientNetworkManager::IsConnected () const
Definition at line 217 of file network.cpp.
{
    return connection_->IsConnected();
}
References connection_.
ReceiveResponse()
std::vector< char > sqlcc::network::ClientNetworkManager::ReceiveResponse ()
Definition at line 225 of file network.cpp.
{
    return connection_->ReceiveData();
}
References connection_.
Referenced by ConnectAndAuthenticate(), and main().
SendAuthMessage()
bool sqlcc::network::ClientNetworkManager::SendAuthMessage (const std::string & username, const std::string & password)
Definition at line 229 of file network.cpp.
{
    // 构造认证消息
    // 格式: [uint32_t username_len][uint32_t password_len][username][password]
    uint32_t username_len = static_cast<uint32_t>(username.length());
    uint32_t password_len = static_cast<uint32_t>(password.length());
    size_t body_size = 2 * sizeof(uint32_t) + username_len + password_len;
    std::vector<char> message(sizeof(MessageHeader) + body_size);
    // 填充消息头
    MessageHeader* header = reinterpret_cast<MessageHeader*>(message.data());
    header->magic = 0x53514C43; // 'SQLC'
    header->length = static_cast<uint32_t>(body_size);
    header->type = AUTH;
    header->flags = 0;
    header->sequence_id = 1;
    // 填充消息体
    char* body = message.data() + sizeof(MessageHeader);
    *reinterpret_cast<uint32_t*>(body) = username_len;
    *reinterpret_cast<uint32_t*>(body + sizeof(uint32_t)) = password_len;
    std::memcpy(body + 2 * sizeof(uint32_t), username.c_str(), username_len);
    std::memcpy(body + 2 * sizeof(uint32_t) + username_len, password.c_str(), password_len);
    return SendRequest(message);
}
References sqlcc::network::AUTH, sqlcc::network::MessageHeader::flags, sqlcc::network::MessageHeader::length, sqlcc::network::MessageHeader::magic, SendRequest(), sqlcc::network::MessageHeader::sequence_id, and sqlcc::network::MessageHeader::type.
SendRequest()
bool sqlcc::network::ClientNetworkManager::SendRequest (const std::vector< char > & request)
Definition at line 221 of file network.cpp.
{
    return connection_->SendData(request);
}
References connection_.
Referenced by ConnectAndAuthenticate(), main(), and SendAuthMessage().
Member Data Documentation
connection_
std::unique_ptr<ClientConnection> sqlcc::network::ClientNetworkManager::connection_ private
Definition at line 127 of file network.h.
Referenced by Connect(), Disconnect(), IsConnected(), ReceiveResponse(), and SendRequest().
session_manager_
std::shared_ptr<SessionManager> sqlcc::network::ClientNetworkManager::session_manager_ private
Definition at line 128 of file network.h.
The documentation for this class was generated from the following files:
include/network/network.h
src/isql_network/client_main.cpp
src/network/network.cpp