SQLCC: sqlcc::sql_parser::ForeignKeyConstraint Class Reference
sqlcc::sql_parser::ForeignKeyConstraint Class Reference
#include <ast_nodes.h>
Public Member Functions
ForeignKeyConstraint ()
void addColumn (const std::string &columnName)
void setReferencedTable (const std::string &tableName)
void setReferencedColumn (const std::string &columnName)
const std::vector< std::string > & getColumns () const
const std::string & getReferencedTable () const
const std::string & getReferencedColumn () const
Public Member Functions inherited from sqlcc::sql_parser::TableConstraint
TableConstraint (Type type)
virtual ~TableConstraint ()=default
Type getType () const
void setName (const std::string &name)
const std::string & getName () const
Private Attributes
std::vector< std::string > columns_
std::string referencedTable_
std::string referencedColumn_
Additional Inherited Members
Public Types inherited from sqlcc::sql_parser::TableConstraint
enum Type { PRIMARY_KEY , UNIQUE , FOREIGN_KEY , CHECK }
Protected Attributes inherited from sqlcc::sql_parser::TableConstraint
Type type_
std::string name_
Detailed Description
外键约束
Definition at line 83 of file ast_nodes.h.
Constructor & Destructor Documentation
ForeignKeyConstraint()
sqlcc::sql_parser::ForeignKeyConstraint::ForeignKeyConstraint ()
ForeignKeyConstraint 实现
Definition at line 683 of file ast_nodes.cpp.
                                           : TableConstraint(TableConstraint::FOREIGN_KEY) {
}
Member Function Documentation
addColumn()
void sqlcc::sql_parser::ForeignKeyConstraint::addColumn (const std::string & columnName)
Definition at line 686 of file ast_nodes.cpp.
{
    columns_.push_back(columnName);
}
References columns_.
getColumns()
const std::vector< std::string > & sqlcc::sql_parser::ForeignKeyConstraint::getColumns () const
Definition at line 698 of file ast_nodes.cpp.
{
    return columns_;
}
References columns_.
Referenced by sqlcc::ForeignKeyConstraintExecutor::ForeignKeyConstraintExecutor(), sqlcc::ForeignKeyConstraintExecutor::getPrimaryKeyValue(), and sqlcc::ForeignKeyConstraintExecutor::setCurrentTableName().
getReferencedColumn()
const std::string & sqlcc::sql_parser::ForeignKeyConstraint::getReferencedColumn () const
Definition at line 706 of file ast_nodes.cpp.
{
    return referencedColumn_;
}
References referencedColumn_.
Referenced by sqlcc::ForeignKeyConstraintExecutor::ForeignKeyConstraintExecutor().
getReferencedTable()
const std::string & sqlcc::sql_parser::ForeignKeyConstraint::getReferencedTable () const
Definition at line 702 of file ast_nodes.cpp.
{
    return referencedTable_;
}
References referencedTable_.
Referenced by sqlcc::ForeignKeyConstraintExecutor::ForeignKeyConstraintExecutor().
setReferencedColumn()
void sqlcc::sql_parser::ForeignKeyConstraint::setReferencedColumn (const std::string & columnName)
Definition at line 694 of file ast_nodes.cpp.
{
    referencedColumn_ = columnName;
}
References referencedColumn_.
setReferencedTable()
void sqlcc::sql_parser::ForeignKeyConstraint::setReferencedTable (const std::string & tableName)
Definition at line 690 of file ast_nodes.cpp.
{
    referencedTable_ = tableName;
}
References referencedTable_.
Member Data Documentation
columns_
std::vector<std::string> sqlcc::sql_parser::ForeignKeyConstraint::columns_ private
Definition at line 96 of file ast_nodes.h.
Referenced by addColumn(), and getColumns().
referencedColumn_
std::string sqlcc::sql_parser::ForeignKeyConstraint::referencedColumn_ private
Definition at line 98 of file ast_nodes.h.
Referenced by getReferencedColumn(), and setReferencedColumn().
referencedTable_
std::string sqlcc::sql_parser::ForeignKeyConstraint::referencedTable_ private
Definition at line 97 of file ast_nodes.h.
Referenced by getReferencedTable(), and setReferencedTable().
The documentation for this class was generated from the following files:
include/sql_parser/ast_nodes.h
src/sql_parser/ast_nodes.cpp