SQLCC: sqlcc::sql_parser::Lexer Class Reference
sqlcc::sql_parser::Lexer Class Reference
#include <lexer.h>
Public Member Functions
Lexer (const std::string &input)
Token nextToken ()
bool hasMoreTokens () const
Private Member Functions
char advance ()
char peek () const
bool isAtEnd () const
bool isDigit (char c) const
bool isLetter (char c) const
bool isWhitespace (char c) const
void skipWhitespace ()
Token parseIdentifierOrKeyword ()
Token parseNumber ()
Token parseString ()
Private Attributes
std::string input_
size_t position_
Detailed Description
Definition at line 10 of file lexer.h.
Constructor & Destructor Documentation
Lexer()
sqlcc::sql_parser::Lexer::Lexer (const std::string & input) explicit
Member Function Documentation
advance()
char sqlcc::sql_parser::Lexer::advance () private
hasMoreTokens()
bool sqlcc::sql_parser::Lexer::hasMoreTokens () const
isAtEnd()
bool sqlcc::sql_parser::Lexer::isAtEnd () const private
isDigit()
bool sqlcc::sql_parser::Lexer::isDigit (char c) const private
isLetter()
bool sqlcc::sql_parser::Lexer::isLetter (char c) const private
isWhitespace()
bool sqlcc::sql_parser::Lexer::isWhitespace (char c) const private
nextToken()
Token sqlcc::sql_parser::Lexer::nextToken ()
Referenced by sqlcc::sql_parser::Parser::consume(), sqlcc::sql_parser::Parser::Parser(), sqlcc::sql_parser::Parser::Parser(), and TEST_F().
parseIdentifierOrKeyword()
Token sqlcc::sql_parser::Lexer::parseIdentifierOrKeyword () private
parseNumber()
Token sqlcc::sql_parser::Lexer::parseNumber () private
parseString()
Token sqlcc::sql_parser::Lexer::parseString () private
peek()
char sqlcc::sql_parser::Lexer::peek () const private
skipWhitespace()
void sqlcc::sql_parser::Lexer::skipWhitespace () private
Member Data Documentation
input_
std::string sqlcc::sql_parser::Lexer::input_ private
Definition at line 21 of file lexer.h.
position_
size_t sqlcc::sql_parser::Lexer::position_ private
Definition at line 22 of file lexer.h.
The documentation for this class was generated from the following file:
include/sql_parser/lexer.h