SQLCC: sqlcc::DataType Class Reference
sqlcc::DataType Class Reference
SQL数据类型体系
#include <data_type.h>
Public Types
enum Type {
INTEGER , SMALLINT , BIGINT , DECIMAL ,
DOUBLE , CHAR , VARCHAR , TEXT ,
DATE , TIME , TIMESTAMP , BOOLEAN
}
数据类型枚举
using Value = std::variant< std::monostate, int32_t, int16_t, int64_t, double, std::string, bool >
数据值表示
Public Member Functions
DataType ()=default
默认构造函数
DataType (Type type)
构造函数 - 基础类型
DataType (Type type, int param1, int param2=0)
构造函数 - 带长度/精度的类型
DataType (const std::string &typeStr)
构造函数 - 从字符串创建
bool operator== (const DataType &other) const
bool operator!= (const DataType &other) const
Type getType () const
bool hasLength () const
int getLength () const
bool hasPrecision () const
int getPrecision () const
bool hasScale () const
int getScale () const
bool isNumeric () const
bool isString () const
bool isDateTime () const
bool isBoolean () const
std::string toString () const
size_t estimateSize () const
Static Private Member Functions
static Type parseTypeString (const std::string &str, int &param1, int &param2)
static std::string extractParams (const std::string &str, int &param1, int &param2)
Private Attributes
Type type_ = INTEGER
int param1_ = 0
int param2_ = 0
Detailed Description
SQL数据类型体系
支持完整的SQL-92数据类型，包括精确数值、近似数值、字符串、日期时间等类型
Definition at line 15 of file data_type.h.
Member Typedef Documentation
Value
using sqlcc::DataType::Value = std::variant<std::monostate, int32_t, int16_t, int64_t, double, std::string, bool>
数据值表示
使用std::variant支持多种数据类型的统一表示
Definition at line 100 of file data_type.h.
Member Enumeration Documentation
Type
enum sqlcc::DataType::Type
数据类型枚举
Enumerator
INTEGER
SMALLINT
BIGINT
DECIMAL
DOUBLE
CHAR
VARCHAR
TEXT
DATE
TIME
TIMESTAMP
BOOLEAN
Definition at line 20 of file data_type.h.
            {
    // 精确数值类型
    INTEGER,  // INT, INTEGER - 32位整数
    SMALLINT, // SMALLINT - 16位整数
    BIGINT,   // BIGINT - 64位整数（预留）
    // 近似数值类型
    DECIMAL, // DECIMAL(p,s) - 定点小数
    DOUBLE,  // DOUBLE, REAL - 双精度浮点数
    // 字符串类型
    CHAR,    // CHAR(n) - 定长字符串
    VARCHAR, // VARCHAR(n) - 变长字符串
    TEXT,    // TEXT - 长文本（预留）
    // 日期时间类型
    DATE,      // DATE - 日期
    TIME,      // TIME - 时间
    TIMESTAMP, // TIMESTAMP - 时间戳
    // 布尔类型
    BOOLEAN // BOOLEAN - 布尔值
    // 未来扩展类型:
    // BLOB, CLOB, BINARY, VARBINARY, etc.
  };
Constructor & Destructor Documentation
DataType() [1/4]
sqlcc::DataType::DataType () default
默认构造函数
DataType() [2/4]
sqlcc::DataType::DataType (Type type) explicit
构造函数 - 基础类型
Parameters
type 数据类型
Definition at line 20 of file data_type.cpp.
                            : type_(type), param1_(0), param2_(0) {
  // 为某些类型设置默认参数
  switch (type) {
  case VARCHAR:
    param1_ = 255; // 默认VARCHAR长度
    break;
  case CHAR:
    param1_ = 1; // 默认CHAR长度
    break;
  case DECIMAL:
    param1_ = 10, param2_ = 2; // 默认DECIMAL精度和小数位数
    break;
  default:
    break;
  }
}
References CHAR, DECIMAL, param1_, param2_, and VARCHAR.
DataType() [3/4]
sqlcc::DataType::DataType (Type type, int param1, int param2 = 0)
构造函数 - 带长度/精度的类型
Parameters
type 数据类型
param1 第一个参数（如长度、精度）
param2 第二个参数（如小数位数）
Definition at line 37 of file data_type.cpp.
    : type_(type), param1_(param1), param2_(param2) {
  // 基本参数验证
  if (param1 < 0 || param2 < 0) {
    throw DataTypeException("Data type parameters cannot be negative");
  }
}
DataType() [4/4]
sqlcc::DataType::DataType (const std::string & typeStr) explicit
构造函数 - 从字符串创建
Parameters
typeStr 类型字符串（如"INT", "VARCHAR(100)", "DECIMAL(10,2)"）
Definition at line 45 of file data_type.cpp.
    : type_(INTEGER), param1_(0), param2_(0) {
  int param1 = 0, param2 = 0;
  DataType::Type parsedType = parseTypeString(typeStr, param1, param2);
  type_ = parsedType;
  param1_ = param1;
  param2_ = param2;
}
References param1_, param2_, parseTypeString(), and type_.
Member Function Documentation
estimateSize()
size_t sqlcc::DataType::estimateSize () const
Definition at line 92 of file data_type.cpp.
{
  switch (type_) {
  case INTEGER:
    return sizeof(int32_t);
  case SMALLINT:
    return sizeof(int16_t);
  case BIGINT:
    return sizeof(int64_t);
  case DECIMAL:
  case DOUBLE:
    return sizeof(double);
  case BOOLEAN:
    return sizeof(bool);
  case CHAR:
    return param1_; // 定长字符串
  case VARCHAR:
    return param1_ + 4; // 变长字符串需要额外的长度字段
  case TEXT:
    return 256; // 预估长文本大小（可调）
  case DATE:
    return 10; // "YYYY-MM-DD"
  case TIME:
    return 8; // "HH:MM:SS"
  case TIMESTAMP:
    return 19; // "YYYY-MM-DD HH:MM:SS"
  default:
    return 8; // 默认大小
  }
}
References BIGINT, BOOLEAN, CHAR, DATE, DECIMAL, DOUBLE, INTEGER, param1_, SMALLINT, TEXT, TIME, TIMESTAMP, type_, and VARCHAR.
extractParams()
std::string sqlcc::DataType::extractParams (const std::string & str, int & param1, int & param2) static private
Definition at line 132 of file data_type.cpp.
{
  std::string result = str;
  param1 = 0;
  param2 = 0;
  // 查找参数
  size_t openParen = str.find('(');
  if (openParen != std::string::npos) {
    size_t closeParen = str.find(')', openParen);
    if (closeParen != std::string::npos) {
      // 提取参数字符串
      std::string params =
          str.substr(openParen + 1, closeParen - openParen - 1);
      // 分离第一个和第二个参数
      size_t comma = params.find(',');
      if (comma != std::string::npos) {
        // 有两个参数
        try {
          param1 = std::stoi(params.substr(0, comma));
          param2 = std::stoi(params.substr(comma + 1));
        } catch (const std::exception &) {
          throw DataTypeException("Invalid numeric parameters in type: " + str);
        }
      } else {
        // 只有一个参数
        try {
          param1 = std::stoi(params);
        } catch (const std::exception &) {
          throw DataTypeException("Invalid numeric parameter in type: " + str);
        }
      }
      // 移除参数部分得到基本类型
      result = str.substr(0, openParen);
    }
  }
  return result;
}
Referenced by parseTypeString().
getLength()
int sqlcc::DataType::getLength () const inline
Definition at line 79 of file data_type.h.
{ return param1_; }
References param1_.
getPrecision()
int sqlcc::DataType::getPrecision () const inline
Definition at line 81 of file data_type.h.
{ return param1_; }
References param1_.
getScale()
int sqlcc::DataType::getScale () const inline
Definition at line 83 of file data_type.h.
{ return param2_; }
References param2_.
getType()
Type sqlcc::DataType::getType () const inline
Definition at line 77 of file data_type.h.
{ return type_; }
References type_.
hasLength()
bool sqlcc::DataType::hasLength () const inline
Definition at line 78 of file data_type.h.
{ return param1_ > 0; }
References param1_.
Referenced by toString().
hasPrecision()
bool sqlcc::DataType::hasPrecision () const inline
Definition at line 80 of file data_type.h.
{ return param1_ > 0; }
References param1_.
Referenced by toString().
hasScale()
bool sqlcc::DataType::hasScale () const inline
Definition at line 82 of file data_type.h.
{ return param2_ > 0; }
References param2_.
Referenced by toString().
isBoolean()
bool sqlcc::DataType::isBoolean () const
Definition at line 76 of file data_type.cpp.
{ return type_ == BOOLEAN; }
References BOOLEAN, and type_.
isDateTime()
bool sqlcc::DataType::isDateTime () const
Definition at line 72 of file data_type.cpp.
{
  return type_ == DATE || type_ == TIME || type_ == TIMESTAMP;
}
References DATE, TIME, TIMESTAMP, and type_.
isNumeric()
bool sqlcc::DataType::isNumeric () const
Definition at line 63 of file data_type.cpp.
{
  return type_ == INTEGER || type_ == SMALLINT || type_ == BIGINT ||
         type_ == DECIMAL || type_ == DOUBLE;
}
References BIGINT, DECIMAL, DOUBLE, INTEGER, SMALLINT, and type_.
isString()
bool sqlcc::DataType::isString () const
Definition at line 68 of file data_type.cpp.
{
  return type_ == CHAR || type_ == VARCHAR || type_ == TEXT;
}
References CHAR, TEXT, type_, and VARCHAR.
operator!=()
bool sqlcc::DataType::operator!= (const DataType & other) const
Definition at line 59 of file data_type.cpp.
{
  return !(*this == other);
}
operator==()
bool sqlcc::DataType::operator== (const DataType & other) const
Definition at line 54 of file data_type.cpp.
{
  return type_ == other.type_ && param1_ == other.param1_ &&
         param2_ == other.param2_;
}
References param1_, param2_, and type_.
parseTypeString()
DataType::Type sqlcc::DataType::parseTypeString (const std::string & str, int & param1, int & param2) static private
Definition at line 122 of file data_type.cpp.
{
  param1 = 0;
  param2 = 0;
  // 移除参数部分，提取基本类型名
  std::string baseType = extractParams(str, param1, param2);
  return DataTypeUtils::stringToType(baseType);
}
References extractParams(), and sqlcc::DataTypeUtils::stringToType().
Referenced by DataType().
toString()
std::string sqlcc::DataType::toString () const
Definition at line 78 of file data_type.cpp.
{
  std::string result = DataTypeUtils::typeToString(type_);
  if (hasLength() || hasPrecision()) {
    result += "(" + std::to_string(param1_);
    if (hasScale()) {
      result += "," + std::to_string(param2_);
    }
    result += ")";
  }
  return result;
}
References hasLength(), hasPrecision(), hasScale(), param1_, param2_, type_, and sqlcc::DataTypeUtils::typeToString().
Member Data Documentation
param1_
int sqlcc::DataType::param1_ = 0 private
Definition at line 111 of file data_type.h.
Referenced by DataType(), DataType(), estimateSize(), getLength(), getPrecision(), hasLength(), hasPrecision(), operator==(), and toString().
param2_
int sqlcc::DataType::param2_ = 0 private
Definition at line 112 of file data_type.h.
Referenced by DataType(), DataType(), getScale(), hasScale(), operator==(), and toString().
type_
Type sqlcc::DataType::type_ = INTEGER private
Definition at line 110 of file data_type.h.
Referenced by DataType(), estimateSize(), getType(), isBoolean(), isDateTime(), isNumeric(), isString(), operator==(), and toString().
The documentation for this class was generated from the following files:
include/data_type.h
src/sql_executor/data_type.cpp