SQLCC: sqlcc::BPlusTreeIndex Class Reference
sqlcc::BPlusTreeIndex Class Reference
B+树索引类 管理B+树索引的创建、删除、查找等操作
#include <b_plus_tree.h>
Public Member Functions
BPlusTreeIndex (StorageEngine *storage_engine, const std::string &table_name, const std::string &column_name)
~BPlusTreeIndex ()
bool Create ()
bool Drop ()
bool Insert (const IndexEntry &entry)
bool Delete (const std::string &key)
std::vector< IndexEntry > Search (const std::string &key) const
std::vector< IndexEntry > SearchRange (const std::string &lower_bound, const std::string &upper_bound) const
const std::string & GetTableName () const
const std::string & GetColumnName () const
bool Exists () const
Private Member Functions
void LoadMetadata ()
void SaveMetadata ()
BPlusTreeNode * GetNode (int32_t page_id) const
BPlusTreeNode * CreateNewNode (bool is_leaf)
void DeleteNode (int32_t page_id)
Private Attributes
sqlcc::StorageEngine * storage_engine_
std::string table_name_
std::string column_name_
std::string index_name_
int32_t root_page_id_
int32_t metadata_page_id_
Detailed Description
B+树索引类 管理B+树索引的创建、删除、查找等操作
Definition at line 140 of file b_plus_tree.h.
Constructor & Destructor Documentation
BPlusTreeIndex()
sqlcc::BPlusTreeIndex::BPlusTreeIndex (StorageEngine * storage_engine, const std::string & table_name, const std::string & column_name)
Definition at line 296 of file b_plus_tree.cpp.
    : storage_engine_(storage_engine), table_name_(table_name),
      column_name_(column_name), root_page_id_(-1), metadata_page_id_(-1) {
  index_name_ = table_name + "_" + column_name + "_idx";
  // 加载索引元数据
  LoadMetadata();
}
References index_name_, and LoadMetadata().
~BPlusTreeIndex()
sqlcc::BPlusTreeIndex::~BPlusTreeIndex ()
Definition at line 306 of file b_plus_tree.cpp.
{
  // 保存索引元数据
  SaveMetadata();
}
References SaveMetadata().
Member Function Documentation
Create()
bool sqlcc::BPlusTreeIndex::Create ()
Definition at line 311 of file b_plus_tree.cpp.
{
  // 简化实现
  SQLCC_LOG_INFO("Creating index: " + index_name_);
  return true;
}
References index_name_, and SQLCC_LOG_INFO.
CreateNewNode()
BPlusTreeNode * sqlcc::BPlusTreeIndex::CreateNewNode (bool is_leaf) private
Definition at line 369 of file b_plus_tree.cpp.
{
  // 简化实现
  (void)is_leaf; // 标记参数已使用
  return nullptr;
}
Delete()
bool sqlcc::BPlusTreeIndex::Delete (const std::string & key)
Definition at line 329 of file b_plus_tree.cpp.
{
  // 简化实现
  (void)key; // 标记参数已使用
  return true;
}
DeleteNode()
void sqlcc::BPlusTreeIndex::DeleteNode (int32_t page_id) private
Definition at line 375 of file b_plus_tree.cpp.
{
  // 简化实现
  (void)page_id; // 标记参数已使用
}
Drop()
bool sqlcc::BPlusTreeIndex::Drop ()
Definition at line 317 of file b_plus_tree.cpp.
{
  // 简化实现
  SQLCC_LOG_INFO("Dropping index: " + index_name_);
  return true;
}
References index_name_, and SQLCC_LOG_INFO.
Exists()
bool sqlcc::BPlusTreeIndex::Exists () const
Definition at line 350 of file b_plus_tree.cpp.
{
  // 简化实现
  return root_page_id_ != -1;
}
References root_page_id_.
GetColumnName()
const std::string & sqlcc::BPlusTreeIndex::GetColumnName () const inline
Definition at line 155 of file b_plus_tree.h.
{ return column_name_; }
References column_name_.
GetNode()
BPlusTreeNode * sqlcc::BPlusTreeIndex::GetNode (int32_t page_id) const private
Definition at line 363 of file b_plus_tree.cpp.
{
  // 简化实现
  (void)page_id; // 标记参数已使用
  return nullptr;
}
GetTableName()
const std::string & sqlcc::BPlusTreeIndex::GetTableName () const inline
Definition at line 154 of file b_plus_tree.h.
{ return table_name_; }
References table_name_.
Insert()
bool sqlcc::BPlusTreeIndex::Insert (const IndexEntry & entry)
Definition at line 323 of file b_plus_tree.cpp.
{
  // 简化实现
  (void)entry; // 标记参数已使用
  return true;
}
LoadMetadata()
void sqlcc::BPlusTreeIndex::LoadMetadata () private
Definition at line 355 of file b_plus_tree.cpp.
{
  // 简化实现
}
Referenced by BPlusTreeIndex().
SaveMetadata()
void sqlcc::BPlusTreeIndex::SaveMetadata () private
Definition at line 359 of file b_plus_tree.cpp.
{
  // 简化实现
}
Referenced by ~BPlusTreeIndex().
Search()
std::vector< IndexEntry > sqlcc::BPlusTreeIndex::Search (const std::string & key) const
Definition at line 335 of file b_plus_tree.cpp.
{
  // 简化实现
  (void)key; // 标记参数已使用
  return std::vector<IndexEntry>();
}
SearchRange()
std::vector< IndexEntry > sqlcc::BPlusTreeIndex::SearchRange (const std::string & lower_bound, const std::string & upper_bound) const
Definition at line 342 of file b_plus_tree.cpp.
{
  // 简化实现
  (void)lower_bound; // 标记参数已使用
  (void)upper_bound; // 标记参数已使用
  return std::vector<IndexEntry>();
}
Member Data Documentation
column_name_
std::string sqlcc::BPlusTreeIndex::column_name_ private
Definition at line 161 of file b_plus_tree.h.
Referenced by GetColumnName().
index_name_
std::string sqlcc::BPlusTreeIndex::index_name_ private
Definition at line 162 of file b_plus_tree.h.
Referenced by BPlusTreeIndex(), Create(), and Drop().
metadata_page_id_
int32_t sqlcc::BPlusTreeIndex::metadata_page_id_ private
Definition at line 164 of file b_plus_tree.h.
root_page_id_
int32_t sqlcc::BPlusTreeIndex::root_page_id_ private
Definition at line 163 of file b_plus_tree.h.
Referenced by Exists().
storage_engine_
sqlcc::StorageEngine* sqlcc::BPlusTreeIndex::storage_engine_ private
Definition at line 159 of file b_plus_tree.h.
table_name_
std::string sqlcc::BPlusTreeIndex::table_name_ private
Definition at line 160 of file b_plus_tree.h.
Referenced by GetTableName().
The documentation for this class was generated from the following files:
include/b_plus_tree.h
src/storage_engine/b_plus_tree.cpp