SQLCC: sqlcc::test::ConcurrencyPerformanceTest Class Reference
sqlcc::test::ConcurrencyPerformanceTest Class Reference
#include <concurrency_performance_test.h>
Public Member Functions
ConcurrencyPerformanceTest ()
~ConcurrencyPerformanceTest () override
void RunAllTests () override
Public Member Functions inherited from sqlcc::test::PerformanceTestBase
PerformanceTestBase ()=default
virtual ~PerformanceTestBase ()=default
void SetOutputDirectory (const std::string &directory)
Protected Member Functions
TestResult TestConcurrentReads ()
TestResult TestConcurrentWrites ()
TestResult TestMixedReadWrite ()
TestResult TestLockContention ()
bool ExecuteRealReadOperation (int32_t key)
bool ExecuteRealWriteOperation (int32_t key, const std::string &value)
bool ExecuteRealLockOperation (int32_t lock_id)
void Cleanup () override
Protected Member Functions inherited from sqlcc::test::PerformanceTestBase
std::chrono::high_resolution_clock::time_point GetCurrentTime () const
std::chrono::milliseconds CalculateDuration (const std::chrono::high_resolution_clock::time_point &start, const std::chrono::high_resolution_clock::time_point &end) const
double CalculateThroughput (size_t operations, std::chrono::milliseconds duration) const
void CalculateLatencies (const std::vector< double > &latencies, double &avg, double &p95, double &p99) const
void PrintResult (const TestResult &result) const
void SaveResultsToFile (const std::vector< TestResult > &results, const std::string &filename) const
void GenerateReport (const std::vector< TestResult > &results) const
Private Member Functions
void ReadWorkerThread (int thread_id, size_t operations, std::atomic< size_t > &completed_ops, std::vector< double > &latencies)
void WriteWorkerThread (int thread_id, size_t operations, std::atomic< size_t > &completed_ops, std::vector< double > &latencies)
void MixedWorkerThread (int thread_id, size_t operations, std::atomic< size_t > &completed_ops, std::vector< double > &latencies, double read_ratio)
void LockContentionWorkerThread (int thread_id, size_t operations, std::atomic< size_t > &completed_ops, std::vector< double > &latencies, std::mutex &mutex)
void GenerateTestData ()
void InitializeTestTables ()
Private Attributes
std::unique_ptr< sqlcc::BufferPool > buffer_pool_
std::unique_ptr< sqlcc::DiskManager > disk_manager_
std::unique_ptr< sqlcc::SqlExecutor > sql_executor_
std::string test_db_file_ = "./test_concurrency.db"
std::string test_table_name_
std::vector< int32_t > test_data_
std::vector< std::string > string_data_
std::vector< std::unique_ptr< std::mutex > > lock_table_
SimpleBarrier * start_barrier_
std::atomic< bool > test_running_
std::mt19937 rng_
std::uniform_int_distribution< int32_t > key_dist_
std::uniform_real_distribution< double > random_dist_
Static Private Attributes
static constexpr size_t kDefaultThreadCount = 8
static constexpr size_t kOperationsPerThread = 1000
static constexpr size_t kDataSize = 10000
static constexpr size_t kWorkingSetSize = 100
static constexpr size_t kLockCount = 100
static constexpr const char * kTestDatabase = "concurrency_test_db"
static constexpr const char * kTestTable = "test_data"
Detailed Description
并发性能测试类 测试系统在并发访问下的性能表现
Definition at line 49 of file concurrency_performance_test.h.
Constructor & Destructor Documentation
ConcurrencyPerformanceTest()
sqlcc::test::ConcurrencyPerformanceTest::ConcurrencyPerformanceTest ()
构造函数
Definition at line 21 of file concurrency_performance_test.cc.
    : PerformanceTestBase(),
      test_running_(false),
      sql_executor_(nullptr),
      rng_(std::random_device()()),
      key_dist_(0, static_cast<int32_t>(kDataSize - 1)),
      random_dist_(0.0, 1.0) {
    // 构造函数实现
    std::cout << "ConcurrencyPerformanceTest constructor" << std::endl;
}
~ConcurrencyPerformanceTest()
sqlcc::test::ConcurrencyPerformanceTest::~ConcurrencyPerformanceTest () override
析构函数
Definition at line 32 of file concurrency_performance_test.cc.
{
    // 析构函数实现
    Cleanup();
    std::cout << "ConcurrencyPerformanceTest destructor" << std::endl;
}
References Cleanup().
Member Function Documentation
Cleanup()
void sqlcc::test::ConcurrencyPerformanceTest::Cleanup () override protected virtual
清理测试环境
Implements sqlcc::test::PerformanceTestBase.
Definition at line 60 of file concurrency_performance_test.cc.
{
    try {
        // 清理测试数据
        if (sql_executor_) {
            sql_executor_->Execute("DROP DATABASE IF EXISTS " + std::string(kTestDatabase));
            sql_executor_.reset();
        }
        std::cout << "Test resources cleaned up." << std::endl;
    } catch (const std::exception& e) {
        std::cerr << "Error during cleanup: " << e.what() << std::endl;
    }
}
References kTestDatabase, and sql_executor_.
Referenced by RunAllTests(), and ~ConcurrencyPerformanceTest().
ExecuteRealLockOperation()
bool sqlcc::test::ConcurrencyPerformanceTest::ExecuteRealLockOperation (int32_t lock_id) protected
执行真实锁操作（事务锁）
Definition at line 107 of file concurrency_performance_test.cc.
{
    try {
        std::string query = "SELECT * FROM " + std::string(kTestDatabase) + "." + std::string(kTestTable) +
                           " WHERE id = " + std::to_string(lock_id) + " FOR UPDATE";
        if (sql_executor_) {
            sql_executor_->Execute(query);
        }
        return true;
    } catch (const std::exception& e) {
        std::cerr << "Error executing lock operation: " << e.what() << std::endl;
        return false;
    }
}
References kTestDatabase, kTestTable, and sql_executor_.
Referenced by TestLockContention().
ExecuteRealReadOperation()
bool sqlcc::test::ConcurrencyPerformanceTest::ExecuteRealReadOperation (int32_t key) protected
执行真实读取操作（SQL查询）
Definition at line 75 of file concurrency_performance_test.cc.
{
    try {
        std::string query = "SELECT * FROM " + std::string(kTestDatabase) + "." + std::string(kTestTable) +
                           " WHERE id = " + std::to_string(key);
        if (sql_executor_) {
            sql_executor_->Execute(query);
        }
        return true;
    } catch (const std::exception& e) {
        std::cerr << "Error executing read operation: " << e.what() << std::endl;
        return false;
    }
}
References kTestDatabase, kTestTable, and sql_executor_.
Referenced by TestConcurrentReads(), and TestMixedReadWrite().
ExecuteRealWriteOperation()
bool sqlcc::test::ConcurrencyPerformanceTest::ExecuteRealWriteOperation (int32_t key, const std::string & value) protected
执行真实写入操作（SQL插入/更新）
Definition at line 89 of file concurrency_performance_test.cc.
{
    try {
        std::string query = "INSERT INTO " + std::string(kTestDatabase) + "." + std::string(kTestTable) +
                           " (id, value, timestamp) VALUES (" +
                           std::to_string(key) + ", '" + value + "', " +
                           std::to_string(std::time(nullptr)) + ") " +
                           "ON DUPLICATE KEY UPDATE value = '" + value + "', timestamp = " +
                           std::to_string(std::time(nullptr));
        if (sql_executor_) {
            sql_executor_->Execute(query);
        }
        return true;
    } catch (const std::exception& e) {
        std::cerr << "Error executing write operation: " << e.what() << std::endl;
        return false;
    }
}
References kTestDatabase, kTestTable, and sql_executor_.
Referenced by TestConcurrentWrites(), and TestMixedReadWrite().
GenerateTestData()
void sqlcc::test::ConcurrencyPerformanceTest::GenerateTestData () private
生成测试数据
InitializeTestTables()
void sqlcc::test::ConcurrencyPerformanceTest::InitializeTestTables () private
初始化测试表结构
Definition at line 121 of file concurrency_performance_test.cc.
{
    try {
        // 创建测试数据库和表
        sql_executor_ = std::make_unique<SqlExecutor>();
        if (sql_executor_) {
            sql_executor_->Execute("CREATE DATABASE IF NOT EXISTS " + std::string(kTestDatabase));
            sql_executor_->Execute("USE " + std::string(kTestDatabase));
            sql_executor_->Execute(
                "CREATE TABLE IF NOT EXISTS " + std::string(kTestTable) + " ("
                "id INT PRIMARY KEY, "
                "value VARCHAR(100), "
                "timestamp BIGINT"
                ")"
            );
        }
        std::cout << "Test tables initialized successfully." << std::endl;
    } catch (const std::exception& e) {
        std::cerr << "Error initializing test tables: " << e.what() << std::endl;
    }
}
References kTestDatabase, kTestTable, and sql_executor_.
Referenced by RunAllTests().
LockContentionWorkerThread()
void sqlcc::test::ConcurrencyPerformanceTest::LockContentionWorkerThread (int thread_id, size_t operations, std::atomic< size_t > & completed_ops, std::vector< double > & latencies, std::mutex & mutex) private
锁竞争工作线程函数
MixedWorkerThread()
void sqlcc::test::ConcurrencyPerformanceTest::MixedWorkerThread (int thread_id, size_t operations, std::atomic< size_t > & completed_ops, std::vector< double > & latencies, double read_ratio) private
混合读写工作线程函数
ReadWorkerThread()
void sqlcc::test::ConcurrencyPerformanceTest::ReadWorkerThread (int thread_id, size_t operations, std::atomic< size_t > & completed_ops, std::vector< double > & latencies) private
读取工作线程函数
RunAllTests()
void sqlcc::test::ConcurrencyPerformanceTest::RunAllTests () override virtual
运行所有测试
Implements sqlcc::test::PerformanceTestBase.
Definition at line 40 of file concurrency_performance_test.cc.
{
    std::vector<TestResult> results;
    // 初始化测试环境
    InitializeTestTables();
    // 运行各种并发测试
    results.push_back(TestConcurrentReads());
    results.push_back(TestConcurrentWrites());
    results.push_back(TestMixedReadWrite());
    results.push_back(TestLockContention());
    // 生成测试报告
    GenerateReport(results);
    // 清理测试环境
    Cleanup();
    std::cout << "All concurrency tests completed." << std::endl;
}
References Cleanup(), sqlcc::test::PerformanceTestBase::GenerateReport(), InitializeTestTables(), TestConcurrentReads(), TestConcurrentWrites(), TestLockContention(), and TestMixedReadWrite().
TestConcurrentReads()
PerformanceTestBase::TestResult sqlcc::test::ConcurrencyPerformanceTest::TestConcurrentReads () protected
并发读取测试
Definition at line 142 of file concurrency_performance_test.cc.
{
    PerformanceTestBase::TestResult result;
    result.test_name = "TestConcurrentReads";
    try {
        auto start_time = PerformanceTestBase::GetCurrentTime();
        // 简单实现：使用当前线程执行一些读取操作
        for (size_t i = 0; i < kOperationsPerThread; ++i) {
            int32_t key = key_dist_(rng_);
            ExecuteRealReadOperation(key);
        }
        auto end_time = PerformanceTestBase::GetCurrentTime();
        result.duration = PerformanceTestBase::CalculateDuration(start_time, end_time);
        result.operations_completed = kOperationsPerThread;
        result.throughput = PerformanceTestBase::CalculateThroughput(result.operations_completed, result.duration);
        result.avg_latency = result.duration.count() / static_cast<double>(kOperationsPerThread);
        result.p95_latency = result.avg_latency * 1.5; // 占位值
        result.p99_latency = result.avg_latency * 2.0; // 占位值
        std::cout << "Concurrent reads test completed." << std::endl;
    } catch (const std::exception& e) {
        std::cerr << "Error in TestConcurrentReads: " << e.what() << std::endl;
    }
    return result;
}
References sqlcc::test::PerformanceTestBase::TestResult::avg_latency, sqlcc::test::PerformanceTestBase::CalculateDuration(), sqlcc::test::PerformanceTestBase::CalculateThroughput(), sqlcc::test::PerformanceTestBase::TestResult::duration, ExecuteRealReadOperation(), sqlcc::test::PerformanceTestBase::GetCurrentTime(), key_dist_, kOperationsPerThread, sqlcc::test::PerformanceTestBase::TestResult::operations_completed, sqlcc::test::PerformanceTestBase::TestResult::p95_latency, sqlcc::test::PerformanceTestBase::TestResult::p99_latency, rng_, sqlcc::test::PerformanceTestBase::TestResult::test_name, and sqlcc::test::PerformanceTestBase::TestResult::throughput.
Referenced by RunAllTests().
TestConcurrentWrites()
PerformanceTestBase::TestResult sqlcc::test::ConcurrencyPerformanceTest::TestConcurrentWrites () protected
并发写入测试
Definition at line 171 of file concurrency_performance_test.cc.
{
    PerformanceTestBase::TestResult result;
    result.test_name = "TestConcurrentWrites";
    try {
        auto start_time = PerformanceTestBase::GetCurrentTime();
        // 简单实现：使用当前线程执行一些写入操作
        for (size_t i = 0; i < kOperationsPerThread; ++i) {
            int32_t key = key_dist_(rng_);
            std::string value = "test_value_" + std::to_string(key);
            ExecuteRealWriteOperation(key, value);
        }
        auto end_time = PerformanceTestBase::GetCurrentTime();
        result.duration = PerformanceTestBase::CalculateDuration(start_time, end_time);
        result.operations_completed = kOperationsPerThread;
        result.throughput = PerformanceTestBase::CalculateThroughput(result.operations_completed, result.duration);
        result.avg_latency = result.duration.count() / static_cast<double>(kOperationsPerThread);
        result.p95_latency = result.avg_latency * 1.8; // 占位值
        result.p99_latency = result.avg_latency * 2.5; // 占位值
        std::cout << "Concurrent writes test completed." << std::endl;
    } catch (const std::exception& e) {
        std::cerr << "Error in TestConcurrentWrites: " << e.what() << std::endl;
    }
    return result;
}
References sqlcc::test::PerformanceTestBase::TestResult::avg_latency, sqlcc::test::PerformanceTestBase::CalculateDuration(), sqlcc::test::PerformanceTestBase::CalculateThroughput(), sqlcc::test::PerformanceTestBase::TestResult::duration, ExecuteRealWriteOperation(), sqlcc::test::PerformanceTestBase::GetCurrentTime(), key_dist_, kOperationsPerThread, sqlcc::test::PerformanceTestBase::TestResult::operations_completed, sqlcc::test::PerformanceTestBase::TestResult::p95_latency, sqlcc::test::PerformanceTestBase::TestResult::p99_latency, rng_, sqlcc::test::PerformanceTestBase::TestResult::test_name, and sqlcc::test::PerformanceTestBase::TestResult::throughput.
Referenced by RunAllTests().
TestLockContention()
PerformanceTestBase::TestResult sqlcc::test::ConcurrencyPerformanceTest::TestLockContention () protected
锁竞争测试
Definition at line 235 of file concurrency_performance_test.cc.
{
    PerformanceTestBase::TestResult result;
    result.test_name = "TestLockContention";
    try {
        auto start_time = PerformanceTestBase::GetCurrentTime();
        // 简单实现：执行锁操作测试
        for (size_t i = 0; i < kOperationsPerThread / 10; ++i) { // 减少锁操作次数
            int32_t lock_id = key_dist_(rng_);
            ExecuteRealLockOperation(lock_id);
        }
        auto end_time = PerformanceTestBase::GetCurrentTime();
        result.duration = PerformanceTestBase::CalculateDuration(start_time, end_time);
        result.operations_completed = kOperationsPerThread / 10;
        result.throughput = PerformanceTestBase::CalculateThroughput(result.operations_completed, result.duration);
        result.avg_latency = result.duration.count() / static_cast<double>(kOperationsPerThread / 10);
        result.p95_latency = result.avg_latency * 2.0; // 占位值
        result.p99_latency = result.avg_latency * 3.0; // 占位值
        std::cout << "Lock contention test completed." << std::endl;
    } catch (const std::exception& e) {
        std::cerr << "Error in TestLockContention: " << e.what() << std::endl;
    }
    return result;
}
References sqlcc::test::PerformanceTestBase::TestResult::avg_latency, sqlcc::test::PerformanceTestBase::CalculateDuration(), sqlcc::test::PerformanceTestBase::CalculateThroughput(), sqlcc::test::PerformanceTestBase::TestResult::duration, ExecuteRealLockOperation(), sqlcc::test::PerformanceTestBase::GetCurrentTime(), key_dist_, kOperationsPerThread, sqlcc::test::PerformanceTestBase::TestResult::operations_completed, sqlcc::test::PerformanceTestBase::TestResult::p95_latency, sqlcc::test::PerformanceTestBase::TestResult::p99_latency, rng_, sqlcc::test::PerformanceTestBase::TestResult::test_name, and sqlcc::test::PerformanceTestBase::TestResult::throughput.
Referenced by RunAllTests().
TestMixedReadWrite()
PerformanceTestBase::TestResult sqlcc::test::ConcurrencyPerformanceTest::TestMixedReadWrite () protected
混合读写测试
Definition at line 201 of file concurrency_performance_test.cc.
{
    PerformanceTestBase::TestResult result;
    result.test_name = "TestMixedReadWrite";
    try {
        auto start_time = PerformanceTestBase::GetCurrentTime();
        // 简单实现：混合执行读写操作（80%读，20%写）
        for (size_t i = 0; i < kOperationsPerThread; ++i) {
            int32_t key = key_dist_(rng_);
            if (random_dist_(rng_) < 0.8) {
                ExecuteRealReadOperation(key);
            } else {
                std::string value = "mixed_test_value_" + std::to_string(key);
                ExecuteRealWriteOperation(key, value);
            }
        }
        auto end_time = PerformanceTestBase::GetCurrentTime();
        result.duration = PerformanceTestBase::CalculateDuration(start_time, end_time);
        result.operations_completed = kOperationsPerThread;
        result.throughput = PerformanceTestBase::CalculateThroughput(result.operations_completed, result.duration);
        result.avg_latency = result.duration.count() / static_cast<double>(kOperationsPerThread);
        result.p95_latency = result.avg_latency * 1.6; // 占位值
        result.p99_latency = result.avg_latency * 2.2; // 占位值
        std::cout << "Mixed read-write test completed." << std::endl;
    } catch (const std::exception& e) {
        std::cerr << "Error in TestMixedReadWrite: " << e.what() << std::endl;
    }
    return result;
}
References sqlcc::test::PerformanceTestBase::TestResult::avg_latency, sqlcc::test::PerformanceTestBase::CalculateDuration(), sqlcc::test::PerformanceTestBase::CalculateThroughput(), sqlcc::test::PerformanceTestBase::TestResult::duration, ExecuteRealReadOperation(), ExecuteRealWriteOperation(), sqlcc::test::PerformanceTestBase::GetCurrentTime(), key_dist_, kOperationsPerThread, sqlcc::test::PerformanceTestBase::TestResult::operations_completed, sqlcc::test::PerformanceTestBase::TestResult::p95_latency, sqlcc::test::PerformanceTestBase::TestResult::p99_latency, random_dist_, rng_, sqlcc::test::PerformanceTestBase::TestResult::test_name, and sqlcc::test::PerformanceTestBase::TestResult::throughput.
Referenced by RunAllTests().
WriteWorkerThread()
void sqlcc::test::ConcurrencyPerformanceTest::WriteWorkerThread (int thread_id, size_t operations, std::atomic< size_t > & completed_ops, std::vector< double > & latencies) private
写入工作线程函数
Member Data Documentation
buffer_pool_
std::unique_ptr<sqlcc::BufferPool> sqlcc::test::ConcurrencyPerformanceTest::buffer_pool_ private
Definition at line 159 of file concurrency_performance_test.h.
disk_manager_
std::unique_ptr<sqlcc::DiskManager> sqlcc::test::ConcurrencyPerformanceTest::disk_manager_ private
Definition at line 160 of file concurrency_performance_test.h.
kDataSize
constexpr size_t sqlcc::test::ConcurrencyPerformanceTest::kDataSize = 10000 static constexpr private
Definition at line 152 of file concurrency_performance_test.h.
kDefaultThreadCount
constexpr size_t sqlcc::test::ConcurrencyPerformanceTest::kDefaultThreadCount = 8 static constexpr private
Definition at line 150 of file concurrency_performance_test.h.
key_dist_
std::uniform_int_distribution<int32_t> sqlcc::test::ConcurrencyPerformanceTest::key_dist_ private
Definition at line 176 of file concurrency_performance_test.h.
Referenced by TestConcurrentReads(), TestConcurrentWrites(), TestLockContention(), and TestMixedReadWrite().
kLockCount
constexpr size_t sqlcc::test::ConcurrencyPerformanceTest::kLockCount = 100 static constexpr private
Definition at line 154 of file concurrency_performance_test.h.
kOperationsPerThread
constexpr size_t sqlcc::test::ConcurrencyPerformanceTest::kOperationsPerThread = 1000 static constexpr private
Definition at line 151 of file concurrency_performance_test.h.
Referenced by TestConcurrentReads(), TestConcurrentWrites(), TestLockContention(), and TestMixedReadWrite().
kTestDatabase
constexpr const char* sqlcc::test::ConcurrencyPerformanceTest::kTestDatabase = "concurrency_test_db" static constexpr private
Definition at line 155 of file concurrency_performance_test.h.
Referenced by Cleanup(), ExecuteRealLockOperation(), ExecuteRealReadOperation(), ExecuteRealWriteOperation(), and InitializeTestTables().
kTestTable
constexpr const char* sqlcc::test::ConcurrencyPerformanceTest::kTestTable = "test_data" static constexpr private
Definition at line 156 of file concurrency_performance_test.h.
Referenced by ExecuteRealLockOperation(), ExecuteRealReadOperation(), ExecuteRealWriteOperation(), and InitializeTestTables().
kWorkingSetSize
constexpr size_t sqlcc::test::ConcurrencyPerformanceTest::kWorkingSetSize = 100 static constexpr private
Definition at line 153 of file concurrency_performance_test.h.
lock_table_
std::vector<std::unique_ptr<std::mutex> > sqlcc::test::ConcurrencyPerformanceTest::lock_table_ private
Definition at line 168 of file concurrency_performance_test.h.
random_dist_
std::uniform_real_distribution<double> sqlcc::test::ConcurrencyPerformanceTest::random_dist_ private
Definition at line 177 of file concurrency_performance_test.h.
Referenced by TestMixedReadWrite().
rng_
std::mt19937 sqlcc::test::ConcurrencyPerformanceTest::rng_ private
Definition at line 175 of file concurrency_performance_test.h.
Referenced by TestConcurrentReads(), TestConcurrentWrites(), TestLockContention(), and TestMixedReadWrite().
sql_executor_
std::unique_ptr<sqlcc::SqlExecutor> sqlcc::test::ConcurrencyPerformanceTest::sql_executor_ private
Definition at line 161 of file concurrency_performance_test.h.
Referenced by Cleanup(), ExecuteRealLockOperation(), ExecuteRealReadOperation(), ExecuteRealWriteOperation(), and InitializeTestTables().
start_barrier_
SimpleBarrier* sqlcc::test::ConcurrencyPerformanceTest::start_barrier_ private
Definition at line 171 of file concurrency_performance_test.h.
string_data_
std::vector<std::string> sqlcc::test::ConcurrencyPerformanceTest::string_data_ private
Definition at line 167 of file concurrency_performance_test.h.
test_data_
std::vector<int32_t> sqlcc::test::ConcurrencyPerformanceTest::test_data_ private
Definition at line 166 of file concurrency_performance_test.h.
test_db_file_
std::string sqlcc::test::ConcurrencyPerformanceTest::test_db_file_ = "./test_concurrency.db" private
Definition at line 162 of file concurrency_performance_test.h.
test_running_
std::atomic<bool> sqlcc::test::ConcurrencyPerformanceTest::test_running_ private
Definition at line 172 of file concurrency_performance_test.h.
test_table_name_
std::string sqlcc::test::ConcurrencyPerformanceTest::test_table_name_ private
Definition at line 163 of file concurrency_performance_test.h.
The documentation for this class was generated from the following files:
tests/performance/concurrency_test/concurrency_performance_test.h
tests/performance/concurrency_test/concurrency_performance_test.cc