SQLCC: sqlcc::DiskManager Class Reference
sqlcc::DiskManager Class Reference
磁盘管理器类，负责页面的磁盘I/O操作
#include <disk_manager.h>
Public Member Functions
DiskManager (const std::string &db_file)
构造函数
~DiskManager ()
析构函数
DiskManager (const DiskManager &)=delete
禁止拷贝构造
DiskManager & operator= (const DiskManager &)=delete
禁止赋值操作
bool WritePage (const Page &page)
将页面写入磁盘
bool ReadPage (int32_t page_id, Page *page)
从磁盘读取页面
int32_t AllocatePage ()
分配新页面，返回页面ID
size_t GetFileSize () const
获取数据库文件大小
Private Attributes
std::string db_file_
std::fstream db_io_
size_t file_size_
int32_t next_page_id_
Detailed Description
磁盘管理器类，负责页面的磁盘I/O操作
Definition at line 12 of file disk_manager.h.
Constructor & Destructor Documentation
DiskManager() [1/2]
sqlcc::DiskManager::DiskManager (const std::string & db_file) explicit
构造函数
Parameters
db_file 数据库文件路径
Definition at line 10 of file disk_manager.cc.
    : db_file_(db_file), file_size_(0), next_page_id_(0) {
    SQLCC_LOG_INFO("Initializing DiskManager for database file: " + db_file_);
    // 以读写模式打开文件，如果文件不存在则创建
    db_io_.open(db_file_, std::ios::binary | std::ios::in | std::ios::out | std::ios::app);
    // 如果文件不存在，创建一个空文件
    if (!db_io_.good()) {
        SQLCC_LOG_INFO("Database file does not exist, creating new file: " + db_file_);
        db_io_.clear();
        db_io_.open(db_file_, std::ios::binary | std::ios::in | std::ios::out | std::ios::trunc);
    }
    // 获取文件大小
    if (db_io_.good()) {
        db_io_.seekg(0, std::ios::end);
        file_size_ = db_io_.tellg();
        next_page_id_ = static_cast<int32_t>(file_size_ / PAGE_SIZE);
        SQLCC_LOG_INFO("Opened database file: " + db_file_ + ", file size: " +
                      std::to_string(file_size_) + ", next page ID: " + std::to_string(next_page_id_));
    } else {
        std::string error_msg = "Failed to open database file: " + db_file_;
        SQLCC_LOG_ERROR(error_msg);
        throw DiskManagerException(error_msg);
    }
}
References db_file_, db_io_, file_size_, next_page_id_, sqlcc::PAGE_SIZE, SQLCC_LOG_ERROR, and SQLCC_LOG_INFO.
~DiskManager()
sqlcc::DiskManager::~DiskManager ()
析构函数
Definition at line 38 of file disk_manager.cc.
{
    if (db_io_.is_open()) {
        SQLCC_LOG_INFO("Closing database file: " + db_file_);
        db_io_.close();
    }
}
References db_file_, db_io_, and SQLCC_LOG_INFO.
DiskManager() [2/2]
sqlcc::DiskManager::DiskManager (const DiskManager &) delete
禁止拷贝构造
Member Function Documentation
AllocatePage()
int32_t sqlcc::DiskManager::AllocatePage ()
分配新页面，返回页面ID
Returns
新分配的页面ID
Definition at line 139 of file disk_manager.cc.
{
    int32_t page_id = next_page_id_++;
    SQLCC_LOG_DEBUG("Allocated new page ID: " + std::to_string(page_id));
    return page_id;
}
References next_page_id_, and SQLCC_LOG_DEBUG.
Referenced by sqlcc::BufferPool::NewPage().
GetFileSize()
size_t sqlcc::DiskManager::GetFileSize () const
获取数据库文件大小
Returns
数据库文件大小（以字节为单位）
Definition at line 145 of file disk_manager.cc.
{
    return file_size_;
}
References file_size_.
operator=()
DiskManager & sqlcc::DiskManager::operator= (const DiskManager &) delete
禁止赋值操作
ReadPage()
bool sqlcc::DiskManager::ReadPage (int32_t page_id, Page * page)
从磁盘读取页面
Parameters
page_id 页面ID
page 用于存储读取数据的页面对象
Returns
读取成功返回true，否则返回false
Definition at line 96 of file disk_manager.cc.
{
    if (page_id < 0 || page == nullptr) {
        std::string error_msg = "Invalid page ID: " + std::to_string(page_id) + " or null page pointer";
        SQLCC_LOG_ERROR(error_msg);
        return false;
    }
    // 计算页面在文件中的偏移量
    size_t offset = static_cast<size_t>(page_id) * PAGE_SIZE;
    SQLCC_LOG_DEBUG("Reading page ID " + std::to_string(page_id) + " at offset " + std::to_string(offset));
    // 检查页面是否在文件范围内
    if (offset >= file_size_) {
        std::string warn_msg = "Page " + std::to_string(page_id) + " does not exist in file";
        SQLCC_LOG_WARN(warn_msg);
        return false;
    }
    // 定位到页面位置
    db_io_.seekg(offset, std::ios::beg);
    if (db_io_.fail()) {
        std::string error_msg = "Failed to seek to page " + std::to_string(page_id);
        SQLCC_LOG_ERROR(error_msg);
        db_io_.clear();
        return false;
    }
    // 读取页面数据
    db_io_.read(page->GetData(), PAGE_SIZE);
    if (db_io_.fail()) {
        std::string error_msg = "Failed to read page " + std::to_string(page_id);
        SQLCC_LOG_ERROR(error_msg);
        db_io_.clear();
        return false;
    }
    // 设置页面ID
    page->SetPageId(page_id);
    SQLCC_LOG_DEBUG("Successfully read page ID " + std::to_string(page_id));
    return true;
}
References db_io_, file_size_, sqlcc::Page::GetData(), sqlcc::PAGE_SIZE, sqlcc::Page::SetPageId(), SQLCC_LOG_DEBUG, SQLCC_LOG_ERROR, and SQLCC_LOG_WARN.
Referenced by sqlcc::BufferPool::FetchPage().
WritePage()
bool sqlcc::DiskManager::WritePage (const Page & page)
将页面写入磁盘
Parameters
page 要写入的页面
Returns
写入成功返回true，否则返回false
Definition at line 45 of file disk_manager.cc.
{
    int32_t page_id = page.GetPageId();
    if (page_id < 0) {
        std::string error_msg = "Invalid page ID: " + std::to_string(page_id);
        SQLCC_LOG_ERROR(error_msg);
        return false;
    }
    // 计算页面在文件中的偏移量
    size_t offset = static_cast<size_t>(page_id) * PAGE_SIZE;
    SQLCC_LOG_DEBUG("Writing page ID " + std::to_string(page_id) + " at offset " + std::to_string(offset));
    // 定位到页面位置
    db_io_.seekp(offset, std::ios::beg);
    if (db_io_.fail()) {
        std::string error_msg = "Failed to seek to page " + std::to_string(page_id);
        SQLCC_LOG_ERROR(error_msg);
        db_io_.clear();
        return false;
    }
    // 写入页面数据
    db_io_.write(page.GetData(), PAGE_SIZE);
    if (db_io_.fail()) {
        std::string error_msg = "Failed to write page " + std::to_string(page_id);
        SQLCC_LOG_ERROR(error_msg);
        db_io_.clear();
        return false;
    }
    // 更新文件大小
    size_t new_size = offset + PAGE_SIZE;
    if (new_size > file_size_) {
        file_size_ = new_size;
        SQLCC_LOG_DEBUG("Updated file size to " + std::to_string(file_size_));
    }
    // 刷新到磁盘
    db_io_.flush();
    if (db_io_.fail()) {
        std::string error_msg = "Failed to flush page " + std::to_string(page_id) + " to disk";
        SQLCC_LOG_ERROR(error_msg);
        db_io_.clear();
        return false;
    }
    SQLCC_LOG_DEBUG("Successfully wrote page ID " + std::to_string(page_id));
    return true;
}
References db_io_, file_size_, sqlcc::Page::GetData(), sqlcc::Page::GetPageId(), sqlcc::PAGE_SIZE, SQLCC_LOG_DEBUG, and SQLCC_LOG_ERROR.
Referenced by sqlcc::BufferPool::FlushAllPages(), sqlcc::BufferPool::FlushPage(), and sqlcc::BufferPool::ReplacePage().
Member Data Documentation
db_file_
std::string sqlcc::DiskManager::db_file_ private
Definition at line 64 of file disk_manager.h.
Referenced by DiskManager(), and ~DiskManager().
db_io_
std::fstream sqlcc::DiskManager::db_io_ private
Definition at line 67 of file disk_manager.h.
Referenced by DiskManager(), ReadPage(), WritePage(), and ~DiskManager().
file_size_
size_t sqlcc::DiskManager::file_size_ private
Definition at line 70 of file disk_manager.h.
Referenced by DiskManager(), GetFileSize(), ReadPage(), and WritePage().
next_page_id_
int32_t sqlcc::DiskManager::next_page_id_ private
Definition at line 73 of file disk_manager.h.
Referenced by AllocatePage(), and DiskManager().
The documentation for this class was generated from the following files:
include/disk_manager.h
src/disk_manager.cc