SQLCC: sqlcc::WALManager Class Reference
sqlcc::WALManager Class Reference
#include <wal_manager.h>
Classes
struct WALMetrics
Public Member Functions
WALManager (const std::string &log_file_path, bool force_sync=false)
~WALManager ()
uint64_t Log (LogRecord record)
uint64_t LogBatch (const std::vector< LogRecord > &records)
void ForceFlush ()
void AsyncFlush ()
std::vector< LogRecord > ReadLogRange (uint64_t from_lsn, uint64_t to_lsn)
std::unordered_map< std::string, std::string > AnalyzeLog () const
uint64_t CreateCheckpoint (bool sync=true)
CheckpointState GetLastCheckpoint () const
std::vector< CheckpointState > GetCheckpointHistory () const
bool RecoverFromLog ()
std::vector< TransactionId > GetInProgressTransactions () const
uint64_t ReplayLog (uint64_t from_lsn, uint64_t to_lsn)
WALMetrics GetMetrics () const
void ResetMetrics ()
size_t CompactLog (uint64_t keep_lsn)
bool VerifyLogIntegrity () const
Private Member Functions
void InitializeLogFile ()
uint64_t GenerateLSN ()
size_t WriteRecordsToDisk (const std::vector< LogRecord > &records)
LogRecord ReadRecordFromDisk (uint64_t lsn)
void WriteCheckpointToDisk (const CheckpointState &checkpoint)
CheckpointState ReadCheckpointFromDisk () const
void AsyncFlushThread ()
WALManager (const WALManager &)=delete
WALManager & operator= (const WALManager &)=delete
Private Attributes
std::string log_file_path_
std::string checkpoint_file_path_
std::atomic< uint64_t > next_lsn_
std::atomic< uint64_t > last_flushed_lsn_
std::atomic< uint64_t > last_checkpoint_lsn_
std::vector< LogRecord > log_buffer_
std::mutex buffer_mutex_
std::condition_variable buffer_cv_
std::unique_ptr< std::thread > flush_thread_
std::atomic< bool > stop_flush_thread_
bool force_sync_
uint32_t flush_interval_ms_
std::mutex metrics_mutex_
WALMetrics metrics_
std::vector< CheckpointState > checkpoint_history_
std::mutex checkpoint_mutex_
Detailed Description
WAL（预写日志）管理器 - v0.4.8版本初始实现
核心功能：
日志记录写入和读取
原子性确保 (Atomicity)
持久性确保 (Durability)
检查点机制
崩溃恢复支持
设计原则：
写前日志：数据修改前必须先写日志
顺序写：高性能顺序I/O
批量提交：减少I/O次数
异步刷盘：性能和一致性平衡
Definition at line 91 of file wal_manager.h.
Constructor & Destructor Documentation
WALManager() [1/2]
sqlcc::WALManager::WALManager (const std::string & log_file_path, bool force_sync = false) explicit
构造函数
Parameters
log_file_path 日志文件路径
force_sync 是否强制同步写入
Definition at line 80 of file wal_manager.cpp.
    : log_file_path_(log_file_path),
      checkpoint_file_path_(log_file_path + ".chk"), next_lsn_(1),
      last_flushed_lsn_(0), last_checkpoint_lsn_(0), force_sync_(force_sync),
      flush_interval_ms_(100) { // 100ms异步刷盘间隔
  // 初始化指标
  metrics_.total_records = 0;
  metrics_.flushed_records = 0;
  metrics_.pending_records = 0;
  metrics_.total_checkpoints = 0;
  metrics_.log_file_size_bytes = 0;
  // 初始化日志文件
  InitializeLogFile();
  // 暂时禁用异步刷盘功能以解决编译问题
  force_sync_ = true; // 强制使用同步模式
  stop_flush_thread_ = true;
  std::cout << "WALManager 已初始化 - 日志文件: " << log_file_path_
            << " 强制同步: " << (force_sync_ ? "是" : "否") << std::endl;
}
References sqlcc::WALManager::WALMetrics::flushed_records, force_sync_, InitializeLogFile(), log_file_path_, sqlcc::WALManager::WALMetrics::log_file_size_bytes, metrics_, sqlcc::WALManager::WALMetrics::pending_records, stop_flush_thread_, sqlcc::WALManager::WALMetrics::total_checkpoints, and sqlcc::WALManager::WALMetrics::total_records.
~WALManager()
sqlcc::WALManager::~WALManager ()
析构函数 - 确保所有日志都刷盘
Definition at line 104 of file wal_manager.cpp.
{
  // 异步刷盘功能已被禁用
  // 此处无需处理线程停止
  // 强制刷盘所有待写入日志
  ForceFlush();
  std::cout << "WALManager 已销毁，所有日志已刷盘" << std::endl;
}
References ForceFlush().
WALManager() [2/2]
sqlcc::WALManager::WALManager (const WALManager &) private delete
Member Function Documentation
AnalyzeLog()
std::unordered_map< std::string, std::string > sqlcc::WALManager::AnalyzeLog () const
分析日志文件状态
Returns
状态信息
Definition at line 247 of file wal_manager.cpp.
{
  std::unordered_map<std::string, std::string> recovery_actions;
  // 临时注释掉会导致编译错误的部分
  // std::unique_lock<std::mutex> lock(buffer_mutex_);
  // TODO: 实现日志分析逻辑
  (void)recovery_actions; // 避免未使用变量警告
  return {};
}
AsyncFlush()
void sqlcc::WALManager::AsyncFlush ()
异步刷盘（后台线程）
Definition at line 217 of file wal_manager.cpp.
{
  // 这里的实现是让异步刷盘线程立即执行一次刷盘
  {
    std::unique_lock<std::mutex> lock(buffer_mutex_);
    buffer_cv_.notify_one(); // 唤醒异步刷盘线程执行刷盘
  }
}
References buffer_cv_, and buffer_mutex_.
AsyncFlushThread()
void sqlcc::WALManager::AsyncFlushThread () private
异步刷盘线程函数
Definition at line 579 of file wal_manager.cpp.
{
  while (!stop_flush_thread_) {
    // 检查是否有待刷盘的记录
    {
      std::unique_lock<std::mutex> lock(buffer_mutex_);
      buffer_cv_.wait_for(
          lock, std::chrono::milliseconds(flush_interval_ms_),
          [this]() { return !log_buffer_.empty() || stop_flush_thread_; });
    }
    if (stop_flush_thread_) {
      break;
    }
    // 执行异步刷盘
    ForceFlush();
  }
  std::cout << "异步刷盘线程已停止" << std::endl;
}
References buffer_cv_, buffer_mutex_, flush_interval_ms_, ForceFlush(), log_buffer_, and stop_flush_thread_.
CompactLog()
size_t sqlcc::WALManager::CompactLog (uint64_t keep_lsn)
整理日志文件（移除不必要的旧日志）
Parameters
keep_lsn 需要保持的最小LSN
Returns
被清理的日志大小（字节）
Definition at line 428 of file wal_manager.cpp.
{
  // 简化实现：记录需要保留的LSN，实际的日志压缩比较复杂
  // 需要考虑并发控制、检查点等因素
  std::cout << "日志整理完成（简化实现），保留LSN >= " << keep_lsn << std::endl;
  return 0; // 未实际压缩
}
CreateCheckpoint()
uint64_t sqlcc::WALManager::CreateCheckpoint (bool sync = true)
创建检查点
Parameters
sync 是否同步写入
Returns
检查点LSN
Definition at line 259 of file wal_manager.cpp.
{
  // 强制刷盘所有待写的记录
  ForceFlush();
  uint64_t checkpoint_lsn = last_flushed_lsn_;
  CheckpointState checkpoint{
      checkpoint_lsn,
      std::chrono::system_clock::now(),
      {} // TODO: 获取当前页面状态快照
  };
  // 写入检查点到磁盘
  if (sync) {
    WriteCheckpointToDisk(checkpoint);
  }
  // 更新检查点历史
  {
    std::unique_lock<std::mutex> lock(checkpoint_mutex_);
    checkpoint_history_.push_back(checkpoint);
    if (checkpoint_history_.size() > 100) { // 保留最近100个检查点
      checkpoint_history_.erase(checkpoint_history_.begin());
    }
  }
  last_checkpoint_lsn_ = checkpoint_lsn;
  // 更新指标
  {
    std::unique_lock<std::mutex> lock(metrics_mutex_);
    metrics_.total_checkpoints++;
  }
  std::cout << "已创建检查点，LSN: " << checkpoint_lsn
            << " 同步模式: " << (sync ? "是" : "否") << std::endl;
  return checkpoint_lsn;
}
References checkpoint_history_, checkpoint_mutex_, ForceFlush(), last_checkpoint_lsn_, last_flushed_lsn_, metrics_, metrics_mutex_, sqlcc::WALManager::WALMetrics::total_checkpoints, and WriteCheckpointToDisk().
ForceFlush()
void sqlcc::WALManager::ForceFlush ()
强制刷盘所有待写入日志
Definition at line 172 of file wal_manager.cpp.
{
  std::vector<LogRecord> records_to_flush;
  // 获取待刷盘的记录
  {
    std::unique_lock<std::mutex> lock(buffer_mutex_);
    records_to_flush.swap(log_buffer_);
  }
  if (records_to_flush.empty()) {
    return; // 没有待刷盘的记录
  }
  // 记录刷盘开始时间
  auto start_time = std::chrono::high_resolution_clock::now();
  // 写入到磁盘
  size_t written_count = WriteRecordsToDisk(records_to_flush);
  // 记录刷盘结束时间并更新性能指标
  auto end_time = std::chrono::high_resolution_clock::now();
  auto flush_time = std::chrono::duration_cast<std::chrono::microseconds>(
      end_time - start_time);
  {
    std::unique_lock<std::mutex> lock(metrics_mutex_);
    metrics_.flushed_records += written_count;
    metrics_.pending_records -= written_count;
    metrics_.total_flush_time += flush_time;
    if (metrics_.flushed_records > 0) {
      metrics_.avg_flush_time = std::chrono::microseconds(
          metrics_.total_flush_time.count() / metrics_.flushed_records);
    }
  }
  // 更新最后刷盘LSN
  if (!records_to_flush.empty()) {
    last_flushed_lsn_ = records_to_flush.back().lsn;
  }
  std::cout << "已强制刷盘 " << written_count << " 条日志记录，用时 "
            << flush_time.count() << " 微秒" << std::endl;
}
References sqlcc::WALManager::WALMetrics::avg_flush_time, buffer_mutex_, sqlcc::WALManager::WALMetrics::flushed_records, last_flushed_lsn_, log_buffer_, metrics_, metrics_mutex_, sqlcc::WALManager::WALMetrics::pending_records, sqlcc::WALManager::WALMetrics::total_flush_time, and WriteRecordsToDisk().
Referenced by AsyncFlushThread(), CreateCheckpoint(), Log(), LogBatch(), and ~WALManager().
GenerateLSN()
uint64_t sqlcc::WALManager::GenerateLSN () private
生成新的LSN
Returns
新的LSN
Definition at line 475 of file wal_manager.cpp.
{
  return next_lsn_.fetch_add(1, std::memory_order_relaxed);
}
References next_lsn_.
Referenced by Log(), and LogBatch().
GetCheckpointHistory()
std::vector< CheckpointState > sqlcc::WALManager::GetCheckpointHistory () const
获取检查点历史
Returns
检查点列表（按时间排序）
Definition at line 303 of file wal_manager.cpp.
{
  std::unique_lock<std::mutex> lock(checkpoint_mutex_);
  return checkpoint_history_;
}
References checkpoint_history_, and checkpoint_mutex_.
Referenced by GetLastCheckpoint().
GetInProgressTransactions()
std::vector< TransactionId > sqlcc::WALManager::GetInProgressTransactions () const
获取正在进行事务的ID列表
Returns
事务ID列表
Definition at line 359 of file wal_manager.cpp.
{
  std::vector<TransactionId> active_transactions;
  // 临时注释掉会导致编译错误的部分
  // std::vector<LogRecord> recent_logs = ReadLogRange(last_checkpoint_lsn_ + 1,
  // next_lsn_.load() - 1);
  // TODO: 实现获取进行中事务的逻辑
  (void)active_transactions; // 避免未使用变量警告
  return {};
}
GetLastCheckpoint()
CheckpointState sqlcc::WALManager::GetLastCheckpoint () const
获取最后一个检查点状态
Returns
检查点状态
Definition at line 299 of file wal_manager.cpp.
{
  return GetCheckpointHistory().back();
}
References GetCheckpointHistory().
Referenced by RecoverFromLog().
GetMetrics()
WALManager::WALMetrics sqlcc::WALManager::GetMetrics () const
获取WAL性能指标
Returns
性能指标
Definition at line 406 of file wal_manager.cpp.
{
  WALMetrics metrics;
  // 临时注释掉会导致编译错误的部分
  // metrics.log_file_size_bytes = std::filesystem::file_size(log_file_path_);
  // std::unique_lock<std::mutex> buffer_lock(buffer_mutex_);
  // metrics.pending_records = log_buffer_.size();
  // TODO: 实现指标收集逻辑
  (void)metrics; // 避免未使用变量警告
  return {};
}
InitializeLogFile()
void sqlcc::WALManager::InitializeLogFile () private
初始化日志文件
Definition at line 446 of file wal_manager.cpp.
{
  // 确保日志目录存在
  std::filesystem::create_directories(
      std::filesystem::path(log_file_path_).parent_path());
  // 如果日志文件不存在，创建空文件
  if (!std::filesystem::exists(log_file_path_)) {
    std::ofstream log_file(log_file_path_, std::ios::binary);
    if (!log_file) {
      throw std::runtime_error("无法创建日志文件: " + log_file_path_);
    }
    // 写入日志文件头信息
    const char *header = "SQLCC WAL v0.4.8";
    log_file.write(header, strlen(header));
    log_file.close();
  }
  // 如果检查点文件不存在，也创建
  if (!std::filesystem::exists(checkpoint_file_path_)) {
    std::ofstream chk_file(checkpoint_file_path_, std::ios::binary);
    if (!chk_file) {
      throw std::runtime_error("无法创建检查点文件: " + checkpoint_file_path_);
    }
    chk_file.close();
  }
  std::cout << "WAL日志文件已初始化: " << log_file_path_ << std::endl;
}
References checkpoint_file_path_, and log_file_path_.
Referenced by WALManager().
Log()
uint64_t sqlcc::WALManager::Log (LogRecord record)
写入日志记录
Parameters
record 要写入的日志记录
Returns
分配的LSN
Definition at line 114 of file wal_manager.cpp.
{
  // 分配LSN
  uint64_t assigned_lsn = GenerateLSN();
  record.lsn = assigned_lsn;
  record.timestamp = std::chrono::system_clock::now();
  // 放入缓冲区
  {
    std::unique_lock<std::mutex> lock(buffer_mutex_);
    log_buffer_.push_back(record);
    buffer_cv_.notify_one(); // 唤醒异步刷盘线程
  }
  // 更新指标
  {
    std::unique_lock<std::mutex> lock(metrics_mutex_);
    metrics_.total_records++;
    metrics_.pending_records++;
  }
  // 如果是强制同步模式，立刻刷盘
  if (force_sync_) {
    ForceFlush();
  }
  return assigned_lsn;
}
References buffer_cv_, buffer_mutex_, force_sync_, ForceFlush(), GenerateLSN(), log_buffer_, sqlcc::LogRecord::lsn, metrics_, metrics_mutex_, sqlcc::WALManager::WALMetrics::pending_records, sqlcc::LogRecord::timestamp, and sqlcc::WALManager::WALMetrics::total_records.
LogBatch()
uint64_t sqlcc::WALManager::LogBatch (const std::vector< LogRecord > & records)
批量写入日志记录
Parameters
records 日志记录列表
Returns
最后分配的LSN
Definition at line 142 of file wal_manager.cpp.
{
  uint64_t last_lsn = 0;
  // 为批量记录分配连续的LSN
  std::unique_lock<std::mutex> buffer_lock(buffer_mutex_);
  for (auto record : records) {
    uint64_t assigned_lsn = GenerateLSN();
    record.lsn = assigned_lsn;
    record.timestamp = std::chrono::system_clock::now();
    log_buffer_.push_back(record);
    last_lsn = assigned_lsn;
  }
  buffer_cv_.notify_one();
  // 更新指标
  {
    std::unique_lock<std::mutex> lock(metrics_mutex_);
    metrics_.total_records += records.size();
    metrics_.pending_records += records.size();
  }
  // 强制批提交
  if (force_sync_) {
    buffer_lock.unlock();
    ForceFlush();
  }
  return last_lsn;
}
References buffer_cv_, buffer_mutex_, force_sync_, ForceFlush(), GenerateLSN(), log_buffer_, metrics_, metrics_mutex_, sqlcc::WALManager::WALMetrics::pending_records, and sqlcc::WALManager::WALMetrics::total_records.
operator=()
WALManager & sqlcc::WALManager::operator= (const WALManager &) private delete
ReadCheckpointFromDisk()
CheckpointState sqlcc::WALManager::ReadCheckpointFromDisk () const private
从磁盘读取检查点
Returns
检查点状态
Definition at line 549 of file wal_manager.cpp.
{
  if (!std::filesystem::exists(checkpoint_file_path_)) {
    return {0, std::chrono::system_clock::now(), {}}; // 返回默认检查点
  }
  std::ifstream chk_file(checkpoint_file_path_, std::ios::binary);
  if (!chk_file) {
    throw std::runtime_error("无法打开检查点文件进行读取: " +
                             checkpoint_file_path_);
  }
  CheckpointState checkpoint;
  chk_file.read(reinterpret_cast<char *>(&checkpoint.checkpoint_lsn),
                sizeof(checkpoint.checkpoint_lsn));
  std::chrono::system_clock::rep timestamp_count;
  chk_file.read(reinterpret_cast<char *>(&timestamp_count),
                sizeof(timestamp_count));
  if (!chk_file.fail()) {
    checkpoint.timestamp = std::chrono::system_clock::time_point(
        std::chrono::system_clock::duration(timestamp_count));
  }
  // TODO: 读取页面状态快照
  return checkpoint;
}
References checkpoint_file_path_, sqlcc::CheckpointState::checkpoint_lsn, and sqlcc::CheckpointState::timestamp.
ReadLogRange()
std::vector< LogRecord > sqlcc::WALManager::ReadLogRange (uint64_t from_lsn, uint64_t to_lsn)
读取指定范围的日志记录
Parameters
from_lsn 起始LSN
to_lsn 结束LSN
Returns
日志记录列表
Definition at line 225 of file wal_manager.cpp.
{
  std::vector<LogRecord> result;
  // 遍历LSN范围
  for (uint64_t lsn = from_lsn; lsn <= to_lsn; ++lsn) {
    try {
      LogRecord record = ReadRecordFromDisk(lsn);
      if (record.lsn > 0) { // 检查记录是否存在
        result.push_back(record);
      } else {
        break; // 没有更多记录
      }
    } catch (const std::exception &) {
      // 记录不存在或损坏，跳过
      break;
    }
  }
  return result;
}
References sqlcc::LogRecord::lsn, and ReadRecordFromDisk().
Referenced by ReplayLog().
ReadRecordFromDisk()
LogRecord sqlcc::WALManager::ReadRecordFromDisk (uint64_t lsn) private
读取日志记录从磁盘
Parameters
lsn 指定的LSN
Returns
日志记录
Definition at line 519 of file wal_manager.cpp.
{
  // 避免未使用参数警告
  (void)lsn;
  // TODO: 实现从磁盘读取记录的逻辑
  return LogRecord();
}
Referenced by ReadLogRange(), and RecoverFromLog().
RecoverFromLog()
bool sqlcc::WALManager::RecoverFromLog ()
从WAL执行崩溃恢复
Returns
是否恢复成功
Definition at line 308 of file wal_manager.cpp.
{
  try {
    std::cout << "开始从WAL执行崩溃恢复..." << std::endl;
    // 1. 从最后一个检查点开始
    CheckpointState last_checkpoint = GetLastCheckpoint();
    uint64_t start_lsn = last_checkpoint.checkpoint_lsn + 1;
    uint64_t current_lsn = start_lsn;
    std::cout << "从检查点LSN " << last_checkpoint.checkpoint_lsn << " 开始恢复"
              << std::endl;
    // 2. 分析未完成事务
    std::unordered_map<TransactionId, bool> txn_status;
    while (true) {
      try {
        LogRecord record = ReadRecordFromDisk(current_lsn);
        if (record.lsn == 0)
          break; // 没有更多记录
        // 跟踪事务状态
        if (record.type == LogRecordType::BEGIN) {
          txn_status[record.txn_id] = false; // 未提交
        } else if (record.type == LogRecordType::COMMIT) {
          txn_status[record.txn_id] = true; // 已提交
          std::cout << "事务 " << record.txn_id << " 已提交" << std::endl;
        } else if (record.type == LogRecordType::ABORT) {
          txn_status.erase(record.txn_id); // 已中止
          std::cout << "事务 " << record.txn_id << " 已中止" << std::endl;
        }
        current_lsn++;
      } catch (const std::exception &) {
        break; // 到达日志文件末尾
      }
    }
    // 3. 回滚未提交的事务
    uint64_t max_recover_lsn = ReplayLog(start_lsn, current_lsn - 1);
    std::cout << "恢复完成，处理了 " << (max_recover_lsn - start_lsn + 1)
              << " 条日志记录" << std::endl;
    std::cout << "检查点后的LSN范围: " << start_lsn << " - " << max_recover_lsn
              << std::endl;
    return true;
  } catch (const std::exception &e) {
    std::cerr << "崩溃恢复失败: " << e.what() << std::endl;
    return false;
  }
}
References sqlcc::ABORT, sqlcc::BEGIN, sqlcc::CheckpointState::checkpoint_lsn, sqlcc::COMMIT, GetLastCheckpoint(), sqlcc::LogRecord::lsn, ReadRecordFromDisk(), ReplayLog(), sqlcc::LogRecord::txn_id, and sqlcc::LogRecord::type.
ReplayLog()
uint64_t sqlcc::WALManager::ReplayLog (uint64_t from_lsn, uint64_t to_lsn)
重演事务日志
Parameters
from_lsn 起始LSN
to_lsn 结束LSN
Returns
成功重演到最后一个LSN
Definition at line 372 of file wal_manager.cpp.
{
  uint64_t last_replay_lsn = from_lsn - 1;
  std::vector<LogRecord> logs_to_replay = ReadLogRange(from_lsn, to_lsn);
  for (const auto &record : logs_to_replay) {
    // 重演逻辑：根据日志记录恢复数据状态
    switch (record.type) {
    case LogRecordType::UPDATE:
      // TODO: 在存储引擎中应用更新操作
      std::cout << "重演更新: " << record.ToString() << std::endl;
      break;
    case LogRecordType::INSERT:
      // TODO: 在存储引擎中应用插入操作
      std::cout << "重演插入: " << record.ToString() << std::endl;
      break;
    case LogRecordType::DELETE:
      // TODO: 在存储引擎中应用删除操作
      std::cout << "重演删除: " << record.ToString() << std::endl;
      break;
    // BEGIN/COMMIT/ABORT 不需要重演，它们是事务控制
    case LogRecordType::COMPENSATE:
      std::cout << "重演补偿: " << record.ToString() << std::endl;
      break;
    default:
      break;
    }
    last_replay_lsn = record.lsn;
  }
  return last_replay_lsn;
}
References sqlcc::COMPENSATE, sqlcc::DELETE, sqlcc::INSERT, ReadLogRange(), and sqlcc::UPDATE.
Referenced by RecoverFromLog().
ResetMetrics()
void sqlcc::WALManager::ResetMetrics ()
重置性能指标
Definition at line 421 of file wal_manager.cpp.
{
  std::unique_lock<std::mutex> lock(metrics_mutex_);
  metrics_ = {
      0, 0, 0, std::chrono::microseconds(0), std::chrono::microseconds(0),
      0, 0};
}
References metrics_, and metrics_mutex_.
VerifyLogIntegrity()
bool sqlcc::WALManager::VerifyLogIntegrity () const
验证日志完整性
Returns
是否完整
Definition at line 436 of file wal_manager.cpp.
{
  // 临时注释掉会导致编译错误的部分
  // ReadRecordFromDisk(0);
  // TODO: 实现日志完整性验证逻辑
  return true;
}
WriteCheckpointToDisk()
void sqlcc::WALManager::WriteCheckpointToDisk (const CheckpointState & checkpoint) private
写入检查点到磁盘
Parameters
checkpoint 检查点状态
Definition at line 527 of file wal_manager.cpp.
{
  std::ofstream chk_file(checkpoint_file_path_, std::ios::binary);
  if (!chk_file) {
    throw std::runtime_error("无法打开检查点文件进行写入: " +
                             checkpoint_file_path_);
  }
  // 写入检查点基本信息
  chk_file.write(reinterpret_cast<const char *>(&checkpoint.checkpoint_lsn),
                 sizeof(checkpoint.checkpoint_lsn));
  auto timestamp_count = checkpoint.timestamp.time_since_epoch().count();
  chk_file.write(reinterpret_cast<const char *>(&timestamp_count),
                 sizeof(timestamp_count));
  // TODO: 写入页面状态快照
  chk_file.flush();
  std::cout << "检查点已写入磁盘，LSN: " << checkpoint.checkpoint_lsn
            << std::endl;
}
References checkpoint_file_path_, sqlcc::CheckpointState::checkpoint_lsn, and sqlcc::CheckpointState::timestamp.
Referenced by CreateCheckpoint().
WriteRecordsToDisk()
size_t sqlcc::WALManager::WriteRecordsToDisk (const std::vector< LogRecord > & records) private
实际写入日志记录到磁盘
Parameters
records 要写入的记录
Returns
成功写入的记录数量
Definition at line 479 of file wal_manager.cpp.
{
  if (records.empty()) {
    return 0;
  }
  std::ofstream log_file(log_file_path_, std::ios::binary | std::ios::app);
  if (!log_file) {
    throw std::runtime_error("无法打开日志文件进行写入: " + log_file_path_);
  }
  size_t written = 0;
  for (const auto &record : records) {
    // 简化二进制格式：
    // txn_id (8字节) + type (1字节) + key长度 (4字节) + key + lsn (8字节)
    uint8_t record_type = static_cast<uint8_t>(record.type);
    uint32_t key_length = record.key.length();
    log_file.write(reinterpret_cast<const char *>(&record.txn_id),
                   sizeof(record.txn_id));
    log_file.write(reinterpret_cast<const char *>(&record_type),
                   sizeof(record_type));
    log_file.write(reinterpret_cast<const char *>(&key_length),
                   sizeof(key_length));
    log_file.write(record.key.data(), key_length);
    log_file.write(reinterpret_cast<const char *>(&record.lsn),
                   sizeof(record.lsn));
    // TODO: 写入old_value, new_value和timestamp
    // 这里为了简化先只写入核心字段
    if (log_file.fail()) {
      throw std::runtime_error("写入日志记录失败");
    }
    written++;
  }
  log_file.flush();
  return written;
}
References log_file_path_.
Referenced by ForceFlush().
Member Data Documentation
buffer_cv_
std::condition_variable sqlcc::WALManager::buffer_cv_ private
Definition at line 288 of file wal_manager.h.
Referenced by AsyncFlush(), AsyncFlushThread(), Log(), and LogBatch().
buffer_mutex_
std::mutex sqlcc::WALManager::buffer_mutex_ private
Definition at line 287 of file wal_manager.h.
Referenced by AsyncFlush(), AsyncFlushThread(), ForceFlush(), Log(), and LogBatch().
checkpoint_file_path_
std::string sqlcc::WALManager::checkpoint_file_path_ private
Definition at line 279 of file wal_manager.h.
Referenced by InitializeLogFile(), ReadCheckpointFromDisk(), and WriteCheckpointToDisk().
checkpoint_history_
std::vector<CheckpointState> sqlcc::WALManager::checkpoint_history_ private
Definition at line 302 of file wal_manager.h.
Referenced by CreateCheckpoint(), and GetCheckpointHistory().
checkpoint_mutex_
std::mutex sqlcc::WALManager::checkpoint_mutex_ mutable private
Definition at line 303 of file wal_manager.h.
Referenced by CreateCheckpoint(), and GetCheckpointHistory().
flush_interval_ms_
uint32_t sqlcc::WALManager::flush_interval_ms_ private
Definition at line 295 of file wal_manager.h.
Referenced by AsyncFlushThread().
flush_thread_
std::unique_ptr<std::thread> sqlcc::WALManager::flush_thread_ private
Definition at line 291 of file wal_manager.h.
force_sync_
bool sqlcc::WALManager::force_sync_ private
Definition at line 294 of file wal_manager.h.
Referenced by Log(), LogBatch(), and WALManager().
last_checkpoint_lsn_
std::atomic<uint64_t> sqlcc::WALManager::last_checkpoint_lsn_ private
Definition at line 283 of file wal_manager.h.
Referenced by CreateCheckpoint().
last_flushed_lsn_
std::atomic<uint64_t> sqlcc::WALManager::last_flushed_lsn_ private
Definition at line 282 of file wal_manager.h.
Referenced by CreateCheckpoint(), and ForceFlush().
log_buffer_
std::vector<LogRecord> sqlcc::WALManager::log_buffer_ private
Definition at line 286 of file wal_manager.h.
Referenced by AsyncFlushThread(), ForceFlush(), Log(), and LogBatch().
log_file_path_
std::string sqlcc::WALManager::log_file_path_ private
Definition at line 278 of file wal_manager.h.
Referenced by InitializeLogFile(), WALManager(), and WriteRecordsToDisk().
metrics_
WALMetrics sqlcc::WALManager::metrics_ private
Definition at line 299 of file wal_manager.h.
Referenced by CreateCheckpoint(), ForceFlush(), Log(), LogBatch(), ResetMetrics(), and WALManager().
metrics_mutex_
std::mutex sqlcc::WALManager::metrics_mutex_ mutable private
Definition at line 298 of file wal_manager.h.
Referenced by CreateCheckpoint(), ForceFlush(), Log(), LogBatch(), and ResetMetrics().
next_lsn_
std::atomic<uint64_t> sqlcc::WALManager::next_lsn_ private
Definition at line 281 of file wal_manager.h.
Referenced by GenerateLSN().
stop_flush_thread_
std::atomic<bool> sqlcc::WALManager::stop_flush_thread_ private
Definition at line 292 of file wal_manager.h.
Referenced by AsyncFlushThread(), and WALManager().
The documentation for this class was generated from the following files:
include/wal_manager.h
src/transaction_manager/wal_manager.cpp