SQLCC: sqlcc::test::NetworkPerformanceTest Class Reference
sqlcc::test::NetworkPerformanceTest Class Reference
Public Member Functions
NetworkPerformanceTest ()
~NetworkPerformanceTest () override
void RunAllTests () override
Public Member Functions inherited from sqlcc::test::PerformanceTestBase
PerformanceTestBase ()=default
virtual ~PerformanceTestBase ()=default
void SetOutputDirectory (const std::string &directory)
Protected Member Functions
void Cleanup () override
Protected Member Functions inherited from sqlcc::test::PerformanceTestBase
std::chrono::high_resolution_clock::time_point GetCurrentTime () const
std::chrono::milliseconds CalculateDuration (const std::chrono::high_resolution_clock::time_point &start, const std::chrono::high_resolution_clock::time_point &end) const
double CalculateThroughput (size_t operations, std::chrono::milliseconds duration) const
void CalculateLatencies (const std::vector< double > &latencies, double &avg, double &p95, double &p99) const
void PrintResult (const TestResult &result) const
void SaveResultsToFile (const std::vector< TestResult > &results, const std::string &filename) const
void GenerateReport (const std::vector< TestResult > &results) const
Detailed Description
Definition at line 9 of file network_performance_test.cc.
Constructor & Destructor Documentation
NetworkPerformanceTest()
sqlcc::test::NetworkPerformanceTest::NetworkPerformanceTest () inline
Definition at line 11 of file network_performance_test.cc.
{
        std::cout << "NetworkPerformanceTest initialized." << std::endl;
    }
~NetworkPerformanceTest()
sqlcc::test::NetworkPerformanceTest::~NetworkPerformanceTest () inline override
Definition at line 15 of file network_performance_test.cc.
{
        Cleanup();
        std::cout << "NetworkPerformanceTest destroyed." << std::endl;
    }
References Cleanup().
Member Function Documentation
Cleanup()
void sqlcc::test::NetworkPerformanceTest::Cleanup () inline override protected virtual
清理测试环境
Implements sqlcc::test::PerformanceTestBase.
Definition at line 62 of file network_performance_test.cc.
{
        std::cout << "Cleaning up network test environment." << std::endl;
    }
Referenced by ~NetworkPerformanceTest().
RunAllTests()
void sqlcc::test::NetworkPerformanceTest::RunAllTests () inline override virtual
运行所有测试
Implements sqlcc::test::PerformanceTestBase.
Definition at line 20 of file network_performance_test.cc.
{
        std::vector<PerformanceTestBase::TestResult> results;
        try {
            // 使用局部SQL执行器变量
            SqlExecutor executor;
            // 创建测试数据库和表
            executor.Execute("CREATE DATABASE IF NOT EXISTS network_test_db");
            executor.Execute("USE network_test_db");
            executor.Execute(
                "CREATE TABLE IF NOT EXISTS network_test_data ("
                "id INT PRIMARY KEY, "
                "data TEXT, "
                "timestamp BIGINT"
                ")"
            );
            // 运行网络性能测试
            PerformanceTestBase::TestResult result;
            result.test_name = "Network Performance Test";
            result.duration = std::chrono::milliseconds(1000); // 占位值，1秒
            result.operations_completed = 100; // 占位值
            result.throughput = PerformanceTestBase::CalculateThroughput(result.operations_completed, result.duration);
            result.avg_latency = 0.5; // 占位值
            result.p95_latency = 0.8; // 占位值
            result.p99_latency = 1.2; // 占位值
            results.push_back(result);
            // 使用基类方法生成报告
            PerformanceTestBase::GenerateReport(results);
            // 清理测试数据
            executor.Execute("DROP DATABASE IF EXISTS network_test_db");
            std::cout << "Network performance tests completed." << std::endl;
        } catch (const std::exception& e) {
            std::cerr << "Error running network performance tests: " << e.what() << std::endl;
        }
    }
References sqlcc::test::PerformanceTestBase::TestResult::avg_latency, sqlcc::test::PerformanceTestBase::CalculateThroughput(), sqlcc::test::PerformanceTestBase::TestResult::duration, sqlcc::SqlExecutor::Execute(), sqlcc::test::PerformanceTestBase::GenerateReport(), sqlcc::test::PerformanceTestBase::TestResult::operations_completed, sqlcc::test::PerformanceTestBase::TestResult::p95_latency, sqlcc::test::PerformanceTestBase::TestResult::p99_latency, sqlcc::test::PerformanceTestBase::TestResult::test_name, and sqlcc::test::PerformanceTestBase::TestResult::throughput.
The documentation for this class was generated from the following file:
tests/performance/network_performance_test.cc