SQLCC: sqlcc::test::BatchPrefetchPerformanceTest Class Reference
sqlcc::test::BatchPrefetchPerformanceTest Class Reference
#include <batch_prefetch_performance_test.h>
Public Member Functions
BatchPrefetchPerformanceTest ()
~BatchPrefetchPerformanceTest () override
void RunAllTests () override
Public Member Functions inherited from sqlcc::test::PerformanceTestBase
PerformanceTestBase ()=default
virtual ~PerformanceTestBase ()=default
void SetOutputDirectory (const std::string &directory)
Protected Member Functions
void Cleanup () override
Protected Member Functions inherited from sqlcc::test::PerformanceTestBase
std::chrono::high_resolution_clock::time_point GetCurrentTime () const
std::chrono::milliseconds CalculateDuration (const std::chrono::high_resolution_clock::time_point &start, const std::chrono::high_resolution_clock::time_point &end) const
double CalculateThroughput (size_t operations, std::chrono::milliseconds duration) const
void CalculateLatencies (const std::vector< double > &latencies, double &avg, double &p95, double &p99) const
void PrintResult (const TestResult &result) const
void SaveResultsToFile (const std::vector< TestResult > &results, const std::string &filename) const
void GenerateReport (const std::vector< TestResult > &results) const
Private Member Functions
void RunSinglePageReadTest ()
void RunBatchPageReadTest ()
void RunSinglePagePrefetchTest ()
void RunBatchPrefetchTest ()
void RunMixedAccessPatternTest ()
void RunVaryingBatchSizeTest ()
void SetupTestEnvironment ()
void GenerateSequentialAccess (std::vector< int32_t > &page_ids, size_t count)
void GenerateRandomAccess (std::vector< int32_t > &page_ids, size_t count, size_t max_page_id)
void GenerateLocalityAccess (std::vector< int32_t > &page_ids, size_t count, size_t working_set)
void ExecuteSinglePageAccesses (const std::vector< int32_t > &page_ids, std::vector< double > &latencies)
void ExecuteBatchPageAccesses (const std::vector< int32_t > &page_ids, std::vector< double > &latencies, size_t batch_size)
void ExecutePrefetchOperations (const std::vector< int32_t > &page_ids, std::vector< double > &latencies)
void ExecuteBatchPrefetchOperations (const std::vector< int32_t > &page_ids, std::vector< double > &latencies, size_t batch_size)
Private Attributes
std::unique_ptr< sqlcc::BufferPool > buffer_pool_
std::unique_ptr< sqlcc::DiskManager > disk_manager_
std::string test_db_file_ = "./test_batch_prefetch.db"
size_t pool_size_ = 128
size_t access_count_ = 10000
size_t working_set_size_ = 1000
std::vector< size_t > batch_sizes_ = {1, 4, 8, 16, 32, 64}
std::mt19937 rng_
Detailed Description
批量读取和预取机制性能测试类 测试批量读取和预取机制的性能表现
Definition at line 18 of file batch_prefetch_performance_test.h.
Constructor & Destructor Documentation
BatchPrefetchPerformanceTest()
sqlcc::test::BatchPrefetchPerformanceTest::BatchPrefetchPerformanceTest ()
构造函数
Definition at line 8 of file batch_prefetch_performance_test.cc.
{
    std::cout << "BatchPrefetchPerformanceTest initialized." << std::endl;
}
~BatchPrefetchPerformanceTest()
sqlcc::test::BatchPrefetchPerformanceTest::~BatchPrefetchPerformanceTest () override
析构函数
Definition at line 12 of file batch_prefetch_performance_test.cc.
{
    Cleanup();
    std::cout << "BatchPrefetchPerformanceTest destroyed." << std::endl;
}
References Cleanup().
Member Function Documentation
Cleanup()
void sqlcc::test::BatchPrefetchPerformanceTest::Cleanup () override protected virtual
清理测试环境
Implements sqlcc::test::PerformanceTestBase.
Definition at line 51 of file batch_prefetch_performance_test.cc.
{
    // 简单的清理实现
    std::cout << "Cleaning up batch prefetch test environment." << std::endl;
}
Referenced by RunAllTests(), and ~BatchPrefetchPerformanceTest().
ExecuteBatchPageAccesses()
void sqlcc::test::BatchPrefetchPerformanceTest::ExecuteBatchPageAccesses (const std::vector< int32_t > & page_ids, std::vector< double > & latencies, size_t batch_size) private
执行批量页面访问操作并记录延迟
ExecuteBatchPrefetchOperations()
void sqlcc::test::BatchPrefetchPerformanceTest::ExecuteBatchPrefetchOperations (const std::vector< int32_t > & page_ids, std::vector< double > & latencies, size_t batch_size) private
执行批量预取操作并记录延迟
ExecutePrefetchOperations()
void sqlcc::test::BatchPrefetchPerformanceTest::ExecutePrefetchOperations (const std::vector< int32_t > & page_ids, std::vector< double > & latencies) private
执行预取操作并记录延迟
ExecuteSinglePageAccesses()
void sqlcc::test::BatchPrefetchPerformanceTest::ExecuteSinglePageAccesses (const std::vector< int32_t > & page_ids, std::vector< double > & latencies) private
执行单个页面访问操作并记录延迟
Definition at line 128 of file batch_prefetch_performance_test.cc.
{
    // 简单的实现，为了编译通过
    latencies.resize(page_ids.size(), 0.1); // 占位值
}
GenerateLocalityAccess()
void sqlcc::test::BatchPrefetchPerformanceTest::GenerateLocalityAccess (std::vector< int32_t > & page_ids, size_t count, size_t working_set) private
生成具有局部性的访问序列
Definition at line 111 of file batch_prefetch_performance_test.cc.
{
    // 简单的实现，为了编译通过
    page_ids.resize(count);
    std::random_device rd;
    std::mt19937 gen(rd());
    for (size_t i = 0; i < count; ++i) {
        // 简单的局部性访问生成
        size_t region = (i / (count / 10)) % 10;
        std::uniform_int_distribution<int32_t> dist(
            static_cast<int32_t>(region * working_set / 10),
            static_cast<int32_t>((region + 1) * working_set / 10 - 1)
        );
        page_ids[i] = dist(gen);
    }
}
GenerateRandomAccess()
void sqlcc::test::BatchPrefetchPerformanceTest::GenerateRandomAccess (std::vector< int32_t > & page_ids, size_t count, size_t max_page_id) private
生成随机访问序列
Definition at line 99 of file batch_prefetch_performance_test.cc.
{
    // 简单的实现，为了编译通过
    page_ids.resize(count);
    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_int_distribution<int32_t> dist(0, static_cast<int32_t>(max_page_id - 1));
    for (size_t i = 0; i < count; ++i) {
        page_ids[i] = dist(gen);
    }
}
GenerateSequentialAccess()
void sqlcc::test::BatchPrefetchPerformanceTest::GenerateSequentialAccess (std::vector< int32_t > & page_ids, size_t count) private
生成顺序访问序列
Definition at line 91 of file batch_prefetch_performance_test.cc.
{
    // 简单的实现，为了编译通过
    page_ids.resize(count);
    for (size_t i = 0; i < count; ++i) {
        page_ids[i] = static_cast<int32_t>(i);
    }
}
RunAllTests()
void sqlcc::test::BatchPrefetchPerformanceTest::RunAllTests () override virtual
运行所有测试
Implements sqlcc::test::PerformanceTestBase.
Definition at line 17 of file batch_prefetch_performance_test.cc.
{
    std::vector<PerformanceTestBase::TestResult> results;
    try {
        // 设置测试环境
        SetupTestEnvironment();
        // 运行单个页面读取测试
        RunSinglePageReadTest();
        // 运行批量页面读取测试
        RunBatchPageReadTest();
        // 运行单页预取测试
        RunSinglePagePrefetchTest();
        // 运行批量预取测试
        RunBatchPrefetchTest();
        // 运行混合访问模式测试
        RunMixedAccessPatternTest();
        // 运行不同批量大小测试
        RunVaryingBatchSizeTest();
        // 清理测试环境
        Cleanup();
        std::cout << "All batch prefetch performance tests completed." << std::endl;
    } catch (const std::exception& e) {
        std::cerr << "Error running batch prefetch performance tests: " << e.what() << std::endl;
    }
}
References Cleanup(), RunBatchPageReadTest(), RunBatchPrefetchTest(), RunMixedAccessPatternTest(), RunSinglePagePrefetchTest(), RunSinglePageReadTest(), RunVaryingBatchSizeTest(), and SetupTestEnvironment().
RunBatchPageReadTest()
void sqlcc::test::BatchPrefetchPerformanceTest::RunBatchPageReadTest () private
运行批量页面读取性能测试
Definition at line 61 of file batch_prefetch_performance_test.cc.
{
    // 简单的实现，为了编译通过
    std::cout << "Running batch page read test." << std::endl;
}
Referenced by RunAllTests().
RunBatchPrefetchTest()
void sqlcc::test::BatchPrefetchPerformanceTest::RunBatchPrefetchTest () private
运行批量预取性能测试
Definition at line 71 of file batch_prefetch_performance_test.cc.
{
    // 简单的实现，为了编译通过
    std::cout << "Running batch prefetch test." << std::endl;
}
Referenced by RunAllTests().
RunMixedAccessPatternTest()
void sqlcc::test::BatchPrefetchPerformanceTest::RunMixedAccessPatternTest () private
运行混合访问模式测试
Definition at line 76 of file batch_prefetch_performance_test.cc.
{
    // 简单的实现，为了编译通过
    std::cout << "Running mixed access pattern test." << std::endl;
}
Referenced by RunAllTests().
RunSinglePagePrefetchTest()
void sqlcc::test::BatchPrefetchPerformanceTest::RunSinglePagePrefetchTest () private
运行单页预取性能测试
Definition at line 66 of file batch_prefetch_performance_test.cc.
{
    // 简单的实现，为了编译通过
    std::cout << "Running single page prefetch test." << std::endl;
}
Referenced by RunAllTests().
RunSinglePageReadTest()
void sqlcc::test::BatchPrefetchPerformanceTest::RunSinglePageReadTest () private
运行单个页面读取性能测试
Definition at line 56 of file batch_prefetch_performance_test.cc.
{
    // 简单的实现，为了编译通过
    std::cout << "Running single page read test." << std::endl;
}
Referenced by RunAllTests().
RunVaryingBatchSizeTest()
void sqlcc::test::BatchPrefetchPerformanceTest::RunVaryingBatchSizeTest () private
运行不同批量大小性能测试
Definition at line 81 of file batch_prefetch_performance_test.cc.
{
    // 简单的实现，为了编译通过
    std::cout << "Running varying batch size test." << std::endl;
}
Referenced by RunAllTests().
SetupTestEnvironment()
void sqlcc::test::BatchPrefetchPerformanceTest::SetupTestEnvironment () private
设置测试环境
Definition at line 86 of file batch_prefetch_performance_test.cc.
{
    // 简单的实现，为了编译通过
    std::cout << "Setting up test environment." << std::endl;
}
Referenced by RunAllTests().
Member Data Documentation
access_count_
size_t sqlcc::test::BatchPrefetchPerformanceTest::access_count_ = 10000 private
Definition at line 126 of file batch_prefetch_performance_test.h.
batch_sizes_
std::vector<size_t> sqlcc::test::BatchPrefetchPerformanceTest::batch_sizes_ = {1, 4, 8, 16, 32, 64} private
Definition at line 128 of file batch_prefetch_performance_test.h.
{1, 4, 8, 16, 32, 64};  // 不同的批量大小
buffer_pool_
std::unique_ptr<sqlcc::BufferPool> sqlcc::test::BatchPrefetchPerformanceTest::buffer_pool_ private
Definition at line 120 of file batch_prefetch_performance_test.h.
disk_manager_
std::unique_ptr<sqlcc::DiskManager> sqlcc::test::BatchPrefetchPerformanceTest::disk_manager_ private
Definition at line 121 of file batch_prefetch_performance_test.h.
pool_size_
size_t sqlcc::test::BatchPrefetchPerformanceTest::pool_size_ = 128 private
Definition at line 125 of file batch_prefetch_performance_test.h.
rng_
std::mt19937 sqlcc::test::BatchPrefetchPerformanceTest::rng_ private
Definition at line 131 of file batch_prefetch_performance_test.h.
test_db_file_
std::string sqlcc::test::BatchPrefetchPerformanceTest::test_db_file_ = "./test_batch_prefetch.db" private
Definition at line 122 of file batch_prefetch_performance_test.h.
working_set_size_
size_t sqlcc::test::BatchPrefetchPerformanceTest::working_set_size_ = 1000 private
Definition at line 127 of file batch_prefetch_performance_test.h.
The documentation for this class was generated from the following files:
tests/performance/batch_prefetch_performance_test.h
tests/performance/batch_prefetch_performance_test.cc