SQLCC: sqlcc::CheckConstraintExecutor Class Reference
sqlcc::CheckConstraintExecutor Class Reference
CHECK约束执行器
#include <constraint_executor.h>
Public Member Functions
CheckConstraintExecutor (const sql_parser::CheckConstraint &constraint, const std::string &table_name)
构造函数
bool validateInsert (const std::vector< std::string > &record, const std::vector< sql_parser::ColumnDefinition > &table_schema) override
验证插入操作
bool validateUpdate (const std::vector< std::string > &old_record, const std::vector< std::string > &new_record, const std::vector< sql_parser::ColumnDefinition > &table_schema) override
验证更新操作
bool validateDelete (const std::vector< std::string > &record, const std::vector< sql_parser::ColumnDefinition > &table_schema) override
验证删除操作
const std::string & getConstraintName () const override
获取约束名称
sql_parser::TableConstraint::Type getConstraintType () const override
获取约束类型
Public Member Functions inherited from sqlcc::ConstraintExecutor
virtual ~ConstraintExecutor ()=default
Private Member Functions
bool evaluateCheckCondition (const std::vector< std::string > &record, const std::vector< sql_parser::ColumnDefinition > &table_schema)
求值CHECK约束表达式
Private Attributes
std::reference_wrapper< const sql_parser::CheckConstraint > constraint_
std::string table_name_
Detailed Description
CHECK约束执行器
负责验证CHECK约束条件
Definition at line 231 of file constraint_executor.h.
Constructor & Destructor Documentation
CheckConstraintExecutor()
sqlcc::CheckConstraintExecutor::CheckConstraintExecutor (const sql_parser::CheckConstraint & constraint, const std::string & table_name)
构造函数
Parameters
constraint CHECK约束定义
table_name 表名
Definition at line 330 of file constraint_executor.cpp.
    : constraint_(constraint) {
  // 存储检查约束的表达式
  (void)table_name; // 避免未使用参数警告
}
Member Function Documentation
evaluateCheckCondition()
bool sqlcc::CheckConstraintExecutor::evaluateCheckCondition (const std::vector< std::string > & record, const std::vector< sql_parser::ColumnDefinition > & table_schema) private
求值CHECK约束表达式
Parameters
record 记录数据
table_schema 表结构
Returns
true if condition evaluates to true
Definition at line 366 of file constraint_executor.cpp.
{
  try {
    // 简化的CHECK约束验证
    // 实际实现需要完整的表达式求值引擎
    const auto &condition = constraint_.get().getCondition();
    if (!condition) {
      // 没有条件表达式，默认通过
      return true;
    }
    // 这里应该调用ExpressionEvaluator来求值约束表达式
    // 目前返回true作为占位符
    return ExpressionEvaluator::evaluate(condition.get(), record, table_schema);
  } catch (const std::exception &e) {
    // CHECK约束验证失败
    return false;
  }
}
References constraint_, and sqlcc::ExpressionEvaluator::evaluate().
Referenced by validateInsert(), and validateUpdate().
getConstraintName()
const std::string & sqlcc::CheckConstraintExecutor::getConstraintName () const override virtual
获取约束名称
Returns
约束名称
Implements sqlcc::ConstraintExecutor.
Definition at line 362 of file constraint_executor.cpp.
{
  return constraint_.get().getName();
}
References constraint_.
getConstraintType()
sql_parser::TableConstraint::Type sqlcc::CheckConstraintExecutor::getConstraintType () const inline override virtual
获取约束类型
Returns
约束类型
Implements sqlcc::ConstraintExecutor.
Definition at line 255 of file constraint_executor.h.
{
    return sql_parser::TableConstraint::CHECK;
  }
References sqlcc::sql_parser::TableConstraint::CHECK.
validateDelete()
bool sqlcc::CheckConstraintExecutor::validateDelete (const std::vector< std::string > & record, const std::vector< sql_parser::ColumnDefinition > & table_schema) override virtual
验证删除操作
Parameters
record 要删除的记录
table_schema 表结构信息
Returns
true if validation passes, false otherwise
Implements sqlcc::ConstraintExecutor.
Definition at line 355 of file constraint_executor.cpp.
{
  // 删除操作不影响CHECK约束
  return true;
}
validateInsert()
bool sqlcc::CheckConstraintExecutor::validateInsert (const std::vector< std::string > & record, const std::vector< sql_parser::ColumnDefinition > & table_schema) override virtual
验证插入操作
Parameters
record 要插入的记录
table_schema 表结构信息
Returns
true if validation passes, false otherwise
Implements sqlcc::ConstraintExecutor.
Definition at line 338 of file constraint_executor.cpp.
{
  // 求值CHECK约束表达式
  return evaluateCheckCondition(record, table_schema);
}
References evaluateCheckCondition().
validateUpdate()
bool sqlcc::CheckConstraintExecutor::validateUpdate (const std::vector< std::string > & old_record, const std::vector< std::string > & new_record, const std::vector< sql_parser::ColumnDefinition > & table_schema) override virtual
验证更新操作
Parameters
old_record 旧记录
new_record 新记录
table_schema 表结构信息
Returns
true if validation passes, false otherwise
Implements sqlcc::ConstraintExecutor.
Definition at line 346 of file constraint_executor.cpp.
{
  // 只对新记录进行验证
  return evaluateCheckCondition(new_record, table_schema);
}
References evaluateCheckCondition().
Member Data Documentation
constraint_
std::reference_wrapper<const sql_parser::CheckConstraint> sqlcc::CheckConstraintExecutor::constraint_ private
Definition at line 272 of file constraint_executor.h.
Referenced by evaluateCheckCondition(), and getConstraintName().
table_name_
std::string sqlcc::CheckConstraintExecutor::table_name_ private
Definition at line 273 of file constraint_executor.h.
The documentation for this class was generated from the following files:
include/constraint_executor.h
src/sql_executor/constraint_executor.cpp