SQLCC: sqlcc::test::PerformanceTestBase Class Reference
sqlcc::test::PerformanceTestBase Class Reference abstract
#include <performance_test_base.h>
Classes
struct TestResult
Public Member Functions
PerformanceTestBase ()=default
virtual ~PerformanceTestBase ()=default
virtual void RunAllTests ()=0
void SetOutputDirectory (const std::string &directory)
Protected Member Functions
std::chrono::high_resolution_clock::time_point GetCurrentTime () const
std::chrono::milliseconds CalculateDuration (const std::chrono::high_resolution_clock::time_point &start, const std::chrono::high_resolution_clock::time_point &end) const
double CalculateThroughput (size_t operations, std::chrono::milliseconds duration) const
void CalculateLatencies (const std::vector< double > &latencies, double &avg, double &p95, double &p99) const
void PrintResult (const TestResult &result) const
void SaveResultsToFile (const std::vector< TestResult > &results, const std::string &filename) const
void GenerateReport (const std::vector< TestResult > &results) const
virtual void Cleanup ()=0
Private Member Functions
std::string FormatTime (std::chrono::milliseconds duration) const
std::string FormatThroughput (double throughput) const
std::string FormatLatency (double latency) const
Private Attributes
std::string output_directory_ = "."
Detailed Description
性能测试基类，提供通用的测试工具和指标收集功能
Definition at line 14 of file performance_test_base.h.
Constructor & Destructor Documentation
PerformanceTestBase()
sqlcc::test::PerformanceTestBase::PerformanceTestBase () default
构造函数
~PerformanceTestBase()
virtual sqlcc::test::PerformanceTestBase::~PerformanceTestBase () virtual default
析构函数
Member Function Documentation
CalculateDuration()
std::chrono::milliseconds sqlcc::test::PerformanceTestBase::CalculateDuration (const std::chrono::high_resolution_clock::time_point & start, const std::chrono::high_resolution_clock::time_point & end) const protected
计算持续时间（毫秒）
Definition at line 13 of file performance_test_base.cc.
{
    return std::chrono::duration_cast<std::chrono::milliseconds>(end - start);
}
Referenced by sqlcc::test::ConcurrencyPerformanceTest::TestConcurrentReads(), sqlcc::test::ConcurrencyPerformanceTest::TestConcurrentWrites(), sqlcc::test::ConcurrencyPerformanceTest::TestLockContention(), and sqlcc::test::ConcurrencyPerformanceTest::TestMixedReadWrite().
CalculateLatencies()
void sqlcc::test::PerformanceTestBase::CalculateLatencies (const std::vector< double > & latencies, double & avg, double & p95, double & p99) const protected
计算延迟统计信息
Definition at line 24 of file performance_test_base.cc.
{
    if (latencies.empty()) {
        avg = p95 = p99 = 0.0;
        return;
    }
    // 计算平均值
    double sum = 0.0;
    for (double latency : latencies) {
        sum += latency;
    }
    avg = sum / latencies.size();
    // 计算P95和P99分位数
    std::vector<double> sorted_latencies = latencies;
    std::sort(sorted_latencies.begin(), sorted_latencies.end());
    size_t p95_index = static_cast<size_t>(latencies.size() * 0.95);
    size_t p99_index = static_cast<size_t>(latencies.size() * 0.99);
    p95 = sorted_latencies[p95_index];
    p99 = sorted_latencies[p99_index];
}
CalculateThroughput()
double sqlcc::test::PerformanceTestBase::CalculateThroughput (size_t operations, std::chrono::milliseconds duration) const protected
计算吞吐量
Definition at line 19 of file performance_test_base.cc.
{
    if (duration.count() == 0) return 0;
    return static_cast<double>(operations) * 1000.0 / duration.count();
}
Referenced by sqlcc::test::NetworkPerformanceTest::RunAllTests(), sqlcc::test::ConcurrencyPerformanceTest::TestConcurrentReads(), sqlcc::test::ConcurrencyPerformanceTest::TestConcurrentWrites(), sqlcc::test::ConcurrencyPerformanceTest::TestLockContention(), and sqlcc::test::ConcurrencyPerformanceTest::TestMixedReadWrite().
Cleanup()
virtual void sqlcc::test::PerformanceTestBase::Cleanup () protected pure virtual
清理测试环境
Implemented in sqlcc::test::CpuIntensivePerformanceTest, sqlcc::test::LongTermStabilityTest, sqlcc::test::BatchPrefetchPerformanceTest, sqlcc::test::BufferPoolPerformanceTest, sqlcc::test::ConcurrencyPerformanceTest, sqlcc::test::DiskIOPerformanceTest, sqlcc::test::MemoryStressTest, sqlcc::test::MillionInsertTest, sqlcc::test::MixedWorkloadTest, and sqlcc::test::NetworkPerformanceTest.
FormatLatency()
std::string sqlcc::test::PerformanceTestBase::FormatLatency (double latency) const private
格式化延迟
Definition at line 94 of file performance_test_base.cc.
{
    return std::to_string(latency) + " ms";
}
Referenced by PrintResult().
FormatThroughput()
std::string sqlcc::test::PerformanceTestBase::FormatThroughput (double throughput) const private
格式化吞吐量
Definition at line 90 of file performance_test_base.cc.
{
    return std::to_string(throughput) + " ops/sec";
}
Referenced by PrintResult().
FormatTime()
std::string sqlcc::test::PerformanceTestBase::FormatTime (std::chrono::milliseconds duration) const private
格式化时间
Definition at line 86 of file performance_test_base.cc.
{
    return std::to_string(duration.count()) + " ms";
}
Referenced by PrintResult().
GenerateReport()
void sqlcc::test::PerformanceTestBase::GenerateReport (const std::vector< TestResult > & results) const protected
生成测试报告
Definition at line 78 of file performance_test_base.cc.
{
    std::cout << "\n======== Performance Test Report ========\n";
    for (const auto& result : results) {
        PrintResult(result);
    }
    std::cout << "\nReport generated.\n";
}
References PrintResult().
Referenced by sqlcc::test::ConcurrencyPerformanceTest::RunAllTests(), and sqlcc::test::NetworkPerformanceTest::RunAllTests().
GetCurrentTime()
std::chrono::high_resolution_clock::time_point sqlcc::test::PerformanceTestBase::GetCurrentTime () const protected
获取当前时间点
Definition at line 9 of file performance_test_base.cc.
{
    return std::chrono::high_resolution_clock::now();
}
Referenced by sqlcc::test::ConcurrencyPerformanceTest::TestConcurrentReads(), sqlcc::test::ConcurrencyPerformanceTest::TestConcurrentWrites(), sqlcc::test::ConcurrencyPerformanceTest::TestLockContention(), and sqlcc::test::ConcurrencyPerformanceTest::TestMixedReadWrite().
PrintResult()
void sqlcc::test::PerformanceTestBase::PrintResult (const TestResult & result) const protected
打印测试结果
Definition at line 49 of file performance_test_base.cc.
{
    std::cout << "\n==== Test Result: " << result.test_name << " ====\n";
    std::cout << "Duration: " << FormatTime(result.duration) << "\n";
    std::cout << "Operations: " << result.operations_completed << "\n";
    std::cout << "Throughput: " << FormatThroughput(result.throughput) << "\n";
    std::cout << "Average Latency: " << FormatLatency(result.avg_latency) << "\n";
    std::cout << "P95 Latency: " << FormatLatency(result.p95_latency) << "\n";
    std::cout << "P99 Latency: " << FormatLatency(result.p99_latency) << "\n";
    if (!result.custom_metrics.empty()) {
        std::cout << "\nCustom Metrics:\n";
        for (const auto& [key, value] : result.custom_metrics) {
            std::cout << "  " << key << ": " << value << "\n";
        }
    }
    std::cout << "========================================\n";
}
References sqlcc::test::PerformanceTestBase::TestResult::avg_latency, sqlcc::test::PerformanceTestBase::TestResult::custom_metrics, sqlcc::test::PerformanceTestBase::TestResult::duration, FormatLatency(), FormatThroughput(), FormatTime(), sqlcc::test::PerformanceTestBase::TestResult::operations_completed, sqlcc::test::PerformanceTestBase::TestResult::p95_latency, sqlcc::test::PerformanceTestBase::TestResult::p99_latency, sqlcc::test::PerformanceTestBase::TestResult::test_name, and sqlcc::test::PerformanceTestBase::TestResult::throughput.
Referenced by GenerateReport().
RunAllTests()
virtual void sqlcc::test::PerformanceTestBase::RunAllTests () pure virtual
运行所有测试
Implemented in sqlcc::test::CpuIntensivePerformanceTest, sqlcc::test::LongTermStabilityTest, sqlcc::test::BatchPrefetchPerformanceTest, sqlcc::test::BufferPoolPerformanceTest, sqlcc::test::ConcurrencyPerformanceTest, sqlcc::test::DiskIOPerformanceTest, sqlcc::test::IndexConstraintBenchmark, sqlcc::test::LargeScaleIndexConstraintTest, sqlcc::test::MemoryStressTest, sqlcc::test::MillionInsertTest, sqlcc::test::MixedWorkloadTest, and sqlcc::test::NetworkPerformanceTest.
SaveResultsToFile()
void sqlcc::test::PerformanceTestBase::SaveResultsToFile (const std::vector< TestResult > & results, const std::string & filename) const protected
将结果保存到文件
Definition at line 67 of file performance_test_base.cc.
{
    // 简单实现，实际应用中应该使用更健壮的文件IO
    try {
        std::cout << "Saving results to file: " << filename << std::endl;
        // 这里可以添加实际的文件保存逻辑
    } catch (const std::exception& e) {
        std::cerr << "Error saving results to file: " << e.what() << std::endl;
    }
}
SetOutputDirectory()
void sqlcc::test::PerformanceTestBase::SetOutputDirectory (const std::string & directory) inline
设置输出目录
Definition at line 84 of file performance_test_base.h.
{ output_directory_ = directory; }
References output_directory_.
Member Data Documentation
output_directory_
std::string sqlcc::test::PerformanceTestBase::output_directory_ = "." private
输出目录
Definition at line 102 of file performance_test_base.h.
Referenced by SetOutputDirectory().
The documentation for this class was generated from the following files:
tests/performance/performance_test_base.h
tests/performance/performance_test_base.cc