SQLCC: sqlcc::sql_parser::Token Class Reference
sqlcc::sql_parser::Token Class Reference
#include <token.h>
Public Types
enum Type {
BEGIN , COMMIT , ROLLBACK , SAVEPOINT ,
SET , TRANSACTION , CREATE , IDENTIFIER ,
STRING , NUMBER , LPAREN , RPAREN ,
SEMICOLON , END_OF_INPUT , UNKNOWN
}
Public Member Functions
Token ()
Token (Type type, const std::string &lexeme, int line, int column)
Type getType () const
const std::string & getLexeme () const
int getLine () const
int getColumn () const
Private Attributes
Type type_
std::string lexeme_
int line_
int column_
Detailed Description
Definition at line 9 of file token.h.
Member Enumeration Documentation
Type
enum sqlcc::sql_parser::Token::Type
Enumerator
BEGIN
COMMIT
ROLLBACK
SAVEPOINT
SET
TRANSACTION
CREATE
IDENTIFIER
STRING
NUMBER
LPAREN
RPAREN
SEMICOLON
END_OF_INPUT
UNKNOWN
Definition at line 11 of file token.h.
              {
        // 关键字
        BEGIN,
        COMMIT,
        ROLLBACK,
        SAVEPOINT,
        SET,
        TRANSACTION,
        CREATE,
        // 标识符和字面量
        IDENTIFIER,
        STRING,
        NUMBER,
        // 操作符和标点符号
        LPAREN,
        RPAREN,
        SEMICOLON,
        // 特殊标记
        END_OF_INPUT,
        UNKNOWN
    };
Constructor & Destructor Documentation
Token() [1/2]
sqlcc::sql_parser::Token::Token () inline
Definition at line 37 of file token.h.
: type_(END_OF_INPUT), lexeme_(""), line_(0), column_(0) {}
Token() [2/2]
sqlcc::sql_parser::Token::Token (Type type, const std::string & lexeme, int line, int column) inline
Definition at line 39 of file token.h.
        : type_(type), lexeme_(lexeme), line_(line), column_(column) {}
Member Function Documentation
getColumn()
int sqlcc::sql_parser::Token::getColumn () const inline
Definition at line 45 of file token.h.
{ return column_; }
References column_.
getLexeme()
const std::string & sqlcc::sql_parser::Token::getLexeme () const inline
Definition at line 43 of file token.h.
{ return lexeme_; }
References lexeme_.
Referenced by sqlcc::sql_parser::Parser::parseCreate(), sqlcc::sql_parser::Parser::parseStatement(), and TEST_F().
getLine()
int sqlcc::sql_parser::Token::getLine () const inline
Definition at line 44 of file token.h.
{ return line_; }
References line_.
getType()
Type sqlcc::sql_parser::Token::getType () const inline
Definition at line 42 of file token.h.
{ return type_; }
References type_.
Referenced by sqlcc::sql_parser::Parser::match(), sqlcc::sql_parser::Parser::parseSavepoint(), sqlcc::sql_parser::Parser::parseSingleStatement(), sqlcc::sql_parser::Parser::parseStatement(), sqlcc::sql_parser::Parser::parseStatements(), and TEST_F().
Member Data Documentation
column_
int sqlcc::sql_parser::Token::column_ private
Definition at line 51 of file token.h.
Referenced by getColumn().
lexeme_
std::string sqlcc::sql_parser::Token::lexeme_ private
Definition at line 49 of file token.h.
Referenced by getLexeme().
line_
int sqlcc::sql_parser::Token::line_ private
Definition at line 50 of file token.h.
Referenced by getLine().
type_
Type sqlcc::sql_parser::Token::type_ private
Definition at line 48 of file token.h.
Referenced by getType().
The documentation for this class was generated from the following file:
include/sql_parser/token.h