SQLCC: sqlcc::test::performance::IndexPerformanceTest Class Reference
sqlcc::test::performance::IndexPerformanceTest Class Reference
#include <index_performance_test.h>
Public Member Functions
IndexPerformanceTest ()
virtual ~IndexPerformanceTest ()
virtual void SetUp ()
virtual void TearDown ()
virtual void RunTests ()
virtual std::string GetOutputDirectory () const
virtual void CleanOutputDirectory ()
Public Member Functions inherited from sqlcc::test::PerformanceTestBase
PerformanceTestBase ()=default
virtual ~PerformanceTestBase ()=default
virtual void RunAllTests ()=0
void SetOutputDirectory (const std::string &directory)
Private Member Functions
void CreateTestTable ()
bool InsertData (const std::string &key, const std::string &value)
std::string FindData (const std::string &key, bool use_index)
std::vector< std::string > RangeQuery (const std::string &lower, const std::string &upper, bool use_index)
void TestSequentialInserts ()
void TestRandomLookups ()
void TestRangeQueries ()
void TestMixedWorkload ()
void TestIndexSizeGrowth ()
void GenerateReport ()
std::string GetCurrentTimestamp () const
Private Attributes
std::string test_table_name_
std::string db_file_path_
ConfigManager config_manager_
std::unique_ptr< StorageEngine > storage_engine_
IndexManager * index_manager_
std::vector< TestResult > results_
std::unordered_map< std::string, std::string > data_store_
Additional Inherited Members
Protected Member Functions inherited from sqlcc::test::PerformanceTestBase
std::chrono::high_resolution_clock::time_point GetCurrentTime () const
std::chrono::milliseconds CalculateDuration (const std::chrono::high_resolution_clock::time_point &start, const std::chrono::high_resolution_clock::time_point &end) const
double CalculateThroughput (size_t operations, std::chrono::milliseconds duration) const
void CalculateLatencies (const std::vector< double > &latencies, double &avg, double &p95, double &p99) const
void PrintResult (const TestResult &result) const
void SaveResultsToFile (const std::vector< TestResult > &results, const std::string &filename) const
void GenerateReport (const std::vector< TestResult > &results) const
virtual void Cleanup ()=0
Detailed Description
Definition at line 18 of file index_performance_test.h.
Constructor & Destructor Documentation
IndexPerformanceTest()
sqlcc::test::performance::IndexPerformanceTest::IndexPerformanceTest ()
~IndexPerformanceTest()
virtual sqlcc::test::performance::IndexPerformanceTest::~IndexPerformanceTest () virtual
Member Function Documentation
CleanOutputDirectory()
virtual void sqlcc::test::performance::IndexPerformanceTest::CleanOutputDirectory () virtual
Referenced by TearDown().
CreateTestTable()
void sqlcc::test::performance::IndexPerformanceTest::CreateTestTable () private
FindData()
std::string sqlcc::test::performance::IndexPerformanceTest::FindData (const std::string & key, bool use_index) private
GenerateReport()
void sqlcc::test::performance::IndexPerformanceTest::GenerateReport () private
GetCurrentTimestamp()
std::string sqlcc::test::performance::IndexPerformanceTest::GetCurrentTimestamp () const private
GetOutputDirectory()
virtual std::string sqlcc::test::performance::IndexPerformanceTest::GetOutputDirectory () const virtual
Referenced by SetUp().
InsertData()
bool sqlcc::test::performance::IndexPerformanceTest::InsertData (const std::string & key, const std::string & value) private
RangeQuery()
std::vector< std::string > sqlcc::test::performance::IndexPerformanceTest::RangeQuery (const std::string & lower, const std::string & upper, bool use_index) private
RunTests()
virtual void sqlcc::test::performance::IndexPerformanceTest::RunTests () virtual
SetUp()
void sqlcc::test::performance::IndexPerformanceTest::SetUp () virtual
Definition at line 8 of file index_performance_test.cc.
{
    // 初始化测试环境
    // 注意：不使用sql_executor_，因为类中没有定义这个成员变量
    test_table_name_ = "index_test_data";
    db_file_path_ = GetOutputDirectory() + "/index_test.db";
}
References db_file_path_, GetOutputDirectory(), and test_table_name_.
TearDown()
void sqlcc::test::performance::IndexPerformanceTest::TearDown () virtual
Definition at line 15 of file index_performance_test.cc.
{
    // 清理测试数据
    CleanOutputDirectory();
    // 基类中没有TearDown方法，移除调用
}
References CleanOutputDirectory().
TestIndexSizeGrowth()
void sqlcc::test::performance::IndexPerformanceTest::TestIndexSizeGrowth () private
TestMixedWorkload()
void sqlcc::test::performance::IndexPerformanceTest::TestMixedWorkload () private
TestRandomLookups()
void sqlcc::test::performance::IndexPerformanceTest::TestRandomLookups () private
TestRangeQueries()
void sqlcc::test::performance::IndexPerformanceTest::TestRangeQueries () private
TestSequentialInserts()
void sqlcc::test::performance::IndexPerformanceTest::TestSequentialInserts () private
Member Data Documentation
config_manager_
ConfigManager sqlcc::test::performance::IndexPerformanceTest::config_manager_ private
Definition at line 51 of file index_performance_test.h.
data_store_
std::unordered_map<std::string, std::string> sqlcc::test::performance::IndexPerformanceTest::data_store_ private
Definition at line 55 of file index_performance_test.h.
db_file_path_
std::string sqlcc::test::performance::IndexPerformanceTest::db_file_path_ private
Definition at line 50 of file index_performance_test.h.
Referenced by SetUp().
index_manager_
IndexManager* sqlcc::test::performance::IndexPerformanceTest::index_manager_ private
Definition at line 53 of file index_performance_test.h.
results_
std::vector<TestResult> sqlcc::test::performance::IndexPerformanceTest::results_ private
Definition at line 54 of file index_performance_test.h.
storage_engine_
std::unique_ptr<StorageEngine> sqlcc::test::performance::IndexPerformanceTest::storage_engine_ private
Definition at line 52 of file index_performance_test.h.
test_table_name_
std::string sqlcc::test::performance::IndexPerformanceTest::test_table_name_ private
Definition at line 49 of file index_performance_test.h.
Referenced by SetUp().
The documentation for this class was generated from the following files:
tests/performance/index_performance_test.h
tests/performance/index_performance_test.cc