SQLCC: sqlcc::BufferPoolSharded Class Reference
sqlcc::BufferPoolSharded Class Reference
#include <buffer_pool_sharded.h>
Classes
struct PageWrapper
struct Shard
struct Stats
Public Member Functions
BufferPoolSharded (DiskManager *disk_manager, ConfigManager &config_manager, size_t pool_size, size_t num_shards=16)
~BufferPoolSharded ()
Page * FetchPage (int32_t page_id, bool exclusive=false)
bool FlushPage (int32_t page_id)
void FlushAllPages ()
bool DeletePage (int32_t page_id)
bool UnpinPage (int32_t page_id, bool is_dirty)
Page * NewPage (int32_t *page_id)
std::unordered_map< std::string, double > GetStats () const
size_t GetPoolSize () const
size_t GetCurrentPageCount () const
Private Member Functions
size_t GetShardIndex (int32_t page_id) const
int32_t ReplacePage (Shard &shard)
void MoveToHead (Shard &shard, int32_t page_id)
void RemoveFromLRU (Shard &shard, int32_t page_id)
Private Attributes
DiskManager * disk_manager_
ConfigManager & config_manager_
size_t pool_size_
size_t num_shards_
std::vector< std::unique_ptr< Shard > > shards_
struct sqlcc::BufferPoolSharded::Stats stats_
std::unordered_set< int32_t > allocated_pages_
std::mutex allocated_pages_mutex_
std::atomic< int32_t > next_page_id_
Detailed Description
基于RocksDB风格的Sharded Buffer Pool实现 特点：
按2^n分shard，使用page_id哈希取模定位shard
每个shard独立LRU + 独立mutex
支持高并发访问
Definition at line 29 of file buffer_pool_sharded.h.
Constructor & Destructor Documentation
BufferPoolSharded()
sqlcc::BufferPoolSharded::BufferPoolSharded (DiskManager * disk_manager, ConfigManager & config_manager, size_t pool_size, size_t num_shards = 16)
构造函数
Parameters
disk_manager 磁盘管理器实例
config_manager 配置管理器实例
pool_size 缓冲池大小
num_shards shard数量（必须是2的幂）
Definition at line 7 of file buffer_pool_sharded.cpp.
    : disk_manager_(disk_manager), config_manager_(config_manager),
      pool_size_(pool_size), next_page_id_(0) {
  // 确保num_shards是2的幂
  if (num_shards & (num_shards - 1)) {
    // 找到最接近的2的幂
    num_shards_ = 1;
    while (num_shards_ < num_shards) {
      num_shards_ <<= 1;
    }
    SQLCC_LOG_INFO("Adjusting shard count to power of 2: " +
                   std::to_string(num_shards_));
  } else {
    num_shards_ = num_shards;
  }
  // 初始化shards
  size_t shard_size = pool_size_ / num_shards_;
  shards_.resize(num_shards_);
  for (size_t i = 0; i < num_shards_; ++i) {
    shards_[i] = std::make_unique<Shard>(shard_size);
  }
  SQLCC_LOG_INFO("Sharded BufferPool initialized with " +
                 std::to_string(num_shards_) + " shards, each with " +
                 std::to_string(shard_size) + " pages");
}
References num_shards_, pool_size_, shards_, and SQLCC_LOG_INFO.
~BufferPoolSharded()
sqlcc::BufferPoolSharded::~BufferPoolSharded ()
析构函数
Definition at line 37 of file buffer_pool_sharded.cpp.
{
  SQLCC_LOG_INFO("Destroying Sharded BufferPool");
  FlushAllPages();
}
References FlushAllPages(), and SQLCC_LOG_INFO.
Member Function Documentation
DeletePage()
bool sqlcc::BufferPoolSharded::DeletePage (int32_t page_id)
删除页面
Parameters
page_id 页面ID
Returns
是否删除成功
Definition at line 171 of file buffer_pool_sharded.cpp.
{
  size_t shard_idx = GetShardIndex(page_id);
  Shard &shard = *shards_[shard_idx];
  std::lock_guard<std::mutex> lock(shard.mutex);
  auto it = shard.page_table.find(page_id);
  if (it == shard.page_table.end()) {
    return false;
  }
  std::shared_ptr<PageWrapper> page_wrapper = it->second;
  if (page_wrapper->ref_count > 0) {
    return false; // 页面正在被使用
  }
  RemoveFromLRU(shard, page_id);
  shard.page_table.erase(it);
  shard.current_size--;
  // 从已分配页面集合中移除
  {
    std::lock_guard<std::mutex> alloc_lock(allocated_pages_mutex_);
    allocated_pages_.erase(page_id);
  }
  return true;
}
References allocated_pages_, allocated_pages_mutex_, sqlcc::BufferPoolSharded::Shard::current_size, GetShardIndex(), sqlcc::BufferPoolSharded::Shard::mutex, sqlcc::BufferPoolSharded::Shard::page_table, RemoveFromLRU(), and shards_.
FetchPage()
Page * sqlcc::BufferPoolSharded::FetchPage (int32_t page_id, bool exclusive = false)
获取页面
Parameters
page_id 页面ID
exclusive 是否需要独占锁
Returns
页面对象指针，失败时返回nullptr
Definition at line 42 of file buffer_pool_sharded.cpp.
{
  // 避免未使用参数警告
  (void)page_id;
  (void)exclusive;
  // TODO: 实现页面获取逻辑
  return nullptr;
}
FlushAllPages()
void sqlcc::BufferPoolSharded::FlushAllPages ()
刷新所有页面到磁盘
Definition at line 83 of file buffer_pool_sharded.cpp.
{
  for (size_t i = 0; i < num_shards_; ++i) {
    Shard &shard = *shards_[i];
    std::lock_guard<std::mutex> lock(shard.mutex);
    for (const auto &pair : shard.page_table) {
      int32_t page_id = pair.first;
      std::shared_ptr<PageWrapper> page_wrapper = pair.second;
      if (page_wrapper->is_dirty) {
        // 释放锁，执行磁盘I/O
        lock.~lock_guard();
        disk_manager_->WritePage(
            page_id, static_cast<char *>(page_wrapper->page->GetData()));
        // 重新获取锁
        std::lock_guard<std::mutex> lock2(shard.mutex);
        page_wrapper->is_dirty = false;
      }
    }
  }
}
References disk_manager_, sqlcc::BufferPoolSharded::Shard::mutex, num_shards_, sqlcc::BufferPoolSharded::Shard::page_table, shards_, and sqlcc::DiskManager::WritePage().
Referenced by ~BufferPoolSharded().
FlushPage()
bool sqlcc::BufferPoolSharded::FlushPage (int32_t page_id)
刷新页面到磁盘
Parameters
page_id 页面ID
Returns
是否刷新成功
Definition at line 51 of file buffer_pool_sharded.cpp.
{
  size_t shard_idx = GetShardIndex(page_id);
  Shard &shard = *shards_[shard_idx];
  std::lock_guard<std::mutex> lock(shard.mutex);
  auto it = shard.page_table.find(page_id);
  if (it == shard.page_table.end()) {
    return false;
  }
  std::shared_ptr<PageWrapper> page_wrapper = it->second;
  if (!page_wrapper->is_dirty) {
    return true;
  }
  // 释放锁，执行磁盘I/O
  lock.~lock_guard();
  bool write_success = disk_manager_->WritePage(
      page_id, static_cast<char *>(page_wrapper->page->GetData()));
  // 重新获取锁
  std::lock_guard<std::mutex> lock2(shard.mutex);
  if (write_success) {
    page_wrapper->is_dirty = false;
  }
  return write_success;
}
References disk_manager_, GetShardIndex(), sqlcc::BufferPoolSharded::Shard::mutex, sqlcc::BufferPoolSharded::Shard::page_table, shards_, and sqlcc::DiskManager::WritePage().
GetCurrentPageCount()
size_t sqlcc::BufferPoolSharded::GetCurrentPageCount () const
获取当前页面数量
Returns
当前页面数量
Definition at line 259 of file buffer_pool_sharded.cpp.
{
  size_t total_count = 0;
  (void)total_count; // 避免未使用变量警告
  return 0;
}
Referenced by GetStats().
GetPoolSize()
size_t sqlcc::BufferPoolSharded::GetPoolSize () const inline
获取缓冲池大小
Returns
缓冲池大小
Definition at line 98 of file buffer_pool_sharded.h.
{ return pool_size_; }
References pool_size_.
GetShardIndex()
size_t sqlcc::BufferPoolSharded::GetShardIndex (int32_t page_id) const inline private
Definition at line 136 of file buffer_pool_sharded.h.
{
        // 使用哈希分片，确保是2的幂时快速取模
        return (static_cast<size_t>(page_id) & (num_shards_ - 1));
    }
References num_shards_.
Referenced by DeletePage(), FlushPage(), NewPage(), and UnpinPage().
GetStats()
std::unordered_map< std::string, double > sqlcc::BufferPoolSharded::GetStats () const
获取缓冲池统计信息
Returns
统计信息哈希表
Definition at line 265 of file buffer_pool_sharded.cpp.
{
  std::unordered_map<std::string, double> stats;
  stats["total_accesses"] = static_cast<double>(stats_.total_accesses);
  stats["total_hits"] = static_cast<double>(stats_.total_hits);
  stats["total_misses"] = static_cast<double>(stats_.total_misses);
  stats["total_evictions"] = static_cast<double>(stats_.total_evictions);
  if (stats_.total_accesses > 0) {
    stats["hit_rate"] =
        static_cast<double>(stats_.total_hits) / stats_.total_accesses;
  } else {
    stats["hit_rate"] = 0.0;
  }
  stats["current_page_count"] = GetCurrentPageCount();
  stats["pool_size"] = static_cast<double>(pool_size_);
  stats["num_shards"] = static_cast<double>(num_shards_);
  return stats;
}
References GetCurrentPageCount(), num_shards_, pool_size_, stats_, sqlcc::BufferPoolSharded::Stats::total_accesses, sqlcc::BufferPoolSharded::Stats::total_evictions, sqlcc::BufferPoolSharded::Stats::total_hits, and sqlcc::BufferPoolSharded::Stats::total_misses.
MoveToHead()
void sqlcc::BufferPoolSharded::MoveToHead (Shard & shard, int32_t page_id) private
Definition at line 236 of file buffer_pool_sharded.cpp.
{
  auto map_it = shard.lru_map.find(page_id);
  if (map_it != shard.lru_map.end()) {
    shard.lru_list.erase(map_it->second);
  }
  shard.lru_list.push_front(page_id);
  shard.lru_map[page_id] = shard.lru_list.begin();
}
References sqlcc::BufferPoolSharded::Shard::lru_list, and sqlcc::BufferPoolSharded::Shard::lru_map.
NewPage()
Page * sqlcc::BufferPoolSharded::NewPage (int32_t * page_id)
创建新页面
Parameters
page_id 输出参数，页面ID
Returns
页面对象指针，失败时返回nullptr
Definition at line 128 of file buffer_pool_sharded.cpp.
{
  // 分配新的页面ID
  int32_t new_page_id = next_page_id_++;
  // 获取对应的shard
  size_t shard_idx = GetShardIndex(new_page_id);
  Shard &shard = *shards_[shard_idx];
  std::lock_guard<std::mutex> lock(shard.mutex);
  // 如果shard已满，需要替换页面
  if (shard.current_size >= shard.max_size) {
    int32_t replaced_page_id = ReplacePage(shard);
    if (replaced_page_id == -1) {
      SQLCC_LOG_ERROR("Failed to replace page for new page creation");
      return nullptr;
    }
  }
  // 创建新页面
  auto page = std::make_unique<Page>(new_page_id);
  Page *page_ptr = page.release();
  auto page_wrapper = std::make_shared<PageWrapper>(page_ptr);
  page_wrapper->ref_count = 1;
  page_wrapper->is_dirty = false;
  shard.page_table[new_page_id] = page_wrapper;
  shard.lru_list.push_front(new_page_id);
  shard.lru_map[new_page_id] = shard.lru_list.begin();
  page_wrapper->is_in_lru = true;
  shard.current_size++;
  // 记录已分配的页面
  {
    std::lock_guard<std::mutex> alloc_lock(allocated_pages_mutex_);
    allocated_pages_.insert(new_page_id);
  }
  *page_id = new_page_id;
  return page_ptr;
}
References allocated_pages_, allocated_pages_mutex_, sqlcc::BufferPoolSharded::Shard::current_size, GetShardIndex(), sqlcc::BufferPoolSharded::Shard::lru_list, sqlcc::BufferPoolSharded::Shard::lru_map, sqlcc::BufferPoolSharded::Shard::max_size, sqlcc::BufferPoolSharded::Shard::mutex, next_page_id_, sqlcc::BufferPoolSharded::Shard::page_table, ReplacePage(), shards_, and SQLCC_LOG_ERROR.
RemoveFromLRU()
void sqlcc::BufferPoolSharded::RemoveFromLRU (Shard & shard, int32_t page_id) private
Definition at line 246 of file buffer_pool_sharded.cpp.
{
  auto map_it = shard.lru_map.find(page_id);
  if (map_it != shard.lru_map.end()) {
    shard.lru_list.erase(map_it->second);
    shard.lru_map.erase(map_it);
  }
  auto page_it = shard.page_table.find(page_id);
  if (page_it != shard.page_table.end()) {
    page_it->second->is_in_lru = false;
  }
}
References sqlcc::BufferPoolSharded::Shard::lru_list, sqlcc::BufferPoolSharded::Shard::lru_map, and sqlcc::BufferPoolSharded::Shard::page_table.
Referenced by DeletePage(), and ReplacePage().
ReplacePage()
int32_t sqlcc::BufferPoolSharded::ReplacePage (Shard & shard) private
Definition at line 200 of file buffer_pool_sharded.cpp.
{
  for (auto it = shard.lru_list.rbegin(); it != shard.lru_list.rend(); ++it) {
    int32_t page_id = *it;
    auto page_it = shard.page_table.find(page_id);
    if (page_it != shard.page_table.end()) {
      std::shared_ptr<PageWrapper> page_wrapper = page_it->second;
      if (page_wrapper->ref_count == 0) {
        // 释放锁，执行磁盘I/O（如果需要）
        std::unique_lock<std::mutex> lock(shard.mutex, std::adopt_lock);
        lock.unlock();
        if (page_wrapper->is_dirty) {
          disk_manager_->WritePage(
              page_id, static_cast<char *>(page_wrapper->page->GetData()));
        }
        // 重新获取锁
        lock.lock();
        // 再次检查，避免在释放锁期间状态改变
        if (page_wrapper->ref_count == 0) {
          RemoveFromLRU(shard, page_id);
          shard.page_table.erase(page_it);
          shard.current_size--;
          stats_.total_evictions++;
          return page_id;
        }
      }
    }
  }
  return -1; // 无法找到可替换的页面
}
References sqlcc::BufferPoolSharded::Shard::current_size, disk_manager_, sqlcc::BufferPoolSharded::Shard::lru_list, sqlcc::BufferPoolSharded::Shard::mutex, sqlcc::BufferPoolSharded::Shard::page_table, RemoveFromLRU(), stats_, sqlcc::BufferPoolSharded::Stats::total_evictions, and sqlcc::DiskManager::WritePage().
Referenced by NewPage().
UnpinPage()
bool sqlcc::BufferPoolSharded::UnpinPage (int32_t page_id, bool is_dirty)
解除页面固定
Parameters
page_id 页面ID
is_dirty 是否为脏页
Returns
是否解除成功
Definition at line 105 of file buffer_pool_sharded.cpp.
{
  size_t shard_idx = GetShardIndex(page_id);
  Shard &shard = *shards_[shard_idx];
  std::lock_guard<std::mutex> lock(shard.mutex);
  auto it = shard.page_table.find(page_id);
  if (it == shard.page_table.end()) {
    return false;
  }
  std::shared_ptr<PageWrapper> page_wrapper = it->second;
  if (page_wrapper->ref_count > 0) {
    page_wrapper->ref_count--;
  }
  if (is_dirty) {
    page_wrapper->is_dirty = true;
  }
  return true;
}
References GetShardIndex(), sqlcc::BufferPoolSharded::Shard::mutex, sqlcc::BufferPoolSharded::Shard::page_table, and shards_.
Member Data Documentation
allocated_pages_
std::unordered_set<int32_t> sqlcc::BufferPoolSharded::allocated_pages_ private
Definition at line 174 of file buffer_pool_sharded.h.
Referenced by DeletePage(), and NewPage().
allocated_pages_mutex_
std::mutex sqlcc::BufferPoolSharded::allocated_pages_mutex_ mutable private
Definition at line 175 of file buffer_pool_sharded.h.
Referenced by DeletePage(), and NewPage().
config_manager_
ConfigManager& sqlcc::BufferPoolSharded::config_manager_ private
Definition at line 154 of file buffer_pool_sharded.h.
disk_manager_
DiskManager* sqlcc::BufferPoolSharded::disk_manager_ private
Definition at line 151 of file buffer_pool_sharded.h.
Referenced by FlushAllPages(), FlushPage(), and ReplacePage().
next_page_id_
std::atomic<int32_t> sqlcc::BufferPoolSharded::next_page_id_ private
Definition at line 178 of file buffer_pool_sharded.h.
Referenced by NewPage().
num_shards_
size_t sqlcc::BufferPoolSharded::num_shards_ private
Definition at line 160 of file buffer_pool_sharded.h.
Referenced by BufferPoolSharded(), FlushAllPages(), GetShardIndex(), and GetStats().
pool_size_
size_t sqlcc::BufferPoolSharded::pool_size_ private
Definition at line 157 of file buffer_pool_sharded.h.
Referenced by BufferPoolSharded(), GetPoolSize(), and GetStats().
shards_
std::vector<std::unique_ptr<Shard> > sqlcc::BufferPoolSharded::shards_ private
Definition at line 163 of file buffer_pool_sharded.h.
Referenced by BufferPoolSharded(), DeletePage(), FlushAllPages(), FlushPage(), NewPage(), and UnpinPage().
stats_
struct sqlcc::BufferPoolSharded::Stats sqlcc::BufferPoolSharded::stats_ private
Referenced by GetStats(), and ReplacePage().
The documentation for this class was generated from the following files:
include/buffer_pool_sharded.h
src/storage_engine/buffer_pool_sharded.cpp