SQLCC: sqlcc::network::SessionManager Class Reference
sqlcc::network::SessionManager Class Reference
#include <network.h>
Public Member Functions
SessionManager ()
std::shared_ptr< Session > CreateSession ()
std::shared_ptr< Session > GetSession (int session_id)
void DestroySession (int session_id)
bool Authenticate (int session_id, const std::string &username, const std::string &password)
bool CheckPermission (int session_id, const std::string &database, const std::string &operation)
Private Attributes
std::unordered_map< int, std::weak_ptr< Session > > sessions_
std::mutex sessions_mutex_
int next_session_id_
Detailed Description
Definition at line 74 of file network.h.
Constructor & Destructor Documentation
SessionManager()
sqlcc::network::SessionManager::SessionManager ()
Definition at line 48 of file network.cpp.
: next_session_id_(1) {}
Member Function Documentation
Authenticate()
bool sqlcc::network::SessionManager::Authenticate (int session_id, const std::string & username, const std::string & password)
Definition at line 72 of file network.cpp.
{
    // 简单的身份验证逻辑
    if (username == "admin" && password == "password") {
        auto session = GetSession(session_id);
        if (session) {
            session->SetAuthenticated(username);
            return true;
        }
    }
    return false;
}
References GetSession().
CheckPermission()
bool sqlcc::network::SessionManager::CheckPermission (int session_id, const std::string & database, const std::string & operation)
Definition at line 85 of file network.cpp.
{
    auto session = GetSession(session_id);
    if (!session || !session->IsAuthenticated()) {
        return false;
    }
    // 简单的权限检查逻辑
    return true;
}
References GetSession().
CreateSession()
std::shared_ptr< Session > sqlcc::network::SessionManager::CreateSession ()
Definition at line 50 of file network.cpp.
{
    std::lock_guard<std::mutex> lock(sessions_mutex_);
    int session_id = next_session_id_++;
    auto session = std::make_shared<Session>(session_id);
    sessions_[session_id] = session;
    return session;
}
References next_session_id_, sessions_, and sessions_mutex_.
DestroySession()
void sqlcc::network::SessionManager::DestroySession (int session_id)
Definition at line 67 of file network.cpp.
{
    std::lock_guard<std::mutex> lock(sessions_mutex_);
    sessions_.erase(session_id);
}
References sessions_, and sessions_mutex_.
GetSession()
std::shared_ptr< Session > sqlcc::network::SessionManager::GetSession (int session_id)
Definition at line 58 of file network.cpp.
{
    std::lock_guard<std::mutex> lock(sessions_mutex_);
    auto it = sessions_.find(session_id);
    if (it != sessions_.end()) {
        return it->second.lock();
    }
    return nullptr;
}
References sessions_, and sessions_mutex_.
Referenced by Authenticate(), and CheckPermission().
Member Data Documentation
next_session_id_
int sqlcc::network::SessionManager::next_session_id_ private
Definition at line 89 of file network.h.
Referenced by CreateSession().
sessions_
std::unordered_map<int, std::weak_ptr<Session> > sqlcc::network::SessionManager::sessions_ private
Definition at line 87 of file network.h.
Referenced by CreateSession(), DestroySession(), and GetSession().
sessions_mutex_
std::mutex sqlcc::network::SessionManager::sessions_mutex_ private
Definition at line 88 of file network.h.
Referenced by CreateSession(), DestroySession(), and GetSession().
The documentation for this class was generated from the following files:
include/network/network.h
src/network/network.cpp