SQLCC: src/isql_main.cc File Reference
isql_main.cc File Reference
交互式SQL命令行工具主程序
#include <iostream>
#include <string>
#include <memory>
#include <csignal>
#include "version.h"
#include "config_manager.h"
#include "storage_engine.h"
#include "sql_executor.h"
#include "exception.h"
Functions
void signalHandler (int signal)
信号处理函数，处理Ctrl+C信号
void showHelp ()
显示帮助信息
void showVersion ()
显示版本信息
bool handleInteractiveCommand (const std::string &cmd, SqlExecutor &executor)
处理交互式命令
bool executeScript (const std::string &file_path, SqlExecutor &executor)
执行SQL脚本文件
int main (int argc, char *argv[])
主函数
Variables
volatile sig_atomic_t g_running = 1
Detailed Description
交互式SQL命令行工具主程序
Why: 需要一个交互式命令行工具来执行SQL语句和脚本 What: isql工具支持交互式执行SQL命令，以及通过-f参数执行SQL脚本 How: 解析命令行参数，创建存储引擎和SQL执行器，实现交互循环
Definition in file isql_main.cc.
Function Documentation
executeScript()
bool executeScript (const std::string & file_path, SqlExecutor & executor)
执行SQL脚本文件
Parameters
file_path 文件路径
executor SQL执行器引用
Returns
执行是否成功
Definition at line 132 of file isql_main.cc.
{
    try {
        std::cout << "Executing script from file: " << file_path << std::endl;
        std::string result = executor.ExecuteFile(file_path);
        std::cout << result << std::endl;
        return true;
    } catch (const std::exception& e) {
        std::cerr << "Error executing script: " << e.what() << std::endl;
        return false;
    }
}
References sqlcc::SqlExecutor::ExecuteFile().
Referenced by main().
handleInteractiveCommand()
bool handleInteractiveCommand (const std::string & cmd, SqlExecutor & executor)
处理交互式命令
Parameters
cmd 命令字符串
executor SQL执行器引用
Returns
是否应该退出程序
Definition at line 88 of file isql_main.cc.
{
    if (cmd == "exit" || cmd == "quit" || cmd == ".exit" || cmd == ".quit") {
        std::cout << "Goodbye!" << std::endl;
        return true;
    }
    if (cmd == "help" || cmd == ".help") {
        showHelp();
        return false;
    }
    if (cmd == ".schema" || cmd == "show tables" || cmd == ".show tables") {
        std::string result = executor.ListTables();
        std::cout << result << std::endl;
        return false;
    }
    // 处理DESCRIBE TABLE命令
    if (cmd.substr(0, 8) == "describe" || cmd.substr(0, 4) == ".desc" || cmd.substr(0, 7) == "show create table") {
        std::string table_name;
        size_t pos = cmd.find_last_of(' ');
        if (pos != std::string::npos) {
            table_name = cmd.substr(pos + 1);
            // 移除可能的引号
            if (!table_name.empty() && (table_name[0] == '\'' || table_name[0] == '"')) {
                table_name = table_name.substr(1, table_name.length() - 2);
            }
            std::string result = executor.ShowTableSchema(table_name);
            std::cout << result << std::endl;
        } else {
            std::cout << "Error: Table name required" << std::endl;
        }
        return false;
    }
    return false;
}
References sqlcc::SqlExecutor::ListTables(), showHelp(), and sqlcc::SqlExecutor::ShowTableSchema().
Referenced by main().
main()
int main (int argc, char * argv[])
主函数
Definition at line 147 of file isql_main.cc.
{
    // 注册信号处理函数
    std::signal(SIGINT, signalHandler);
    // 解析命令行参数
    std::string script_file;
    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "-h" || arg == "--help") {
            showHelp();
            return 0;
        } else if (arg == "-v" || arg == "--version") {
            showVersion();
            return 0;
        } else if (arg == "-f" && i + 1 < argc) {
            script_file = argv[++i];
        } else {
            std::cerr << "Unknown option: " << arg << std::endl;
            showHelp();
            return 1;
        }
    }
    try {
        // 创建SQL执行器（简化模式）
        // 不依赖配置文件和存储引擎，专注于SQL解析和命令行交互
        SqlExecutor executor;
        // 如果指定了脚本文件，则执行脚本
        if (!script_file.empty()) {
            return executeScript(script_file, executor) ? 0 : 1;
        }
        // 设置readline配置（如果可用）
#ifdef USE_READLINE
        rl_bind_key("\t", rl_complete);
        using_history();
#endif
        // 显示欢迎信息
        std::cout << "Welcome to isql (SqlCC " << SQLCC_VERSION << ")" << std::endl;
        std::cout << "Type 'help' for help, 'exit' or 'quit' to exit." << std::endl;
        std::cout << std::endl;
        // 交互式命令循环
        std::string prompt = "sqlcc> ";
        std::string current_sql;
        while (g_running) {
            std::string input;
            // 显示提示符
            std::cout << prompt;
            std::cout.flush();
            // 读取输入
            #ifdef USE_READLINE
            char* line = readline("");
            // 如果用户按下Ctrl+D，退出程序
            if (line == nullptr) {
                std::cout << "\nGoodbye!" << std::endl;
                break;
            }
            input = line;
            free(line);
            // 保存到历史记录
            if (!input.empty()) {
                add_history(input.c_str());
            }
            #else
            // 使用标准输入
            if (!std::getline(std::cin, input)) {
                // 处理EOF或错误
                std::cout << "\nGoodbye!" << std::endl;
                break;
            }
            #endif
            // 检查是否是交互式命令（以.开头或特殊命令）
            if (!input.empty() && (input[0] == '.' || input == "exit" || input == "quit" || input == "help")) {
                if (handleInteractiveCommand(input, executor)) {
                    break;
                }
                continue;
            }
            // 处理SQL语句
            current_sql += input;
            // 检查语句是否结束（以分号结尾）
            if (current_sql.find_last_of(';') != std::string::npos) {
                // 执行SQL语句
                std::string result = executor.Execute(current_sql);
                std::cout << result << std::endl;
                // 重置当前SQL语句
                current_sql.clear();
            } else {
                // SQL语句未结束，继续输入
                prompt = "...> ";
                continue;
            }
            // 重置提示符
            prompt = "sqlcc> ";
        }
        // 清理资源
        // 在模拟模式下，不需要清理存储引擎资源
    } catch (const std::exception& e) {
        std::cerr << "Error: " << e.what() << std::endl;
        return 1;
    }
    return 0;
}
References sqlcc::SqlExecutor::Execute(), executeScript(), g_running, handleInteractiveCommand(), showHelp(), showVersion(), signalHandler(), and SQLCC_VERSION.
showHelp()
void showHelp ()
显示帮助信息
Definition at line 52 of file isql_main.cc.
                {
    std::cout << "Usage: isql [options]" << std::endl;
    std::cout << "Options:" << std::endl;
    std::cout << "  -f <file>   Execute SQL script from file" << std::endl;
    std::cout << "  -h, --help  Show this help message" << std::endl;
    std::cout << "  -v, --version  Show version information" << std::endl;
    std::cout << std::endl;
    std::cout << "Interactive commands:" << std::endl;
    std::cout << "  exit, quit  Exit the program" << std::endl;
    std::cout << "  help        Show this help message" << std::endl;
    std::cout << "  show tables, .schema  Show all tables" << std::endl;
    std::cout << "  describe <table>, .desc <table>  Show table structure" << std::endl;
    std::cout << "  show create table <table>  Show CREATE TABLE statement" << std::endl;
    std::cout << "  .exit, .quit  Exit the program" << std::endl;
    std::cout << std::endl;
    std::cout << "Supported SQL commands:" << std::endl;
    std::cout << "  CREATE DATABASE, CREATE TABLE" << std::endl;
    std::cout << "  USE database" << std::endl;
    std::cout << "  INSERT INTO, SELECT, UPDATE, DELETE" << std::endl;
    std::cout << "  ALTER TABLE, DROP TABLE, DROP DATABASE" << std::endl;
}
Referenced by handleInteractiveCommand(), and main().
showVersion()
void showVersion ()
显示版本信息
Definition at line 77 of file isql_main.cc.
                   {
    std::cout << "isql (SqlCC) " << SQLCC_VERSION << std::endl;
    std::cout << "Interactive SQL command-line utility" << std::endl;
}
References SQLCC_VERSION.
Referenced by main().
signalHandler()
void signalHandler (int signal)
信号处理函数，处理Ctrl+C信号
Definition at line 36 of file isql_main.cc.
{
    if (signal == SIGINT) {
        std::cout << "\nInterrupted by user. Type 'exit' or 'quit' to exit." << std::endl;
        // 重置readline的输入行（如果可用）
#ifdef USE_READLINE
        rl_replace_line("", 0);
        rl_on_new_line();
        rl_redisplay();
#endif
        g_running = true; // 确保程序继续运行
    }
}
References g_running.
Referenced by main().
Variable Documentation
g_running
volatile sig_atomic_t g_running = 1
Definition at line 31 of file isql_main.cc.
Referenced by main(), and signalHandler().