SQLCC: tests/storage_engine_test.cc File Reference
storage_engine_test.cc File Reference
#include <gtest/gtest.h>
#include "storage_engine.h"
#include "exception.h"
#include <filesystem>
#include <cstdio>
Classes
class StorageEngineTest
Functions
TEST_F (StorageEngineTest, InitializeStorageEngine)
TEST_F (StorageEngineTest, CreateNewPage)
TEST_F (StorageEngineTest, FetchPage)
TEST_F (StorageEngineTest, FlushPage)
TEST_F (StorageEngineTest, DeletePage)
TEST_F (StorageEngineTest, FlushAllPages)
TEST_F (StorageEngineTest, ManyPagesOperation)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 165 of file storage_engine_test.cc.
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
TEST_F() [1/7]
TEST_F (StorageEngineTest , CreateNewPage)
Definition at line 33 of file storage_engine_test.cc.
{
    sqlcc::StorageEngine engine(TEST_DB_FILE);
    int32_t page_id;
    sqlcc::Page* page = engine.NewPage(&page_id);
    EXPECT_NE(page, nullptr);
    EXPECT_GE(page_id, 0);
    EXPECT_EQ(page->GetPageId(), page_id);
}
References sqlcc::Page::GetPageId(), and sqlcc::StorageEngine::NewPage().
TEST_F() [2/7]
TEST_F (StorageEngineTest , DeletePage)
Definition at line 83 of file storage_engine_test.cc.
{
    sqlcc::StorageEngine engine(TEST_DB_FILE);
    int32_t page_id;
    // 创建新页面
    sqlcc::Page* page = engine.NewPage(&page_id);
    ASSERT_NE(page, nullptr);
    // 取消固定页面并标记为脏页，确保页面被刷新到磁盘
    EXPECT_TRUE(engine.UnpinPage(page_id, true));
    // 删除页面
    EXPECT_TRUE(engine.DeletePage(page_id));
    // 尝试获取已删除的页面应该失败
    sqlcc::Page* fetched_page = engine.FetchPage(page_id);
    EXPECT_EQ(fetched_page, nullptr);
}
References sqlcc::StorageEngine::DeletePage(), sqlcc::StorageEngine::FetchPage(), sqlcc::StorageEngine::NewPage(), and sqlcc::StorageEngine::UnpinPage().
TEST_F() [3/7]
TEST_F (StorageEngineTest , FetchPage)
Definition at line 45 of file storage_engine_test.cc.
{
    sqlcc::StorageEngine engine(TEST_DB_FILE);
    int32_t page_id;
    // 创建新页面
    sqlcc::Page* page1 = engine.NewPage(&page_id);
    ASSERT_NE(page1, nullptr);
    // 取消固定页面
    EXPECT_TRUE(engine.UnpinPage(page_id, false));
    // 获取页面
    sqlcc::Page* page2 = engine.FetchPage(page_id);
    EXPECT_NE(page2, nullptr);
    EXPECT_EQ(page2->GetPageId(), page_id);
}
References sqlcc::StorageEngine::FetchPage(), sqlcc::Page::GetPageId(), sqlcc::StorageEngine::NewPage(), and sqlcc::StorageEngine::UnpinPage().
TEST_F() [4/7]
TEST_F (StorageEngineTest , FlushAllPages)
Definition at line 103 of file storage_engine_test.cc.
{
    sqlcc::StorageEngine engine(TEST_DB_FILE);
    const int NUM_PAGES = 5;
    int32_t page_ids[NUM_PAGES];
    // 创建多个页面
    for (int i = 0; i < NUM_PAGES; ++i) {
        sqlcc::Page* page = engine.NewPage(&page_ids[i]);
        ASSERT_NE(page, nullptr);
        // 修改页面数据
        char test_data[100];
        snprintf(test_data, sizeof(test_data), "Test data for page %d", i);
        page->WriteData(0, test_data, strlen(test_data) + 1);
        // 取消固定页面并标记为脏页
        EXPECT_TRUE(engine.UnpinPage(page_ids[i], true));
    }
    // 刷新所有页面
    EXPECT_NO_THROW({
        engine.FlushAllPages();
    });
}
References sqlcc::StorageEngine::FlushAllPages(), sqlcc::StorageEngine::NewPage(), sqlcc::StorageEngine::UnpinPage(), and sqlcc::Page::WriteData().
TEST_F() [5/7]
TEST_F (StorageEngineTest , FlushPage)
Definition at line 63 of file storage_engine_test.cc.
{
    sqlcc::StorageEngine engine(TEST_DB_FILE);
    int32_t page_id;
    // 创建新页面
    sqlcc::Page* page = engine.NewPage(&page_id);
    ASSERT_NE(page, nullptr);
    // 修改页面数据
    char test_data[] = "Test data for flushing";
    page->WriteData(0, test_data, sizeof(test_data));
    // 取消固定页面并标记为脏页
    EXPECT_TRUE(engine.UnpinPage(page_id, true));
    // 刷新页面
    EXPECT_TRUE(engine.FlushPage(page_id));
}
References sqlcc::StorageEngine::FlushPage(), sqlcc::StorageEngine::NewPage(), sqlcc::StorageEngine::UnpinPage(), and sqlcc::Page::WriteData().
TEST_F() [6/7]
TEST_F (StorageEngineTest , InitializeStorageEngine)
Definition at line 23 of file storage_engine_test.cc.
{
    EXPECT_NO_THROW({
        sqlcc::StorageEngine engine(TEST_DB_FILE);
    });
    // 检查数据库文件是否创建
    EXPECT_TRUE(std::filesystem::exists(TEST_DB_FILE));
}
TEST_F() [7/7]
TEST_F (StorageEngineTest , ManyPagesOperation)
Definition at line 129 of file storage_engine_test.cc.
{
    sqlcc::StorageEngine engine(TEST_DB_FILE);
    const int NUM_PAGES = 100;
    std::vector<int32_t> page_ids;
    // 创建大量页面
    for (int i = 0; i < NUM_PAGES; ++i) {
        int32_t page_id;
        sqlcc::Page* page = engine.NewPage(&page_id);
        ASSERT_NE(page, nullptr);
        page_ids.push_back(page_id);
        // 写入一些数据
        page->WriteData(0, reinterpret_cast<const char*>(&i), sizeof(i));
        // 取消固定页面
        EXPECT_TRUE(engine.UnpinPage(page_id, i % 2 == 0)); // 偶数页标记为脏页
    }
    // 随机获取一些页面并验证数据
    for (int i = 0; i < 10; ++i) {
        int idx = rand() % NUM_PAGES;
        int32_t page_id = page_ids[idx];
        sqlcc::Page* page = engine.FetchPage(page_id);
        ASSERT_NE(page, nullptr);
        int stored_value;
        page->ReadData(0, reinterpret_cast<char*>(&stored_value), sizeof(stored_value));
        EXPECT_EQ(stored_value, idx);
        // 取消固定页面
        EXPECT_TRUE(engine.UnpinPage(page_id, false));
    }
}
References sqlcc::StorageEngine::FetchPage(), sqlcc::StorageEngine::NewPage(), sqlcc::Page::ReadData(), sqlcc::StorageEngine::UnpinPage(), and sqlcc::Page::WriteData().