package(default_visibility = ["//visibility:public"])

cc_test(
    name = "wal_fast",
    srcs = ["wal_test.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//src/storage_engine:storage_engine",
    ],
)

cc_test(
    name = "wal_tests",
    srcs = glob([
        "*.cpp",
        "**/*.cpp",
    ]),
    deps = [
        "@com_google_googletest//:gtest_main",
        "//src/storage_engine:storage_engine",
    ],
)

test_suite(
    name = "all",
    tests = [":wal_fast"],
)
