cc_test(
    name = "multi_threaded_network_manager_test",
    srcs = ["multi_threaded_network_manager_test.cpp"],
    deps = [
        "//include/network:multi_threaded_network_manager",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "network_boundary_test",
    srcs = ["network_boundary_test.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//include/network:network",
        "//src/core:sqlcc_database_core",
        "//src/sql_executor:sqlcc_executor",
    ],
)
