load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "client_server_integration_test",
    srcs = ["client_server_integration_test.cpp"],
    deps = [
        "//src/core:core",
        "//src/network:network",
        "//src/execution:execution",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
    tags = ["level7", "integration", "core"],
)

cc_test(
    name = "encrypted_integration_test",
    srcs = ["encrypted_integration_test.cpp"],
    deps = [
        "//src/core:core",
        "//src/network:network",
        "//src/execution:execution",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
    tags = ["level7", "integration", "core", "encrypted"],
)
