load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "transaction",
    srcs = [
        "transaction.cpp",
        "transaction.h",
    ],
    copts = [
        "-std=c++20",
        "-g",
        "-Wall",
        "-Wextra",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "transaction_context",
    hdrs = ["transaction_context.h"],
    copts = [
        "-std=c++20",
        "-g",
        "-Wall",
        "-Wextra",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "transaction_context_impl",
    srcs = ["transaction_context_impl.cpp", "transaction_context_impl.h"],
    hdrs = ["transaction_context.h"],
    copts = [
        "-std=c++20",
        "-g",
        "-Wall",
        "-Wextra",
    ],
    deps = [
        ":transaction",
        "//src/transaction_manager:transaction_manager",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "savepoint_manager",
    srcs = ["savepoint_manager.cpp"],
    hdrs = ["savepoint_manager.h"],
    copts = [
        "-std=c++20",
        "-g",
        "-Wall",
        "-Wextra",
    ],
    deps = [
    ],
    visibility = ["//visibility:public"],
)