cc_test(
    name = "utils_test",
    srcs = ["utils_test.cpp"],
    copts = [
        "-fprofile-instr-generate",
        "-fcoverage-mapping",
    ],
    linkopts = ["-fprofile-instr-generate"],
    deps = [
        "//src/utils:utils",
        "//src/logger:logger",
        "//src/core:core",
        "@com_google_googletest//:gtest_main",
        "@com_google_googletest//:gtest",
    ],
    tags = ["coverage", "level1"],
)
