cc_library(
    name = "bptree_node",
    srcs = [
        "b_plus_tree_node.cpp",
        "b_plus_tree_internal_node.cpp",
        "b_plus_tree_leaf_node.cpp",
    ],
    hdrs = [
        "b_plus_tree_node.h",
        "b_plus_tree_internal_node.h",
        "b_plus_tree_leaf_node.h",
        "b_plus_tree_nodes.h",
    ],
    deps = [
        "//src/storage_engine/buffer_pool:buffer_pool",
        "//include:storage_engine",

        "//include:exception",
        "//include/utils:utils",
        "//include:page",
    ],
    visibility = ["//visibility:public"],
)
