package(default_visibility = ["//visibility:public"])

cc_library(
    name = "connection_state",
    hdrs = ["connection_state.h"],
)

cc_library(
    name = "encryption",
    hdrs = ["encryption.h"],
)

cc_library(
    name = "multi_threaded_network_manager",
    hdrs = ["multi_threaded_network_manager.h"],
)

cc_library(
    name = "mysql_protocol",
    hdrs = ["mysql_protocol.h"],
)

cc_library(
    name = "network_server",
    hdrs = ["network_server.h"],
)

cc_library(
    name = "network",
    hdrs = ["network.h"],
)
