package(default_visibility = ["//visibility:public"])

cc_library(
    name = "join_executor_hdr",
    hdrs = ["join_executor.h"],
)

cc_library(
    name = "set_operation_executor_hdr",
    hdrs = ["set_operation_executor.h"],
)

cc_library(
    name = "subquery_executor_hdr",
    hdrs = ["subquery_executor.h"],
)

cc_library(
    name = "task_executor_hdr",  # 添加任务执行器头文件定义
    hdrs = ["task_executor.h"],
)