# 索引管理器头文件库定义

package(default_visibility = ["//visibility:public"])

# 智能索引缓存头文件
cc_library(
    name = "smart_index_cache",
    hdrs = ["smart_index_cache.h"],
    includes = ["../.."],
    visibility = ["//visibility:public"],
)

# 智能索引工厂头文件
cc_library(
    name = "smart_index_factory",
    hdrs = ["smart_index_factory.h"],
    includes = ["../.."],
    visibility = ["//visibility:public"],
)