package(default_visibility = ["//visibility:public"])

cc_test(
    name = "disk_manager_fast",
    srcs = ["disk_manager_test.cpp"],
    deps = [
        "//src/storage_engine:storage_engine",
        "@com_google_googletest//:gtest_main",
    ],
)

test_suite(
    name = "all",
    tests = [":disk_manager_fast"],
)
