# Mock头文件库定义

package(default_visibility = ["//visibility:public"])

# 存储引擎Mock头文件
cc_library(
    name = "storage_engine_mock",
    hdrs = ["storage_engine_mock.h"],
)

# 数据库管理器Mock头文件
cc_library(
    name = "database_manager_mock",
    hdrs = ["database_manager_mock.h"],
)

# 事务管理器Mock头文件
cc_library(
    name = "transaction_manager_mock",
    hdrs = ["transaction_manager_mock.h"],
)

# 索引管理器Mock头文件
cc_library(
    name = "index_manager_mock",
    hdrs = ["index_manager_mock.h"],
)