# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Example Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
#models:
#  - name: my gpt-5
#    provider: openai
#    model: gpt-5
#    apiKey: YOUR_OPENAI_API_KEY_HERE
#  - uses: ollama/qwen2.5-coder-7b
#  - uses: anthropic/claude-4-sonnet
#    with:
#      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}


models:
  # 主对话 / 设计 / 重构 / Apply
  - name: SQLCC-Coder
    provider: ollama
    model: sqlcc-coder:latest
    apiBase: http://192.168.0.252:11434
    roles:
      - chat
      - edit
      - apply

  # 代码补全（低延迟）
  - name: Qwen2.5-Coder
    provider: ollama
    model: qwen2.5-coder:14b
    apiBase: http://192.168.0.252:11434
    roles:
      - autocomplete

  # 向量索引 / 语义搜索
  - name: Nomic Embed
    provider: ollama
    model: nomic-embed-text:latest
    apiBase: http://192.168.0.252:11434
    roles:
      - embed

# MCP Servers that Continue can access
# https://docs.continue.dev/customization/mcp-tools
mcpServers:
  - uses: anthropic/memory-mcp
