cc_test(
    name = "execution_result_tests",
    srcs = glob(["*.cpp"]),
    deps = [
        "@com_google_googletest//:gtest_main",
        "//src/core:core",
        "//src/exception:exception",
    ],
    copts = [
        "-std=c++20",
        "-fprofile-instr-generate",
        "-fcoverage-mapping",
    ],
    linkopts = ["-fprofile-instr-generate"],
    tags = ["coverage", "level2", "core_services", "execution_result"],
)
