cc_test(
    name = "stored_procedure_manager_test",
    srcs = ["stored_procedure_manager_test.cpp"],
    deps = [
        "//include/core:stored_procedure_manager",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "config_manager_test",
    srcs = ["config_manager_test.cpp"],
    deps = [
        "//src/core:core",
        "@com_google_googletest//:gtest_main",
    ],
)
