package(default_visibility = ["//visibility:public"])

cc_test(
    name = "wal_system_fast",
    srcs = ["wal_system_test.cpp"],
    deps = [
        "//src/storage_engine:storage_engine",
        "@com_google_googletest//:gtest_main",
    ],
)

test_suite(
cc_test(
    name = "wal_system_tests",
    srcs = glob([
        "*.cpp",
        "**/*.cpp",
    ]),
    deps = [
        "//src/storage_engine",
        "@com_google_googletest//:gtest_main",
    ],
)
    name = "all",
    tests = [":wal_system_fast"],
)
