load("@rules_cc//cc:defs.bzl", "cc_library")

# Replace strategy headers - 替换策略头文件
cc_library(
    name = "replace_strategy_headers",
    hdrs = [
        "abstract_strategy.h",
        "arc_strategy.h",
        "clock_strategy.h",
        "lfu_strategy.h",
        "lru_strategy.h",
        "strategy_factory.h",
    ],
    includes = ["."],
    visibility = ["//visibility:public"],
)
