# 配置管理器组件Bazel构建配置

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "sqlcc_config_manager",
    srcs = ["config_manager.cpp"],
    hdrs = ["//include:config_manager"],
    copts = [
    ],
    includes = ["../include"],
    deps = [
        "//src/utils:utils",
    ],
    visibility = ["//visibility:public"],
)
