cc_test(
    name = "basic_test",
    srcs = ["basic_test.cpp"],
    copts = [
        "-fprofile-instr-generate",
        "-fcoverage-mapping",
    ],
    linkopts = ["-fprofile-instr-generate"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//src/exception:exception",
    ],
    tags = ["coverage", "level1"],
)
