/**
 * @file buffer_exception.h
 * @brief 缓冲池异常类定义
 *
 * Why: 需要一个专门的异常类来处理缓冲池操作中可能出现的错误
 * What: BufferPoolException类继承自Exception，用于处理缓冲池相关的异常
 * How: 继承Exception类，在构造函数中添加"Buffer Pool Error: "前缀
 */

#pragma once

#include "base_exception.h"
#include <string>

namespace sqlcc {

/**
 * @brief 缓冲池异常类
 *
 * Why: 需要一个专门的异常类来处理缓冲池操作中可能出现的错误
 * What: BufferPoolException类继承自Exception，用于处理缓冲池相关的异常
 * How: 继承Exception类，在构造函数中添加"Buffer Pool Error: "前缀
 */
class BufferPoolException : public Exception {
public:
    /**
     * @brief 构造函数
     *
     * Why: 需要创建缓冲池异常对象并初始化异常消息
     * What: 构造函数接收异常消息字符串，添加"Buffer Pool Error: "前缀后传递给基类
     * How: 使用成员初始化列表调用基类构造函数，添加前缀标识异常类型
     *
     * @param message 异常消息字符串
     */
    explicit BufferPoolException(const std::string& message);
};

}  // namespace sqlcc

</final_file_content>

IMPORTANT: For any future changes to this file, use the final_file_content shown above as your reference. This content reflects the current state of the file, including any auto-formatting (e.g., if you used single quotes but the formatter converted them to double quotes). Always base your SEARCH/REPLACE operations on this final version to ensure accuracy.

<environment_details>
# Visual Studio Code Visible Files
include/exception/buffer_exception.h

# Visual Studio Code Open Tabs
src/isql_network/client_main.cpp
docs/项目进展/v1.1.3/v1.1.3工作日记.md
docs/项目进展/v1.1.3/v1.1.3_TODO.md
docs/releases/RELEASE_NOTES_v1.1.3.md
docs/项目进展/v1.1.4/v1.1.4测试报告.md
docs/unit/executor/test_runner.cpp
tools/mcp/core.py
docs/项目进展/v1.1.4/TEST_REDESIGN_PLAN.md
docs/项目进展/v1.1.4/TEST_REDESIGN_PROGRESS_REPORT.md
docs/项目进展/v1.1.4/TEST_REDESIGN_FINAL_REPORT.md
tools/mcp/cli.py
tools/mcp/__init__.py
docs/项目进展/v1.1.4/testing_coverage_analysis.md
../.config/Qoder/User/settings.json
scripts/test_pipeline.sh
scripts/prepare_test_environment.sh
scripts/run_integration_tests.sh
tests/comprehensive_test_suite.bzl
src/storage_engine/replace_strategy.cpp
docs/项目进展/v1.1.4/全面测试报告_20251215.md
docs/项目进展/v1.1.4/全面测试报告.md
docs/项目进展/v1.1.4/测试流水线完善报告.md
scripts/test_communication_protocol.sh
scripts/start_test_server.sh
scripts/run_e2e_tests.sh
scripts/generate_test_report.sh
scripts/analyze_coverage_trends.sh
docs/项目进展/v1.1.4/network_integration_test_analysis.md
docs/项目进展/v1.2.3/TODO.md
src/storage_engine/data_integrity_validator.cpp
include/storage/data_integrity_validator.h
tests/integration/encrypted_integration_test.cpp
tests/performance/basic/cpu_intensive_performance_test.cc
tests/performance/stability_test/long_term_stability_test_main.cc
tests/performance/index_performance_test.h
tests/performance/buffer_pool_performance_test.h
tests/performance/concurrency/concurrency_performance_test.h
tests/performance/stability_test/long_term_stability_test.h
tests/performance/cpu_test/cpu_intensive_performance_test.h
tests/performance/memory_stress_test/memory_stress_test.cc
tests/performance/memory_stress_test/memory_stress_test.h
tests/integration/client_server_integration_test.cpp
include/storage/record_boundary_validator.h
src/storage_engine/disk_error_handler.cpp
include/storage/disk_error_handler_clean.h
src/storage_engine/page_allocator.cpp
src/storage_engine/concurrent_access_validator.cpp
src/network/encryption.cpp
docs/development/TODO.md
docs/项目进展/v1.1.4/sql_92_support_evaluation.md
docs/项目进展/v1.1.4/memory_safety_evaluation.md
docs/项目进展/v1.1.4/performance_evaluation.md
docs/项目进展/v1.1.4/refactoring_improvement_plan.md
docs/releases/RELEASE_NOTES_v1.1.4.md
docs/项目进展/v1.1.4/内存安全改进计划_v1.1.4.md
docs/项目进展/v1.1.4/内存安全深度修复进展报告_20251215_004600.md
docs/项目进展/v1.1.4/B+树索引系统深度修复完成报告_20251215_004808.md
include/network/connection_state.h
include/utils/ssl_wrapper.h
docs/项目进展/v1.1.4/网络通信模块深度修复完成报告_20251215_010051.md
docs/项目进展/v1.1.4/内存安全深度修复最终完成报告_20251215_010700.md
docs/项目进展/v1.1.4/表存储系统深度修复部分完成报告_20251215_011600.md
src/storage_engine/index_manager/index_manager_smart_ptr_enhancement.cpp
docs/项目进展/v1.1.4/表存储系统深度修复完成报告_20251215_012400.md
docs/项目进展/v1.1.4/内存安全修复进展报告_20251215_003250.md
docs/项目进展/v1.1.4/内存安全深度修复全部完成最终报告_20251215_013400.md
docs/项目进展/v1.1.4/内存安全审计报告_20251215_025149.md
docs/项目进展/v1.1.4/测试修复与全面评估完成报告.md
docs/项目进展/v1.1.4/测试报告.md
docs/项目进展/v1.1.4/TODO.md
docs/项目进展/v1.1.4/变更日志.md
docs/项目进展/v1.1.4/工作日记.md
tests/scripts/BUILD.bazel
tests/network/BUILD.bazel
include/storage/wal_buffer.h
src/storage_engine/wal_writer.cpp
src/storage_engine/checkpoint.cpp
include/procedure/procedure_parser.h
include/execution/procedure_trigger_task.h
docs/存储过程与触发器实现完成报告.md
docs/项目进展/v1.2.1/v1.2.1工作日记.md
docs/项目进展/v1.2.1/v1.2.1_TODO.md
docs/releases/RELEASE_NOTES_v1.2.1.md
docs/项目进展/v1.2.2/v1.2.2_TODO.md
include/storage/disk_manager.h
docs/项目进展/v1.2.2/v1.2.2工作日记.md
tests/unit/executor/comprehensive_task_executor_test.cpp
src/network/connection_state_machine.cpp
src/unified_executor.cpp
src/sql_parser/json.cpp
scripts/validate_build.sh
tests/validate/user_manager_test.cpp
docs/prompt.md
src/storage_engine/index_manager/smart_index_cache.cpp
src/storage_engine/index_manager/transactional_index_manager.cpp
include/storage_engine/index_manager/smart_index_factory.h
src/storage_engine/index_manager/smart_ptr_lifetime_manager.cpp
src/storage_engine/index_manager/smart_index_factory.cpp
src/storage_engine/index_manager/enhanced_index_manager.cpp
scripts/fix_bazel_paths.py
src/network/client_connection.cpp
docs/项目进展/v1.2.5/v1.2.5_TODO.md
tools/include_path_manager.py
.github/workflows/include_check.yml
tools/analyze_header_usage.py
include/sqlcc_pch.h
scripts/benchmark_compile_time.sh
scripts/monitor_compile_performance.sh
docs/guides/BUILD_AND_TEST_GUIDE.md
include/storage_engine_pch.h
src/storage_engine/table_storage_complete.cpp
include/types/domain_manager.h
docs/项目进展/v1.2.6/include_dependency_optimization_final_report.md
src/utils/config_lifecycle.cpp
include/utils/config_lifecycle.h
docs/项目进展/v1.2.5/v1.2.5工作日记.md
tools/bazel_dep_fixer_enhanced.py
docs/项目进展/v1.2.3/测试源码整理完成报告.md
tests/storage_engine/comprehensive_bplus_tree_test.cpp
docs/项目进展/v1.2.3/性能基准测试报告.md
docs/项目进展/v1.2.3/test_summary_report.md
docs/项目进展/v1.2.3/最终项目完成报告.md
src/sql_parser/constraint.cpp
tests/constraint_advanced_test.cpp
docs/项目进展/v1.2.3/v1.2.3_TODO.md
src/network/mysql_protocol.cpp
docs/项目进展/v1.3.0/v1.3.0_企业级特性实施计划.md
docs/项目进展/v1.2.3/constraint_system_implementation_report.md
docs/项目进展/v1.2.3/config_manager_upgrade_guide.md
docs/项目进展/v1.2.3/config_manager_improvement_plan.md
docs/项目进展/v1.2.3/v1.2.3工作日记.md
docs/项目进展/v1.2.3/v1.2.3_内存安全专项修复总结.md
docs/项目进展/v1.3.0/evaluation_v1.3.0.md
docs/releases/RELEASE_NOTES_v1.2.4.md
docs/项目进展/v1.2.4/TPC-H支持评估报告.md
src/storage_engine/b_plus_tree_fixed.cpp
docs/项目进展/v1.2.7/comprehensive_test_system_fix_final_report.md
docs/项目进展/v1.2.7/v1.2.8_测试重构工作日记.md
docs/项目进展/v1.2.7/v1.2.7项目总结报告.md
tests/unit/executor/task_executor_test.cpp
tools/test_config_validator_test.py
tools/tool_effectiveness_analysis.py
docs/项目进展/v1.2.7/test_config_validator_effectiveness_final_report.md
docs/项目进展/v1.2.7/comprehensive_test_auto_improvement_assessment.md
docs/项目进展/v1.2.7/test_auto_fix_final_verification_report.md
tools/test_config_validator.py
docs/项目进展/v1.2.7/v1.2.7工作日记.md
docs/releases/RELEASE_NOTES_v1.2.7.md
VERSION
docs/releases/CHANGELOG_v1.2.7.md
docs/releases/CHANGELOG_v1.2.8.md
docs/releases/CHANGELOG_v1.2.9.md
docs/releases/CHANGELOG_v1.2.11.md
docs/releases/CHANGELOG_v1.2.12.md
docs/releases/CHANGELOG_v1.2.13.md
docs/releases/RELEASE_NOTES_v1.1.2.md
docs/项目进展/v1.2.14/v1.2.14项目总结报告.md
WORKSPACE
src/BUILD.bazel
README.md
src/sqlcc_server/BUILD.bazel
src/sql_executor/BUILD.bazel
include/sql_parser/ast_node.h
src/sqlcc_server/server_main.cpp
.bazelrc
docs/releases/RELEASE_NOTES_v1.2.14.md
docs/releases/CHANGELOG_v1.2.14.md
tests/unit/parser/json_parser_test.cpp
tests/unit/parser/advanced_query_test.cpp
tests/unit/execution/aggregation_executor_test.cpp
tests/unit/execution/transaction_manager_test.cpp
tests/security/BUILD
tests/integration/BUILD.bazel
tests/integration/sql/BUILD.bazel
include/storage_engine/BUILD.bazel
include/storage_engine/table_storage/BUILD.bazel
include/core/BUILD.bazel
include/BUILD.bazel
docs/项目进展/v1.2.14/编译环境基础修复测试报告.md
docs/项目进展/v1.2.14/v1.2.14_TODO.md
docs/项目进展/v1.2.14/v1.2.14工作日记.md
src/config_manager.cpp
tests/security/memory_safety_framework.cpp
tools/bazel_label_fixer_enhanced.py
.github/workflows/ci.yml
docs/security/memory_safety_training.md
scripts/memory_safety_audit.sh
scripts/memory_safety_cron.conf
scripts/quick_memory_check.sh
include/storage/disk_error_handler.h
.trae/rules/project_rules.md
src/storage_engine/record_boundary_validator.cpp
tests/test_smart_config_manager.cpp
scripts/run_incremental_tests.sh
scripts/test_status_tracker.py
scripts/enhanced_coverage_analyzer.py
scripts/sqlcc_test_system.py
docs/design/README_v1.2.3.md
docs/design/storage_engine/storage_engine_v1.2.3_design.md
docs/项目进展/v1.2.3/evaluation_v1.2.3.md
docs/project_progress.md
docs/项目进展/project_organization_plan.md
docs/项目进展/PROJECT_SUMMARY.md
docs/项目进展/sql_command_support_evaluation.md
docs/version_summary_v1.2.3.md
docs/项目进展/v1.2.3/v1.2.3测试改进日记.md
docs/项目进展/v1.2.3/v1.2.3_测试进展报告.md
include/storage/partition_manager.h
docs/项目进展/v1.2.3/测试改进TODO清单.md
docs/项目进展/v1.2.3/测试执行日志.md
docs/项目进展/v1.2.3/测试执行摘要.md
src/sql_parser/token.cpp
src/storage_engine/partition_manager.cpp
src/sql_parser/ast_nodes.cpp
tests/view_operations_test.cpp
docs/项目进展/v1.2.3/advanced_sql92_design.md
include/trigger/sql_trigger_executor.h
include/transaction/savepoint_manager.h
src/transaction/savepoint_manager.cpp
tests/advanced_sql92_test_suite.cpp
tests/unit/buffer_pool_smart_pointer_test.cpp
include/sql_executor/BUILD.bazel
include/database_manager/BUILD.bazel
include/error_handler/BUILD.bazel
docs/项目进展/v1.2.5/dependency_analysis_report.md
docs/项目进展/v1.2.5/dependency_graph.txt
docs/项目进展/v1.2.6/package_build_order_analysis.md
include/trigger/BUILD.bazel
include/network/BUILD.bazel
src/trigger/BUILD.bazel
src/sql_parser/window_function.h
src/security/memory_monitor.h
src/network/session.cpp
src/network/session_manager.cpp
src/security/memory_monitor.cpp
src/procedure/procedure_parser.cpp
docs/项目进展/v1.2.6/package_refactoring_status_report.md
src/utils/config_manager.cpp
docs/项目进展/v1.2.10/严重技术错误记录_20251227.md
docs/项目进展/v1.2.10/层次1_基础工具类测试分析报告.md
docs/项目进展/v1.2.10/v1.2.10详细覆盖率数据报告.md
tests/unit/parser/constraint_test.cpp
tests/unit/basic/config_manager_test.cpp
src/execution/procedure_trigger_task.cpp
docs/项目进展/v1.2.10/SQLCC测试系统完整索引报告_v1.2.10.md
tests/unit/basic/advanced_performance_monitor_test.cpp
tests/storage_engine/buffer_pool_quick_test.cpp
tests/storage_engine/buffer_pool_performance_benchmark_test.cpp
tests/unit/basic/performance_monitor_persistence_test.cpp
docs/项目进展/v1.2.11/SQLCC测试系统完整索引报告_v1.2.11.md
tests/unit/parser/ast_comprehensive_test.cpp
tests/unit/parser/expression_parser_test.cpp
tests/unit/parser/BUILD.bazel
docs/项目进展/v1.2.11/v1.2.11覆盖率测试数据报告.md
docs/项目进展/v1.2.11/v1.2.11工作日记.md
docs/项目进展/v1.2.11/层次4测试重构改进完成报告.md
docs/项目进展/v1.2.11/v1.2.11_TODO.md
scripts/run_crud_coverage_tests.sh
scripts/coverage_pipeline.sh
tests/performance/BUILD.bazel
tests/performance/basic/performance_test_base.cc
scripts/generate_crud_coverage_data.sh
tests/storage_engine/index_manager_test.cpp
include/types/transaction_types.h
tests/storage_engine/concurrency_control_test.cpp
tests/storage_engine/page_allocator_test.cpp
tests/storage_engine/storage_engine_comprehensive_test.cpp
scripts/verify_crud_coverage.sh
src/core/system_database.cpp
src/core/BUILD.bazel
src/execution/BUILD.bazel
tests/BUILD.bazel
scripts/generate_crud_coverage_report.sh
tests/crud_test.cpp
tests/performance/crud/real_crud_performance_test.cpp
scripts/test_clang18_features.sh
docs/clang18_validation_report.md
src/execution/cost_estimator.cpp
src/monitoring/performance_monitor.cpp
docs/releases/RELEASE_NOTES_v1.3.0.md
CHANGELOG.md
tests/unit/network/tls_connection_test.cpp
src/storage_engine/BUILD.bazel
docs/项目进展/v1.3.0/v1.3.0_TODO.md
tests/unit/basic/decimal_test.cpp
src/sql_parser/decimal.cpp
include/sql_executor/procedure_executor.h
tests/unit/basic/stored_procedure_test.cpp
src/sql_executor/procedure_executor.cpp
src/core/permission_validator.cpp
tests/unit/basic/permission_validator_test.cpp
include/core/permission_validator.h
src/network/BUILD.bazel
docs/design/Architecture.md
docs/design/config_manager/config_manager_design.md
docs/README.en.md
docs/design/transaction_system_design.md
scripts/sync_document_versions.py
src/storage_engine/advanced_lock_manager.cpp
src/storage_engine/concurrency_control.cpp
src/storage_engine/performance_monitor.cpp
src/network/data_transmission_validator.cpp
tests/unit/executor/task_executor_comprehensive_test.cpp
tests/unit/executor/standalone_test.cpp
src/sql_executor/sql_executor.cpp
src/core/user_manager.cpp
src/network/network.cpp
src/database_manager.cpp
src/config_manager/config_manager.cpp
src/main.cpp
src/execution_engine.cpp
src/execution/unified_query_plan.cpp
src/execution/task_result.cpp
src/execution/query_plan_factory.cpp
src/sql_parser/lexer.cpp
src/sql_parser/ast_node.cpp
src/storage_engine/storage_engine.cpp
src/storage_engine/b_plus_tree.cpp
src/storage_engine/index_manager/index_manager.cpp
src/logger/logger.cpp
src/error_handler.cpp
src/transaction_manager/transaction_manager.cpp
docs/项目进展/v1.2.15/v1.2.15_SQLCC注释补全项目核心源文件阶段完成报告.md
include/utils/smart_config_manager.h
include/exception.h
include/monitoring/performance_monitor.h
include/monitoring/slow_query_analyzer.h
include/exception/base_exception.h
include/exception/io_exception.h
include/exception/buffer_exception.h
include/execution_engine.h
docs/项目进展/v1.2.15/v1.2.15_SQLCC注释补全项目Phase9-14工作计划文档.md
docs/项目进展/v1.2.15/SQLCC_v1.2.15_Client_Server架构项目计划.md
docs/项目进展/v1.2.15/v1.2.15_Client_Server详细TODO.md
docs/项目进展/v1.2.15/v1.2.15_Client_Server项目总结报告.md
include/utils/config_snapshot.h
docs/项目进展/v1.2.15/v1.2.15_SQLCC注释补全项目Phase9-14工作总结.md
include/sql_executor.h
include/unified_query_plan.h
include/view_manager.h
include/wal_manager.h
scripts/check_comment_quality.sh
include/core/execution_context.h
include/core/execution_result.h
include/core/system_database.h
include/core/core_database_manager.h
include/storage/buffer_pool.h
include/storage_engine/b_plus_tree_index.h
include/storage_engine/b_plus_tree_node.h
include/storage_engine/b_plus_tree_leaf_node.h
include/storage_engine/b_plus_tree_internal_node.h
include/storage_engine/node_size_manager.h
tools/comment_quality_analyzer.py
tools/comment_quality_config.yaml
scripts/ci_check_comments.sh
docs/code/comment_quality_training_guide.md
include/storage/b_plus_tree.h
include/storage_engine/buffer_pool/lru_manager.h
include/storage_engine/buffer_pool/statistics_collector.h
include/storage_engine/index_manager/smart_index_cache.h
include/sql_parser/ast_nodes.h
include/sql_parser/data_types.h
include/sql_parser/token.h
include/sql_parser/constraint.h
include/sql_parser/window_function.h
include/sql_parser/set_operation.h
include/sql_parser/parser.h
include/sql_parser/json.h
include/sql_parser/datetime.h
docs/项目进展/v1.2.12/四阶段执行计划_todo.md
tests/coverage/debug_and_demo_tests.bzl
tests/coverage/BUILD.bazel
tests/unit/debug/BUILD.bazel
docs/项目进展/v1.2.12/debug_demo_coverage_integration_report.md
docs/项目进展/v1.2.13/v1.2.13_TODO.md
docs/项目进展/v1.2.13/v1.2.13工作日记.md
docs/项目进展/v1.2.13/v1.2.13阶段2完成报告.md
docs/项目进展/v1.2.13/v1.2.13阶段3工作计划.md
docs/项目进展/v1.2.13/v1.2.13阶段3工作日记.md
scripts/generate_coverage_report.sh
scripts/generate_coverage_html_report.sh
tests/unit/basic/token_test.cpp
tests/debug/src/BUILD.bazel
tests/debug/BUILD.bazel
src/sql_executor/window_function_executor.cpp
docs/项目进展/v1.2.13/v1.2.13_最终项目总结报告.md
src/transaction/BUILD.bazel
include/transaction/BUILD.bazel
include/sql_executor/transaction_control_manager.h
src/sql_executor/domain_manager.cpp
tests/unit/network/BUILD.bazel
include/sql_executor/enhanced_alter_table_manager.h
src/sql_executor/enhanced_alter_table_manager.cpp
include/sql_executor/enhanced_trigger_manager.h
src/sql_executor/enhanced_trigger_manager.cpp
include/sql_executor/procedure_function_manager.h
src/sql_executor/procedure_function_manager.cpp
scripts/generate_llvm_coverage_report.sh
docs/AI-Agent/AI开发原则.md
scripts/analyze_test_coverage.sh
BUILD.bazel
src/sql_parser/advanced_sql92_features.cpp
src/sql_parser/BUILD.bazel
tests/storage_engine/BUILD.bazel
src/storage_engine/b_plus_tree_leaf_node.cpp
src/storage_engine/b_plus_tree_index.cpp
src/storage_engine/b_plus_tree_node.cpp
docs/SQLCC_1.2.x_综合覆盖率分析报告.md
scripts/test_clang18_coverage.sh
scripts/comprehensive_coverage_test.sh
docs/COMPREHENSIVE_COVERAGE_GUIDE.md
docs/ai-agent/sqlcc_test_integration_and_coverage_guide.md
docs/项目进展/v1.2.12/SQLCC测试系统错误分析报告_v1.2.12.md
tests/unit/buffer_pool_test.cpp
tests/unit/parser/lexer_test.cpp
tests/unit/executor/load_data_boundary_test.cpp
docs/项目进展/v1.2.12/层次4-7测试重构改进完成报告.md
docs/项目进展/v1.2.12/v1.2.12覆盖率测试数据报告.md
docs/自助式改进计划.md
tests/unit/basic/logger_test.cpp
src/utils/config_snapshot.cpp
src/trigger/trigger_manager.cpp
include/trigger/trigger_manager.h
src/trigger/trigger_executor.cpp
include/security/BUILD.bazel
src/trigger/sql_trigger_executor.cpp
src/security/BUILD
src/network/server_network_manager.cpp
src/trigger/trigger_definition.cpp
src/trigger/recursion_guard.cpp
docs/项目进展/v1.2.6/phase1_missing_files_completion_report.md
src/core/sql_executor.cpp
include/execution_ast/BUILD.bazel
include/execution_ast/ast_interface.h
src/sql_parser/recursive_query.cpp
docs/项目进展/v1.2.6/v1.2.6重构工作日记.md
docs/项目进展/v1.2.6/refactoring_experience_summary.md
docs/项目进展/v1.2.6/phase2_bottom_up_fix_progress_report.md
scripts/bottom_up_build_validation.sh
docs/项目进展/v1.2.6/v1.2.6_TODO.md
docs/项目进展/v1.2.8/BUILD系统重构分析报告_20251224.md
src/storage_engine/buffer_pool/statistics_collector.cpp
docs/项目进展/v1.2.10/层次2_存储引擎基础测试分析报告.md
docs/项目进展/v1.2.10/层次3_索引系统测试分析报告.md
tests/unit/BUILD.bazel
src/storage_engine/buffer_pool/BUILD.bazel
src/storage_engine/buffer_pool/lru_manager.cpp
tools/bazel_coverage_build_template.bzl
docs/guides/COVERAGE_TEST_GUIDE.md
docs/项目进展/v1.2.10/测试改进验证完成报告.md
docs/项目进展/v1.2.10/工作日记.md
src/storage_engine/b_plus_tree_internal_node.cpp
docs/项目进展/v1.2.10/B+树索引系统深度修复最终完成报告.md
docs/项目进展/v1.2.10/v1.2.10工作日记.md
docs/项目进展/v1.2.10/v1.2.10_TODO.md
docs/项目进展/v1.2.10/B+树测试覆盖率分析报告.md
docs/releases/CHANGELOG_v1.2.10.md
scripts/run_layer1_coverage_tests.sh
tests/storage_engine/test_bplus_tree_fix.cpp
scripts/collect_full_coverage.sh
scripts/analyze_full_coverage.sh
tests/unit/basic/ast_node_basic_test_fixed.cpp
tools/BUILD.bazel
scripts/run_storage_engine_coverage_tests.sh
docs/项目进展/v1.2.10/v1.2.10覆盖率测试执行报告.md
docs/项目进展/v1.2.10/v1.2.10工作总结报告.md
docs/项目进展/v1.2.10/v1.2.10测试执行总结报告.md
docs/development/ai_development_principles.md
tests/storage_engine/storage_engine_boundary_test.cpp
docs/项目进展/v1.2.10/v1.2.10测试重构改进计划.md
tests/storage_engine/buffer_pool_test.cpp
src/sql_parser/function_definition.cpp
docs/项目进展/v1.2.10/层次4_SQL解析器测试分析报告.md
docs/项目进展/v1.2.10/层次5_执行引擎测试分析报告.md
docs/项目进展/v1.2.10/层次6_网络通信测试分析报告.md
docs/项目进展/v1.2.10/层次7_高层功能测试分析报告.md
tools/bazel_label_auto_fixer.py
docs/项目进展/v1.2.7/v1.2.7_测试目录全面分析报告_20251224.md
docs/项目进展/v1.2.7/v1.2.7_TODO.md
docs/项目进展/v1.2.8/BUILD系统第一周重构完成报告_20251224.md
docs/项目进展/v1.2.8/BUILD系统第二周核心修复完成报告_20251224.md
docs/项目进展/v1.2.8/BUILD系统第三周验证与优化完成报告_20251224.md
docs/项目进展/v1.2.8/BUILD系统测试验证详细报告_20251224.md
docs/项目进展/v1.2.8/SQLCC测试系统完整索引报告_20251225.md
docs/项目进展/v1.2.8/SQLCC测试系统完整执行状态报告_20251225.md
docs/项目进展/v1.2.8/SQLCC测试系统编译错误详细分析与修正方案_20251225.md
docs/项目进展/v1.2.8/SQLCC系统性C++20迁移与编译验证实施计划_20251225.md
tools/systematic_build_fix.sh
docs/项目进展/v1.2.8/SQLCC编译和测试改进计划_20251225.md
src/procedure/BUILD.bazel
docs/项目进展/v1.2.8/SQLCC编译和测试改进项目最终总结_20251225.md
docs/项目进展/v1.2.8/SQLCC编译和测试改进项目最终完成报告_20251225.md
docs/项目进展/v1.2.8/SQLCC依赖关系错误分析与改进方案_20251225.md
scripts/run_unit_tests.sh
docs/项目进展/v1.2.9/Logger测试覆盖率手动评估报告.md
docs/项目进展/v1.2.9/SQLCC测试覆盖率改进项目完成报告.md
docs/项目进展/v1.2.9/StorageEngine测试覆盖率评估报告.md
docs/项目进展/v1.2.9/编译错误修复与测试执行报告.md
docs/项目进展/v1.2.9/BUILD系统第二阶段核心修复完成总结报告_20251225.md
include/procedure/BUILD.bazel
src/utils/smart_config_manager.cpp
src/utils/BUILD.bazel
src/core/error_handler.cpp
docs/项目进展/v1.2.9/SQLCC组件级覆盖率详细分析报告_20251225.md
tools/include_path_analyzer/config.yaml
tools/include_path_analyzer/utils/models.py
tools/include_path_analyzer/__init__.py
tools/include_path_analyzer/analyzers/path_analyzer.py
tools/include_path_analyzer/utils/config_loader.py
tools/include_path_analyzer/test_script.py
tools/include_path_analyzer/include_path_analyzer.py
tools/include_path_analyzer/build_fix_verification.py
include/execution/BUILD.bazel
tools/include_path_analyzer/build_system_fixer.py
include/sql_parser/BUILD.bazel
include/storage/BUILD.bazel
include/utils/BUILD.bazel
include/exception/BUILD.bazel
src/types/BUILD.bazel
src/config_manager/BUILD.bazel
src/sql_parser/function_ast.cpp
src/execution/subquery_executor.cpp
scripts/analyze_module_coverage.sh
docs/项目进展/v1.2.9/SQLCC测试覆盖率改进项目完成报告_20251225.md
scripts/collect_demo_coverage.sh
docs/项目进展/v1.2.9/demo测试修复与覆盖率收集报告.md
include/storage/advanced_lock_manager.h
tests/demo/BUILD.bazel
docs/development/sql_parser_coverage_improvement_plan.md
tests/unit/parser/window_function_test.cpp
tests/unit/execution/BUILD.bazel
tests/unit/execution/task_executor_test.cpp
tests/unit/execution/load_data_executor_test.cpp
tests/unit/execution/set_operation_executor_test.cpp
tests/unit/execution/recursive_query_executor_test.cpp
tests/unit/execution/subquery_executor_test.cpp
tests/unit/execution/window_function_executor_test.cpp
tests/unit/execution/function_executor_test.cpp
docs/项目进展/v1.2.9/SQLCC_v1.2.9_BUILD系统测试覆盖率改进分析报告.md
docs/项目进展/v1.2.9/SQLCC测试覆盖率阶段1改进完成报告.md
docs/include_path_fixes_summary.md
include/storage/cache_consistency_manager.h
src/storage_engine/cache_consistency_manager.cpp
tests/sql/BUILD.bazel
tests/sql/test_dcl_parsing.cpp
tests/demo/expression_test.cpp
tests/unit/core/BUILD.bazel
docs/项目进展/v1.2.7/v1.2.7_测试重构工作日记.md
docs/项目进展/v1.2.7/v1.2.7_测试重构TODO.md
docs/项目进展/v1.2.8/BUILD系统重构详细变更记录_20251224.md
include/storage/concurrency_control.h
include/core/sql_executor_interface.h
include/procedure/procedure_vm.h
src/procedure/procedure_vm.cpp
src/execution/function_executor.cpp
docs/guides/BUILD_STANDARD_TEMPLATE.md
src/execution/set_operation_executor.cpp
include/procedure/procedure_trigger_executor.h
src/procedure/procedure_trigger_executor.cpp
src/execution/load_data_executor.cpp
include/transaction_context.h
include/storage_accessor.h
include/transaction_context_impl.h
src/transaction_context_impl.cpp
include/storage_accessor_impl.h
docs/项目进展/v1.2.6/v1.2.6工作日记.md
docs/项目进展/v1.2.4/v1.2.4层次化修复过程记录.md
docs/项目进展/v1.2.5/v1.2.5层次化修复过程记录.md
docs/releases/CHANGELOG_v1.1.4.md
docs/releases/CHANGELOG_v1.1.5.md
docs/releases/CHANGELOG_v1.1.6.md
docs/releases/CHANGELOG_v1.1.7.md
docs/releases/CHANGELOG_v1.1.8.md
docs/releases/CHANGELOG_v1.1.9.md
docs/releases/CHANGELOG_v1.2.0.md
docs/releases/CHANGELOG_v1.2.1.md
docs/releases/CHANGELOG_v1.2.2.md
docs/releases/CHANGELOG_v1.2.3.md
docs/releases/CHANGELOG_v1.2.4.md
docs/releases/CHANGELOG_v1.2.5.md
docs/releases/CHANGELOG_v1.2.6.md
docs/api/README.md
docs/features/implementation_status.md
docs/code/coding_standards.md
docs/versions/roadmap.md
docs/user/user_guide.md
scripts/check_documentation.sh
docs/project/overview.md
docs/project/history.md
docs/project/header_index.md
docs/ai-agent/project_index_usage_guide.md
include/page/BUILD.bazel
include/disk_manager/BUILD.bazel
tests/unit/basic/logger_basic_test.cpp
tools/test_dependency_analyzer.py
docs/项目进展/v1.2.7/test_configuration_repair_report.md
docs/guides/test_configuration_repair_process.md
tools/test_layer_analyzer.py
docs/项目进展/v1.2.7/comprehensive_test_layer_analysis_final_report.md
tests/unit/parser/sql_parser_high_coverage_test.cpp
tests/unit/executor/BUILD.bazel
tests/validate/BUILD.bazel
docs/code/source_code_comments_guide.md
docs/项目进展/v1.2.6/documentation_system_construction_process_record.md
docs/design/storage_engine/sharded_buffer_pool_design.md
docs/项目进展/v1.2.6/v1.2.6注释补全工作日记.md
src/storage_engine/buffer_pool_sharded.cpp
tests/unit/storage/wal_buffer_test.cpp
src/storage_engine/wal_buffer.cpp
tools/include_path_analyzer/advanced_include_analyzer.py
include/storage/wal_writer.h
docs/design/storage_engine/wal_system_design.md
include/storage/checkpoint.h
docs/design/query_processor_design.md
docs/项目进展/v1.2.6/v1.2.6注释补全TODO.md
docs/textbook/learning_guide_database_system.md
docs/textbook/database_system_case_studies.md
docs/releases/RELEASE_NOTES_v1.2.6.md
docs/design/storage_engine_design.md
include/utils/logger.h
src/sql_parser/parser.cpp
third_party/absl.BUILD
docs/项目进展/v1.2.9/v1.2.9_BUILD系统修复工作日记.md
docs/项目进展/v1.2.9/下一步行动执行指南.md
docs/项目进展/v1.2.9/错误处理覆盖分析报告.md
docs/项目进展/v1.2.9/v1.2.9_BUILD系统修复TODO清单.md
docs/textbook/《数据库系统原理与开发实践》.md
docs/design/sql_parser_design.md
docs/design/storage_engine/b_plus_tree_index_design.md
docs/项目进展/v1.2.6/core_components_commenting_and_documentation_plan.md
include/network/encryption/BUILD.bazel
tools/bazel_config_analyzer.py
tools/bazel_config_detector.py
tools/bazel_file_creator.py
tools/bazel_include_fixer.py
tools/bazel_dependency_fixer.py
docs/项目进展/v1.2.6/bazel_build_system_refactoring_final_report.md
tools/bazel_improvement_suggestions.py
tools/bazel_label_fixer_enhanced_v2.py
docs/项目进展/v1.2.6/bottom_up_refactoring_progress_report.md
src/logger/logger_module.cpp
src/logger/logger_module_impl.cpp
scripts/validate_build_system.sh
docs/项目进展/v1.2.6/sqlcc_v1_2_6_final_refactoring_report.md
docs/项目进展/v1.2.6/manual_improvement_plan_bottom_up.md
docs/项目进展/v1.2.5/dependency_refactoring_report.md
docs/项目进展/v1.2.5/class_file_separation_analysis_report.md
include/exception/io_exception.h
include/exception/buffer_exception.h
include/exception/page_exception.h
include/exception/disk_exception.h
include/exception/lock_exception.h
include/exception/feature_exception.h
include/exception/argument_exception.h
include/storage/replace_strategy/abstract_strategy.h
include/storage/replace_strategy/lru_strategy.h
include/storage/replace_strategy/lfu_strategy.h
include/storage/replace_strategy/clock_strategy.h
include/storage/replace_strategy/arc_strategy.h
include/storage/replace_strategy/strategy_factory.h
include/storage/replace_strategy.h
include/network/encryption/encryption_key.h
include/network/encryption/simple_encryptor.h
include/network/encryption/aes_encryptor.h
include/network/encryption/hmac_sha256.h
include/network/encryption/pbkdf2.h
include/trigger/trigger_definition.h
include/trigger/trigger_executor.h
include/trigger/recursion_guard.h
include/sql_parser/constraint/foreign_key_constraint.h
include/sql_parser/constraint/check_constraint.h
include/sql_parser/constraint/primary_key_constraint.h
include/sql_parser/constraint/unique_constraint.h
include/sql_parser/constraint/not_null_constraint.h
include/sql_parser/constraint/assertion_constraint.h
include/sql_parser/function/function_definition.h
docs/项目进展/v1.2.5/sqlcc_refactoring_improvement_summary.md
include/sql_parser/function/function_call.h
include/sql_parser/function/function_ddl.h
include/network/network_exception.h
include/network/message_processor.h
include/network/key_rotation_policy.h
include/sql_parser/function/function_parameter.h
include/sql_parser/function/create_function.h
include/sql_parser/function/alter_function.h
include/network/network_exception_handler.h
include/network/network_monitor.h
include/network/network_stability_guard.h
include/network/data_transmission_validator.h
include/execution/aggregate_engine.h
include/execution/group_by_executor.h
include/execution/unified_executor.h
include/execution/test_runner.h
include/execution/standalone_test.h
docs/项目进展/v1.2.5/class_file_separation_refactoring_progress.md
docs/项目进展/v1.2.5/header_refactoring_improvement_report.md
docs/releases/RELEASE_NOTES_v1.2.5.md
include/sql_executor/domain_manager.h
src/sql_executor/advanced_sql92_executor.cpp
src/types/domain_manager.cpp
src/storage_engine/table_storage/page_raii.cpp
docs/项目进展/v1.2.9/B+树索引实现算法分析报告.md
docs/项目进展/v1.2.9/B+树重构进展报告.md
src/logger/BUILD.bazel
docs/项目进展/v1.2.10/SQLCC_v1.2.10_全面覆盖率测试系统完成报告.md
docs/项目进展/v1.2.10/SQLCC_v1.2.10_覆盖率测试完成报告.md
docs/项目进展/v1.2.10/执行引擎模块BUILD修复总结.md
src/execution/task_executor_simple.cpp
tests/unit/basic/ast_node_basic_test.cpp
tests/unit/storage/BUILD.bazel
docs/项目进展/v1.2.10/循环依赖修复任务清单.md
docs/项目进展/v1.2.10/AI辅助循环依赖分析报告.md
docs/testing/TESTING_ENHANCEMENT_REPORT_v0.5.3.md
docs/测试计划/SQL语句真实执行和持久化测试与改进计划.md
docs/项目进展/v1.2.9/最新覆盖率测试报告_20251226.md
tests/storage_engine/b_plus_tree_core_test.cpp
tests/storage_engine/wal_system_test.cpp
tests/storage_engine/data_integrity_test.cpp
src/storage_engine/node_size_manager.cpp
tests/storage_engine/node_size_manager_test.cpp
docs/项目进展/v1.2.14/SQLCC测试覆盖率测试项目完成报告.md
scripts/run_coverage_tests.sh
tests/unit/basic/exception_test.cpp
tests/unit/basic/BUILD.bazel
include/sql_executor/json_executor.h
include/sql_executor/trigger_executor.h
include/sql_parser/json_parser.h
include/sql_parser/trigger_parser.h
docs/项目进展/v1.2.12/v1.2.12_TODO.md
docs/项目进展/v1.2.12/v1.2.12工作日记.md
docs/项目进展/v1.2.12/错误修复工作日记.md
tests/storage_engine/disk_manager_test.cpp
.github/workflows/coverage.yml
src/sql_parser/ast/view_statements.cpp
docs/项目进展/v1.2.9/下一步行动执行指南_20251225.md
include/storage_engine/buffer_pool/BUILD.bazel
src/sql_executor/transaction_control_manager.cpp
include/sql_parser/json/json_value.h
src/sql_parser/json/json_value.cpp
include/sql_parser/json/json_null.h
include/sql_parser/json/json_boolean.h
include/sql_parser/json/json_number.h
include/sql_parser/json/json_string.h
include/sql_parser/json/json_array.h
include/sql_parser/json/json_object.h
include/storage_engine/table_storage/page_raii.h
include/storage_engine/table_storage/record_validator.h
src/storage_engine/table_storage/record_validator.cpp
docs/项目进展/v1.2.3/测试源码详细整理报告.md
scripts/coverage_analysis_passed_tests.sh
docs/项目进展/v1.2.3/测试改进综合分析报告.md
docs/项目进展/v1.2.3/测试改进实施计划.md
docs/项目进展/v1.2.3/测试改进编译验证报告.md
docs/项目进展/v1.2.3/覆盖率数据收集问题诊断报告.md
docs/项目进展/v1.2.3/覆盖率数据收集成功报告.md
docs/项目进展/v1.2.3/当前覆盖率数据收集报告.md
docs/项目进展/v1.2.3/SQLCC核心组件覆盖率分析报告.md
docs/项目进展/v1.2.4/v1.2.4_TODO.md
tests/query_features_test.cpp
src/execution/window_function_executor.cpp
docs/项目进展/v1.2.3/内存安全修复实施计划_20251217.md
docs/项目进展/v1.2.3/内存安全修复代码示例指南.md
tests/load_data_test.cpp
docs/项目进展/v1.2.3/详细测试执行报告.md
docs/项目进展/v1.2.3/测试源码整理报告.md
docs/项目进展/v1.2.3/详细测试总结报告.md
include/storage/b_plus_tree_nodes.h
docs/项目进展/v1.2.3/测试总结报告.md
docs/项目进展/v1.2.4/v1.2.4测试改进计划.md
docs/项目进展/v1.2.4/v1.2.4测试源码详细整理报告.md
docs/项目进展/v1.2.4/测试验证报告.md
docs/项目进展/v1.2.4/测试改进变更记录.md
tests/unit/executor/join_executor_boundary_test.cpp
docs/项目进展/v1.2.3/测试验证报告.md
docs/项目进展/v1.2.4/测试改进TODO清单.md
tests/unit/executor/set_operation_boundary_test.cpp
tests/unit/network/network_boundary_test.cpp
docs/项目进展/v1.2.4/测试变更记录.md
tests/unit/executor/window_function_boundary_test.cpp
include/constraint_executor.h
docs/项目进展/v1.2.4/v1.2.4工作日记.md
docs/项目进展/v1.2.4/测试改进工作日志_20251220.md
src/execution/recursive_query_executor.cpp
scripts/collect_coverage_data.sh
docs/c++20_modules_migration_plan.md
docs/c++20_modules_evaluation_report.md
docs/c++20_modules_implementation_summary.md
docs/c++20_modules_compiler_analysis.md
scripts/test_clang18_simple.sh
docs/clang18_modules_migration_guide.md
docs/final_modules_migration_report.md
scripts/setup_clang18_environment.sh
docs/stage1_completion_report.md
src/utils/logger.cpp
docs/stage2_utils_migration_report.md
include/core/user_manager.h
docs/stage2_core_migration_report.md
docs/migration_execution_plan.md
docs/stage2_migration_summary_report.md
docs/stage3_logger_modules_report.md
docs/final_migration_assessment_report.md
docs/stage4_storage_engine_migration_report.md
docs/final_compilation_validation_report.md
docs/bazel_integration_final_report.md
docs/bazel_debug_final_report.md
docs/项目
docs/ai-agent/bazel_build_principles.md
docs/项目进展/v1.2.6/package_refactoring_assessment_report.md
docs/项目进展/v1.2.6/layer2_build_fix_completion_report.md
tools/bazel_check_deps.sh
tools/validate_cpp20_clang18.sh
src/isql_network/BUILD.bazel
docs/design/sqlcc_package_design.md
docs/项目进展/v1.2.4/sqlcc_package_design.md
docs/项目进展/v1.2.4/其他核心组件重构改进完成报告.md
docs/项目进展/v1.2.4/核心组件系统性重构改进完成报告.md
docs/项目进展/v1.2.4/重构进展总结和下一步改进计划.md
docs/项目进展/v1.2.4/阶段1完成报告.md
tests/unit/core/config_manager_test.cpp
docs/项目进展/v1.2.4/测试重构改进总结报告.md
docs/ai-agent/test_refactoring_methodology.md
docs/ai-agent/systematic_refactoring_knowledge_base.md
docs/项目进展/v1.2.4/系统性测试重构项目完成报告.md
docs/项目进展/v1.2.4/test_analysis_report.json
docs/项目进展/v1.2.4/Bazel重构改进计划.md
docs/项目进展/v1.2.4/Bazel重构改进工作总结_20251220.md
docs/项目进展/sql_parser_成功经验总结报告.md
docs/项目进展/工具和工作流程改进方案.md
tools/build_validator.sh
docs/项目进展/v1.2.4/Bazel构建配置系统性修复完成报告.md
docs/项目进展/v1.2.4/Bazel重构改进记录.md
docs/ai-agent/bazel_tools_manual.md
docs/ai-agent/bazel_knowledge_base.md
tools/bazel_debug.sh
tools/bazel_fixer.sh
docs/ai-agent/bazel_improvement_guide.md
tools/bazel_code_checker.py
tools/bazel_label_fixer.py
docs/ai-agent/bazel_workflow_guide.md
src/sql_parser/set_operation.cpp
src/sql_parser/window_function.cpp
docs/项目进展/v1.2.3/测试变更记录.md
src/sql_parser/load_data_ast.h
docs/design/multi_task_executor_design.md
docs/design/README.md
docs/design/storage_engine/buffer_pool.md

# Current Time
1/12/2026, 3:45:26 AM (Asia/Shanghai, UTC+8:00)

# Current Mode
ACT MODE

}  // namespace sqlcc
