# //src/exception/BUILD.bazel - 异常处理库

load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "exception",
    srcs = glob(["*.cpp"]),
    hdrs = ["//include/exception:exception"],
    includes = ["../../include"],
    deps = [
        "//include/exception:exception",
    ],
    visibility = ["//visibility:public"],
)