package(default_visibility = ["//visibility:public"])

cc_test(
    name = "index_manager_fast",
    srcs = [
        "index_manager_test.cpp",
        "index_insert_test.cpp",
    ],
    deps = [
        "//src/storage_engine/index_manager",
        "@com_google_googletest//:gtest_main",
    ],
)

test_suite(
    name = "all",
    tests = [":index_manager_fast"],
)
