#!/bin/bash

# SQLCC Test Build Configuration Refactor Script
# Batch refactor BUILD.bazel files to use unified configuration template

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo "🔧 SQLCC Test Build Configuration Refactor"
echo "=========================================="

# Check if unified config template exists
if [ ! -f "$PROJECT_ROOT/tests/build_config.bzl" ]; then
    echo "❌ Error: Unified config template not found at $PROJECT_ROOT/tests/build_config.bzl"
    exit 1
fi

echo "✅ Found unified config template"

# Function to refactor a single BUILD.bazel file
refactor_build_file() {
    local build_file="$1"
    local dir_name=$(basename "$(dirname "$build_file")")
    local temp_file="${build_file}.tmp"

    echo "🔄 Refactoring $build_file..."

    # Create new BUILD.bazel content
    cat > "$temp_file" << EOF
# $dir_name Tests - Unified Configuration
# Auto-generated by refactor_build_configs.sh

load("//tests:build_config.bzl", "sqlcc_test")

# Test targets will be added here during manual review
# This file serves as a template for unified configuration
EOF

    # Move temp file to replace original
    mv "$temp_file" "$build_file"

    echo "✅ Refactored $build_file"
}

# Find all level BUILD.bazel files
echo "📋 Finding BUILD.bazel files to refactor..."
build_files=$(find "$PROJECT_ROOT/tests" -name "BUILD.bazel" | grep "level" | sort)

if [ -z "$build_files" ]; then
    echo "❌ No BUILD.bazel files found in level directories"
    exit 1
fi

echo "Found $(echo "$build_files" | wc -l) BUILD.bazel files to refactor:"
echo "$build_files" | nl

# Ask for confirmation
echo ""
echo "⚠️  WARNING: This will replace all BUILD.bazel files with unified templates"
echo "   Manual review and completion will be required afterwards"
read -p "Continue? (y/N): " -n 1 -r
echo

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Operation cancelled"
    exit 1
fi

# Refactor each file
echo "🚀 Starting refactor process..."
refactored_count=0

while IFS= read -r build_file; do
    if [ "$build_file" != "$PROJECT_ROOT/tests/level1_foundation/BUILD.bazel" ] &&
       [ "$build_file" != "$PROJECT_ROOT/tests/level2_core_services/BUILD.bazel" ]; then
        refactor_build_file "$build_file"
        ((refactored_count++))
    else
        echo "⏭️  Skipping already refactored file: $build_file"
    fi
done <<< "$build_files"

echo ""
echo "✅ Refactor complete!"
echo "📊 Summary:"
echo "   - Template created: $PROJECT_ROOT/tests/build_config.bzl"
echo "   - Files refactored: $refactored_count"
echo "   - Files skipped: 2 (already refactored)"
echo ""
echo "📝 Next steps:"
echo "   1. Manually review each BUILD.bazel file"
echo "   2. Add appropriate test targets using sqlcc_test() function"
echo "   3. Specify correct dependencies for each test"
echo "   4. Test compilation with 'bazel build //tests/...'"

echo ""
echo "🎯 Refactor completed successfully!"