# Demo tests BUILD file

cc_test(
    name = "expression_test",
    srcs = ["expression_test.cpp"],
    copts = ["-std=c++17"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
    tags = ["coverage_enabled"],
    linkopts = [
        "-stdlib=libc++",
        "-lc++abi",
    ],
)

cc_test(
    name = "parser_integration_test",
    srcs = ["parser_integration_test.cpp"],
    copts = ["-std=c++17"],
    deps = [
        "//src/sql_parser:sql_parser",
        "@com_google_googletest//:gtest_main",
    ],
    linkopts = [
        "-stdlib=libc++",
        "-lc++abi",
    ],
)
