# TODO: lazy_writer target does not exist in src/storage_engine/BUILD.bazel
# cc_test(
#     name = "lazy_writer_test",
#     srcs = ["lazy_writer_test.cpp"],
#     deps = [
#         "@com_google_googletest//:gtest_main",
#         "//src/utils:utils",
#         "//src/storage_engine:lazy_writer",
#         "//src/storage_engine:storage_engine",
#     ],
# )

cc_test(
    name = "wal_buffer_test",
    srcs = ["wal_buffer_test.cpp"],
    deps = [
        "//include:storage:storage_headers_lib",
        "@com_google_googletest//:gtest_main",
    ],
)