load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

# Mock库
cc_library(
    name = "storage_engine_mock",
    srcs = ["storage_engine_mock.cpp"],
    hdrs = ["//src/mocks:storage_engine_mock.h"],
    deps = [
        "//src/storage_engine:storage_engine",
        "//src/transaction:transaction",
        "//src:storage_engine",
    ],
)

cc_library(
    name = "database_manager_mock",
    srcs = ["database_manager_mock.cpp"],
    hdrs = ["//src/mocks:database_manager_mock.h"],
    deps = [
        "//src:core_database_manager",
    ],
)

cc_library(
    name = "transaction_manager_mock",
    srcs = ["transaction_manager_mock.cpp"],
    hdrs = ["//src/mocks:transaction_manager_mock.h"],
    deps = [
        "//src:transaction_manager",
    ],
)

cc_library(
    name = "index_manager_mock",
    srcs = ["index_manager_mock.cpp"],
    hdrs = ["//src/mocks:index_manager_mock.h"],
    deps = [
        "//src/mocks:index_manager_mock",
        "//src:storage_index_manager",
    ],
)

cc_library(
    name = "mocks",
    deps = [
        ":storage_engine_mock",
        ":database_manager_mock",
        ":transaction_manager_mock",
        ":index_manager_mock",
    ],
)