cc_test(
    name = "b_plus_tree_tests",
    srcs = glob(["*.cpp"]),
    deps = [
        "//include/storage_engine:b_plus_tree",
        "//include/storage_engine:b_plus_tree_index",
        "//include/storage_engine:b_plus_tree_node",
        "//include/storage_engine:b_plus_tree_leaf_node",
        "//include/storage_engine:b_plus_tree_internal_node",
        "//src/storage_engine:b_plus_tree_lib",
        "//src/storage_engine:b_plus_tree_index_lib",
        "//src/storage_engine:b_plus_tree_node_lib",
        "@com_google_googletest//:gtest_main",
    ],
    copts = [
        "-std=c++20",
        "-fprofile-instr-generate",
        "-fcoverage-mapping",
    ],
    linkopts = ["-fprofile-instr-generate"],
    tags = ["coverage", "level2", "storage_engine"],
)
