package(default_visibility = ["//visibility:public"])

test_suite(
    name = "level2_storage_engine_all",
    tests = [
        "//tests/level2_storage_engine/b_plus_tree:all",
        "//tests/level2_storage_engine/buffer_pool:all",
        "//tests/level2_storage_engine/disk_management:all",
        "//tests/level2_storage_engine/disk_manager:all",
        "//tests/level2_storage_engine/index:all",
        "//tests/level2_storage_engine/index_manager:all",
        "//tests/level2_storage_engine/storage_engine:all",
        "//tests/level2_storage_engine/wal:all",
        "//tests/level2_storage_engine/wal_system:all",
    ],
)
