cc_library(
    name = "session",
    srcs = ["session.cpp"],
    hdrs = ["//include/network:session.h"],
    deps = [
        "//include/network/encryption:aes_encryptor",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "session_manager",
    srcs = ["session_manager.cpp"],
    hdrs = ["//include/network:session_manager.h"],
    deps = [
        ":session",
    ],
    visibility = ["//visibility:public"],
)
